### ISSUE TITLE
Higher the wages for EMS

### ISSUE THREAD

**Issue by TheLitteralIcemanStraightOuttaFinlandia** [ChainedDev/CityLife#100]
**Is your feature request related to a problem? Please describe.**
EMS is lacking and it feels like the police are the only doing what EMS would had done. Nowadays I go online there are cops running around healing people instead of EMS. This leads to when store robberies happen, either the dying people aren't getting help or the robbers will be getting away because the law enforcement is busy with the people.

**Describe the feature you'd like**
Give EMS higher wages because of the high demand and low supply.
**Describe alternatives you've considered**
Or you could be more soft with the EMS applications because the server is otherwise not going to have any medical care, making it able to revive each other would also be a final alternative right now.

**Comment by yggun** [comment]
Value your life.

**Comment by TheLitteralIcemanStraightOuttaFinlandia** [comment]
> Value your life.
Did I mention that I was affected by this? Even if you pretty much never get downed it affects you because police are busy running around delivering people to the hospital.
**funny comment.**

**Comment by yggun** [comment]
Police don't deliver people to the hospital.

**Comment by gullidog** [comment]
EMS applications are being looked at but some are just too stupid to even accept lol. As for higher wages, EMS wages are high as they are already compared to other whitelisted jobs!

_**gullidog**_
