### ISSUE TITLE
EMS not informed about when silent alarms are turned off

### ISSUE THREAD

**Issue by Snewie** [ChainedDev/CityLife#101]
As an EMS I've responded to many 10-90 this is normal but sometimes they get turned off and EMS are not informed about it unless you ask a cop in dispatch, which sometimes they do not announce because we can be driving there and it gets turned off and I just go there to wait a few minutes just to find out it was turned off and a false alert

I would want a feature that EMS will be informed that the silent alarm is turned off so we won't be wasting our times and can start saving people's lives.

**Comment by yggun** [comment]
Agreed.

**Comment by ChainedDev** [comment]
Fixed
