### ISSUE TITLE
The Inventory Size

### ISSUE THREAD

**Issue by GamerNA** [ChainedDev/CityLife#102]
**Describe the bug**
I play at 1280x720 resolution and the entire first column is not visibile.

**Expected Behaviour**
It must show each and every row and column on all the resolutions.

**Comment by yggun** [comment]
https://www.amazon.com/Acer-KA220HQ-21-5-viewable-Monitor/dp/B078WPPX2Z/ref=sr_1_24?keywords=1920x1080+Monitor&qid=1583695675&sr=8-24

Here's a 1920x1080 monitor for $70. This will fix your issue.

**Comment by ChainedDev** [comment]
Change to lowest resolution and you might be able to use it
