### ISSUE TITLE
EMS getting tasers when clocking in 

### ISSUE THREAD

**Issue by Snewie** [ChainedDev/CityLife#103]
When I was recruited into the EMS I heard EMS used to get tasers when clocking in, the issue was that EMS were selling the tasers to other people so it was removed, I feel like this should be added back to EMS so we can enhance our roleplay experience like when we use a AED on somebody we can use a taser to represent us shocking them with a AED, and also use it as self-defense because we are not allowed to carry weapons so we are defenseless 

Since EMS used to sell tasers what we could do is after you clock off as an EMS your taser would be removed from your inventory, if people still try to sell it you can implement some consequences like a strike or fired from the EMS force, I’m sure you can also add a function where you can’t give tasers to other people and can be only obtained when clocking in as an EMS

**Comment by yggun** [comment]
Another alternative could be actually going down to the PD and being issued one and paying a fee of maybe 5k. Only because as an EMS, my money sits in my bank account anyway. 5k can be made in about two hours with our paychecks. 

Actually going through the effort to go down to PD, and buy one will most likely prevent people from reselling them since they go for about 5k anyway.

**Comment by Snewie** [comment]
Should still give us a option to buy one instead of going to pd

**Comment by gullidog** [comment]
> Another alternative could be actually going down to the PD and being issued one and paying a fee of maybe 5k. Only because as an EMS, my money sits in my bank account anyway. 5k can be made in about two hours with our paychecks.
> 
> Actually going through the effort to go down to PD, and buy one will most likely prevent people from reselling them since they go for about 5k anyway.

I like this idea! You can totally RP this out. Maybe talk to the chief of police?

**_gullidog_**
