### ISSUE TITLE
Add the BMW E36 to the game

### ISSUE THREAD

**Issue by TheLitteralIcemanStraightOuttaFinlandia** [ChainedDev/CityLife#105]
**Is your feature request related to a problem? Please describe.**
There is no M36

**Describe the feature you'd like**
Add the M36, pretty nice car and all
https://sv.gta5-mods.com/vehicles/bmw-m3-e36-streetcustom-add-on-tuning
**Describe alternatives you've considered**
None

**Comment by gullidog** [comment]
New cars are in the works!

**_gullidog_**
