### ISSUE TITLE
Drive by bug when not doing a drive by

### ISSUE THREAD

**Issue by GordonRamsay69** [ChainedDev/CityLife#106]
**Describe the bug**
If you have a pistol or any weapon that your able to do a drive by with most of the time when you get out of your car you have the gun in your hand and if u have the gun in your hand and you get into the car it will throw you out of the car because of the drive buy feature when your character pulls out his gun before he start the car witch is super annoying

**How to Reproduce the Behavior**
Take gun out 
Try to get in the car
“Kicks you out”
Other one
Get into car with a pistol
Drive a little ways
Get out of car
And gun is in your hand
Doesn’t happen all the time

**Expected Behaviour**
When you get into your car the character can take out his weapon from his waste band but when you get out of the car the gun shouldn’t come out in your hand and when you get into the car with the gun in your hand it should restart the animation of the character pulling it out of his waste band

**Additional context**
Others get annoyed as well because you have to put the gun away and if you try to get into your car before the animation is done it kicks you out of the car

**Comment by gullidog** [comment]
If you press TAB it switches between your guns and fist while you are in a car, that's probably why. Just make sure before you exit the vehicle. If this is not the reason please be sure to comment back on this!

**_gullidog_**
