### ISSUE TITLE
Auto Turret to prevent people enterting the base a

### ISSUE THREAD

**Issue by Vlurt** [ChainedDev/CityLife#107]
**Is your feature request related to a problem? Please describe.**
Yes, People will instead die instead of getting shot, ( Warn EMS Not to enter near the base if someone is asking to be helped)

**Describe the feature you'd like**
https://www.gta5-mods.com/scripts/mobile-multi-turret
This turret will detect players and shoot them, Great way to prevent bans as well as people who try troll the city and get in a tank or jet

**Describe alternatives you've considered**
I have thought about just locking the gate and extended the fences where u can jump over but what is the fun in that, Players who break the rule should face the consequences ( Add to the rules that the base is off-limits to start off with)

**Additional context**
Maybe let me make the military base into a fun place by making it into a jungle, covering it with trees and all sorts of stuff

**Comment by gullidog** [comment]
https://store.steampowered.com/app/252490/Rust/
Buy this game.

**Comment by Vlurt** [comment]
Already got it...
