### ISSUE TITLE
The more cops on duty the more drugs sell for to locals

### ISSUE THREAD

**Issue by Vlurt** [ChainedDev/CityLife#108]
**Is your feature request related to a problem? Please describe.**
When there are no cops on, people sell drugs like crazy, Making the cops have less work to do but when cops are on and people are selling drugs it would have cops for a reason to go to the area and check it out

**Describe the feature you'd like**
0 cops on - Drugs sells for  0% more
2 cops on - Drugs sells for 25% more 
4 cops on - Drugs sells for 50% more
6 cops on - Drugs sells for 75% more

*Describe alternatives you've considered**
Having better drugs but harder to produce. 
Sells for more but also alerts the cops more
There should also be a npc that comes out at night who buys wholesale and comes up in certains spots of the city. there should be 5 location in the same area and that one npc can buy like 20 drugs for a fixed price but it will alert the cop more regular 
List of NPC That could be the person
https://wiki.gtanet.work/index.php?title=File:OGBoss01AMM.png
https://wiki.gtanet.work/index.php?title=File:SalvaGoon01GMY.png
https://wiki.gtanet.work/index.php?title=File:SouCent02AMY.png
https://wiki.gtanet.work/index.php?title=File:PrisMuscl01SMY.png ( Change clothes)

**Additional context**
[Add any other context or screenshots about the feature request here. **Remove this line!**]

**Comment by l-Crynic-l** [comment]
I like this idea. High risk, high reward.

**Comment by ChainedDev** [comment]
👀 ?
