### ISSUE TITLE
We need heathbars when we are on our feet

### ISSUE THREAD

**Issue by Droshky** [ChainedDev/CityLife#109]
**Is your feature request related to a problem? Please describe.**
If i get shot or hurt, etc. I can't see how well I'm doing (ik about the statuses in my top right but those give minimal information and are wonky).

**Describe the feature you'd like**
Give us a healthbar at all times and not only when we're in a car.

**Describe alternatives you've considered**
A little number with our health out of #/#

**Additional context**
People are annoyed by it at all times.

**Comment by ChainedDev** [comment]
Added
