### ISSUE TITLE
EMS issue not being able to buy charger and most likely not being able to take it out

### ISSUE THREAD

**Issue by Snewie** [ChainedDev/CityLife#111]
Recently I’ve been promoted to a senior EMT, at this point we get a new car a Dodge Charger, but once we buy it it does not appear into our garage I’ve tried to buy it two times once before a tsunami and after a tsunami. 

It would be nice if we were able to access this car so we could go to scene faster and call a ambulance to transport them if needed

**Comment by gullidog** [comment]
This will be fixed on restart, thanks for bringing this to our attention!
17//03/20 - 22:48 GMT

**gullidog**
