### ISSUE TITLE
Bags/Inventory

### ISSUE THREAD

**Issue by Nightshade93** [ChainedDev/CityLife#112]
**Is your feature request related to a problem? Please describe.**
No problems.

**Describe the feature you'd like**
Make it so that bags affect inventory capacity.

**Describe alternatives you've considered**
Alternatives include adding a mod that adds backpacks that affect capacity, or making backpacks have a separate inventory.

**Additional context**
Here is one that could work. Not sure if it is usable by you for the server. https://forum.cfx.re/t/release-esx-kr-bag-inventory-a-bag-inventory-script-synced-with-the-server/283141?__cf_chl_captcha_tk__=cced700c7034877c2e6ed1043cc63054c870d644-1584467228-0-AXA9dU15RzjpGPJ9bhQvYl38snFZBr80R07-2EuRIw2H3FDgmGzZr4kBfNaz_VQzmWgyUvRMEtiXv7qTIbikTastPhwpU6ZHpoNJfgp0ZW84boUaFTFovFrb4J4Pwjgj2CIRfjALzSUn7HOeEd5z9LH4GxWdh0NUdU_SsMHJY8jbDacxunHcVEMiUv3bS8wboqxiOM_HJhcaKERrXo_ak0qxDyvJqkgKM1GM1R-DYpWBGKfIyu6AkhvewzYW_eDaDNhczz6cxs9Ads1wNBStWXDOtb01ANBgh7upxsdha7hlpCMUzb3sefucykF9k6WW1V99cwswG_NaED264s0tqRCs-W4lMzxHERSLwv2C3yTjPFZwoVzuXuQrnFN8odGFE38Vzpz6Co2MivlWYSyRBRS08y9ywmkeprplThtcOUvAdtOD1S99sBj3ja4yFYGY6_ow5Jav5JxHHHJfMvSkjCwvmexNYs1FhZTdh1-pd5-RjCl4jmN74pE-998HjFU4FONW6xPB_B0WbNRqM0vpPI8nRMADJy17J7x2Pyzpo4ljF1hvKn-jp_uiXE0VQ-FV2w

**Comment by gullidog** [comment]
Hello, thanks for the suggestion we really appreciate it! However, this script is poorly written and very scuffy.

_**gullidog**_
