### ISSUE TITLE
House Robberies

### ISSUE THREAD

**Issue by JJG1997** [ChainedDev/CityLife#113]
**Is your feature request related to a problem? Please describe.**
No just something else to force RP between cops and crims. Also another thing for cops to respond to.

**Describe the feature you'd like**
Making house robberies possible (not player owned) If they are player owned they cannot be robbed. For example, you would find a house in Little Seoul by the beach and use a lockpick (possible to add a mini game so it's not too easy) You would then be inside the house with a bar that shows how safe you are depending on how you move. You could then search drawers and dressers to find items such as cash, ammo, parts for crafting and very rarely, a gun (pistols only so it's not too over powered.)

**Describe alternatives you've considered**
None at the moment. 
**Additional context**
Sort of like the way it is on NoPixel if anyone has ever seen that. It's also an extra thing for crims to do to get money and/or parts.

**Comment by gullidog** [comment]
I have been contemplating implementing a system like this but wasn't sure if it is wanted, if you would like this feature please say and I will look into it!

_**gullidog**_

**Comment by JJG1997** [comment]
Another thing to add, could be done late night early morning (in game) and only possible with 2+ cops on to stop people abusing it
