### ISSUE TITLE
Limiting Robberies for RP

### ISSUE THREAD

**Issue by NinjaTinaH** [ChainedDev/CityLife#114]
**Is your feature request related to a problem? Please describe.**
Mostly, when there are enough SASP 'on duty', there are tons of store robberies going on to the point where there is often no SASP found anywhere else.

**Describe the feature you'd like**
- If one store is being robbed, all other stores goes on 'lockdown' (and non-rob-able) for a certain length of time to allow officers to be able to respond to the situation. Lockdowns TIMER start after the safe-minigame has ended yet starts Lockdown when the first safe-minigame has begun. 

- Lockdown Timer depends on how long usually robbers can take? Or perhaps a static amount?

- The number of robbers has to be less than the number of police with maximum of 5; perhaps limiting the amount the robbers can get from the safe based on number of SASP on duty.

Eg. 
- 7 police on duty, 5 robbers max. Robbers can gain a bit more money.
- 3 police on duty, 2 robbers max. Minimal amount of money. (or your safe/hostage guy will not have a good time as sole robber)

**Describe alternatives you've considered**
Mostly back and forth to develop this... Other ideas are welcome.

**Additional context**
Want more proper RP with SASP :o

**Comment by ChainedDev** [comment]
Safes already go on lockdown mode for a set time after completed and start when the store first gets robbed

**Comment by NinjaTinaH** [comment]
I meant for all the safes in LS to go into lockdown so there isn't chain robberies to deal with while multiple different groups go at them, give the SASP some time to 'recover'.

**Comment by JJG1997** [comment]
I see what you mean. Maybe have a longer cool down on all safes. Chases could last a while and if someone is eventually caught then the writing up will add time onto this

**Comment by ChainedDev** [comment]
Changed from 5 - 10 minute global cooldown
