### ISSUE TITLE
Cops with hands on Holster

### ISSUE THREAD

**Issue by Skader91** [ChainedDev/CityLife#115]
**Describe the bug**
Whenever a cop puts their weapon away they leave their hand on their holster, this can lead to tensions being raised for no reason. It does not show in the cops eye's just everyone else.

**How to Reproduce the Behavior**
Steps to reproduce the behaviour: Put weapon away

**Expected Behaviour**
After holstering a weapon it would be nice if there was a automatic "stop current animation" or something to resolve this.

**Screenshots**
I will work on obtaining these however it's a bit complicated as it requires multiple people

**Additional context**
We aren't that trigger happy. Promise.

**Comment by yggun** [comment]
let me know if you need help recreating. I’d be more than happy to help. - nuggy

**Comment by NinjaTinaH** [comment]
I'd happily be extra eyes if needed. -Jala

**Comment by ChainedDev** [comment]
Looking into you

**Comment by ChainedDev** [comment]
Still happening?
