### ISSUE TITLE
Adding Garages by job locations

### ISSUE THREAD

**Issue by montastical** [ChainedDev/CityLife#117]
**Is your feature request related to a problem? Please describe.**
Do you ever put your car in garage then have to spend a good 5 minutes walking to your job each way I feel it would be better if garages were built next to jobs such as garbage,taxi and all the others.

**Describe the feature you'd like**
I'd like garages by job locations which adds to the convenience as If I leave my car there it just tends to despawn

**Describe alternatives you've considered**
reducing the rate at which cars despawn however it will increase lag

**Additional context**
N/A

**Comment by NinjaTinaH** [comment]
Would probably be best if they were limited to just people whom have that specific job. It would definitely be nice as a Mechanic.

**Comment by ChainedDev** [comment]
What jobs need them?

**Comment by NinjaTinaH** [comment]
In the Tuner shop can be nice :o

**Comment by ChainedDev** [comment]
MORE GARAGES!

**Comment by ChainedDev** [comment]
What locations?

**Comment by ChainedDev** [comment]
What locations
