### ISSUE TITLE
Stress Element

### ISSUE THREAD

**Issue by JJG1997** [ChainedDev/CityLife#118]
**Is your feature request related to a problem? Please describe.**
No just another feature.

**Describe the feature you'd like**
Add stress, gained from illegal activities, shooting, doing a job (not a lot of stress for this), driving fast etc. Stress can be lowered by smoking a joint. Add an effect to the screen when too much stress is accumulated. 
**Describe alternatives you've considered**
None

**Additional context**
This adds in the need for weed, not making it useless and actually having a market for it. Creates more RP, adding a dealer in. Get rid of smoke on the water entirely so weed can only be gained via farming it or buying from other players.

**Comment by ChainedDev** [comment]
Added ability for stress to be easily implemented

**Comment by l-Crynic-l** [comment]
How would this work for cops though? Same way? Also, would stress prohibit the player from doing things normally?
