### ISSUE TITLE
Armor balancing 

### ISSUE THREAD

**Issue by CityLifeRp** [ChainedDev/CityLife#119]
**What is the reason for this balance request?**
Allow civs to be be able to get full armor,so it will be fair if we fight the cops

**What solution would you like?**
Allow the civs to be able to go to a hidden dealer to buy full armor or craft full armor which ever one is better for yall

**Additional context**
This will make it fair for cops and civs.

**Comment by ChainedDev** [comment]
👀

**Comment by montastical** [comment]
it isn't meant to be fair with cops against civs IRL they will be more heavily armed and there will be more cops than civs. Because of this you are forced to be creative in how you would fight the cops that's just my opinion

**Comment by BobTheBuiIder** [comment]
> it isn't meant to be fair with cops against civs IRL they will be more heavily armed and there will be more cops than civs. Because of this you are forced to be creative in how you would fight the cops that's just my opinion

I guess that's why they should be hard to get since the big gangs/orgs have good gear irl

**Comment by Droshky** [comment]
no.

**Comment by ChainedDev** [comment]
Do yall want to be able to get 100% armour?

**Comment by ChainedDev** [comment]
Balanced
