### ISSUE TITLE
Trunk space should be larger for some vehicles

### ISSUE THREAD

**Issue by Kman259** [ChainedDev/CityLife#120]
**What is the reason for this balance request?**
Vehicles like the Yosemite truck and the slamvan only have 20 storage. But other cars like the Kalahari has 40 and even the baller SUV has 35 space. Vehicles like the Yosemite and the slamvan have very large truck beds yet still have significantly smaller storage capacity than vehicles with smaller trunks. 

**What solution would you like?**
Bring vehicles that have large truck beds like the Yosemite and slamvan to have 40 storage. 

**Additional context**
Just to clarify, I am not saying storage on vehicles like the Kalahari and baller need to be nerfed. I think the storage amounts for them are good. What I am saying is some vehicle's storage need to be buffed.... *cough, cough, the Yosemite*
Thank you

**Comment by ChainedDev** [comment]
This is now possible will look at your suggestions, if you have any other vehicles that should be balanced please let us know!
