### ISSUE TITLE
Jewlery Heist

### ISSUE THREAD

**Issue by ZZeto** [ChainedDev/CityLife#121]
Please add what is known as the Jewlery Heist Mod, here is the link: https://www.gta5-mods.com/scripts/vangelico-jewellery-store-heist-luahttps://www.gta5-mods.com/scripts/vangelico-jewellery-store-heist-lua

"This mod script does just what the title says, it allows you to rob the Vangelico Jewellery Store like in the mission. I have remade the script and removed a lot of redundant code making the script run faster."

I've seen a couple rp servers include this in their servers, this made an interesting way of making money. I'm sure this will bring a exciting mod and rp situation to the table with others as well hooked in! Hope you'll consider this!

**Comment by yggun** [comment]
Tony doesn't like jewelry store heists.

**Comment by ChainedDev** [comment]
Do people want this?

**Comment by JJG1997** [comment]
**Please**

**Comment by ChainedDev** [comment]
Are we ready though yet?

**Comment by JJG1997** [comment]
Yes! Add a cool down of 1-2 hours so it can’t be robbed constantly

**Comment by TerryDavis-CL** [comment]
I would love this. Maybe have an item that is needed for the robbery. Something that not just anybody can get so it's not a bunch of pepegas robbing it 24/7. This should be treated as a legit heist.

**Comment by yggun** [comment]
make a craftable crowbar bwo

**Comment by l-Crynic-l** [comment]
And make the crowbar so it can crack safes faster maybe

**Comment by yggun** [comment]
no^

**Comment by ChainedDev** [comment]
YALL SERIOUSLY WANT THIS?

**Comment by ChainedDev** [comment]
we have now
