### ISSUE TITLE
Police Impound

### ISSUE THREAD

**Issue by Billy-Grey** [ChainedDev/CityLife#122]
**Is your feature request related to a problem? Please describe.**
Negative

**Describe the feature you'd like**
So after a crime is committed, and we've got the criminal or his vehicle an option for us to drive the vehicle to a certain place where we would be able to impound the vehicle for the amount of time that would be set in police sop. After the vehicle is impounded for an example 1 hour, they would have to pay a small fee to take it out.

**Describe alternatives you've considered**
0

**Additional context**
People would stop using their vehicles in all sorts of crimes.

**Comment by Skader91** [comment]
This is a better system because currently you can trash your shit, use it in a bunch of crimes then just pay the small amount no matter what happened.

If people actually feared for their vehicles being impounded for sometime it would reduce the amount of crime in the city.

**Comment by ChainedDev** [comment]
Yes?

**Comment by Chainedster** [comment]
Yes!

Sheesh this was over 2 years ago..... I feel old
