### ISSUE TITLE
Fps optimization 

### ISSUE THREAD

**Issue by BobTheBuiIder** [ChainedDev/CityLife#123]
**Is your feature request related to a problem? Please describe.**
When I play I get low fps and lag even tho I have a decent pc and can play other games on ultra

**Describe the feature you'd like**
I would like a fps optimization 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by l-Crynic-l** [comment]
Not just other games, but on other servers I get less stuttering. Idk whats causing it.

**Comment by ChainedDev** [comment]
Hopefully everyone's noticed more performance as of recent, I'm going to close this as it'll always be a priority and doesn't really need to be a open suggestion. More optimization will always be coming :D
