### ISSUE TITLE
Can store clean money in trunk

### ISSUE THREAD

**Issue by BobTheBuiIder** [ChainedDev/CityLife#125]
**Is your feature request related to a problem? Please describe.**
In case you got a lot of cash on you from work you can store it in trunk so in case you get robbed there is a chance they don't think of asking you to open the trunk and you don't lose your money

**Describe the feature you'd like**
Ability to put clean money in my car trunk

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by l-Crynic-l** [comment]
Yeah, why is this not possible already?

**Comment by ChainedDev** [comment]
> Yeah, why is this not possible already?

there's banks for clean money and trunks/houses for dirty money
