### ISSUE TITLE
S.W.A.T.

### ISSUE THREAD

**Issue by Skader91** [ChainedDev/CityLife#129]
https://www.gta5-mods.com/vehicles/lenco-bearcat-swat-code-3-arch-liberty-more-lights

https://www.lcpdfr.com/downloads/gta5mods/vehiclemodels/22432-els-non-els-2009-lenco-bearcat/

https://www.gta5-mods.com/vehicles/lapd-swat-insurgent

https://www.gta5-mods.com/paintjobs/lenco-bearcat-skin-pack

Other than needing a SWAT vehicle, we also need police ability to raid houses.

**Comment by Skader91** [comment]
SWAT CHOPPA
https://www.lcpdfr.com/downloads/gta5mods/vehiclemodels/8545-police-maverick-mapped/
https://www.gta5-mods.com/player/swat-team-replacer-fictional-aka-just-for-show

**Comment by littlewilms** [comment]
Fix rappelling if its possible with that

**Comment by littlewilms** [comment]
https://www.gta5-mods.com/paintjobs/lspd-lapd-swat-truck-texture
