### ISSUE TITLE
Special Pursuit Vehicles for SASP

### ISSUE THREAD

**Issue by Skader91** [ChainedDev/CityLife#130]
**What is the reason for this balance request?**
Now that people have farmed drugs for the last few months, we are starting to see faster and faster vehicles. Police have a max speed of 150MPH.

**What solution would you like?**
If we aren't going to improve some of the PD vehicles that we have now or atleast balance them better (Crown Vic goes same speed as charger) then I suggest we get new vehicles in the city.

I propose we have another division called the Pursuit Intervention Team or P.I.T. They wouldn't go around patrolling in these vehicles but they would be deployed in cases where we have Aston Martins and Lambo's going 220+

https://www.gta5-mods.com/vehicles/2017-ford-gt-hot-pursuit-police-add-on-replace-template

https://www.gta5-mods.com/vehicles/lamborghini-reventon-police-nfs-hot-pursuit-template

https://www.gta5-mods.com/vehicles/bugatti-chiron-hot-pursuit-police-add-on-replace-template

https://www.gta5-mods.com/vehicles/need-for-speed-hot-pursuit-lamborghini-avantador

https://www.gta5-mods.com/vehicles/mclaren-mp4-12c-seacrest-county-police-template

https://www.gta5-mods.com/vehicles/lamborghini-centenario-hot-pursuit-police-add-on-replace

https://www.gta5-mods.com/vehicles/2015-police-mustang-gt-addon

**Comment by ChainedDev** [comment]
Heck no to those cars are too expensive for the SASP's budget, faster pursuit vehicle changes could be changed though
