### ISSUE TITLE
Bank/Savings/Business/Investments

### ISSUE THREAD

**Issue by DaPlugKilo** [ChainedDev/CityLife#132]
What yall want to see in the future I'm just curious cause I know the city getting dry Business that does cost a lot but if its got anything to do with a online player's an your the owner you will have your own person spot to clean out your bloody money only **IF THE BUSSINESS IS ACCEPTABLE an REASONABLE ON HOW YOUR GOING TO CLEAN OUT YOUR MONEY** an make money, plus more rp **THEREFORE** we can add an **investment system** into these business there for its on most like a savings account only thing is that **the business can get drop or go up so becarful what you invest in**, in the long run this will help more roleplay, get more money, an keep people doing there mains jobs knowing they have something to look forward too with this idea an it want get boring driving around 24/7 waiting on a taxi call an knowing trying to keep your hardest from taxing or busting there head because the taxi job itself don't have a good payrate if it did then this idea could be wipe or use in the future. **I DONT MEAN NO HARM IF YOUR READING THIS JUST WOULD LOVE TO SEE THE BOSSES GET THAT CHANCE TO DEVELOPE THERE CHARACTERS AN SEE WHAT YALL THINK IT WAS WORTH A TRY!!!!**

**Comment by ChainedDev** [comment]
There are many jobs that just aren't at the job center(we want to get rid of it completely). We plan on adding player owned businesses at a later date financing it's really a goal we have set

**Comment by ChainedDev** [comment]
Gonna be closing this issue, if anyone has any suggestions for player-owner-businesses please make a suggestion and let us know!
