### ISSUE TITLE
New /showid

### ISSUE THREAD

**Issue by thejopu** [ChainedDev/CityLife#133]
**Is your feature request related to a problem? Please describe.**
In a sense, the current /showid is kinda jank, and really not that easy for us LEO's to work with. We are sort of forced to check ID via the F6 menu.

**Describe the feature you'd like**
I think /showid should show in the chatbox, something like 

"Myles Merlin Shows His ID: Name: Myles Merlyn | Licences: Driving Licence, Permit, Truckers Licence | Known Address: 1234 Tony Lane | 

Obviously all seperated by colours, to make it easy to read.

**Comment by JJG1997** [comment]
There is a /giveid feature?

**Comment by thejopu** [comment]
Yeah but it's kinda whacky, has little to no info, and disappears within seconds. As a cop, that's just something else we need to screenshot.

Something that stayed in the chatbox, would be SOOOOO helpful. and imo look so much clearer.

**Comment by ChainedDev** [comment]
OKAY JOPU

**Comment by ChainedDev** [comment]
Will be added in next update
