### ISSUE TITLE
Hunting Licence

### ISSUE THREAD

**Issue by SuperHornet14** [ChainedDev/CityLife#134]
**Is your feature request related to a problem? Please describe.**
Add a hunting licence that people have to buy.

**Describe the feature you'd like**
Have a hunting licence to buy so you can hunt legally. You can still hunt even if you don't have one but you can get charged with Poaching. The idea is to help add RP and so police can check up on all the shooting up near Paleto which will also expand where things are happening so not every single interaction is in the city

**Comment by ChainedDev** [comment]
Popular opining? 👍 or 👎

**Comment by ChainedDev** [comment]
https://chained.pw/imgs/edved.png coming sometime in the near future i guess :D

**Comment by ChainedDev** [comment]
YEAH SO WTF WHERE MY LICENSE REQUIREMENTS???? GOD

**Comment by ChainedDev** [comment]
Also re-do licenses server side for BeTtEr PeRfOrMaNcE

**Comment by ChainedDev** [comment]
![image](https://user-images.githubusercontent.com/44199939/99890921-40ad0580-2c32-11eb-8a99-326c574d362e.png)

**Comment by ChainedDev** [comment]
Added to the Hunting Lodge, you will be arrested if hunting without one!
