### ISSUE TITLE
Bus Driver job!

### ISSUE THREAD

**Issue by Pietro011** [ChainedDev/CityLife#138]
**Is your feature request related to a problem? Please describe.**

Some folks don't want to bother with a taxi and would rather just quietly go from one place to another instead of running. A bus driver job can help fix that issue and it's a new way for people to make money!

**Describe the feature you'd like**

In the real world, bus drivers are an essential travel method for those who do and do not have licenses, or would rather not drive to their location. Perhaps we can make use of buses in game where they go from one stop to another along their route to pick up anyone needing a ride. Other buses can have different routes allowing for easy transport around the state. It also serves a great rp purpose! Remember to thank your bus driver!

**Describe alternatives you've considered**

Uber can be one, but technically that is just being a taxi driver. However, it might be possible to set up an uber like system where people can chauffeur people around in their personal vehicles allowing for easier and rp'd transport while also paying for such. Instead of it being a random, maybe they can get paid for it via their paycheck.

**Additional context**

https://www.ign.com/wikis/gta-5/Bus_Routes
https://gta.fandom.com/wiki/Bus
https://www.jjslist.com/blog/importance-of-public-transportation

**Comment by ChainedDev** [comment]
Was thinking about adding more vehicles to the Taxi Department selection for people who want to do tours/busses/etc from there

**Comment by ChainedDev** [comment]
Added more vehicles to taxi depart
