### ISSUE TITLE
Snus

### ISSUE THREAD

**Issue by TheLitteralIcemanStraightOuttaFinlandia** [ChainedDev/CityLife#140]
**Is your feature request related to a problem? Please describe.**
Lack of legal drugs, at the moment we only have cigarettes as the only legal option. Everytime I've been on this island I've thought there has been something missing.

**Describe the feature you'd like**
Snus, also known as tobacco pouches. You put it under the lip which will make you consume the nicotine out of it and filling your needs. They should cost 6-7$ per snus box. If you consume too much of it, it will give you a nicotine buzz, which is very similar to the blackout effect when you're bleeding out.
If you're still unsure what snus is, read this wikipedia article: https://en.wikipedia.org/wiki/Snus

**Comment by ChainedDev** [comment]
Don't know about snus but we have plans for more/different drugs
