### ISSUE TITLE
WEAPON CHANGES

### ISSUE THREAD

**Issue by Aspratic** [ChainedDev/CityLife#141]
**Is your feature request related to a problem? Please describe.**
The current issue is that gunfights are over before they even begin. With the lack of crosshair detection available and the high damage values, gunfights last sometimes seconds. Getting 1 shotted by a pistol when you are carrying an AR is stupid and makes bringing out ARs and SMGs dumb. This will add value to all guns as well, offering an advantage to people who decide to pay 3400 for heavys vs finding a free pistol on a local

**Describe the feature you'd like**
[A clear and concise description of what you want to happen. Include any other documents that may reinforce your idea here. **Remove this line!**]
I want weapon damages to be reduced and weapon recoil to be added
proper documents can be provided via discord @ Aspratic#3121
**Describe alternatives you've considered**
None -  reduced damage and increased recoil

**Additional context**
This will extend roleplay and carry out gunfights, making them last longer and be more fun and a lot more intense. Dying in 1 bullet is not fun, and I don't think headshots should have a huge multiplier at all

**Comment by Aspratic** [comment]
this is an example of a script

**Comment by Aspratic** [comment]
A quick test poll made in discussion (at 4:30 am est may i remind you)

**Comment by gullidog** [comment]
We already have recoil script, are you asking us to increase the values? 

**_gullidog_**

**Comment by Rankin11** [comment]
I feel like making weapons not one shot will be so much better will actually make AR'S and big weapons actually have a purpose.Also recoil on certain weapons will just make it more realistic.

**Comment by Aspratic** [comment]
I would also love to have the driver of cars to be able to do drivebys, the other side of this would be to increase car weapon recoil. 
The current recoil is okay for the start but spraying 30 bullets shouldnt be controlable, spray and pray shouldnt be a thing and it should be more calculated IMO

**Comment by ChainedDev** [comment]
Damages changed
