### ISSUE TITLE
GT86 splitters, wings, and skirts

### ISSUE THREAD

**Issue by TheRatSerf** [ChainedDev/CityLife#142]
**Is your feature request related to a problem? Please describe.**
Yes, i cant customize the car very much, even though there is one person with a splitter

**Describe the feature you'd like**
[A clear and concise description of what you want to happen. Include any other documents that may reenforce your idea here. **Spoilers, skirts, and splitters, and also hoods.**]

**Describe alternatives you've considered**
I cant think of any, people already have the already have the parts on theirs, so i dont get why i cant get them
![2020 04 24-22 41](https://user-images.githubusercontent.com/64294831/80269336-d7a1e700-867c-11ea-8691-8d0e787678f1.png)

**Additional context**
[Add any other context or screenshots about the feature request here. **Remove this line!**]

**Comment by ChainedDev** [comment]
You'd have to visit a mechanic and see if the parts suddenly are not 'available' anymore for some reason then we can see what's going on

**Comment by TheRatSerf** [comment]
> You'd have to visit a mechanic and see if the parts suddenly are not 'available' anymore for some reason then we can see what's going on

Ive been to like 4 or 5 mechanics in the past 4 days and they never had the option to put them on

**Comment by Skader91** [comment]
Can confirm, he was in shop last night and all Cosmetics show Stock only

**Comment by ChainedDev** [comment]
Moved to #148
