### ISSUE TITLE
Housekeeper job/Hotel Owner 

### ISSUE THREAD

**Issue by Mike-Hawk** [ChainedDev/CityLife#144]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the feature you'd like**
Be a housekeeper for the Hotel business where people can rent rooms for the night or week. 

**Describe alternatives you've considered**
N/A

**Additional context**
I would like to see RP of people renting rooms and having a party at the Hotel hottub or pool and would be cool to see actually housekeeper cleaning the rooms after people check out

**Comment by ChainedDev** [comment]
Citizens can buy complexes and rent them out themselves
