### ISSUE TITLE
Loans to buy cars and or house

### ISSUE THREAD

**Issue by Mike-Hawk** [ChainedDev/CityLife#145]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
It would be paid back out of everyone check every click it would take a percentage of the income out to pay for the car or house and if they are unemployed they have a amount of days to pay it back. Details to be worked out, however, we also want to set basic qualifications for loan programs. Ex: if your debt to income ratio is too high, you will not qualify until other debts are paid or verified income increase. This decreases desire to focus time on crimes because this is not a verified income.

**Describe alternatives you've considered**
N/A

**Additional context**
I have resources who have worked in the mortgage/finance industry in real life and they are willing to be assets to set up qualifications and basic guidelines that loan originators must follow. We can introduce ways to commit loan fraud as well, if the legal system is at capacity to handle these additional cases.

**Comment by ChainedDev** [comment]
We don't want to head into loans/financing
