### ISSUE TITLE
Fine Prices Re-Balance

### ISSUE THREAD

**Issue by l-Crynic-l** [ChainedDev/CityLife#146]
**What is the reason for this balance request?**

     The fine prices are way too high in my opinion and a lot of people would agree. They're also very unbalanced. They don't fit in with the economy. If someone new decides to pay 60k in fines, theyre going to be in debt forever. They can't even buy food! Officers can say "don't do the crime if you don't want to pay the fine" but the prices for these are a little crazy.

**What solution would you like?**

     I would like the fine prices to re-balanced and lowered according to the economy.

**Additional context**

     Two scenarios that prove my point:

     **Story1**: You kidnap someone and rob a store with a weapon you legally own. Your vehicle that you legally own is parked outside. You treat the hostage well, and you make a deal with the officers to gain free passage to your vehicle. You have the dirty money from the safe and you're ready to go. You and the hostage walk out of the store, you get into your vehicle. You get into a chase with the cops; lets just assume you're driving 80 mph tops and staying on the right side of the road. You spin out somehow and the cops box you in. You give up and they take you in. 
     **Charges**: You're going to get store robbery, felony evasion, possession of dirty money, kidnapping, and brandishing a weapon. **You're going to be fined $26250**

     **Story2**: You have 18 meth, roughly 2k in dirty money, everything needed to make meth, and you were witnessed handing off. Officer comes up yells for your hands, so you get in your car that you legally own. You take off, not too fast, but you somehow spin out, get boxed in, and give up.
     **Charges**: You're going to get possession of class 2 drugs, intent to supply them, manufacturing of them, possession of dirty money, and felony evasion. **You're going to be fined $28500**

     I think its a little bonkers how you get charged more for drug calls than for robbing a store and kidnapping someone. Of course these vary according to the situation, but I think being able to afford and pay fines would just add that option to get out quicker. I can't remember the last time a civilian payed the fines when being sentenced. Both as cop and a civilian, I think the fines currently are 🤯.

**Comment by ChainedDev** [comment]
Prices were already re-balanced a while ago. If you have more fine balances requests please open another issue
