### ISSUE TITLE
No more /carry

### ISSUE THREAD

**Issue by ChiefRiggs** [ChainedDev/CityLife#147]
The /carry feature is getting heavily abused. I see at least 5/6 people carry their friends to pillbox when driving. People have also been calling EMS but then just carrying the person anyways. It is having a major effect on Medical RP.

Please consider removing it as it keeps getting abused or make it so you can't carry when EMS is online

**Comment by NinjaTinaH** [comment]
What if.. cant use that command if EMS are online? Like the system will throw an error message.

**Comment by slimjimtim** [comment]
I don't like the idea because the EMS are barely every online and a lot of people would get screwed if the feature was removed.

**Comment by l-Crynic-l** [comment]
The /carry feature should only be available when EMS are offline and the person carrying them isn't driving. It should also be available up in Sandy and Paleto but while EMS are on, as ground unit EMS rarely go up there.

**Comment by JJG1997** [comment]
I think /carry should still be a thing but have it so if you're carried to hospital when EMS are available, you need to be treated by them in the hospital. This means they still get some RP out of it :)

**Comment by JJG1997** [comment]
And if you see anyone carrying while driving, report them.

**Comment by ChiefRiggs** [comment]
> I don't like the idea because the EMS are barely every online and a lot of people would get screwed if the feature was removed.

Ems are on very often. Don’t know what your talking about

**Comment by iDulvious** [comment]
They should upgrade the prison system. If you go to prison there is nothing to do. Allow people to go to the court yard and get a prison job to earn a bit of money. Add prison guards that patrol the court yards. Prison should have Prison RP. All I see when im pinched is people going AFK in their cells and its really boring.

**Comment by NinjaTinaH** [comment]
> They should upgrade the prison system. If you go to prison there is nothing to do. Allow people to go to the court yard and get a prison job to earn a bit of money. Add prison guards that patrol the court yards. Prison should have Prison RP. All I see when im pinched is people going AFK in their cells and its really boring.

Make another topic please. This one is on /carry and EMS.

**Comment by ChainedDev** [comment]
Moved to #173
