### ISSUE TITLE
Add more cosmetics to car e.g (evo, rx7 and gt86).

### ISSUE THREAD

**Issue by KaneCallaghan** [ChainedDev/CityLife#148]
**Is your feature request related to a problem? Please describe.**
yes everyone wants to make theyre car look better and cant as im not sure as i went in once and they had the bumpers then the next day they didnt please fix

**Describe the feature you'd like**
I would like you to add bumpers,spoilers,skirts and exhausts etc. to all the addon cars as we know you can as i seen them on other cars in the city and on the gta5 mods website on the car

**Describe alternatives you've considered**
none

**Additional context**
none

Thanks

**Comment by ChainedDev** [comment]
Moving to #156
