### ISSUE TITLE
Notes/Notepad

### ISSUE THREAD

**Issue by JJG1997** [ChainedDev/CityLife#150]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
The ability to buy a notebook/pad where we can write our own notes. Keep them in our pockets or drop them. This can be used for advertising (dropping notes at highly populated places) or when you have killed someone and you want to send them a message you can drop this in their pockets.

https://forum.cfx.re/t/releases-esx-notepad/655595?__cf_chl_captcha_tk__=d535994c3ec23b117fafa0eb027ec8a8c883a118-1587988116-0-AXaQ2U_x4Lm34x8Pni4xIAPrpMJIEQUIQsEk-nDQv3X2nKRET4KBUJ11fFzLoJLH8o_-teO9bb4cBT4sqzfHppqhN3eGYD0HeMu7zgd-fFp0Pi8XitaoVLRBKF6xMZvFRu4IOOTUpocPWTEEMnSddCovPaGf9HAaJEiGBikjsVHFiA8grUBktefjlxb0zAmeWb_BlfPF9wiVJQ2kF3dd5Ipf3-Hrh4hKhgQ5eTmRIxyeYTayGNSPk1Q9jtXQUQKRSdUW2GGi1Yi3W_ny6ORZCoDgkckiUSrQFZ9JeL7ovTMrycJMa_oksdzdmFEfRsEuCU3MFW3d7T_gUJrVDSSxwsfCK386f6lR8wiRA1FO4srgK2uLRsGd5yrAqWe0j1c6cQn9LrCrYDXd_CHmIQlqwee-o_QP74fYWZCiM-rrJA4ob7UC1qy8gL9dpoCcrW4wR5PgXk2QTH8oGgB2bpJiLJX6jROHPzRJEsHiEypzAobV6tg3BHYHEW5i5jlHSOggGIEe51_jya8SOMmVkhoII9-3z9zQCn0FW0fLCdXUw6PoFhuPuQ4KHWJ4gxOEyXnpbQR2wt5VLPRQUeEapU45e_I

**Describe alternatives you've considered**
None

**Comment by ChainedDev** [comment]
when you have killed someone and you want to send them a message

Isn't this meta-gaming? And why would you need to kill someone to leave them a message?

**Comment by ChainedDev** [comment]
Added
