### ISSUE TITLE
MDT hardly opens

### ISSUE THREAD

**Issue by Jnismoth** [ChainedDev/CityLife#151]
Whenever you open the MDT its either instantly or can take a minute or two. This is terrible in traffic stops and has made people run numerous times personally.

**How to Reproduce the Behavior**
Literally clock in and press L

**Expected Behaviour**
For it to open instantly

**Comment by l-Crynic-l** [comment]
Adding to this - if you attempt to open it in a traffic stop and then the person takes off, it might load in during a chase which could cause us to lose control of the vehicle.

**Comment by ChainedDev** [comment]
Should be fixed now?

**Comment by ChainedDev** [comment]
Going with fixed.

**Comment by JJG1997** [comment]
Not an issue anymore, just a suggestion as I know it was talked about. 

Any way we can get the MDT to auto add up charges, and so we can jail them direct from the MDT?
