### ISSUE TITLE
Musket only for hunting

### ISSUE THREAD

**Issue by Jnismoth** [ChainedDev/CityLife#153]
**Is your feature request related to a problem? Please describe.**
Yeah the fact 10-13 calls are always on the highway and extremely annoying
**Describe the feature you'd like**
Make it so you can't hunt unless using muskets or against the rules. Its annoying constantly seeing these damn 10-13 calls on the highway lmao.

**Comment by ChainedDev** [comment]
Community thoughts on only musket?

**Comment by ChainedDev** [comment]
Just looking back at this and even if they were using a musket there would still be a 10-13 call, we could make it so musket's don't give the alert however it would work that way anywhere else in the map causing guns people can use in crimes knowing they will get away with it
