### ISSUE TITLE
Make it so Officers can drive with controller

### ISSUE THREAD

**Issue by Jnismoth** [ChainedDev/CityLife#154]
**Is your feature request related to a problem? Please describe.**
Yeah when we drive with a controller it pulls up the MDT
**Describe the feature you'd like**
Just make it so we can drive without the MDT coming up. It can be really annoying and I prefer using a controller as it helps with more precise movements.

**Comment by ChainedDev** [comment]
Can you give more detail on when/how controller messes with it

**Comment by Jnismoth** [comment]
Well its just whenever you accelerate it pulls open the MDT. Thats pretty much it.

**Comment by ChainedDev** [comment]
Should be fixed now
