### ISSUE TITLE
Personal garage

### ISSUE THREAD

**Issue by vapeslinger** [ChainedDev/CityLife#157]
**Is your feature request related to a problem? Please describe.**
Personal garage at your owned property to store cars.

**Describe the feature you'd like**
To have personal garage to store your personal vehicles in and implement a key system for houses instead of the codes to make sharing a home more pleasant and streamer friendly. That way any key holder can store vehicles there as well but I also feel like that’s going to change the whole garage system to you can only pull your vehicle out where you last stored it I am only requesting this because I’ve seen it before and it seems more realistic.

**Describe alternatives you've considered**
[What alternatives solutions have you considered? **Remove this line!**]

**Additional context**
[Add any other context or screenshots about the feature request here. **Remove this line!**]

**Comment by ChainedDev** [comment]
Interesting, we def have plans to have it so each car can be stored in only 1 garage and same for garages at properties

**Comment by sabas2002** [comment]
i find that this is only needed when you have your own house tho
