### ISSUE TITLE
Faster PD motorbikes

### ISSUE THREAD

**Issue by Wizmex** [ChainedDev/CityLife#158]
**What is the reason for this balance request?**
The PD bike compared to the PD vehicles is really slow. The bike goes about 125 - 130 and is not upgradeable. Vehicles like the shafter hit 150 and even the charger goes faster. I am not asking to make the PD bike the fastest around, but a motorbike of the PD should be able to do high speed chases as its a bike. 

**What solution would you like?**
Well in order to balance the bike with the other vehicles it would be the easiest way to up the bikes speed. like i said above the bike goes about 125 - 130 MPH at this moment. I think if we could up this to around 150 - 155 MPH it would be good, it would be faster than lets say a not upgraded shafter but than slower than an upgarded one. The bike would also still
 be slower than the PD charger.

**Additional context**
No Additional context needed.

**Comment by Forkedup** [comment]
Thanks for the report, I’ll take a look at the bike, and make adjustments where they’re needed.

**Comment by ChainedDev** [comment]
Old suggestion
