### ISSUE TITLE
Prison RP (CRISIS)

### ISSUE THREAD

**Issue by iDulvious** [ChainedDev/CityLife#160]
They should upgrade the prison system. If you go to prison there is nothing to do. Allow people to go to the court yard and get a prison job to earn a bit of money. Add prison guards that patrol the court yards. Prison should have Prison RP. All I see when im pinched is people going AFK in their cells and its really boring.

**Comment by Wizmex** [comment]
This would indeed add a very big and nice aspect of RP to citylife!

**Comment by ChainedDev** [comment]
Follow the template please

**Comment by ChainedDev** [comment]
Duplicate of #32
