### ISSUE TITLE
MRPD Revamp

### ISSUE THREAD

**Issue by Skader91** [ChainedDev/CityLife#161]
**Is your feature request related to a problem? Please describe.**
The current model for MRPD is outdated, we don't have a gate, there is a "door" where the gate used to be. It's tiny and not pleasant to look at when inside.

**Describe the feature you'd like**
https://www.gta5-mods.com/maps/community-mission-row-pd

**Describe alternatives you've considered**
Dealing with what we have

**Additional context**
This allows for better and more immersive SASP roleplay with the addition of a medical wing, multiple conference rooms, better lockup, better interrogation rooms, armory.

**Comment by slimjimtim** [comment]
that looks pretty nice
