### ISSUE TITLE
Pd boat

### ISSUE THREAD

**Issue by littlewilms** [ChainedDev/CityLife#162]
Is your feature request related to a problem? Please describes 

Add police boats for pd as many people have recently been jumping into the sea with no way for us to pursuit them 

**Describe the feature you'd like**

https://www.gta5-mods.com/vehicles/custom-offshore-lspd-lspd-v1-0-beta

Gives pd a chance to actually pursue a chase instead of someone just swimming out to sea so we can’t catch them

**Comment by ChainedDev** [comment]
If air one's in the sky then they could track them for now although it would take a lot of time and resources

**Comment by Rankin11** [comment]
Helicopters can only be used if there is a appropriate amount of officers on, and you have to be air-1 certified to fly.

**Comment by ChainedDev** [comment]
> Helicopters can only be used if there is a appropriate amount of officers on, and you have to be air-1 certified to fly.

So should boats

**Comment by littlewilms** [comment]
All good air-1 tracking them but air-1 can’t do anything to catch them as it’ll have to land to refuel eventually

**Comment by Forkedup** [comment]
Police boat has been added, thanks for the suggestion.
