### ISSUE TITLE
Stopping people from dying from falling through the world or spawning in the sky when they join the server

### ISSUE THREAD

**Issue by ThomasBonelli** [ChainedDev/CityLife#163]
A lot of people have experienced spawning into city life just to see themselves high up in the air falling down or under the ground falling into an abyss.

I think that it would be a great addition to the city if for the first 15 seconds when you come to the city you would be invincible. Therefore preventing people from dying as soon as they get in the city.

**Comment by ChainedDev** [comment]
Never experienced this before, could you possibly get a clip when if you see it happen to you again?

**Comment by ThomasBonelli** [comment]
Yeah, if it happens again I'll clip it and make a ticket.
