### ISSUE TITLE
carspace 

### ISSUE THREAD

**Issue by sabas2002** [ChainedDev/CityLife#164]
**Is your feature request related to a problem? Please describe.**
no 

**Describe the feature you'd like**
I know It is a possibility to change the weight of every item, now a fishbait weights like 1kg so you can store a limited fishbait of 10-40. I find this very unrealistic and frustrating. 
**Describe alternatives you've considered**
an alternative would be that the storage would get bigger but that would be more unrealistic. 

**Additional context**

**Comment by ChainedDev** [comment]
Reworked
