### ISSUE TITLE
fishing and prices

### ISSUE THREAD

**Issue by sabas2002** [ChainedDev/CityLife#165]
**What is the reason for this balance request?**
fishing is the most popular way of making money at the moment if I'm not mistaken, but I find that the prices don't really match you normally make around 1100-1800 every 15-20 minutes.
 also, the fishing chance is very weird like come on, getting a trout 60% of the time, if this was real life those species would be dead by now, also getting those fish in the ocean where it is 2km deep. I don't think so. 
**What solution would you like?**
a slight increase in the prices 35->45, 50-> 60, 55->75 and 100 -> 125 the fishes that are the rarest like the stingray should be more worth than 85 around 200 because you don't find those fishes very often.  I also would like to see a small decrease in the chance of getting a trout and more of the other fish(an increase of 10%-20%). just to balance somethings out
**Additional context**
I think there is a second option instead of changing the prices you could let us say increase the amount of fish bait we can have in our inventory/car(make the bait much lighter )

**Comment by Msblueshines** [comment]
I agree, 1 warm shouldn't weigh 1 pound. That's super unrealistic. Not only that but 1 gram of weed isn't 1 pound. All this does it make it harder to make money. Its already hard as it is. If they don't want everyone to fish create other jobs or make the other jobs pay more.

**Comment by ChainedDev** [comment]
Fixidith
