### ISSUE TITLE
Issue bans for misuse of in game OOC

### ISSUE THREAD

**Issue by TerryDavis-CL** [ChainedDev/CityLife#166]
**Is your feature request related to a problem? Please describe.**
Yes. The problem is pepegas trying to use in game OOC as a play through guide for the server. These are squeakers trying to play GTA in a modded server and somehow landed here. The problem is they flood OOC daily with "how do I rob?" "how do sell drugs?". Immersion ruined. 

**Describe the feature you'd like**
I would like to see a swift ban issued to people who misuse OOC specifically for meta game purposes like the ones described above.

**Describe alternatives you've considered**
Instead of a ban we can either publicly shame these people in the legion fountain or issue them 10 minutes in the citylife gulag with me, Frank and Gaz

**Additional context**
You can find context in in game OOC. Guarantee you can open it at any point in time and there will be some idiot asking dumb shit.

**Comment by SuperHornet14** [comment]
another thing that can be done is keeping the chat always frozen and the only time it can be unfrozen is when staff are contacting people. If they need help with something they should go to the support channel or the useful infomation channel and not the OOC chat in the city

**Comment by NinjaTinaH** [comment]
Even muting those ppl so others can properly use that ooc helps :x
