### ISSUE TITLE
diving job

### ISSUE THREAD

**Issue by sabas2002** [ChainedDev/CityLife#167]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like**
so you can dive with you're equipment you need to buy at the tool store so that you can go diving for wrecks or to dive for corals. https://forum.cfx.re/t/release-esx-ocean-salvage-job/137770

**Comment by ChainedDev** [comment]
Very nice

**Comment by ChainedDev** [comment]
interesting

**Comment by Tiquoti** [comment]
Please no ;-; theres already too many legal jobs that aren't rp based

**Comment by EDGIES** [comment]
I would like to add on to the ticket to make a request for at least scuba diving. Lately I see a lot of people dumping bodies in the ocean and would like to start a small business to do a search and rescue. The gear is already available at the clothing store but the oxygen level will have to be reworked and the scuba oxygen tank. (It doesn't like to stay on when equipped a the clothes store).

**Comment by ChainedDev** [comment]
Old issue, moving into #460
