### ISSUE TITLE
Find alternative to taking phones when sending people to jail

### ISSUE THREAD

**Issue by TerryDavis-CL** [ChainedDev/CityLife#169]
**Is your feature request related to a problem? Please describe.**
Problem is that white names and default dannys use their phones in jail. Now phones are being confiscated before jail. When you get out of jail you have no way to call a taxi, uber or a friend to get you. This obviously makes it impossible to get back to the city when you are out.

**Describe the feature you'd like**
Maybe disabling the phone while in jail. Or ban people who use it while in jail. That's what we used to do and it worked well.

**Describe alternatives you've considered**
Allowing ONLY Terry and Roman to have phones in prison. 

**Additional context**

**Comment by TerryDavis-CL** [comment]
This also results in spending another $400 for a new phone. When you arent just grinding money all day thats a lot.

**Comment by ChainedDev** [comment]
You can't use your phone anyway while in Jail

**Comment by slimjimtim** [comment]
sometimes they don't take your phone

**Comment by ChainedDev** [comment]
If you see people abusing this please let us know!
