### ISSUE TITLE
Items on Ground Above Max Carry Limit

### ISSUE THREAD

**Issue by l-Crynic-l** [ChainedDev/CityLife#170]
**Describe the bug**
If you can hold a max of 20 of item "x" and 40 of it is on the floor, there is no possible way to pick it up.

**How to Reproduce the Behavior**
Steps to reproduce the behavior: Only way I can think of is to process meth and get more than 30, which is its max. You can hold it, but as soon as you drop it all in one. it will be stuck there until a tsunami.

**Expected Behavior**
It should just pick up as much as it can. If you have none of item "x" and its max is 20 and there's 40 on the ground, when you try to pick it up, you will pick up 20 from that 40, and then there will be 20 left on the ground.
Or, when you open the inventory there should be a "Nearby" part to drag custom amounts of the items on the ground into it.

**Comment by ChainedDev** [comment]
Looking into reworking dropped items as well as dropped guns glitching

**Comment by ChainedDev** [comment]
FIX IT NOW

**Comment by ChainedDev** [comment]
Fixed with new inventory
