### ISSUE TITLE
/carry

### ISSUE THREAD

**Issue by yggun** [ChainedDev/CityLife#173]
**What is the reason for this balance request?**
Bruh, EMS RP sucks ass now everyone /carry's their friends to pillbox. I was on EMS for 3 hours yesterday and responded to 3 calls. We had 5-10 active EMS every day and now we have none because there is nothing to do. I watch countless amount of people come to pillbox with their friends and dont even bother to ask the EMS for help. 

**What solution would you like?**
Tony, I am very sus. make it so when EMS are on duty people cant use pillbox. Like a message pops up where the "Press E to check in" is and says something along the lines of "Doctors are unavailable right now. There are EMS on duty, go find them!" 

**Additional context**
Something like this will increase the EMS RP and force people to call medics.

**Comment by Aspratic** [comment]
I would love this to be added once doctors are a thing. The reason most people carry there friends is because people get hospitalized a lot of times (or have in the past) and the reasoning is they dont want to be hospitalized. The RP isn't good by people doing this but no one can blame them.
Anyways this would be a +1 for me if doctors are implemented.

**Comment by yggun** [comment]
Personally, I rarely hospitalize people unless i know for a fact it was an explosion or an extreme gunshot wound. I try to teach my EMT's not to hospitalize people unless needed. People shouldn't be worried about being hospitalized because they'll lose their gun. They should be more worried about their life than losing a gun. IMO that's the main reason people carry their friends. Hospitalizing people has no negative other than losing your weapon that's why people are so afraid. But anyone that knows my EMS character knows i do not hospitalize easily.

**Comment by yggun** [comment]
There are just no need for EMS in the city if people are just going to continue to /carry their friends.

**Comment by Aspratic** [comment]
Yeah I 100% get where your coming from, but we can't change how people act. In the past hospitalizations were very common and we have to try and change that. People aren't going to do it for the RP so we have to meet somewhere in the middle, I think doctors are the best compromise. Then EMS and Doctors will get good rp and we can restrict the /carry and having their friends bring them to the hospital

**Comment by CosmicMe0w** [comment]
I think that having the /carry as an option is important for those times that EMS are not available, or other special circumstances. I don't think the solution is getting rid of it completely. In other servers, they are very strict that if you are downed and do not at least try and wait for EMS, it's a bannable offence. If we had EMS able to treat people when they're checked into Pillbox, that would definitely add to their RP experience as well.  Just have to make the expectations known to everyone, and hopefully they listen.

**Comment by yggun** [comment]
I dont want to get rid of it i just want it so that if EMS are on duty you cant check in to pillbox. you are going to have to wait for EMS or find them.

**Comment by ChiefRiggs** [comment]
The reason a lot of people got life flights was there lack of RP when injured. If your not going to RP out your injuries EMS can’t help you. 

I say only 2/10 people really RP out injures others just say “ I hurt my knee”

**Comment by ChainedDev** [comment]
Can't sell clock in if more than x medicals online? Possibly illegal spot?

**Comment by JJG1997** [comment]
Can be checked in if EMS are online but you get put into a bed to be assessed and treated for injuries maybe 🤷‍♂️
