### ISSUE TITLE
F92SellDrugs

### ISSUE THREAD

**Issue by Skader91** [ChainedDev/CityLife#174]
**What is the reason for this balance request?**
Currently, everyone is bitch made and will stock up on their drugs then login late at night whenever cops are not usually present to sell drugs. The only drug calls cops are getting are people that are new and are selling pot.

**What solution would you like?**
Only allowing the sale of drugs if 2 or more officers are online.

**Comment by yggun** [comment]
Adding to this, make selling territorial. Maybe you can only sell on Grove and Forum or in the ghetto as a whole. I have seen people going into the subway system and selling to locals to make it so cops get confused from the GPS locations.

**Comment by Aspratic** [comment]
Dont agree with the first point, people shouldnt be limited to selling when cops arent on, it is the PD duty to hire people for different timezones. However territorial selling would create so many Rp scenarios with crim to crim interactions, and crim to cop interactions.

**Comment by Skader91** [comment]
People shouldn't be limited your right but all they do anyway is wait for it to eventually happen. 
We have people that are Pacific Standard Time and people that are GMT+7.

This isn't about limiting people its about curbing the lets see how many service members are on before I do any action behavior. It happens with Mechs too.

**Comment by Aspratic** [comment]
I think majority of times cops are on anyway, and most people dont wait to sell from what ive seen. Only a select group of people. Not sure if removing the ability to sell when no cops on is the correct solution to this problem, just a band-aid

**Comment by Aspratic** [comment]
However I don't think people should be selling without any cops on, but adding something like this removes other potential RP. If there are no cops on, people can still have gang to gang interactions with people selling on their block etc.

**Comment by Aspratic** [comment]
Instead of restricting the sell mechanic, limit the areas to sell in. Because that helps fix the problem either way if cops are on or if they're not on. As well as helping the problem of people going far far away from normal sell locations such as los santos airport, no one in their right mind would sell drugs at an airport. When cops are on they have to drive 5-10 minutes just to get to an area and then they are already gone. Southside and vinewood would be my recommendations for area restrictions for selling drugs

**Comment by Skader91** [comment]
Sounds like ya'll need to make your own suggestion. ;)

**Comment by Skader91** [comment]
I stand by mine, people be F9'ing before engaging in anything and making sell locations regional has nothing to do with that.

**Comment by TerryDavis-CL** [comment]
What you are suggesting would remove all criminal RP during the hours cops are not on. At the moment the only crim RP we have is selling drugs or robbing a store. We should not have to wait for cops to be around to RP.

**Comment by Skader91** [comment]
Walking up to locals and pressing E is RP?

**Comment by TerryDavis-CL** [comment]
You’ve never seen me sell drugs. Anyone who has done it with me can tell you I have a sales pitch for every single local. I don’t make the mechanics, I just use them.

**Comment by TerryDavis-CL** [comment]
And weak game mechanics are not a reason to eliminate crim RP when there are no cops on. Maybe PD should hire some people in the impacted time zones 🤷🏼‍♂️

**Comment by Skader91** [comment]
What's weak is the attitude of, I will stockpile drugs then sell them when it's not possible to face repercussions.

**Comment by Skader91** [comment]
I know you are correct that it shouldn't punish everyone but unless someone actually has a better solution then your opinion isn't valued.

**Comment by TerryDavis-CL** [comment]
The better solution is to hire more cops. I know I’ve been trying to get hired for a week myself. Whoever stockpiles drugs for when cops aren’t online is bitchmade and should be shamed publicly. You can look at my record and will wee multiple arrests for distribution. I sell drugs during the day and get caught 75% of the time

**Comment by TerryDavis-CL** [comment]
Stockpiling drugs to sell when cops aren’t online is kind of abusing mechanics and definitely both metagaming and fail RP. Those people who are doing this have a win mentality and are not here for RP. They should be dealt with accordingly

**Comment by Skader91** [comment]
I just don't think the best solution is to make sure a cop is present in the city at all times, yes that's ideal but not realistic. We currently have 44 officers (Not counting Cadets)

Not sure if you want cops from Guam and shit.

**Comment by Aspratic** [comment]
I personally think the best option is a mixture of things, theres not 1 sole fix or else someone would've already came up with it

**Comment by TerryDavis-CL** [comment]
I strongly believe that Guam PD would be an excellent source of RP.  Is this a real possibility? If not Guam what about Dubai PD? This is the answer to ALL of our problems.

**Comment by l-Crynic-l** [comment]
^ +1 
Go Guam!!

**Comment by yggun** [comment]
Dubai hours when the Police Lambos come out kek

**Comment by DaPlugKilo** [comment]
I like how it is already the drugs already don't go for much plus is doing too much just to obtain you feel not just that just for the drugs to sale more back in there old update it said they needed it to be 7 or more cops online for it to sale for 75% so keep it like it is or it will break the game an any other gangs or drug role player would lose value in taking that rout to role play

**Comment by Wizmex** [comment]
What about making durgs become more valueable by cops activity, 
When no cops are around and you sell you will get the lowest price,
When 1 - 2 cops are on this price will increase
And so on.

In that way people will be temped to go for the biigger price when more cops are around.
With this you also don't have to limit sellers too have atleast 2 cops around.

**Comment by Skader91** [comment]
That's been talked about before and is worth a shot imo,
