### ISSUE TITLE
1 Shot headshot

### ISSUE THREAD

**Issue by Rankin11** [ChainedDev/CityLife#175]
**What is the reason for this balance request?**
So weapons,that are not as good as others are just able to one tap you,such as pistols.

**What solution would you like?**
Dont make any weapons one shot,it is just unfair,and it would increase gun fight Rp by a ton.

**Additional context**
This will be alot better because the Ar's that people pay alot of money for arent just useless and they actually have a better use,and keep people from one tapping in gun fights with only pistols.

**Comment by Aspratic** [comment]
Bullet damage need to be decreased by a lot, and headshots should have a wayyy lower headshot bonus than how it is atm.

**Comment by slimjimtim** [comment]
I mean it's supposed to be like real life and it doesn't matter what gun someone uses, if you get a bullet in the head you're dead

**Comment by Aspratic** [comment]
> I mean it's supposed to be like real life and it doesn't matter what gun someone uses, if you get a bullet in the head you're dead

noo you couldn't be more wrong in this aspect. This isn't a real life simulator and i think a lot of people get that confused... it's roleplay, situations are supposed to be exaggerated and fun, it's a game. Having it be a real life simulator would not be fun and it's not currently set up for this. It is a game and some aspects of the game should not be in relation to real life.

**Comment by Aspratic** [comment]
Roleplay is not supposed to be real life. Robberies every 5 mins, shootouts, drug deals. Half the people would be working 9-5 and if you shot someone u get 15 years minimum. Doesn't sound like much fun to me

**Comment by Aspratic** [comment]
But having extended gunfights allows for more intense situations and EXPANDS roleplay and allows time for every side to experience RP, Criminal vs criminal and allows cops to try and do their job. When someone dies in 1 bullet, no one gets caught and it's not fun for any side. A long gunfight win is 100x more satisfying than killing someone in 10 seconds

**Comment by DaPlugKilo** [comment]
A head shot is a head shot if you get shot in your head that should already be an instance death theres no role playing from that some people don't want to get caught cause half the time they get hit with more charges then there suppose leave the city an headshots like it is some where your coming from I can see 50% an the other I cant your asking for people to go to jail plus police got a fast response time to gunshots ammo would cost so much an theres so much more but its like bro by police come the criminal be out of ammo an they police just going shoot them down with no role play an take em to jail keep it like it is what I think tbh.

**Comment by Aspratic** [comment]
> A head shot is a head shot if you get shot in your head that should already be an instance death theres no role playing from that some people don't want to get caught cause half the time they get hit with more charges then there suppose leave the city an headshots like it is some where your coming from I can see 50% an the other I cant your asking for people to go to jail plus police got a fast response time to gunshots ammo would cost so much an theres so much more but its like bro by police come the criminal be out of ammo an they police just going shoot them down with no role play an take em to jail keep it like it is what I think tbh.

Had an insanely hard time reading this but, explain to me how this creates more RP? To me I only see it limiting RP at the current state

**Comment by slimjimtim** [comment]
it's not that easy to hit a headshot though unless you're using some sort of external crosshair

**Comment by Aspratic** [comment]
Yeah because majority of players dont... Kappa. Solve the problem before it starts, not after its already a problem.
