### ISSUE TITLE
Suggestion for new job or feature (stringing)

### ISSUE THREAD

**Issue by toastedbagels** [ChainedDev/CityLife#176]
**Is your feature request related to a problem? Please describe.**
No problem, however I noticed the "news" section on the phone is unused. 

**Describe the feature you'd like**
Have you considered adding a "stringer" profession, where someone can purchase a camera and police scanner and do freelance work chasing stories throughout the city. They could be posted in the "news" section of the cell phone. You could either have media outlet bosses who do 'payouts' based on the quality of the news they receive, or perhaps it could be coded to reach certain tiers of payout depending on what is captured.

**Describe alternatives you've considered**
This could be done with twitter photographs when it is functioning, but there would be no way to earn money from it.

**Additional context**
 It would be really cool if there was a way to type up a short story along with your photos or videos which would encourage players to try and get interviews with criminals / police involved in situations. This would create interesting RP scenarios of the police getting annoyed by stringers, or looking like heroes.

**Comment by ChainedDev** [comment]
Good idea and would love to have something like this become a possibility however, this probably would just end up being tied into Weazel News instead of adding in a completely extra job

**Comment by ChainedDev** [comment]
If we were to add Weazel News as whitelisted, would anyone be interested in actually being dedicated and running it?

**Comment by Ashytoon** [comment]
I thought it already was whitelisted?

**Comment by ChainedDev** [comment]
> I thought it already was whitelisted?

nop

**Comment by Ashytoon** [comment]
> > I thought it already was whitelisted?
> 
> nop

think there would be quite a few people down to run it/be a reporter

**Comment by ChainedDev** [comment]
Moving into #479, I think we got the right man for the job!
