### ISSUE TITLE
Suggestion of new role (confidential informant)

### ISSUE THREAD

**Issue by toastedbagels** [ChainedDev/CityLife#177]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem, however in this game people freely talk about illegal activity and gang connections in ways that are not realistic. I understand why, I have been playing as realistically as possible and not 'being nosey' and prodding with questions and it's been difficult to break into a crew or do crime with other people. To me, it's a little unrealistic how people talk about criminal activity. Most people are not willing to be a witness unless they are defending a friend. 

**Describe the feature you'd like**
It would be cool if you could become a confidential informant, either through recruitment, or perhaps to get out of a charge if you are willing to "roll" on your fellow gang members. You should have to wear an item in your inventory called "a wire" in order to prosecute your fellow criminals. You should have rules about what kind of crime you yourself can commit without fear of prosecution. You should be paid relatively for the size of crime families, or specific crimes that you stop. This would create a real-world sense of distrust of people who are not "vetted" by other connected criminals. People might have to start searching each other to see if they are wearing a wire, or perhaps it's taboo to do so and people need to go by another person's "word". 

**Describe alternatives you've considered**
This could be done without any new items, however than it's your word against there's. Police would need to ability to access Government funds to effect some kind of payment.

**Additional context**

**Comment by NinjaTinaH** [comment]
Dunno, it depends who you talk to? Also an easily known role to everyone outside the CID is dangerous in cases of metagaming, both concious or not.

**Comment by toastedbagels** [comment]
Yea sorry, i wasn't trying to make an absolute comment. Some people are a bit more careful than others, and really it's just a game so you can't be perfect.  It might not be feasible, and could create problems. I am interested to know what people think about it.

**Comment by ChainedDev** [comment]
Become snitch rp bwo

**Comment by ChainedDev** [comment]
This is an element that needs to be RPed out
