### ISSUE TITLE
PD Car Changes

### ISSUE THREAD

**Issue by Aspratic** [ChainedDev/CityLife#179]
**Is your feature request related to a problem? Please describe.**
The current issue is that the PD looks like some special unit like the FBI or damn robocops with the current Liveries, also the current ones are not all the same (to my knowedge)

**Describe the feature you'd like**
What I would like to see is the liveries change to more appealing ones. I want the PD to look like an actual police department and not the US ARMY. I can easily send matching outfits to also make our PD look more professional.

**Describe alternatives you've considered**
There are many alternatives such as this popular LAPD based car pack. Picking 3-4 of these would greatly increase the look and professionalism of our PD and make the PD appear to be on the same page. 
My car choices would be as follows:
Crown Vic
Tarus
Charger
Explorer
Tahoe
Maybe the Impala, not sure though
(other unmarked cars currently in PD are fine as only certain members can use them)
https://www.lcpdfr.com/downloads/gta5mods/vehiclemodels/19912-lspd-mega-pack-els-lapd-based/

**Additional context**
![image](https://user-images.githubusercontent.com/52019072/81251684-da43fb00-8ff1-11ea-8e75-a5640becb7d7.png)

![image](https://user-images.githubusercontent.com/52019072/81251720-f051bb80-8ff1-11ea-9ff2-cda74b91f421.png)

![image](https://user-images.githubusercontent.com/52019072/81251743-00699b00-8ff2-11ea-9665-96f4dd3ddd6d.png)

**Comment by Skader91** [comment]
State police are more equipped than your local PD and should represent as such.

**Comment by ChainedDev** [comment]
New liveries have been added that look similar to the designs above.
