### ISSUE TITLE
Street Racing 

### ISSUE THREAD

**Issue by StikyLicky2** [ChainedDev/CityLife#181]
I think it would be neat to add street racing into the city. Make an app on the phone for racing. when people link up and want to join the race you can open the phone, click on racing than join race. after joining the race there will be a countdown until the race begins. the map would show you the track layout with checkpoints. when joining a race you could place wagers.there could be multiple tracks on the phone app and you choose which race you would like to do. For example. 10 people show up to a location and want to race. They choose the track to race. The make a wager or entry fee say $500. to join the race you click the app on your phone and join. when joining you will pay the $500 and be entered in the race. countdown will begin until race is ready. they race through the checkpoints and when the race is over whoever wins gets the pot. pot could also be split however you want. if you want to pay 1st 2nd and 3rd you can.

**Comment by ChainedDev** [comment]
We used to have a street racing script but no one really used it, do you guys want it again?

**Comment by ChainedDev** [comment]
We just teased with an improved version last night/this morning. More to come soon 👀

**Comment by ChainedDev** [comment]
👀 Check our update log in discord! https://discord.gg/CLRP
