### ISSUE TITLE
Mugging NPCs

### ISSUE THREAD

**Issue by slimjimtim** [ChainedDev/CityLife#182]
**Is your feature request related to a problem? Please describe.**
Not really, but could create more rp for cops and random players.

**Describe the feature you'd like**
The mod is better described on the forum page but basically if you aim a gun at a civilian you can press e or something to mug them. On default settings you get between 5 and 100 dollars (which I think is too low) and has a 40% chance to alert a cop. Both of these can be changed to whatever you want along with other things explained on the actual page.

**Additional context**
The forum link is https://forum.cfx.re/t/esx-mugging/546591. If this mod doesn't look very good but if you like the idea I think there are a few other mods with the same principle out there.

**Comment by ChainedDev** [comment]
Appreciate the suggestion but this would just add more chaos and spam dispatch reports than the pd already needs
