### ISSUE TITLE
Golf Mini-game

### ISSUE THREAD

**Issue by Tetronas** [ChainedDev/CityLife#184]
GTA Golf is awesome. Great way to blow off steam and adds a unique (I haven't seen any other servers with it) and a medium for some non-violent RP which this city **desperately** needs.

**Comment by gullidog** [comment]
We used to have golf but nobody ever used it.

**Comment by Tetronas** [comment]
Gimme

**Comment by Tetronas** [comment]
Bumping, would love to see this happen, I would definitely play when i'm in city

**Comment by jackofalloffs** [comment]
too bad you are never in the city KEK

**Comment by Tetronas** [comment]
@jackofalloffs 
To bad you never see me

**Comment by ChainedDev** [comment]
Wanna t-up some golf clubs?

**Comment by Tetronas** [comment]
@ChainedDev Yasssss
t-time me bbe
