### ISSUE TITLE
S2000 unrealistically slow 

### ISSUE THREAD

**Issue by RavioliMans** [ChainedDev/CityLife#185]
**What is the reason for this balance request?**
The ingame S2000 is unrealistically slow compared to other cars. In game I own both the S2000 and the EK9 and have noticed the EK9 is much faster than the S2000. On a downhill the EK9 top speed can hit 175 while the S2000 can only hit maybe 120. A real life S2000 has a top speed of 149 while an EK9 is 146. I've also noticed that the panto can reach a higher top speed than the S2000 which makes no sense since the S2000 is a sports car.

**What solution would you like?**
I would like the top speed of the S2000 to be increased because it costs more than the EK9 and is a faster car. The S2000 isnt worth the money at all right now with what its speed is set to.

**Additional context**
I believed that maybe the car was just slow stock so I decided to max it out and only got an increase of maybe 2mph which keeps the car still incredibly slow and only around 120.

**Comment by Madcroc** [comment]
I made major handling adjustments to the Honda EK9 in terms of performance (nerfed).
I also made slight tweaks to the AP2000.

Thanks for the report.

**Comment by Forkedup** [comment]
I made major tweaks to the handling of the Honda EK9's performance (nerfed)
I also made slight buffs to the AP2.

Thanks for the report.
