### ISSUE TITLE
Yamaha R1 motorcycle

### ISSUE THREAD

**Issue by hillkevin99** [ChainedDev/CityLife#186]
**Is your feature request related to a problem? Please describe.**
No. Just a request to add a new motorcycle.

**Describe the feature you'd like**
2008 Yamaha R1 motorcycle! Here is a link where you can download the mod.
https://www.gta5-mods.com/vehicles/2018-yamaha-yzf-r1-addons-tuning

**Describe alternatives you've considered**
I wouldn't complain if you added the Kawasaki H2R either. Here is the link for that one too. 
https://www.gta5-mods.com/vehicles/ninja-h2r

**Additional context**
They are both highly popular motorcycles that I think many people would enjoy!

**Comment by Msblueshines** [comment]
This would be awesome i would for sure buy one these

**Comment by Forkedup** [comment]
Thanks for the vehicle suggestion, we definitely need more motorcycles in the city! I’ll take a look at this bike.

**Comment by Forkedup** [comment]
Closing as it is similar to another suggestion. Will be adding new bikes very soon. 

Thank you 👍
