### ISSUE TITLE
Real Estate Horizontal Monopoly (Dynasty 8)

### ISSUE THREAD

**Issue by Tetronas** [ChainedDev/CityLife#187]
**What is the reason for this balance request?**
Dynasty 8 currently is currently the sole distributor of real estate in CLRP. This is creating a high concentration of products (housing) which is harmful to a free market model and discourages competition. 

**What solution would you like?**
In order to encourage competition, we should create a second real estate company.

**Additional context**
Without a second company to compete against, buying property is a binary decision. If we create a second company, advertisement, negotiation, and friendly competition would all be added to a Non-Crime RP experience.

**Comment by jorhanstahl01** [comment]
I believe a second estate company would not only allow the roleplay of competition but will give people a chance to seek out best offers based on actions taken by both companies.

**Comment by iDulvious** [comment]
Dont care didnt ask @jorhanstahl01 . I have rebranded the Pacific Standard bank into the Maze Bank and we are trying to implement a Maze Bank Foreclosures branch. We are currently attempting to secure a real estate license.

**Comment by jorhanstahl01** [comment]
@iDulvious I know you're trying to find at least some relevancy with your dumb repetitive comments, yet you lack brain cells to positively contribute to the cause.

**Comment by iDulvious** [comment]
thx

**Comment by ChainedDev** [comment]
Players can buy up properties and rent them out/sell them themself
