### ISSUE TITLE
Name Change access in game for Judge or Justice positions

### ISSUE THREAD

**Issue by Tetronas** [ChainedDev/CityLife#188]
**Is your feature request related to a problem? Please describe.**
Currently, name changes are encouraged through roleplay with a cost associated with them. While the activity is engaging, the turnaround time is terrible.

**Describe the feature you'd like**
In order to make name changes more timely, realistic, and enjoyable. The Judge or Justice in the city should have the ability to access (on his computer or where ever this may be in-game), the names of every citizen in the game.

**Describe alternatives you've considered**
I've attempted to follow through with the original plan of "message me..." This has proven ineffective.

**Additional context**
This may be a large time investment from staff to create this feature. However, I believe that this city could run much smoother by beginning to give positions in the city the ability to act autonomously instead of relying on staff who already have a large task-list ahead of them.

**Comment by ChainedDev** [comment]
Coming soon

**Comment by ChainedDev** [comment]
![image](https://user-images.githubusercontent.com/44199939/99890921-40ad0580-2c32-11eb-8a99-326c574d362e.png)
