### ISSUE TITLE
Courthouse Bugs

### ISSUE THREAD

**Issue by Tetronas** [ChainedDev/CityLife#189]
**Describe the bug**
1) Phase through walls to get underneath the courthouse
2) First person mode

**How to Reproduce the Behavior**
Steps to reproduce the behaviour:
Bug #1) Walls where there are originally doors can still be walked through towards the sides of the courthouse doors
Bug #2) Spawn into the courthouse, enter first person mode, you can now see through walls and floors.

**Expected Behaviour**
Bug #1) I expected to run into a wall, not a door to hell)
Bug #2) I expected to see in first person mode, not becoming omnispective.

**Screenshots**
Did not screenshot, but both are very easy to reproduce.

**Additional context**
N/A

**Comment by ChainedDev** [comment]
Just tested this and couldn't reproduce, if you have a video that would be of great help

**Comment by jorhanstahl01** [comment]
Still a bug.
Inside is glitchy.
Running through wall sends you straight to a 3rd dimension.

**Comment by Tetronas** [comment]
This is still a bug, just walk into the wall adjacent to the courthouse doors.
