### ISSUE TITLE
Radios in offices and homes

### ISSUE THREAD

**Issue by Tetronas** [ChainedDev/CityLife#190]
**Is your feature request related to a problem? Please describe.**
No issue or problem

**Describe the feature you'd like**
I'd like to have a radio in my office to listen to music while doing paperwork, or to have a radio in my home when having a party.

**Describe alternatives you've considered**
Listening out of game destroys verisimilitude. I've also considered driving my car into my house so we have a radio... car doesn't fit.

**Additional context**
N/A

**Comment by ChainedDev** [comment]
There already exists a radio in-game where you can play swift non-copyright songs from youtube

**Comment by ChainedDev** [comment]
(could make them more common tho)
