### ISSUE TITLE
Custom playlists

### ISSUE THREAD

**Issue by Tetronas** [ChainedDev/CityLife#191]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the feature you'd like**
The ability to load custom playlists and to play them on radios in cars and on radios in homes and offices.

**Describe alternatives you've considered**
Listening out of game lacks verisimilitude. 

**Additional context**
Understand that this could lead to some abuse, however, it would be easy to enforce with temp bans.

**Comment by Skader91** [comment]
You can already create what's known as "Self Radio"

It's not possible for other people to hear it but I put my own songs into a GTA5 folder and it plays in game.

**Comment by ChainedDev** [comment]
There are special rare items that let you do this
