### ISSUE TITLE
Whitelist Meth

### ISSUE THREAD

**Issue by Skader91** [ChainedDev/CityLife#192]
**What is the reason for this balance request?**
We already have two drugs avail to the public for easy access, make meth whitelisted for better gang RP

**What solution would you like?**
Remove the all access path to meth

**Additional context**
Tired of seeing default dannies and shit slinging this drug, if we whitelist it and one of the whitelisted gangs down the line controls Meth it would result in better experience.

The van system is alright but has lots of bugs

**Comment by Aspratic** [comment]
Give 2 gangs the ability to do it
create competition
+1 tho

**Comment by Skader91** [comment]
Exactly, There seems to be multiple MC's sprouting up. ;)
