### ISSUE TITLE
Hire More Night Time Whitelisters 

### ISSUE THREAD

**Issue by wolfeelive** [ChainedDev/CityLife#193]
**What is the reason for this balance request?**
We need more whitelist police and ems for night time play. I love to play during the day time and have support of these 2 jobs that open up different role play scenes.

**What solution would you like?**
Balance the applications on night time and day time shifts 

**Additional context**
The city at night time is unrealistic everything is just crazy and with no police people are just bored shooting for no reason or taking cars and crashing them for no reason.

**Comment by ChainedDev** [comment]
This is a issue for the departments not the server. If you want to fill a role during those times feel free to apply
