### ISSUE TITLE
Player Movement/Injuries 

### ISSUE THREAD

**Issue by Gunnar15** [ChainedDev/CityLife#194]
**What is the reason for this balance request?**
Fix player sprint timer, and injuries. You can only sprint for like a good 3 seconds before you are stuck doing a very slow jog for the rest of the time. You literally cant even jump without face planting, same goes with trying to climb anything half the time you just throw yourself into the wall and now your entire body feels pain. 

**What solution would you like?**
The ability to actually jump something without face planting and just pure lack of athleticism of the characters. Actually being able to climb on things without falling over. Longer sprinting distance and or be able to sprint again sooner. Not getting injured so easily, if someone tackles you; you then get some type of injury and then makes your already slow movement even worse. Same goes if you fall over on your own. 

**Additional context**
I think that the way it is now is just to unrealistic and even how it is I shouldn't have my entire body feel pain everywhere just because I fell over.

**Comment by l-Crynic-l** [comment]
Bump

**Comment by ChainedDev** [comment]
> You literally cant even jump without face planting, same goes with trying to climb anything half the time you just throw yourself into the wall and now your entire body feels pain.

Your fault 😅 

Will look into sprinting though
