### ISSUE TITLE
Trucking is garbage

### ISSUE THREAD

**Issue by Farcere** [ChainedDev/CityLife#195]
**What is the reason for this balance request?**
Trucking is a horrible job that nobody does because doing delivery driving is alot faster and has better pay out.

**What solution would you like?**
Increase the reward, having to drive all the way back is awful and the time/reward is abysmal 

**Additional context**
Trucking is a joke

**Comment by iDulvious** [comment]
I used to do Teamsters Trucking Union but our strikes only increased is by a small amount so idk you can take that over if you want.

**Comment by ChainedDev** [comment]
Still Garbage?
