### ISSUE TITLE
Oxy is Scuffed

### ISSUE THREAD

**Issue by Skader91** [ChainedDev/CityLife#196]
**What is the reason for this balance request?**
Currently Oxy doesn't show in your inventory or anything you just go to a few places to sell drugs without actually possessing drugs.

**What solution would you like?**
When you pickup Oxy you get a physical amount that has to be sold. I don't mind the destination method it is now.

**Additional context**
Kinda hard to catch drug dealers if there's no drugs.

**Comment by ChainedDev** [comment]
Then people will just start it to collect all the oxy and not do the missions. That's why you only get them as a rare chance.
