### ISSUE TITLE
Add RP - Lawyer discord channel 

### ISSUE THREAD

**Issue by wolfeelive** [ChainedDev/CityLife#197]
**Is your feature request related to a problem? Please describe.**
It is hard to contact Lawyers because our request in the RP Twitter channel we get lost before seen 

**Describe the feature you'd like**
A channel that we can post that we need a lawyer 

**Describe alternatives you've considered**
So far you can only text them in game or get lucky on the rp twitter channel. I am a late player and 90% of the time lawyers are not on.

**Comment by jorhanstahl01** [comment]
You can always meet me in the city as I'm all the time during EU hours.

**Comment by ChainedDev** [comment]
Added #looking-for-lawyer under DoJ Section
