### ISSUE TITLE
Boats

### ISSUE THREAD

**Issue by JJG1997** [ChainedDev/CityLife#198]
**Describe the bug**
Boats are slightly scuffed, sometimes you can see them and sometimes they're invisible along with the people who are in it.

**How to Reproduce the Behavior**
Steps to reproduce the behaviour: Pull out a boat, sometimes you get lucky and can see people but sometimes you can't.

**Expected Behaviour**
Should be able to see people in the boat aswell as the boat itself.

**Screenshots**
N/A
**Additional context**
N/A

**Comment by ChainedDev** [comment]
Still a problem?

**Comment by JJG1997** [comment]
Yeah :(

**Comment by ChainedDev** [comment]
Still a problem?
