### ISSUE TITLE
Anti-Grinding / Encouraging Role-Play Balancing Suggestions

### ISSUE THREAD

**Issue by rcj0003** [ChainedDev/CityLife#199]
**What is the reason for this balance request?**
Everyone is complaining about the lack of RP and the excessive grinding (and how to fix it), so I thought I'd offer up my thoughts.

The city is a grind-fest. There is absolutely no doubt about that. We know the *what*. However, one thing I have yet to see anyone ask is the *why*.

I'm of the opinion that the economy was intentionally designed to be grindy (in comparison to older versions of the city). I think it served very well (initially), but over time, repeated nerfs to legal and illegal jobs alike have essentially increased the number of hours grinded to money earned ratio.

Around the time I started playing this wipe, you were able to earn about $6.000 to $10,000 by just mining for an hour. Of course, it was nerfed, and now, next to nobody goes mining. Next, we move onto coke. Of course, it was removed altogether, as well as all non-whitelisted drug locations changed. Then, oxy was a somewhat fair source of income, where it was (you guessed it) changed entirely (I'm not sure if it was nerfed per se, but the system for drugs is entirely different now).

Even before the wipe, this was a problem. Popular things in general get nerfed, and then everyone moves to a new thing en masse. Its just a cycle.

For context, what could've taken 9-15 hours to grind before the mining nerf took me and a friend 20+ hours combined to grind out $90,000 (I believe it to be around the 25 hour mark). Money can be an important part of RP depending on your RP play style, and for us, it was. Our play style required us to appear successful and professional, and no one is going to take you seriously if you are driving around a Panto.

So the answer to the question, why are people spending so much time grinding?
Its because you have to grind more to earn less, and you have to do it before whatever you are grinding gets nerfed, as nerfs are always right around the corner. 

**What solution would you like?**
I am proposing a three-pronged plan that focus on the two biggest problems: people will always grind and the economy is increasingly grind-oriented.

***Add new RP-oriented jobs / modify existing ones***
The current jobs are somewhat mediocre and boring. They need to be modified in a way that makes the job "fun" **without ruining the job**. What was done to mining did nothing to change the fact that you just click at a wall for 30 minutes until your car is filled up. I understand why it was done, but it basically ruined the job. It decreased the profit per trip and increased the time a trip took (hence why nobody does it anymore). In general, making tasks longer and more complicated (money wash!) is the wrong way to go about making these jobs more RP-oriented / less grindy.

I'm sure there are some creative ways to improve the current jobs, but I think a better course of action would be to add these (somewhat) RP-oriented jobs,
* Trinket Hunting - this job piggybacks off the already existing scanner system. The idea would be to add in several new items that could be taken to the Pawn Shop and sold. Right now, nobody wants to do this unless they are looking for gun parts themselves. Most buyers offer $150-$300 for a single part that takes 5 minutes to find. Add several new trinkets, averaging in about $600 value (with some being crazy valuable but super rare) and *slightly* increase the density of buried items.
* Food Truck Driver / Server - the implementation of this is probably going to the difficult, but I think it would be nice if you could add a job where a destination is selected while you are driving a food truck, and then when you reach said destination, you have to idle there for about 5-15 minutes. Then, you have to get into the back of the food truck and flex E to start preparing burgers. The location of the food trucks would be broadcasted on the map, and if there is stock available (which you have to refill by making the burgers), then the person can purchase food just like the convenience store. After the time is up, you have to move to a new destination.
* Paparazzi - if you are within 10 feet of a local or citizen, then there is a chance they could be "identified" as a celebrity. When you are not in the vehicle, you can flex E to take a "photo" of them and receive X dollars for taking the photo.
* Bus Driver - this job is kind of a combination of the taxi job and the driving school. Essentially, you'd be given a bus that goes on different routes. Bus stops would be added on the map and riding the bus would be free (generously paid for by the Los Santos Department of Transportation). If you arrived at a bus stop, it would make you idle for a bit as people began boarding the bus. You'd get paid X dollars per stop. Ideally there should be various routes and not just a single route.

***Buff the entire economy / reduce the need for grinding***
Yes, this is (in my opinion) essential to cutting down on the amount of grinding and increasing the RP. You might say, "but then every Default Danny will have X supercar!" First, you need to recognize that there are always going to be people on here just for the grind. That will never change. Second, you also need to recognize that there are people who could be RPing but need to grind at least a little bit for the money. These people hate grinding for money as much as you hate that everyone is grinding. A balance needs to be established and the constant nerfing needs to be addressed. The economy is a gradient. Anyways, here are my thoughts on what could be done to improve the economy:
- Increase timed paychecks to $125.
- Increase earnings from jobs.
- Improve existing jobs.
- Add the above suggestions for jobs.
- Perhaps implement a cooldown for doing certain jobs. The RP reason for the cooldown could be to prevent the person from working overtime.

***Focus on features related to RP***
I think the final thing you could do to encourage RP is to focus on RP features. Tie RP closer to jobs for starters. Here are some things I think could accomplish this:
- Bring back whitelisted drugs and reduce the already existing drugs. Sure, the system could potentially be unfair at times, but at least it required some amount of RP.
- More server events - I like what C-Blocc has been doing. I think its a step in the right direction for encouraging RP on the server. I think the next step, however, is to host server-sponsored events. Events hosted by the city of Los Santos itself.
- Add a new whitelisted job: interviewers. Their job would be to do a mock-interview for certain jobs and then to reward the interviewee with the actual job. Perhaps they could be stationed at the job center. Obviously, not all jobs should require an interview, because then some people would never be able to get a job. The jobs that require this should be more "mid-tier", like trucking.
- I've seen some members of our community actually do this themselves, but I think it might be a good idea to add a new whitelisted job for car salesmen. Their job would be to sell people's used cars. Pretty self-explanatory, should work like the real estate job. They take commission on the sale too.

**Comment by Aspratic** [comment]
Buffing $$ doesn't make people not grind. Creating ways that people can make money through rp will.

**Comment by Aspratic** [comment]
-1

**Comment by Aspratic** [comment]
Increasing payouts is a lazy mans way out, and only acts as a band-aid

**Comment by ChainedDev** [comment]
Oops was trying to be cool with GitHub ^

**Comment by rcj0003** [comment]
> -1
> Increasing payouts is a lazy mans way out, and only acts as a band-aid
> Buffing $$ doesn't make people not grind. Creating ways that people can make money through rp will.

@Aspratic any thoughts on the rest? Economy-related buffs were only 2 bullet points in this entire issue report.

**Comment by l-Crynic-l** [comment]
Then don't buff payouts, but nerf the non-rp based ways of making money. Its called City Life "RolePlay" for a reason, right?

**Comment by Aspratic** [comment]
none of the jobs u provided will create rp, they will be cool for a day or two and die out. The way to create rp is to have jobs lead into other activities. Such as getting 'special' items and selling to other players who then can use those items to create something else, which then allows them to sell that to another player.
Civ jobs ---> Crim activities

**Comment by Aspratic** [comment]
but make the civ jobs ONLY available to civs. every civ will eventually turn into a criminal, but giving civs meaning needs to happen. I will create a github sometime this week explaining the best way to do this :)

**Comment by iDulvious** [comment]
If you need a job idea for RP ask old frank murphy for one

**Comment by iDulvious** [comment]
I have plenty and I never keep them
