### ISSUE TITLE
More colors for all suits

### ISSUE THREAD

**Issue by jorhanstahl01** [ChainedDev/CityLife#200]
**Is your feature request related to a problem? Please describe.**
Currently, the server doesn't have much variety in terms of colours of fitted suits, approx there's only 4 of them, while there are 12 colours for the fitted suit pants.
**Describe the feature you'd like**
Add more colours of the suits to match the variety of pants. (All of these colours are available in normal GTA Online)

**Describe alternatives you've considered**
None currently.

**Additional context**
N/A

**Comment by ChainedDev** [comment]
We are currently looking at changing up our clothing selection

**Comment by ChainedDev** [comment]
More suits made available
