### ISSUE TITLE
Improvement for the city

### ISSUE THREAD

**Issue by killumky** [ChainedDev/CityLife#201]
**Is your feature request related to a problem? Please describe.**
[Yes]

**Describe the feature you'd like**
[•more clothes
•create a section on discord for suggestions 
•create a team dedicated to adding more custom clothing
- I have heard from many people that the city could be much much better if there was more and better clothes, shoes, and accessories. You could start from adding clothes that are already on mod websites and then transition to making custom clothes. If people see that you have name brand clothing and shoes it will attract more people to join and stay.

•more jobs and less buffing
•there are some jobs in the city but there should be more interactive jobs. For example in one city they had a chicken butching job where you get the chickens, chop them up, pack them, and deliver them to the clucking bell. This was a job that kept you active and spread out the dynamic of the city.
•in recent updates it seems that there isn’t much to do to make money, the drugs were buffed and the jobs that are included don’t make you as much money. I think there should be inclusions of more jobs in the city but also a fair rate on the money you get from the jobs. The more you do the more you make. When you start nerffing things it changes the dynamic of the city, where people get bored and not want to be in the city anymore, and that’s the biggest issue I see. When people get in the city they don’t have the desire to do anything. 

Motels
•I believe there should be motel options for people who don’t own houses yet. A safe place where people can store their belongings. 

Custom Places
•I have seen that the coffee beam has been added, and I think it is a great start, but there should be more customs stores like that. For example, an Apple store where you have to buy your phone at or more player owned stores. Taco places, restaurants, shoe stores, etc. it is very much possible to include these things in the city. Also including more leisure places, movie theater, bowling alleys. ]

**Describe alternatives you've considered**
[None]

**Additional context**
[None]

**Comment by iDulvious** [comment]
Instead of complaining ask old frank to give you one of his ideas for a business and RP it out

**Comment by iDulvious** [comment]
Also YOU make the player owned businesses not Tony.  Hop off tonys dick and go RP
