### ISSUE TITLE
New hair/clothing options....I beg you 

### ISSUE THREAD

**Issue by CosmicMe0w** [ChainedDev/CityLife#202]
**Describe the feature you'd like**
Ready to get on my knees and beg for better hair options/new clothing. The hair in the city is whack and I think we all (me) wanna be cuter. Clearly a very important issue.

![image](https://user-images.githubusercontent.com/64748125/82266438-b197fb80-9937-11ea-95b8-d805709573c0.png)
![image](https://user-images.githubusercontent.com/64748125/82266458-bd83bd80-9937-11ea-8205-8b36d3d6b639.png)
![image](https://user-images.githubusercontent.com/64748125/82266482-cb394300-9937-11ea-989c-69e62a99a87c.png)

**Comment by ChainedDev** [comment]
Where did you get those pictures from?

**Comment by CosmicMe0w** [comment]
https://www.gta5-mods.com/player/long-braided-haircut-for-mp-female

**Comment by ChainedDev** [comment]
You're welcome 😏
