### ISSUE TITLE
Calculate the waiting time on top of the play time in the game tracker

### ISSUE THREAD

**Issue by Tiquoti** [ChainedDev/CityLife#203]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
I want to be able to go on the rplife website and see my waiting hours on top of the hours I've played, it would be a fun way to flex my lack of supporter rank, and instead of complaining about the issue I could have fun with it instead.

**Describe alternatives you've considered**
Idk, being able to pay for supporter in memes. I dont have an alternative.

**Additional context**
Nothing teehee

**Comment by ChainedDev** [comment]
no pls you will end up crying you're welcome
