### ISSUE TITLE
BMW E30 

### ISSUE THREAD

**Issue by TeddyR1** [ChainedDev/CityLife#207]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the feature you'd like**
I would like to see any E30 BMW added, rally, classic, hatchback even just PLEASE add an E30. The closest I can get is the Sentinel Classic which isnt bad but I would love to see the real deal

![Bmw e30](https://user-images.githubusercontent.com/66266112/83427579-ccfa1080-a3e5-11ea-92b6-209d455a3897.jpg)
![BMW](https://user-images.githubusercontent.com/66266112/83427585-cec3d400-a3e5-11ea-847c-3e221811b1cf.jpg)

**Comment by ChainedDev** [comment]
@Forkedup 👀
