### ISSUE TITLE
overdrive

### ISSUE THREAD

**Issue by overdriveie** [ChainedDev/CityLife#208]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the feature you'd like**
I would like to see some new cars imported and or bikes.

**Describe alternatives you've considered**
N/A

**Additional context**
I feel the city needs some new cars/bikes to add diversity people get recognized then for the cars or maybe have exclusive cars for giveaways

**Comment by ChainedDev** [comment]
This is pretty broad, feel free to make a suggestion with what vehicles you'd like to see, thanks!
