### ISSUE TITLE
XA-21 & BANSHEE 900R Performance Update

### ISSUE THREAD

**Issue by ABOW402** [ChainedDev/CityLife#209]
**What is the reason for this balance request?**
The Banshee 900R is roughly 170K, then after upgrades cosmetically and performance wise, I have about 240K into the car. The XA-21 is 340K, and roughly cost me 70K in upgrade, making the car over 400K. These cars aren't cheap. And they only go about 130/140. Would love to see an increase in these, to match the hefty price tag of them :)

**What solution would you like?**
As stated above, would love to see them buffed in speed. I am not saying I need to go 250 mph. However, would love to see 180/190 or something faster then 130 mph. Spent a lot of money on them, and have grinded to do so.

**Additional context**
None at this time. However, just wanted to include that the Banshee 900R is a copy of the Hennessey Viper Venom 1000, which has a top speed of 216 MPH, and the XA-21 is a copy of the McLaren P1, with a top speed of 217 mph. Lmk if you need anything :)

**Comment by JJG1997** [comment]
Agree on this, the Autarch is slow for what it is and is only one of the few cars where your neck snaps if you break quickly.

**Comment by Forkedup** [comment]
Made tweaks to both cars, thanks for the suggestions.
