### ISSUE TITLE
Vehicle Liveries... PLEASE

### ISSUE THREAD

**Issue by ABOW402** [ChainedDev/CityLife#210]
**Describe the bug**
As we all know, just didnt see a github about it, the liveries are so bugged right now, and hate to see it because SASP and Civilians cant do anything about their liveries. I would love to see a fix to this ASAP.

**How to Reproduce the Behavior**
Simply put, you put a livery on the car of your choice, put in the garage, take it out, and boom, completely different livery. :(

**Expected Behaviour**
To be able to buy a livery, and have it stick to the car of your choice. SASP and Civs have been having this issue for sometime now.

**Screenshots**
Unfortunately, didn't know this was a bug till after, or else I would've screen shotted in the bennys workshop

**Additional context**
Please get this fixed ASAP.

**Comment by ChainedDev** [comment]
Looking into a potential fix
