### ISSUE TITLE
#ban-appeals - Suggestion

### ISSUE THREAD

**Issue by l-Crynic-l** [ChainedDev/CityLife#211]
**Is your feature request related to a problem? Please describe.**
Yes, it has to do with the #ban-appeals channel in Discord.

**Describe the feature you'd like**
I'd like it so everyone in the server that isn't staff or banned cannot type in there or even see it. For example: if a person gets banned, they get a role that's called "Banned" or something like that. With that role, they are able to see and type inside of #ban-appeals. Only the CityLife Staff and Banned roles should be able to see it.
The Banned role should be acquired by the connection to FiveM, not sure if that's possible. If not, then the people who get banned maybe could react to a bot message and get the Banned role that way.

**Describe alternatives you've considered**
I haven't considered any alternatives.

**Additional context**
None.

**Comment by ChainedDev** [comment]
Okay
