### ISSUE TITLE
Hawkeye STi

### ISSUE THREAD

**Issue by Rivas006** [ChainedDev/CityLife#213]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the feature you'd like**
2006-2007 Subaru Impreza STi

**Describe alternatives you've considered**
N/A

**Additional context**
I think we should have the hawkeye sti because it's the more popular and better looking, plus we have the Evo9 which would be paired up with the Hawkeye as far as generations of cars go. right now we have the 04-05 which is ok but... eh

**Comment by Forkedup** [comment]
I couldn't find any car models for that specific car, if you have any recommendations just link me a car from https://www.gta5-mods.com/
