### ISSUE TITLE
Drug Rework

### ISSUE THREAD

**Issue by Dasterdlehh** [ChainedDev/CityLife#214]
**Is your feature request related to a problem? 
Sort of. I feel like right now there’s no incentive other than money to have any sort of hard to get drug. 

**Describe the feature you'd like**
I feel like the ability of cocaine inducing some sort of fast legs scenario or even meth with an extremely reduced time cap. This could create more valuable rp, and could even decrease the amount of chases that end in fights if it’s done right. 
**Describe the alternatives you’ve considered**
Honestly I’ve considered things like a combination of drugs or a certain type of a broken down drug. Cocaine and meth are obvious fuck-withable in that sense. 
**Additional context**
This could also open up trade for different drugs between citizens criminals, and everyone. Real incentive to purchase or even become addicted.

**Comment by ChainedDev** [comment]
I likey

**Comment by ChainedDev** [comment]
smoke coke
