### ISSUE TITLE
 More House Interiors

### ISSUE THREAD

**Issue by ShottyShane** [ChainedDev/CityLife#215]
**What is the reason for this balance request?**
1)I've had clients feel discouraged from buying the Eclipse Tower apartments due to the lack of storage it provides. Being that to purchase the property requires 400k, It's a little discouraging to see you can only store 600 Lbs. In hindsight, people could just purchase a warehouse if they wanted to to store items, but the penthouse is technically the "largest property" Numerous rooms, gigantic living area. More importantly, it provides the same storage space as a small shabby property in the deprived neighbourhoods with 600 space.
2) Secondly, The lack of different interior designs, it would be nice to have more than just 3 different interiors for the houses people purchase the most

**What solution would you like?**
For problem 1)
Perhaps Increase the storage in the property, maybe have it at 1200-1600. Somewhere inbetween there, Considering it's a house with 2 floors, 600 storage doesn't feel just.
For problem 2)
Either I can find some interiors that we could add in, or have the ability for people to customise their property. Example, in MixerRP you start off with a empty house, you can hire an Interior house designer to help Add TVs,speakers, couches placement etc. Or Allow people to customise it on their own.

**Additional context**
Just let me know what you think, whether you disagree or not. I understand it wouldn't be a top priority, but it would be nice to hear how you guys feel about it

**Comment by ChainedDev** [comment]
Dynasty should be able to transfer houses easier!!@!!!@1

> people could just purchase a warehouse if they wanted to to store items
Yes.

More interiors will be coming when new housing changes!!!!
