### ISSUE TITLE
Add a mute/volume button to the loading screen

### ISSUE THREAD

**Issue by Jnismoth** [ChainedDev/CityLife#217]
**Describe the feature you'd like**
Deadass just a mute button, I don't like pretty much any of the music and like to listen to my own shit so it can be a lil annoying :)

**Describe alternatives you've considered**
Muting fivem but thats just annoying

**Comment by Tiquoti** [comment]
Press spacebar xd

**Comment by Jnismoth** [comment]
I'm a dumbass thanks a ton haha
