### ISSUE TITLE
Fix Scanners RNG

### ISSUE THREAD

**Issue by Seany1** [ChainedDev/CityLife#219]
**What is the reason for this balance request?**
well, first of all the scanner is for 5500$ which it's RNG sucks when you look for items

**What solution would you like?**
fix the RNG, because it gonna take 5 or 6 hours to find something on the ground

**Additional context**

**Comment by ChainedDev** [comment]
What about the RNG needs to be tweaked?

**Comment by ChainedDev** [comment]
Scanners need a rework in general
