### ISSUE TITLE
Jewellery Store in Vinewood Hills

### ISSUE THREAD

**Issue by LarsJonsson772** [ChainedDev/CityLife#220]
Vinewood Hills Jewellry store.
[A clear and concise description of what you want to happen. Include any other documents that may reenforce your idea here. **Remove this line!**] FEATURE: My idea is to make the jewellery store in Vinewoods hills an actual thing where people can work and buy chains/necklaces,watches,rings and bracelets and maybe earrings. And have a layout similiare to the PDM where for example you walk up to the Watch display and there you can look at watches and change between different ones and then an emplyee walks up and "tags" it and then the customer buys it and then if there can be added a room where the customer can put on the Watch without going to a stora and pay +75 dollars.

**Comment by ChainedDev** [comment]
No sorry you can RP it out though!
