### ISSUE TITLE
Super cars with no rear windows able to be fired out of of

### ISSUE THREAD

**Issue by toastedbagels** [ChainedDev/CityLife#222]
**What is the reason for this balance request?**
Ok, so not to sound bitter but I've come across this several times in the city and I know many people who had too. I don't blame people for using this tactic because it's extremely strong, seemingly unbeatable. There are certain high speed cars that do not have back windows, aside from little slots. Yet people are able to fire stream of fully automatic weapons fire through it and hit targets. Returning fire from these angles seems to have no effect, you can't see your target, if the car is armored I question how much of these slots can be fired into. However there is no issues firing OUT of them. People at times do some questionable things like driving down a highway and raising their trunk to protect them which falls under failRP imo, however this does not. It seems to just be a balancing issue with these vehicles.

**What solution would you like?**
Change or remove the penetration for vehicles that do not appear to really have rear windows. If there can't be a two way exchange of gunfire or sight lines maybe make it so you can't shoot out of them.

**Additional context**
I think that if this was modified it would change the level of interaction / baiting / and types of engagements that people have. Right now, it doesn't feel like something from the real world, it feels like something from GTA online. Just my 2 cents.

**Comment by ChainedDev** [comment]
Thanks for letting us know, people shouldn't be abusing it and we will be looking into it

**Comment by ChainedDev** [comment]
You should be here to roleplay and not abuse game mechanics, if you abuse trunks as a way to gain an advantage in a gun fight you will be perm banned for powergaming. Be smart not stupid.
