### ISSUE TITLE
Upgrading the Supra

### ISSUE THREAD

**Issue by ThomasBonelli** [ChainedDev/CityLife#226]
As of recent the racing scene has started to gain traction and is something that will provide great RP for the server. I think the supra fits the racing community perfectly, but the car currently is not good enough to compete. I think that the driver of the supra should not be at a disadvantage because of the car's performance.

I think that the supra should be examined and buffed accordingly. After driving the supra and other cars you will see that the supra is far below cars like the M4, Lexus 350, and the R35 GTR. 

I think that the car is nicer and should be more expensive than those cars and I am more than willing to pay the difference if the car's price is changed due to the buff.

**Comment by Forkedup** [comment]
Have you noticed any changes?

**Comment by ThomasBonelli** [comment]
noticed buff to top speed and top-end accel turning feels weird now but probably because of going faster through corners.
