### ISSUE TITLE
Ambulance Y and Up Arrow

### ISSUE THREAD

**Issue by mubbsy** [ChainedDev/CityLife#228]
Is there any way we can get the siren button taken off of y, annoying when trying to set cruise control and it either enables or disables a siren. We already have enough buttons for it without doubling up on existing keys.
Also the up arrow also triggers a siren when in the ambulance which is not needed, and it is very annoying when trying to check EMS texts when you can only scroll down in your phone. Getting out of the ambulance to properly read a barrage of EMS texts is annoying and cuts down on our productivity.

**Comment by jorhanstahl01** [comment]
It's connected with your keybinds, certain keybinds are linked to these actions - triggering them. 

Just see what's mapped to your Y and Up arrow.

**Comment by mubbsy** [comment]
I've changed the key bindings off of the things they are tied (y for team chat, up arrow is only tied to cell phone pulling out, and scrolling up in cell phone) too and then the function to use cruise control and pull out your phone isn't available at all.

**Comment by ChainedDev** [comment]
Does anyone hit Y for lights & sirens?

**Comment by klucx** [comment]
No

**Comment by ChainedDev** [comment]
Implemented test for disabling it, but I believe this is default GTA keybind for sirens

**Comment by klucx** [comment]
I thought just E turned on lights and sirens, and holding E was the horn in regular GTA, I’m not sure though

**Comment by ChainedDev** [comment]
Cruise Control has been set to G so should fix situation
