### ISSUE TITLE
Bank Robberies

### ISSUE THREAD

**Issue by WHOMAN23** [ChainedDev/CityLife#229]
I think we should be able to rob banks because most people will love to roleplay a bank heist and like me i dont really like to farm rather rob stores or banks the most so i will love that if the Feature can be added to CityLifeRp :)

**Comment by ChainedDev** [comment]
Do you guys want to rob a bank?

**Comment by ChainedDev** [comment]
Guess not

**Comment by Decirus** [comment]
@ChainedDev I do!

**Comment by ABOW402** [comment]
> Guess not

@ChainedDev I promise WE ALL DO!!!!!!!!!!!!!

**Comment by skiredd** [comment]
@ChainedDev ME ME ME ME

**Comment by ArkRevert** [comment]
Bank robberies would be pretty dope

**Comment by ChainedDev** [comment]
Hmmmmmm

**Comment by xxArmyGuy727xx** [comment]
That would be cool
