### ISSUE TITLE
Store Robberies are to hard 

### ISSUE THREAD

**Issue by WHOMAN23** [ChainedDev/CityLife#230]
I realized after doing two store robberies that they are almost impossible to beat fighting cops is well balanced but you to crack the safe of the shop is very hard and before you even crack the first slot the police is already there i think it should be the drilling method from gta5 online or the hacking one because its faster and easier.. :)

**Comment by JJG1997** [comment]
They’re not hard at all, be smart about it

**Comment by WHOMAN23** [comment]
you again what you r saying is complete bullshit i would love to see you try

**Comment by Yamipandah** [comment]
I'm just gonna +1 store robberies are just fine they're not hard, a variation of the safe would be cool like random safe minigames.

**Comment by TheLitteralIcemanStraightOuttaFinlandia** [comment]
> They’re not hard at all, be smart about it
I agree 100% if you put time and effort into it, it's very easy

**Comment by ChainedDev** [comment]
Just gotta breach the skill gap, some people will tell ya it's hard and some will tell you it's extremely easy
