### ISSUE TITLE
Make the respawn button take 5 seconds before reviving

### ISSUE THREAD

**Issue by Baja-Blast** [ChainedDev/CityLife#231]
**Is your feature request related to a problem? Please describe.**
I hear people almost everyday who waited for EMS or their friend to get them and they accidentally hit respawn. They then lose all the items they worked so hard for just when they were being saved. 

**Describe the feature you'd like**
Could we try having a respawn thats more of a hold function like hold R for 5 seconds to respawn?

**Describe alternatives you've considered**
Not sure of any alternative.

**Additional context**

**Comment by ChainedDev** [comment]
Yeah I've heard of a lot of people doing this(even though it's slightly their fault) but holding it down for 5 seconds is good in general

**Comment by ChainedDev** [comment]
Will be changed to a Hold to Press shortly
