### ISSUE TITLE
Updates to the Trucking Job

### ISSUE THREAD

**Issue by zactasia** [ChainedDev/CityLife#232]
**Is your feature request related to a problem? Please describe.**
The trucking job has one place to start and one place to end, there is no randomness like other jobs. Currently you start at one of the most southern parts of the map, drive to sandy shores and then have to go back. The drive back takes time and you are not earning money.
**Describe the feature you'd like**
The trucking job should have multiple start and end points. I know trucking through the city would be too difficult so that cuts out most of the western and central parts of the city. But along the east side there are big distribution center like buildings. Also On the senora freeway there are a few buildings like "Rons" that could be great as a pickup point. 
**Describe alternatives you've considered**
I understand that this would be difficult because of how large the trucks are and the logistics of picking points that keep trucks out of the main parts of the city would be difficult. I don't think we would need as many spots as Post OPs or other jobs but a few would be nice. Enough to make it so that you don't have to drive as long without earning money.
**Additional context**
Would love to talk more about it Zactasia#3937 on discord.

**Comment by Forkedup** [comment]
There is actually one start point but multiple end points.

We can certainly look into adding even more as time goes by.
