### ISSUE TITLE
Hot Keys

### ISSUE THREAD

**Issue by CalebHorne** [ChainedDev/CityLife#235]
**Is your feature request related to a problem? Please describe.**
No it is not

**Describe the feature you'd like**
I would like hot keys for example 1 2 3 4 5 so it will be easier to access stuff in your pockets 
**Describe alternatives you've considered**
Just adding 12345 as hot keys

**Additional context**
It would just make pulling some stuff just way easier pulling out like popping oxy fast during gun fights and have it faster pulling out guns etc...

**Comment by ChainedDev** [comment]
nah
