### ISSUE TITLE
new PD

### ISSUE THREAD

**Issue by Callum0202** [ChainedDev/CityLife#236]
https://www.gta5-mods.com/maps/police-station-mission-row-exterior-modded-fivem-sp-menyoo-ymap-xml

**Comment by TheLitteralIcemanStraightOuttaFinlandia** [comment]
My friend, there is no need to change the PD look, it's beautiful as it is. This looks like old snus I've reused 15 times. 
Best regards Mr iceman

**Comment by Skader91** [comment]
Disregard Iceman, Acquire new sweet ass PD

**Comment by Skader91** [comment]
This is outside only though, I highly recommend one that has a interior like this.
https://www.gta5-mods.com/maps/community-mission-row-pd

**Comment by ChainedDev** [comment]
Duplicate of #161 please put suggestions on the existing topic please
