### ISSUE TITLE
Police Armory Robbery

### ISSUE THREAD

**Issue by extracheddardon** [ChainedDev/CityLife#237]
**Is your feature request related to a problem? Please describe.**
Yeah, sorta. The fact that this feature is not in place takes away from the RP experience by limiting free will, when clearly there are options at hand. 

**Describe the feature you'd like**
If the police leave their armory unlocked, and you're able to get in there. You should be able to actually take weapons. The fact something is in front of me and I don't have the option to pick it up is not a very seem less rp experience. 

**Describe alternatives you've considered**
Being able to lock pick into the armory too. 

**Additional context**
Crazy stuff happens every second. So don't tell me it wouldn't be realistic to steal from a police Armory.

**Comment by Skader91** [comment]
We can't even take the weapons out of the Armory -SASP

**Comment by ChainedDev** [comment]
Nop
