### ISSUE TITLE
Clear List of Laws

### ISSUE THREAD

**Issue by extracheddardon** [ChainedDev/CityLife#238]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
A clear List of Laws and applicable punishments and fines. I can Google any law and find the potential sentencing and fines associated with it in moments. Meanwhile the laws of CityLife seem to be very subjective of the officer. It would be nice to have a clear concise area with this info. Even jails have law libraries. 

**Describe alternatives you've considered**
N/a

**Additional context**
The fact laws and punishments aren't clearly listed is not realistic.

**Comment by ArkRevert** [comment]
The laws are listed for the officers and they have to follow the set time, it's just not available for everyone to see

**Comment by extracheddardon** [comment]
Which is not realistic. I can google laws for any state, county, or even country right now. And have an understanding of the definition of the laws, as well as the punishment surrounding them. 

How can I know I'm breaking a law if I don't have access to what laws are out there ? RP fail.

**Comment by Skader91** [comment]
It's pretty standard stuff

**Comment by Skader91** [comment]
https://docs.google.com/spreadsheets/d/1RmlwHLqZPZIeDZvgnps1dGF64wAZe7aUqeGSJb8zkLU/edit?usp=sharing

**Comment by ChainedDev** [comment]
It's now public
