### ISSUE TITLE
Secret Location Clues

### ISSUE THREAD

**Issue by extracheddardon** [ChainedDev/CityLife#239]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
Clues or Hints toward drug n gun spots. 
With there being thousands of buildings, doors, etc. in GTA it would be nice to have some sort of info within the city that helped point toward the locations. 

Idk if y'all come from a nice ass neighborhood or something. But in the hood drugs and guns are easy to come by. So by making it so hard to find is not realistic in the least. 

**Describe alternatives you've considered**
NPC Banter, rumors, gossip
Markers / Indicators 
Riddles
Pictures of random hints
Related Graffiti 
Only being in enterable buildings 
Only buildings from the story of gta. 
No random bullshit buildings and items n

**Additional context**
Make the game more fun. If I wanted to work all day I wouldn't be playing a video game.

**Comment by JJG1997** [comment]
There are people to find instead of searching

**Comment by iinFamousJack** [comment]
Me and my buddies already found 1 drug location and 1 gun spot, you just gotta hustle and bustle around. Believe me it's worth it.

**Comment by extracheddardon** [comment]
Like NPC people ??

Because sure I have a bunch of drug locations, and a few guns. But just a hassle with them being moved all the time, and then the fact the option for the spot could be a door, or an AC unit is crazy. 

Then I heard they're white listing coke drops. Gtfo a this bs mods .

**Comment by McFry36** [comment]
I’ve spent at least 200 hours searching for locations. Develop a search team RP it out and have some fun while doing it. Nothing comes easy in this city. The connections and bonds you make within the city can help provide you with valuable information if you also have some to share for them. Being the first to know location spots prior to anyone else is essential part of big move plays within the city. I have pondered the hint game often. I just think the gangs running the drugs shouldnt have to search for their own stuff personally as that doesn’t make any sense to me.

**Comment by extracheddardon** [comment]
Put it this way. If I wanted to go find any drug that's in game in real life, in a major city. It would take me less than 2 hours.

**Comment by JJG1997** [comment]
Build ya connections

**Comment by McFry36** [comment]
You’re composing about two separate things here I guess. Are you upset you don’t know anyone that has drugs or you’ve spent more then 2 hours looking for locations that you don’t even know what you’re looking for as it seems.

**Comment by extracheddardon** [comment]
Just upset by the double standard of "realism" in this game. 

"Oh you can't do this, it wouldn't be realistic"

But meanwhile when systems in the game are far from reality, they wanna keep them. 

You ever buy drugs from an air conditioner my guy?

**Comment by McFry36** [comment]
Your ignorance here on how this city works is showing here. I assure you no big time drugs that you are looking for are just given at a location. Now get out there and head the advice that was given and make connections.

**Comment by Gunnar15** [comment]
Need to stop the comparison between real life and City Life. Though you want the RP to be realistic you cant have everything the same because it is a video game

**Comment by extracheddardon** [comment]
Clearly you live in the suburbs and never did anything against your parents rules irl
So I get it you only have movies to go off of. 


I have meth spot, oxy spot, 3 pistol spots, new meth spot, coke processing. 

I'm not complaining about not finding them. Cuz I have. Just upset how unrealistic it is.

**Comment by McFry36** [comment]
That’s funny... No ya pleb you’re out there looking for locations that don’t exist.

**Comment by toastedbagels** [comment]
Unrealistic? Yea maybe you could go out and SCORE some drugs relatively quickly in your major city. (From people you know, I am sure you could meet some randos and maybe get rolled by some too). However, in this game.. the spots you are looking for are MANUFACTURING, DISTRIBUTION, large scale operations. It actually takes sometimes years in real life to build up enough trust and reputation to meet HIGH end connections like that. You think you could do it in hours? that is insanity. Not only that, it might take you years to gain that trust, but moments to lose it. You are right, it's not that realistic, it's far easier in the game.
