### ISSUE TITLE
Gun Crafting Revamp. 

### ISSUE THREAD

**Issue by extracheddardon** [ChainedDev/CityLife#240]
**Is your feature request related to a problem? Please describe.**
Not realistic. 

**Describe the feature you'd like**
In real life guns, the only hard.to get parts are the Lower Receiver for rifles and Trigger Frames.for pistols. Everything else can be found on Amazon, DHGate, and gun stores. 

Why is it a 3.step process to craft a gun?

I can google the Anarchist Cook Book and find out how to.make tons of sketchy shit. But I have to use trial and error to figure out what goes into a gun? Whack. 

**Describe alternatives you've considered**
Making the gun Crafting experience more realistic to actual gunsmithing. 

**Additional context**
Why doesn't.Ammunation sell rifles either? I can get a rifle from Walmart come 10am.

**Comment by ChainedDev** [comment]
We are currently working on a new system, and no, allowed ar's to be sold out of ammunation is not what we plan
