### ISSUE TITLE
EMS front Garage sending vehicles to helipad

### ISSUE THREAD

**Issue by mubbsy** [ChainedDev/CityLife#242]
Sometimes when taking a vehicle out of EMS garage, instead of spawning in front of the doors where it normally does, it ends up on the helipad roof, basically dooming you to start your shift with an insurance lot run. Had a few wheelchairs end up there which isn't the end of the world since they're cheap to replace (although our garages will eventually fill up with insurance lot wheelchairs as it would take considerable time to get it from insurance and drive it back at 15mph vs $10 to buy a new one), but when your ambulance ends up there and there's no other EMS/SASP available to provide a ride to insurance it can really hinder your ability to promptly assist the fine people of this city. Doesn't seem to be any real logic behind when it happens, full'ish area down below or completely empty, doesn't seem to make a difference.

**Comment by ChainedDev** [comment]
Does this issue still happen? I think I moved the spawning location a while ago to combat this but unsure, I'll do some tests and if anyone has encountered this recently please let me know
