### ISSUE TITLE
SASP/EMS GPS only showing while off duty.

### ISSUE THREAD

**Issue by Skader91** [ChainedDev/CityLife#243]
**Describe the bug**
So as it stands right now, if you clock off duty that's when you can see everyone that is in the city for SASP and EMS.
You have to clock in then go and apply body armor for this to update. (which makes it impossible for EMS to see GPS)

What's really shitty is that if myself and 3 other officers are on duty, and 1 other person comes 10-8. Myself and those 3 other officers have to come back to MRPD and apply body armor to view that 1 persons GPS.

**How to Reproduce the Behavior**
Steps to reproduce the behavior: Clock in/Clock Out

**Expected Behavior**
When someone clocks on duty it should show everyone and keep it that way.

**Video of Issue**
https://youtu.be/5v1dxIHMjCA

**Comment by ChainedDev** [comment]
Test fix has been implemented, will know if it worked shortly
