### ISSUE TITLE
Big boy trucks

### ISSUE THREAD

**Issue by Tiquoti** [ChainedDev/CityLife#244]
**Is your feature request related to a problem? Please describe.**
The only problem this would fix is my broken heart due to the lack of cool cars

**Describe the feature you'd like**
I wish there were purchasable 18 wheelers and a possibility to get a cargo attached so you can transport more stuff, not only would it make more roleplay possible, as in people could offer their services as a trucker to fishermen, miners or woodcutters to let them make them more profit by carrying more, but it would also let me live my dream of being a trucker. All the current cars are similar as in they don't offer different kind of roleplay.

**Describe alternatives you've considered**
Making the trucker job currently available less boring, it makes no money and is very linear. I've used it twice then never touched it again.

**Comment by ChainedDev** [comment]
Don't see the point in people owning tractor trailers, however changes to trucking job can be discussed here #232
