### ISSUE TITLE
Warrants

### ISSUE THREAD

**Issue by THELONEWOLF980** [ChainedDev/CityLife#247]
Please add a way for people to check warrants on their own. Let's utilize the courthouse for it.

**Comment by Skader91** [comment]
You can do this now by contacting a lawyer. Which is better because if you check if you have a warrant yourself and you do have one, you are forced to turn yourself in.

**Comment by ChainedDev** [comment]
Front desk of courthouse can see how many warrants you have maybe and if you have warrants the police get notified!??

**Comment by THELONEWOLF980** [comment]
I like that. The front desk in the courthouse. Search your name and if you
have a warrant then it tells you.

**Comment by ChainedDev** [comment]
Would be nice with possibly a new court house to make things easier to view instead of a front wall with no clear desks to walk up to

**Comment by Chainedster** [comment]
Finished long ago
