### ISSUE TITLE
New Male/Female clothing and accessories

### ISSUE THREAD

**Issue by EvaLaura69** [ChainedDev/CityLife#249]
**Is your feature request related to a problem? Please describe.**
It does not represent a problem. I want to propose some new outfits and accessories for both male and female characters, for the new anniversary update.

**Describe the feature you'd like**
As mentioned, I would like more diversity in the City. As you know new items were added and since that happen, everyone is using the new items and we are back in square one. So for this update, I would like to add some more clothing suggestions, so that there are more chances to be different. 

**Describe alternatives you've considered**
The clothing alternatives that i would like to suggest, are presented below 
https://www.gta5-mods.com/player/mp-female-clothing-mini-pack-1-0
https://www.gta5-mods.com/player/short-double-bun-haircut-for-mp-female-fivem-ready-sashimichin
https://www.gta5-mods.com/player/wavy-hairstyle-or-haircut-for-mp-female
https://www.gta5-mods.com/player/mp-female-presets-pack-3-menyoo
https://www.gta5-mods.com/player/new-short-hairstyle-for-mp-female
https://www.gta5-mods.com/player/dress-for-mp-female
https://www.gta5-mods.com/player/skirt-tights-and-socks-for-mp-female
https://www.gta5-mods.com/player/basics-shorts
https://www.gta5-mods.com/player/military-jumpsuit-for-mp-female
https://www.gta5-mods.com/player/modified-hoodie-2-for-mp-male
https://www.gta5-mods.com/player/tiedup-dreads-for-mp-male
https://www.gta5-mods.com/player/cat-ears-for-mp-female
https://www.gta5-mods.com/player/custom-overalls-for-mp-female
https://www.gta5-mods.com/player/strapback-pack-for-mp-male
https://www.gta5-mods.com/player/top-with-belt-for-mp-female
https://www.gta5-mods.com/player/dreads-for-mp-female
https://www.gta5-mods.com/player/short-ponytail-for-mp-female
https://www.gta5-mods.com/player/hooded-track-for-mp-male
https://www.gta5-mods.com/player/the-north-face-strapback
https://www.gta5-mods.com/player/topknot-with-bangs-for-mp-female
https://www.gta5-mods.com/player/long-haircut-with-bangs-for-mp-female
https://www.gta5-mods.com/player/long-wavy-hair-for-mp-male
https://www.gta5-mods.com/player/hime-haircut-for-mp-female
https://www.gta5-mods.com/player/oversized-hoodie-for-mp-female
https://www.gta5-mods.com/player/mp-male-luisvitton-hoodie
https://www.gta5-mods.com/player/mp-female-adidas-hoodie ( for the slav that lives in me)
https://www.gta5-mods.com/player/16-custom-hoodie-and-sweatpants-pack-for-mp-male
https://www.gta5-mods.com/player/mp-male-obey-shirt-pack
https://www.gta5-mods.com/player/mp-male-louis-vuitton-bape-t-shirt
https://www.gta5-mods.com/player/mp-male-adidas-tee
https://www.gta5-mods.com/player/mp-female-jordan-13-hyper-royal
https://www.gta5-mods.com/player/3-new-hairstyles-for-mp-female-mjames867
https://www.gta5-mods.com/player/better-pink-hair-for-mp-female
https://www.gta5-mods.com/player/asian-haircut-for-mp-male

THE LIST CONTINUES WITH MORE SEXY STUFF

https://www.gta5-mods.com/player/nude-bottom-sexy-undies
https://www.gta5-mods.com/player/see-through-shirt-for-mp-female-18-ultimate
https://www.gta5-mods.com/player/lingerie-high-socks-for-mp-female
https://www.gta5-mods.com/player/wet-shirt-and-wet-bikini-for-mp-female-18
https://www.gta5-mods.com/player/latex-catsuit-for-mp-female ( I WANT THIS ONE SO BAD)
https://www.gta5-mods.com/player/high-socks-for-mp-female ( the socks can be added to any outfit)
https://www.gta5-mods.com/player/swimsuit-pack-for-mp-female-18
https://www.gta5-mods.com/player/pantyhose-for-mp-female-matching-shoes
https://www.gta5-mods.com/player/see-trough-shirt-for-mp-female-v2
https://www.gta5-mods.com/player/bodysuit

**Additional context**
I would very much appreciate if others will join this and add more. I have to admit that i am biased and most of the clothing is for the females.

**Comment by Msblueshines** [comment]
I 100% agree.We need more clothes for the woman. We have way less things

**Comment by ChainedDev** [comment]
This is a long list gonna take some time to go through haha

**Comment by Forkedup** [comment]
More clothing added!

Thanks for the suggestions, helped me out.
