### ISSUE TITLE
Escaping handcuffs. 

### ISSUE THREAD

**Issue by Xignotic84** [ChainedDev/CityLife#25]
**Is your feature request related to a problem? Please describe.**
When breaking out people from being kidnapped by a gang or arrested by the police the kidnapped person may be in cuffs and because of that you won't be able to get them out of their cuffs if there is no one around to do so. 

**Describe the feature you'd like**
Allow people to use lock-picks to break people out of handcuffs, this will give people the ability to break people out easier and actually be successful.

**Describe alternatives you've considered**
To make it less overpowered add chances of failure when using lockpicks which will lead to breaking it. You could also add in handcuff keys that can be stolen from cop vehicles or they can be crafted.

**Comment by ChainedDev** [comment]
Seems like it would bring some balance and maybe be possible through a blackmarket in the future or through crafting

**Comment by gullidog** [comment]
Yeah I agee

**Comment by Resqect** [comment]
we could add bolt cutters.

**Comment by gavisuprstar** [comment]
It will be a little good if police officers can uncuff people which were cuffed by gang members.

**Comment by ChainedDev** [comment]
> It will be a little good if police officers can also uncuff people which were cuffed by gang members.

Gang handcuffs have been removed

**Comment by ChainedDev** [comment]
BRO! ADD THIS SHIT!@!!!

**Comment by ChainedDev** [comment]
SOFT AND HARD CUFFS!@!

**Comment by ChainedDev** [comment]
Handcuffs will now fall off after x minutes, if you feel something more should be added please make a new issue as this has been opened for a long period of time, thanks!
