### ISSUE TITLE
duck in vehicles

### ISSUE THREAD

**Issue by kuf-1** [ChainedDev/CityLife#251]
**Is your feature request related to a problem? Please describe.**
no

**Describe the feature you'd like**
be able to duck or hide in cars   /duck  or /hide ... something like that.... simply duck or hide your head so the car looks vacant

**Describe alternatives you've considered**
no alternatives

**Additional context**
pretty simple to understand the idea of it

**Comment by CosmicMe0w** [comment]
If you do /sleep while in the car it has a similar effect to what you're looking for

**Comment by ChainedDev** [comment]
Can't you hold X while in a seat to lower yourself?

**Comment by skiredd** [comment]
no its buggy and it conflicts with the hands up muscle so it almost never works. you go from ducking to putting ur hands up
