### ISSUE TITLE
Buffing Meth

### ISSUE THREAD

**Issue by QuasTheG** [ChainedDev/CityLife#252]
**What is the reason for this balance request?**
I started playing the server a couple days ago, and I instantly started with drugs, assuming that low-life criminal hustles reap the most benefits in the shortest amount of time at my stage of the game. I found that it was severely disappointing, taking 10-20 minutes to produce 2 batches of meth,taking up to an hour to sell it all to NPCs, and finally around 20 minutes to clean your money if you have terrible luck (like me). This is a terrible way to make money, compared to Post Ops which can make you thousands in an hour. Not to mention, theres a pretty huge risk selling drugs, while Post Ops has only the risk of getting pulled over for speeding. In RP servers, I enjoy playing high risk and high reward, but with selling meth theres barely any reward for all the trouble you have to go through.

**What solution would you like?**
A couple options that could be taken is decrease the chance that NPCs will be not interested, increase the price, and just generally decrease the amount of time it takes to go through the whole producing and selling process.

**Additional context**
N/A

**Comment by ArkRevert** [comment]
I suggest looking around for other things that could possibly be worth more than meth.

**Comment by QuasTheG** [comment]
> I suggest looking around for other things that could possibly be worth more than meth.

Thats not the point - Meth serves little to no purpose when there is way better starting alternatives to it.

**Comment by Dollar82** [comment]
It's like this if you a drig dealer,you don't mind making it & selling it  its the lifestyle....so it's probably best you RP as yourself or something, cause hustling not for you😂

**Comment by QuasTheG** [comment]
> It's like this if you a drig dealer,you don't mind making it & selling it its the lifestyle....so it's probably best you RP as yourself or something, cause hustling not for you😂

It seems you arent getting it either. A hustle implies quick and easy money, meth doesnt qualify as quick or easy on this server.

**Comment by Dollar82** [comment]
I'm a real life hustler, nobody gives you nothing,hustle & stop wanting a easy way out & I make plenty money doing what i do...

**Comment by Dollar82** [comment]
& for crying out loud,it's roleplay.."Real Life" so go be a lawyer if you want it that quick & easy

**Comment by QuasTheG** [comment]
Not sure why you would shoe-in you're IRL financial situation just to try and make a point, its pretty tacky. Another thing, yes it is an RP server which is why I choose a criminal life style. I enjoy the risk of being caught, its way more entertaining compared to being a lawyer. My only problem is that with high risk, there should be a high reward.

**Comment by papatiddy** [comment]
After cooking and selling meth for quite some time now, at first i was buying it off the street and selling it to the locals, but then i linked up with a crew who taught me how to cook it. I do agree that it is very high risk with little payout, only getting around 4k every 30 bags, and thats if you dont get caught or robbed selling. Getting caught by the cops well cost you all your product and dirty money, also you looking at at least 30 mins in jail, and they force you to pay them for the fines. This is why if you ask anyone who has been in the city for some time if they want to buy it off you, they immediately say no, because they know its not worth the time or the risk. 

IMO this is why everyone just does "Post OP" because it makes way more money in way less time with no risk at all, so most people dont even want to RP has a meth dealer. 

I could see how increasing the sell price to locals could make the "job" more enjoyable and not just a complete waste of time.

**Comment by papatiddy** [comment]
> I'm a real life hustler, nobody gives you nothing,hustle & stop wanting a easy way out & I make plenty money doing what i do

I understand what you're getting at here, but in end this is still a video game, where things need to be balanced, buffed, nerfed and tweaked for a better gaming/RP experience. You cant really compare your "real life hustle" to someone selling meth in an RP server

**Comment by ogihara420** [comment]
I agree with buffing the meth. you get a minimum of 30 months in prison over chump change. high risk very low reward.

**Comment by SigilOG** [comment]
Meth is the most consistent payout and I make the most selling meth... you are obviously doing something wrong...

**Comment by Dollar82** [comment]
@SigilOG he apparently isn't a hustler😂😂 I do go off meth also... @tony the meth is fine buddy😂

**Comment by ogihara420** [comment]
if i do post ops for 1 hour i can make 5k. 1 hour with meth and your lucky to get some bags sold for maybe 1k? including time to cook also that would be dirty money which you have the chance of being refused 5+ times because of RNG

**Comment by SigilOG** [comment]
> if i do post ops for 1 hour i can make 5k. 1 hour with meth and your lucky to get some bags sold for maybe 1k? including time to cook also that would be dirty money which you have the chance of being refused 5+ times because of RNG

YOU ARE DOING SOMETHING WRONG. 1k an hour means YOU ARE DOING IT WRONG. Figure it out because Meth ain’t broken.

**Comment by ogihara420** [comment]
"YOU ARE DOING SOMETHING WRONG" lmao there's only one way to sell it. a lot of not interested in there too btw.

**Comment by QuasTheG** [comment]
> > if i do post ops for 1 hour i can make 5k. 1 hour with meth and your lucky to get some bags sold for maybe 1k? including time to cook also that would be dirty money which you have the chance of being refused 5+ times because of RNG
> 
> YOU ARE DOING SOMETHING WRONG. 1k an hour means YOU ARE DOING IT WRONG. Figure it out because Meth ain’t broken.

Let me run you through how I do it then, and you tell me what im doing wrong: I go to the meth house, pay 1k to run meth. I go out to a remote area with little activity and spend 15-20 mins producing the meth, answering all questions correctly. I get 40-50 bags. I then go to areas with a lot of locals, and sell until I get a lot of "not interested" locals. I repeat this until I sell it all, then I spend 10-20 mins cleaning my money and I end up with around 6-8k in the end. If you have a more efficient way that makes just as much money as my current method, go ahead and tell me.

**Comment by skiredd** [comment]
maybe theres another way for you to make money off those bags? rp2findout

**Comment by QuasTheG** [comment]
> maybe theres another way for you to make money off those bags? rp2findout

If your talking about selling in bulk to players, nobody buys them because they know its a huge hassle and risk

**Comment by McFry36** [comment]
You’re doing it on a small scale is your problem bud and that’s all I’m gonna say about that. You need to become creative and business driven. I’ve made big boy bucks off weed in the past. Use some creativity it’s not that hard. Separate yourself from the norm.

**Comment by ChainedDev** [comment]
This is being meta-gaming to win
