### ISSUE TITLE
More Progression for Characters. 

### ISSUE THREAD

**Issue by extracheddardon** [ChainedDev/CityLife#257]
**Is your feature request related to a problem? Please describe.**
Not a problem within the coding etc. But more of an RP problem, which leads to lower quality experience for everyone. 

**Describe the feature you'd like**
I would really love to see someway for characters to have objective progression. I believe too many people try to commit crime, form small gangs, sell drugs etc, as opposed to just living a path of the straight and narrow. I believe this occurs because to form a gang is the only way I see progression in this city outside of White Listed jobs (aside from buying material possessions to show off to other players to show your status / worth like cars and houses).

**Describe alternatives you've considered**

If there could be a skill tree for characters for them to level skills like fishing, running, lock picking, physical strength, etc.

and/or a crafting system that creates a variety of items for players, not just guns and drugs. This system could be leveled to allow for those who have put more effort into crafting being able to craft nicer, more valuable items. These craftables should be relevant to other players to increase RP, drive sales, and make other RP happen based around subsections of the crafting. 

and/or regular job (post ops, wood cutting, etc.) that gave you new positions after certain goals have been met. Example:Make 50 deliveries for Post Ops, get promoted to Union Driver with a pay raise, nicer truck. Fast Forward, 10000 deliveries;  Manager position. Etc. 
But done with all regular jobs, so people can be proud of what they've spent 100s of hours doing. 

**Additional context**
 More progrssion for characters will result in a deeper and more serious RP for many on the server.

**Comment by ChainedDev** [comment]
This has always been on our minds introducing a level system to a lot of features
