### ISSUE TITLE
S2000 Upgraded Slow as Molasses. 

### ISSUE THREAD

**Issue by extracheddardon** [ChainedDev/CityLife#258]
**What is the reason for this balance request?**
Been wanting an S2000 for awhile now just to have as a collectors item in game. Purchased one, upgraded it all the way, and it barley gets to 120 on flat ground. 

In addition to this, my EK hatch can easily get over 130 on flat ground with the same upgrades.

IRL I have taken a stock S2000 to 155 - 160 with a chipped ecu. 

Since this isn't Forza and can not do in depth upgrades I assume all upgrades in the city to use the same "parts". So I'm not sure why the EK has a higher top speed. 

**What solution would you like?**
Please make the fully upgrade S2K 10 to 20mph faster, and a bit better acceleration. Please. 

**Additional context**
I know there needs to a balance between performance and money; but this is a very iconic car and I would really love if the fully upgraded version performed accordingly.

**Comment by Forkedup** [comment]
Sorry for the late reply. I tweaked the handling a bit on the S2000.

Enjoy.
