### ISSUE TITLE
Working Parachutes

### ISSUE THREAD

**Issue by Decirus** [ChainedDev/CityLife#259]
**Is your feature request related to a problem? Please describe.**
Yeah, so as you stated before parachutes do not work, as soon as u jump off it cuts the parachute and u fall into a freefall. It'd be cool if they were working again

**Describe the feature you'd like**
Parachutes that work. It'd create many RP opportunities in my opinion, I've even got a few ideas myself.

**Describe alternatives you've considered**
N/A

**Additional context**
I just really want parachutes that work, they're in the ammunation for 1k and they don't even work so it'd be really cool if it worked.

**Comment by ChainedDev** [comment]
Big scuff and brain hurt trying to figure out why, still looking into it every so often but still failing to get them not to snap
