### ISSUE TITLE
Food Industry Jobs and Salaries

### ISSUE THREAD

**Issue by skiredd** [ChainedDev/CityLife#261]
**Is your feature request related to a problem? Please describe.**
I believe this is related to a problem. Currently, any food place that anyone opens is 1. terrible money, 2. not secure and 3. not immersive.

**Describe the feature you'd like**
I think we could benefit from having actual job titles in game with salaries such as "BurgerShot-CEO" or something so that it makes it worthwhile for people to open places. Currently there is no incentive besides RP, but when everyone is sitting at PDM and not doing anything, you arent getting RP. This suggestion could also maybe fix the PDM problem by having more places every can chill at (food place is a perfect spot to do so without getting in way of business)

**Describe alternatives you've considered**
Instead of making specific jobs, just make a "Food Worker" job with a decent so that they can provide the food they want to provide, but make it worthwhile so there is an incentive to open up these places and have good RP

**Additional context**
For example, the money you make now is all put back into more food, without any money to hire staff

How do you expect to run a 1 man restaurant?

**Comment by ChainedDev** [comment]
You can now deliver foods to businesses
