### ISSUE TITLE
Long Boards

### ISSUE THREAD

**Issue by Zehfiend** [ChainedDev/CityLife#262]
**Is your feature request related to a problem? Please describe.**
This isn't so much a problem as a quality of life issue. I could explain this a lot of ways, but essentially running is too slow and we can't always drive. If we could get long boards, skateboards, roller blades, and/or scooters (they could work similar to bicycles but all of them shouldn't require a license), people of all economic status would be less likely to get into trouble and likewise add to the immersive realism. The impact this idea would have on the course of peoples lives would be unprecedented.

**Describe the feature you'd like**
I would like to be able to purchase and hop on my long board that sits on my back and say goodbye to the days of running in the streets getting hit by people in the dark. We could even implement this in a fashion where we "rent" scooters all over the map and it charges our banks. Also, this shouldn't impact the Taxi business negatively, in fact it should help eliminate the need for some of the smaller, insignificant trips by taxi's and allow time for longer, more profitable ones. 

**Describe alternatives you've considered**
The only "alternative" thing right now is to purchase a bicycle. However, I still need a garage for this and I would like an item that essentially goes in my inventory. Also, none of these modes of transportation, including bicycles, should require a license.

**Additional context**
I really feel this will help bridge the gap between some of the economic and systemic discrimination issues we currently have with pricing, mobility, and income. Obviously, this is not a balancing fix, but it would help that issue without a re-balance and also allow people a low tier way around and another toy to play with. Also, there should be shops located outside Live Invader and maybe the Hospital. 

ON A SIDE NOTE: We could also make this a Supporter benefit, and there is SOOO much untapped potential when talking in regards to donations. These modes of transportation and shops could work similar to the Pet Shop (which is really broken) but for Bronze priority or something. However, this would also be a killer benefit to constantly have on you (no matter what) for a $5 monthly donation. If you pay more than that a month already then you also get the benefit included!

**Comment by Tiquoti** [comment]
You can get a car in less than 4 hours when you start in the city.. and that feels way too convenient, the taxi job which is already struggling would lose any appeal

**Comment by jackofalloffs** [comment]
dont think this is practical. if anything it would be used as a hobby but i dont see this happening anytime soon. like mentioned above you can get a car in the city fairly easy why would you want to ride around on a longboard to get from place to place?
