### ISSUE TITLE
Toko-voip

### ISSUE THREAD

**Issue by Tropical-Gummies** [ChainedDev/CityLife#264]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
Hello city life developers First impression of your servers is really good and I’m enjoying it so far but I was hoping you guys could add a toko-voip system setup as it makes the server more fun, easier and more efficient to communicate with other people in the server and toko-voip does help resolve the issue of people using discord to communicate to other as that is out of role play but server is going good so far as you guys are doing fantastic work. Keep up the great work :)
**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by Aspratic** [comment]
Toko Voip would add so much to the city

**Comment by skiredd** [comment]
pretty sure someone in management said they will add a new FiveM exclusive VoIP whenever its stable for server use in 100 slots

**Comment by ChainedDev** [comment]
Not planning on it sorry to everyone that'll get dissapointed by this
