### ISSUE TITLE
Dealerships

### ISSUE THREAD

**Issue by Tropical-Gummies** [ChainedDev/CityLife#265]
**Is your feature request related to a problem? Please describe.**
no

**Describe the feature you'd like**
hello citylife roleplay developers ive been on this server for a decent amount of time now and i got a few opinions from other members in this community and they all seemed to like this feature, the feature id like you devlopers to add is more dealerships as it does make the server have more variety. we would like to see more dealerships on the map in areas like sandy,Grapeseed,Paletobay and the main highway goining from the city to sandy.Also we would like to see repairshops connected to dealer ships as that is realistic. 

**Describe alternatives you've considered**
none in mind

**Additional context**
with that being said you could also make limited stock to vehicles as that is realistic and it gives the people that own those limited stock vehicles some options like being able to make some more profit as that car has become rare or no dealer is selling it at that time. this gives opportunities to have rare car collections. Also by adding repair shops in dealerships it gives mechanics more opportunities to work around the map and make more profit. This feature makes it so mechanics could be near people that break down on the road in areas farther from city. And yes I know this is alot of ideas and it might take some time but i think its worth it. here are some example links.[https://www.gta5-mods.com/maps/car-dealership-showroom-fivem-y-map-ymap](url),[https://www.gta5-mods.com/maps/car-dealership-building](url),[https://www.gta5-mods.com/maps/rolls-royce-showroom-ymap](url). **IF YOU DID LIKE THESE I HAVE MANY MORE IDEAS**  👍

**Comment by Forkedup** [comment]
Thanks for the suggestion, we'll consider something like this in the near future.
