### ISSUE TITLE
Public Robbery Guidelines

### ISSUE THREAD

**Issue by skiredd** [ChainedDev/CityLife#266]
**Is your feature request related to a problem? Please describe.**
Yes, there is a clear inconsistency when it comes to what you are able to demand with x amount of hostage(s) and what 
the cops are allowed to give back to those demands.
**Describe the feature you'd like**
A public robbery handbook in discord or something like that.

**Describe alternatives you've considered**
An alternative is to update rule 7.8 with a more detailed robbery standard when it comes to demands and the responses to those demands.

**Additional context**
For example, we did 4 store robberies on different days at different times. Each time, we had different cops all with different responses. 2 times, 1 hostage got us free passage and no spike strips (which has been that way almost every single time I have been in a robbery, both on the criminal and cop side) The other time, the cop gave us only free passage but didnt put down spike strips anyways (denied no spike strips demands). Then the last time, the cops gave us only free passage to ONE bike, when in the dozens of robberies we have done, we have always gotten free passage to both bikes. The reason why this is a problem is because when its already a 7v2, I feel like being inconsistent with demands can literally be taken as just trying to get yourself an unfair advantage which is literally powergaming to my understanding.

**Comment by kuf-1** [comment]
Yessss

**Comment by ChainedDev** [comment]
If there's 7 cops on, and all 7 cops are worries about 1 store robbery we have bigger problems then the inconsistency of demands

**Comment by skiredd** [comment]
well im pretty sure it was 6 but one cop doesnt make much of a difference but both are still important issues

**Comment by kuf-1** [comment]
True, but it appears both problems exist. What you're describing would be on the FTO end of their guidlines & way of doing procedures. This suggestion would solve one of those issues i.e. this suggestion. <3
