### ISSUE TITLE
Make Female & Male Health Equal.

### ISSUE THREAD

**Issue by pixlangel** [ChainedDev/CityLife#268]
**What is the reason for this balance request?**
The medkits in the city only heal females to about 80% health. The only way we can receive full health is from an EMS or going to pillbox. If the medkits, and other health related items are filling males health to 100%, this is completely unfair for the females.

**What solution would you like?**
Make it so that male and female health bars are both equal in the city.

**Comment by ChainedDev** [comment]
Medkits should be healing you the same as EMS or Checking in to the hospital, natively GTA 5 sets female ped health to 175 and male health to 200.
