### ISSUE TITLE
An army crawl action

### ISSUE THREAD

**Issue by THELONEWOLF980** [ChainedDev/CityLife#269]
Would like to see an army crawl action added. Its kinda hard to sneak around when your head is always sticking up out of a bush while crouching. I know we have some actions that you can lay down with but you can only lay there for so long without moving before you get kicked for afk. I had a scene where I was hiding in a bush from the cops and they waited for 10mins around the area and I got caught cuz I had to get up and move around so I didn't get kicked for afk.

**Comment by ChainedDev** [comment]
./e sleep 
./ sunbathe
./e crawl
