### ISSUE TITLE
Dark Web

### ISSUE THREAD

**Issue by BluDruw** [ChainedDev/CityLife#27]
**Is your feature request related to a problem? Please describe.**
ID if there is an issue related to this but it would be very helpful to people who chose the life of crime.

**Describe the feature you'd like**
A Dark Web app on the phone that people would gain access to by being invited by someone who is already in it. It would deny access to anyone who is signed in as a cop to prevent metagaming.

**Describe alternatives you've considered**
There could be a way for cops to gain access to it by having a cybercrime fighting tag/role in-game that way it could be balanced a little.

**Comment by ChainedDev** [comment]
That feature already exists in game, there's plans to make it better though
