### ISSUE TITLE
Officer Clock In and Clock Off Log For Discord

### ISSUE THREAD

**Issue by ABOW402** [ChainedDev/CityLife#270]
**Is your feature request related to a problem? Please describe.**
No problems. Sometimes its hard for us to know who has been on duty and not on duty.

**Describe the feature you'd like**
I would like to see a log in discord for the SASP command to see when someone has clocked on and clocked off. This helps us track activity, especially when coming to promotions. I know there are plenty of scripts that can track when an officers hits the E command to clock on and off. I have provided link below, and can provide other resources as well if need be! I know this would greatly help the SASP, and don't think this would be that rough to put in place! :)

https://github.com/utkuali/Shift-Log-to-Discord

**Describe alternatives you've considered**
I am not sure what other alternatives there need to be. this would be super simple and easy to put in place! 

**Additional context**
LINK TO SHIFT LOG TO DISCORD - https://github.com/utkuali/Shift-Log-to-Discord

**Comment by McFry36** [comment]
Looks very similar to my EMS open suggestion as well

**Comment by ChainedDev** [comment]
Mentioned in #221
