### ISSUE TITLE
SASP EUP COMPLETELY MESSED UP

### ISSUE THREAD

**Issue by ABOW402** [ChainedDev/CityLife#271]
**Is your feature request related to a problem? Please describe.**
Yes. Currently we have about 30% of the EUP brought in with the Chapter 2 update. We were hoping chapter 3 would fix. Can we please get this fixed ASAP. Even just the vests and shirts at this point.

**Describe the feature you'd like**
The EUP we have in now is AMAZING and I know we will be super stoked to get the full EUP in place. However, right now as it stands, we have 30% of the pack. The SASP has no vests, no hats, no badges, no comms, etc. Its missing a lot. This pack looks great and super nice, and I know this would look great for the SASP. I hope this can be fixed and brought in, cause I really like these outfits, and they just look so nice. If we could get the rest of the features from the EUP, thatd be AMAZING.

LINK TO THE EUP - https://imgur.com/a/n0S4aTE

**Describe alternatives you've considered**
Either getting this EUP in place, or considering getting another one. I would also be down to pay for one myself, if that means my officers can be suited up correctly.

**Additional context**
LINK TO WHAT WE SHOULD HAVE - https://imgur.com/a/n0S4aTE

**Comment by Forkedup** [comment]
@ABOW402 Is this all good now?

**Comment by ChainedDev** [comment]
yes
