### ISSUE TITLE
Add Bigfoot to the city

### ISSUE THREAD

**Issue by TimmyTwoStep** [ChainedDev/CityLife#273]
**Describe the feature you'd like**
I think it would be really cool if Bigfoot was added to the city and he could be hunted down and be worth a lot of money. The best way I think it should it could be done is after every reset there is a 1/100 chance that he is in the woods up north around in the Canyon so people couldn't just farm him for cash. 

**Describe alternatives you've considered**
I haven't came up with any alternatives besides just making him pretty rare and worth less instead of the 1to1 with a chance of him being in the city. Or the werewolf from GTA online as something you could hunt.

**Additional context**
I don't have any kind of files for him or anything but he is in the base game of Grand Theft Auto 5. I'm not a fancy dev or anything and wouldn't know how to get those

![bigfoot-from-grand-theft-auto-v-01](https://user-images.githubusercontent.com/68301984/87478793-56614d00-c5f8-11ea-9208-94a40be35279.jpg)

**Comment by ChainedDev** [comment]
no pls
