### ISSUE TITLE
Hire some cops 

### ISSUE THREAD

**Issue by ParasitePickle** [ChainedDev/CityLife#274]
**Is your feature request related to a problem? Please describe.**

Yeah there are no cops!
**Describe the feature you'd like**
Bruh just hire some cops 
**Describe alternatives you've considered**
[What alternatives solutions have you considered? 
none
**Additional context**
Dont say there are no applications I know like 6 people who applied more then a week and a half ago. And like 75% of the police force now is super inactive although a couple are on LOA from what ive been told

**Comment by ArkRevert** [comment]
All depends when you are around the server is primarily EST timezone so there will be less when its late. AMD they have to train the cadets there are before hiring more.

**Comment by ThomasBonelli** [comment]
It is not just about hiring as many cops as possible. It is about hiring cops that bring good rp and are not going to be corrupt. That is why there is an application process. To be honest if your cop application is turned down then you need to put more time into your application and think about bringing more to the force than "a good shot" or "good driving". The PD is looking for people that will make interactions with the police force more interesting than people bullshitting you from my understanding.
