### ISSUE TITLE
A possible fix for the hearing everyone in the server bug.

### ISSUE THREAD

**Issue by VivusNAE** [ChainedDev/CityLife#275]
**Is your feature request related to a problem? Please describe.**
Some people including me have this problem where we can hear the whole server when we load in and we have all tried everything. We have cleared our cache, turned voice chat on/off, reinstalled FiveM, etc. Nothing seems to work.

**Describe the feature you'd like**
I have noticed that the bug only sticks to the server so if we made a second CityLife Roleplay server the problem would go away and we could still play CityLife. Also, having a second server could help with queue times, there would be 2 servers people can go into instead of having 1 server with 1+ hour long queue times.

**Describe alternatives you've considered**
I have not thought of any alternatives other than making a new server.

**Additional context**
N/A

**Comment by ChainedDev** [comment]
Should be fixed with the new voice system, don't know about the ladder as of recent kek
