### ISSUE TITLE
new clothing ideas

### ISSUE THREAD

**Issue by hippyyy** [ChainedDev/CityLife#276]
**New clothes and personal customization**
i think that we can all agree that one of the reason we love FiveM is for the diversity of the game and the possibility's included with it, and one of the possibilities is obviously player customization, i think having more customization will enhance the fun in playing in the city, i have a few ideas here are they.
1. Custom bullet proof vest ex: vest with the louis V pattern, vest with all over supreme logos ect ect
2. headbands: supreme headbands, Gucci ect ect
3. more skirts for females (suggested by a fellow player in the discord server)
4. custom pants: pants that are "saggy" or just louis v pants ect ect
5. custom hair! custom dreads, many many hair ideas can come to mind
**Describe alternatives you've considered**
 for alternatives i think we could just add some of the trend clothing brand that are ongoing in the world of today, like i suggested with the saggy pants in 2020 that's a popular trend, i think implementing that into the server will turn the city even more realistic for the simple fact it makes you feel like you are experiencing the same lifestyle as in real life

**Additional context**

pictures of ideas:

bulletproof vest: 
![image](https://user-images.githubusercontent.com/68348921/87583660-b1577a80-c6b2-11ea-88ca-158827126e50.png)

Headbands: 
![image](https://user-images.githubusercontent.com/68348921/87584201-828dd400-c6b3-11ea-9a0f-0e4c8d662472.png)

skirts: 
![image](https://user-images.githubusercontent.com/68348921/87584270-9df8df00-c6b3-11ea-9a58-94e8056ba10d.png)

pants: 
![image](https://user-images.githubusercontent.com/68348921/87584323-b10baf00-c6b3-11ea-8f8f-a74b4f9df6e7.png)
![image](https://user-images.githubusercontent.com/68348921/87584372-c4b71580-c6b3-11ea-9d56-a28ac5116e23.png)

hair: 
![image](https://user-images.githubusercontent.com/68348921/87584581-1a8bbd80-c6b4-11ea-89e5-cc7181c977b8.png)
![image](https://user-images.githubusercontent.com/68348921/87584600-211a3500-c6b4-11ea-9c90-89f3c77df49e.png)
![image](https://user-images.githubusercontent.com/68348921/87584609-27101600-c6b4-11ea-90ff-72188b313506.png)
![image](https://user-images.githubusercontent.com/68348921/87584621-2c6d6080-c6b4-11ea-8f5c-7c65283ade07.png)
![image](https://user-images.githubusercontent.com/68348921/87584634-31321480-c6b4-11ea-83fc-f53607242afe.png)
![image](https://user-images.githubusercontent.com/68348921/87584651-35f6c880-c6b4-11ea-940a-d397b03cf0d2.png)
![image](https://user-images.githubusercontent.com/68348921/87584662-3b541300-c6b4-11ea-8eae-16f91a05a50b.png)
![image](https://user-images.githubusercontent.com/68348921/87584685-41e28a80-c6b4-11ea-8dd8-9bd30ac23b18.png)
![image](https://user-images.githubusercontent.com/68348921/87584716-49099880-c6b4-11ea-9017-c96c1e608d78.png)

**Comment by hippyyy** [comment]
Bump

**Comment by hippyyy** [comment]
Bump

**Comment by ChainedDev** [comment]
Where did you find these from? @hippyyy

**Comment by hippyyy** [comment]
> Where did you find these from? @hippyyy

@ChainedDev i found them on a server called something like ganglife rp or crimeliferp cant remember but i think it would add so much fun into the city for gangs ect honnestly just overall a big improvement

**Comment by hippyyy** [comment]
@ChainedDev its called hoodrichrp :)

**Comment by Forkedup** [comment]
Thanks for the suggestions, I am currently looking into expanding our current clothing line for both female / males and will take these suggestions into consideration.
