### ISSUE TITLE
Fix pdm cars

### ISSUE THREAD

**Issue by LarsJonsson772** [ChainedDev/CityLife#277]
**Is your feature request related to a problem? Please describe.**
It is related to the problem that you cant do cosmetic upgrades on most of the new pdm cars.

**Describe the feature you'd like**
The feture i would like is that the goverment fixes the cars so you can upgrade performance and cosmetics sicne you cant do almost anything on some cars that you should be able to do cosmetics to.

**Comment by ChainedDev** [comment]
Can you give examples on what cars are bugged?

**Comment by Decirus** [comment]
2 that I know are GP1 and Adder, I think Adder is just super slow but the GP1 is also really slow for its cost but also its missing a mechanic feature you're normally able to do, headlight covers are missing as an option which have like 3-4 different options on it

**Comment by Forkedup** [comment]
Made changes to the adder, and GP1 to better reflect their price.
The mechanic problem is a different issue and will take more time, but we are aware of it.

Thanks for the suggestions.
