### ISSUE TITLE
pdm cars scuffed

### ISSUE THREAD

**Issue by Givantee** [ChainedDev/CityLife#280]
**What is the reason for this balance request?**
[The new cars have terrible tune]

**What solution would you like?**
[properly tune them with more realistic numbers]

**Additional context**
[Example: Bifta can beat the new Adder in a race. Also beats all the other new cars or comes close to it because they are extremely slow for their price point and their speed in the real world.]

**Comment by Rileystone-Lost** [comment]
Caracara 4x4 tops out at 97 with turbo tuning for 82k
Bison tops out at 105 stock for 18k

**Comment by Forkedup** [comment]
Sorry for the late reply all. 
I balanced the cars pointed out here. Please let me know if there are others.

Thanks a lot.
