### ISSUE TITLE
Fix the Rebla gts

### ISSUE THREAD

**Issue by LarsJonsson772** [ChainedDev/CityLife#281]
**Describe the bug**
The pdm suv rebla gts customization is bugged. You can only do engine and turbo even tho you should be able to do more performance and cosmetic upgrades like exhaust,grill etc. And you can also not go into first person when in the car.

**How to Reproduce the Behavior**
Maybe fix the bug so that you can actually upgrade the car as you normaly can.

**Comment by ChainedDev** [comment]
Fixed.
