### ISSUE TITLE
More Bikes

### ISSUE THREAD

**Issue by Glxxm** [ChainedDev/CityLife#282]
**Is your feature request related to a problem? Please describe.**
Nah not a problem.

**Describe the feature you'd like**
Just some more bikes at the dealership. There's a decent amount already, but it'd be cool to have access to more. especially some that are a little faster :)

**Comment by ChainedDev** [comment]
Any suggestions for what kind of vehicle models you'd like to see?

**Comment by ABOW402** [comment]
@ChainedDev R6, ZX6R, GSXR, CBR600, ZX10R, CBR1000, DUCATI, SOME ACTUAL DIRTBIKES LIKE YAMAHA AND KAWASAKI MODELS :)

**Comment by Tiquoti** [comment]
> Normal bikes, like a BMX

Theres a bmx already im 90% sure

**Comment by skiredd** [comment]
there is already a BMX at the motorcycle dealership

**Comment by Msblueshines** [comment]
i had suggested this a while ago .. LOL 
 https://www.gta5-mods.com/vehicles/2018-yamaha-yzf-r1-addons-tuning

**Comment by Forkedup** [comment]
I'll be adding a lot more motorcycles and cars very soon, appreciate the suggestions.
