### ISSUE TITLE
House Robberies

### ISSUE THREAD

**Issue by KrispyTheElf** [ChainedDev/CityLife#283]
**What is the reason for this balance request?**
House robbing is no longer profitable.

**What solution would you like?**
Please adjust the rates of drops during house robberies closer to what they originally were.

**Additional context**
The entire city is excited for these house robberies. And when stuff like this becomes no longer profitable, it makes people rather upset that yet another lucrative side-job has been nerfed and once again they're forced to rely on Post Ops or Drug Dealing.

**Comment by yggun** [comment]
yall abused it so it got nerfed.

**Comment by yggun** [comment]
like yall abused sharks

**Comment by yggun** [comment]
house robberies arent supposed to be a " lucrative side-job". Its supposed to add cop to crim interaction not for you to run from house to house as fast as possible and make 40k every night cycle. learn how to RP.

**Comment by ChainedDev** [comment]
As soon as the most op thing gets a slight nerf you guys complain, cut this shit out already
