### ISSUE TITLE
0 as total inventory of item

### ISSUE THREAD

**Issue by mubbsy** [ChainedDev/CityLife#284]
**Is your feature request related to a problem? Please describe.**
No current problem besides it taking extra time to type in quantities of each item you want to move to a form of storage/the ground.

**Describe the feature you'd like**
Would be very handy to have 0 move all quantity (if it fits) into things like trunks, storage, the ground, etc. instead of just saying invalid quantity.

**Describe alternatives you've considered**
I mean other numbers could work, but 0 is unused currently and very easy to hit.

**Additional context**
https://i.imgur.com/7tBZvUk.png

**Comment by ChainedDev** [comment]
👀 could def be possible

**Comment by ChainedDev** [comment]
nah
