### ISSUE TITLE
Purchasing Certain properties without the use of D8

### ISSUE THREAD

**Issue by zactasia** [ChainedDev/CityLife#285]
**Is your feature request related to a problem? Please describe.**
D8 isn't always on and available so making a system for small apartments/houses to be bought without them.
**Describe the feature you'd like**
Similar to buying a car. The small apartments/houses can be bought without a D8 agent. Anything under the price of 100k can be bought by walking up to the apartment and purchasing.
**Describe alternatives you've considered**
Hiring more D8, maybe like property management that have some D8 power for certain houses/apartments but not like the main D8 Realtors. Almost like a Cadet for the police but for D8.

**Additional context**
I see a ton of people asking for D8 on twitter/discord and do see much response from D8.

**Comment by Decirus** [comment]
Maybe if you looked at the pinned messages it says to DM us so we can schedule a meeting. I'm in the city every single day but not on duty because noone is asking on twitter nor my dms.

**Comment by Decirus** [comment]
Completely would cancel the point of D8

**Comment by zactasia** [comment]
wasn't meant to be a shot at d8 it was just a suggestion...

**Comment by ChainedDev** [comment]
You can rent from other players by getting the key
