### ISSUE TITLE
Ability to be a tow truck driver

### ISSUE THREAD

**Issue by Tiquoti** [ChainedDev/CityLife#288]
**Describe the feature you'd like**
I would like it if it was possible to be a tow truck driver without having to be a fully fledged mechanic. I find the idea of working with pmd/ems/pd to tow vehicules parked in spots they shouldn't be in fun and could bring another kind of rp, but I have no interest in being a mechanic.

**Additional context**
It could still remain a whitelisted job, maybe be paid by the cars towed and/or make it possible to fine cars that are improperly parked. Tow trucks are badass.

**Comment by ChainedDev** [comment]
Rp and see if you can work as just tow truck driver through the mechanics
