### ISSUE TITLE
Ability to be a Gruppe Sechs worker

### ISSUE THREAD

**Issue by Dopeyxd** [ChainedDev/CityLife#289]
**Is your feature request related to a problem? Please describe.**
no

**Describe the feature you'd like**
pretty much post ops but better 

**Describe alternatives you've considered**

**Additional context**
ah yes dont know

**Comment by TheLitteralIcemanStraightOuttaFinlandia** [comment]
Wouldnt that eliminate the purpose of postops if theres a superior version?

**Comment by Forkedup** [comment]
We’ve had a job similar to this and it was very buggy overall.

We will be implementing a lot of new jobs and balancing the current ones very soon.

Take care
