### ISSUE TITLE
New feature?

### ISSUE THREAD

**Issue by THELONEWOLF980** [ChainedDev/CityLife#290]
**Is your feature request related to a problem? Please describe.**
No problem. Just a suggestion.

**Describe the feature you'd like**
Make it so we can hide in the trunks of vehicles and put players in the trunks such as hostages. I feel it would be more "Realistic" because you're not gonna carry someone in your lap or let them sit in a seat where the cops can see them when you're taking them hostage.

**Comment by ChainedDev** [comment]
Duplicate of #256 but we do plan on getting this in as soon as we get the chance to
