### ISSUE TITLE
teased inventory color

### ISSUE THREAD

**Issue by skiredd** [ChainedDev/CityLife#292]
**Is your feature request related to a problem? Please describe.**
new inventory orange

**Describe the feature you'd like**
make new inventory not orange

**Describe alternatives you've considered**
anything other than orange

**Additional context**
why is it neon orange

**Comment by ChainedDev** [comment]
Do you guys seriously not like it?........

I think it looks fire

**Comment by skiredd** [comment]
dude ur trolling stop it

**Comment by skiredd** [comment]
i refuse to believe you looked at that color and deemed it okay LMFAOO

**Comment by klucx** [comment]
That dog shit inventory looks like josh ate a bunch of fucking Taco Bell burritos and shat all over the fucking  inventory. If I have to open my inventory every time I go gambling and see that dog shit fucking color on my screen I’m going to punch my monitor every time and quit the server

**Comment by ChainedDev** [comment]
It's too fire yo
