### ISSUE TITLE
Make a gang whitelist application/ add gang looking for group section in discord

### ISSUE THREAD

**Issue by xxArmyGuy727xx** [ChainedDev/CityLife#293]
1.) So I think you should add a gang whitelist application to the game so that way when a gang gets big enough (5-10) people they can be given the role/job ingame and out of game (discord). Not only would this help make more gangs but it would probably make shit more fun.

2.) I also think you should make a Gang LFG section in discord so that way when gangs need members or people want to join a specific type of gang they can advertise what they want or that they are recruiting. It would make joining gangs easier.

**Comment by McFry36** [comment]
The gang aspect of the city should all be developed through genuine good RP in the city. Not crafted OOC

**Comment by xxArmyGuy727xx** [comment]
> The gang aspect of the city should all be developed through genuine good RP in the city. Not crafted OOC

Okay thats cool but the first part isnt OOC.

**Comment by McFry36** [comment]
A gang gets whitelisted when they’ve dedicated enough time, and immersion within the city. They stand out with stellar RP and hold themselves to a standard. It doesn’t just happen when 5 people join up that have been here for 10 days.

**Comment by skiredd** [comment]
yeah i feel an application would just ruin the work and rp that goes into being whitelisted

**Comment by ChainedDev** [comment]
https://rplife.city/apply/WhitelistedGang
