### ISSUE TITLE
Let us change the color of cars without a mechanic please

### ISSUE THREAD

**Issue by Retrodios** [ChainedDev/CityLife#294]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the feature you'd like**
It would be awesome to be able to repair and change the color of the car at bennys without a mechanic.

**Describe alternatives you've considered**
There could also be legal and illegal upgrades to balance it out for the mechs.

**Comment by zactasia** [comment]
What if when you bought the car you could choose a basic color. Just the primary color and there are only a few options?

**Comment by Tiquoti** [comment]
I just want to be able to see the possible modifications instead of relying on a mech, when I probably won't even buy it.

**Comment by Droshky** [comment]
bump

**Comment by ChainedDev** [comment]
yewah

**Comment by Retrodios** [comment]
> 
> 
> What if when you bought the car you could choose a basic color. Just the primary color and there are only a few options?

That sounds even better :) 

I just noticed in my timezone there are barely any mechs around so it would be a nice feature. But you guys know best :)
