### ISSUE TITLE
Make Cuffs More Immersive

### ISSUE THREAD

**Issue by kuf-1** [ChainedDev/CityLife#295]
**Is your feature request related to a problem? Please describe.**
Not Necessarily.
**Describe the feature you'd like**
Currently Cuffs Cost 2k, & "Disappear". The reason it is like that, is because it lessens the need to rob while preventing people from being money driven, as opposed to role play driven. That is understood, but there is also a rule in place that prevents chain robberies. If one robbery happens, you CANNOT rob another person for 45 minutes. So, why make it so the cuffs disappear? 9/10 times the person being "robbed" doesn't even hold $300 let alone what the price of cuffs were. Robbing a store grants 3k dirty, MAX on a good day. Avg, is 1.5k dirty. The cuffs(2k) nullify that completely & harness robberies to be theoretically useless. The best way to prevent "chain robberies" is with the rule. Chain robberies can be just as bad as Fail RP, or RDM. There is no real reason to use 2 sources to diminish 1 problem. Either have the chain robbery rule, or have the 1 time cuff use(to rob). In my opinion, keep the chain robbery rule, & allow Cuffs to be used multiple times & potentially "break" like lockpicks or as such items(advanced picks,etc..)..

**Comment by skiredd** [comment]
i dont think handcuffs should ever be unbreakable but i agree that the 2 solutions to one problem isnt good


but the average danny criminal with handcuffs isnt going to follow the 45 minute rule unlike most experienced crims

**Comment by skiredd** [comment]
and them not following the rule would ruin it even more than it already is
