### ISSUE TITLE
using ID for cuffing/carrying/dragging

### ISSUE THREAD

**Issue by skiredd** [ChainedDev/CityLife#296]
**Is your feature request related to a problem? Please describe.**
sometimes cuffing someone or dragging/carrying someone picks up the wrong person

**Describe the feature you'd like**
maybe have those commands tied to an id rather than whoever is closest

**Describe alternatives you've considered**
none

**Comment by ChainedDev** [comment]
Will be brought in with #419 gonna close this ticket for now!

**Comment by ChainedDev** [comment]
Nevermind, redact previous statement check out 419 tho
