### ISSUE TITLE
city buildings not loading properly

### ISSUE THREAD

**Issue by IonClaw** [ChainedDev/CityLife#297]
**Is your feature request related to a problem? Please describe.**
there is an issue with the city buildings not loading for many people 

**Describe the feature you'd like**
create 2 servers with a population of 64 people this would help with the city buildings not loading.  at times there is a large flight time this will lower that with the extra 28 slots created. server 1 could be whitelisted to help with the danny situations for the people that have been here for x amount of months make then whitelisted those that are not whitelisted but are trying to be good role players would have an opportunity to be whitelisted after x amount of months on server 2 

**Describe alternatives you've considered**

**Additional context**

**Comment by ChainedDev** [comment]
Has to do with some textures not all because of player slots, it doesn't help when 50 people hangout at PDM/Legion/Legion garage 24/7
