### ISSUE TITLE
More features for handcuffs

### ISSUE THREAD

**Issue by skiredd** [ChainedDev/CityLife#298]
**Is your feature request related to a problem? Please describe.**
Yes, handcuffs have limited use

**Describe the feature you'd like**
Have the handcuffs allow a menu to be opened (like the F6 menu) that lets you search, drag, uncuff etc.

**Describe alternatives you've considered**
none

**Comment by skiredd** [comment]
to add on to this, handcuffs shouldnt be just a burglary tool

it should be a tool used to make fun rp in hostage situations and more

**Comment by ChainedDev** [comment]
More things coming to handcuffs

**Comment by ChainedDev** [comment]
Added use into #419
