### ISSUE TITLE
Add upgrades and bodyparts to the Caracara 4x4 and the other cars that cannot be customised

### ISSUE THREAD

**Issue by WillGG12** [ChainedDev/CityLife#299]
**Is your feature request related to a problem? Please describe.**
No, its just a preference for my experience

**Describe the feature you'd like**
Just to add the upgrades and parts for the cars that are only able to have turbo and colour put on them
**Describe alternatives you've considered**
none
**Additional context**
no

**Comment by ChainedDev** [comment]
Do you know which other cars cannot be customized?

**Comment by WillGG12** [comment]
> Do you know which other cars cannot be customized?

Not too sure, I think it may be most of the newer DLC gta vehicles

**Comment by Forkedup** [comment]
Issue has been fixed, thanks for bringing it to our attention.
