### ISSUE TITLE
Add Radios, Remove "Bluetooth"/Outside Communications.

### ISSUE THREAD

**Issue by kuf-1** [ChainedDev/CityLife#300]
**Is your feature request related to a problem? Please describe.**
Yes, People dont communicate "Out-loud" when around other people & in blue tooth.

**Describe the feature you'd like**
Add Radios,  Turn it on using inventory (drag to use) and theres like 1000 channels you can select from with your, "gang" or police"

**Additional context**
This will make the server SO MUCH MORE Immersive. Not only will gangs or people grouped up be forced to talk in game, it just makes everything so much more immersive. Say you and your boy are in the middle of the desert alone.. talking through bluetooth..  even just talking in game makes that scenario so much more realistic for the user as opposed to outside communications. It doesnt make sense for it to be like this. Add radios, enforce them for civilians and with the acception of maybe police BAN outside communications completely. Have everything be In game. This will get rid of people having "gang discords" and Doing shit for unfair advantage because it happens. Instead of people using their discord to talk and to get information, in game people can use the dark web #VercettiInfo or something like that to find the latest news of what happened in the gang if noone else is online or getting DMs. Get rid of all outside communications.

**Comment by skiredd** [comment]
pretty sure mumble voip also already has radios built in just like Toko its just buggy afaik but getting that to work would be insane

**Comment by ChainedDev** [comment]
Done!
