### ISSUE TITLE
Tuner Chips

### ISSUE THREAD

**Issue by kuf-1** [ChainedDev/CityLife#301]
**Describe the feature you'd like**
A purchasable "Tuner Chip" That will increase acceleration & speed for roughly 45 minutes or so..
**Additional context**
Gang Controlled & Whitelisted Like other Drugs/Items, There are plenty of abandoned or badass mech shops around the city that this Whitelisted gang could use to install these underground"Tuner Chips". As we Know RACING is MASSIVE in this City. Customizing Cars & gaining an advantage in Racing or Getting away from a Store Robbery etc.. Many servers have Tuner Chips. They could be given to the whitelisted gang from the "Government" and sold at a rate that isn't insanely profitable but costs enough for what it is worth. These Chips would work on personal , or local vehicles. - P.S. This was Preacher Preachhhh's idea. (We are gang affiliated "The Saints" & would also be willing to own this underground "mod shop".  The tuner shop up on w. vespucci blvd/murrieta heights would be an ideal static location, or it could be anywhere we meet them.)

**Comment by kuf-1** [comment]
Preacher Preachhhh's idea.

**Comment by gamerdude23** [comment]
What about permanent tuner chips? If someone likes their vehicle a lot and want it to bring out say 10-30 more MPH, they could pay a lot of money and be able to have fun with their vehicle chassis and speed.
