### ISSUE TITLE
loading screen playlist

### ISSUE THREAD

**Issue by skiredd** [ChainedDev/CityLife#303]
**Is your feature request related to a problem? Please describe.**
playlist ass

**Describe the feature you'd like**
pop smoke only playlist to piss people off

**Describe alternatives you've considered**
none

**Additional context**
Buddy gon', grrrt that, grrrt that, blrrt that, blrrt that
Send shots, make him get back
All that chit-chat, chit-chat, riff-raff, riff-raff

**Comment by ChainedDev** [comment]
deal
