### ISSUE TITLE
pdm cars upgrades

### ISSUE THREAD

**Issue by LarsJonsson772** [ChainedDev/CityLife#306]
**Describe the bug**
The cars that cannot be upgraded that i know are blista kanjo,rebla gts,carcara 4x4

**Comment by JJG1997** [comment]
Basically it is most of the new update. The Street Blazer can’t be upgraded or customised mechs don’t even get the option

**Comment by ChainedDev** [comment]
Looking into it, it is also prevalent with some ad-don cars as well

**Comment by ChainedDev** [comment]
Fixed!
