### ISSUE TITLE
New LEO Departments (maybe some COs)

### ISSUE THREAD

**Issue by xxArmyGuy727xx** [ChainedDev/CityLife#307]
**Is your feature request related to a problem? Please describe.**
Yes, the SASP can’t be everywhere at once.

**Describe the feature you'd like**
I think it would better the RP experience of everyone to implement multiple Police Departments for different areas. Like up north would be Blaine County Sheriffs Office. Then SASP would get major road ways (since that’s what state troopers actually do). Then LSPD would obviously get the major city. Maybe also add some corrections officers to make prison more of an RP experience for those that have a longer sentence. I feel like adding all of these or at least one more would benefit both the citizens and Police Officers.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Tiquoti** [comment]
The only way i could see this working is if an officer misbehaves they're sent north, due to the fact it's very dull up there

**Comment by skiredd** [comment]
i think the problem with this is the amount of cops on

if there is 10+ like that one day then it could work

but having less than 10 would not be viable imo

**Comment by JJG1997** [comment]
Cops do patrol up north too, as we are state troopers we patrol the whole of LS.

**Comment by xxArmyGuy727xx** [comment]
Some people (such as older individuals) want to be a cop but without all the excitement. So having them would benefit these players. Also it would benefit RP situations that lead into car chases having people up North.

**Comment by Skader91** [comment]
I get you, We allow people to patrol up north once we have enough in the city. If we have 4-5 in LS then it's allowed to go up north and being as that we are State Police we cover the entire map with no plans on opening Sheriff nor Park Ranger's Departments.

**Comment by xxArmyGuy727xx** [comment]
Well that still doesn’t take out my CO option for prison. Prison can get really boring. So to make it better and if multiple people get arrested for a long time they can actually RP with a CO present to make things real

**Comment by Skader91** [comment]
I do like the idea of having correctional officers, so let's see what we can come up with for that.
