### ISSUE TITLE
hayabusa drag way to slow for price 

### ISSUE THREAD

**Issue by oENDGAMEo** [ChainedDev/CityLife#31]
**What is the reason for this balance request?**
[Bike to slow compared to others in city for its price**]

**What solution would you like?**
[At least 170-180 for a bike that cant do wheelies !**]

**Additional context**
[this bike only does 120 as of now and is a stock price of 130k when fully upgraded it does 120mph!**]

**Comment by gullidog** [comment]
Did you mean the Hakuchou Drag? Also, long bikes do not do wheelies?

**Comment by oENDGAMEo** [comment]
yes and it does 120 mph maxed

**Comment by ChainedDev** [comment]
Made before wipe, not sure how the price to speed ratio is hope we did a good job :D
