### ISSUE TITLE
DIRTY MONEY

### ISSUE THREAD

**Issue by TheLitteralIcemanStraightOuttaFinlandia** [ChainedDev/CityLife#310]
**Is your feature request related to a problem? Please describe.**
Dirty money not being able to be stored anyways and your able to see it on people when handcuffing or searching

**Describe the feature you'd like**
Reversing back to the old system and having dirty money as a physical object that is able to be stored while the new system with dirty money is being made that tony stated somewhere. 

**Describe alternatives you've considered**
Make it so you can't confiscate dirty money from other people while the new system is being implemented even though that is a bad idea because drug sellers can get away with with the drugs theyve sold. 

**Additional context**
I think a lot people like me are afraid of being in the city because of the high amount of dirty money they are possesing, because if a cop arrests you, then Theyll take all of your dirty money and youll loose a lot of it, or if someone robs you on it, they will seize all of your grind because you can't store it.

**Comment by ChainedDev** [comment]
We are currently working on a new system for dirty money, thank you for your concerns and we hope to address them sooner than later
