### ISSUE TITLE
IFAK

### ISSUE THREAD

**Issue by skiredd** [ChainedDev/CityLife#311]
**Is your feature request related to a problem? Please describe.**
theres no legal alternative to oxy

**Describe the feature you'd like**
Add IFAKs that cops can use to stop bleeding/reduce damage quickly in battle just like oxy.

**Describe alternatives you've considered**
I would say medkits, but medkits take too long and are not viable.

**Comment by ChainedDev** [comment]
Medical Syringes!

**Comment by ChainedDev** [comment]
(You guys have morphine btw)
