### ISSUE TITLE
New searching system for cops

### ISSUE THREAD

**Issue by JohnRankin19** [ChainedDev/CityLife#312]
**Is your feature request related to a problem? Please describe.**
When police confiscate items, they just disappear.

**Describe the feature you'd like**
Something similar to what criminals have, where if you do /steal you can drag items from the persons inventory you are searching to your inventory 

**Describe alternatives you've considered**
Something that allows police when they confiscate items they don’t just disappear 

**Additional context**

**Comment by skiredd** [comment]
this could also help in any like court cases where evidence is needed, cops can take an ss of the stuff in their inventory and have it on file both on picture and in person

**Comment by ChainedDev** [comment]
Additional feature: /case [32.9] where after taking the persons items you put it in a case number if it heads to DoJ and keep track of everything
