### ISSUE TITLE
Test server

### ISSUE THREAD

**Issue by Tiquoti** [ChainedDev/CityLife#313]
**Is your feature request related to a problem? Please describe.**
Yes, when an update hits it's fine to have some small issues, but the latest one just fucked a lot of things up, and with a test server where a moderate number of people test everything out over a few days before the update hits to solve some of those issues would help a lot.

**Describe the feature you'd like**
A test server for 15-20 people that are chosen or volunteer to test new updates that will be implemented so that issues are fixed before they can even become issues.

**Describe alternatives you've considered**
idk

**Additional context**
New update kinda messed things up for a lot of people

**Comment by ChainedDev** [comment]
Yeah we kinda fucked up not gonna lie with inventory but working round clock to ensure proper fixes, in event of big changes we will deffenently make sure they work properly and smoothly next time around.
