### ISSUE TITLE
Rifles showing on backs.

### ISSUE THREAD

**Issue by JJG1997** [ChainedDev/CityLife#315]
**Describe the bug**
Rifles not showing on the backs of people

**How to Reproduce the Behavior**
Steps to reproduce the behaviour: Grab an AR, pull it out and it won't be on the persons back.

**Expected Behaviour**
AR on the back.

**Screenshots**
https://i.imgur.com/eEimOBX.png
https://i.imgur.com/fM3Yjli.png

**Additional context**
N/a

**Comment by JJG1997** [comment]
Working.

**Comment by JJG1997** [comment]
Ignore - it's not

**Comment by Forkedup** [comment]
Fixed this issue, still being polished.
