### ISSUE TITLE
Duplication by passing and /ensureinv

### ISSUE THREAD

**Issue by Dasterdlehh** [ChainedDev/CityLife#318]
**Describe the bug**
It was happening with simple things like water and more crazy things like drugs at points but when passing certain amounts of items it seems to have some sort of delay and then it will duplicate some random number in the person who originally was giving something away's inventory after using the /ensureinv. Yet the people who they were passing it to will actually receive the intended amount by a simple /ensureinv as well.

**How to Reproduce the Behavior**
Steps to reproduce the behaviour:
Try passing things back and forth at random numbers. Seemed almost random

**Expected Behaviour**

Passing 5, resulting in person passing having 5 and person who passed has 0
**Screenshots**

n/a wait in comments
**Additional context**

just pls fix so no one abuses

**Comment by ChainedDev** [comment]
Put in proper checks, should be fixed.

Thank you greatly for reporting this issue to us!
