### ISSUE TITLE
Add a radio/boombox at the new studio

### ISSUE THREAD

**Issue by hippyyy** [ChainedDev/CityLife#319]
**Is your feature request related to a problem? Please describe.**
Not a problem but see not everyone has a boombox but alot of people would like to go to the studio with their friends and do some freestyle/song and its ristricting us from doing so by making us need a boom box for songs
**Describe the feature you'd like**
A boombox/radio that would be permanent into the studio to play beats/songs on for people who dont have boomboxes and still would like to rp some rapper lifestyle

**Describe alternatives you've considered**
Adding a permanent boombox in the stoo

**Comment by ChainedDev** [comment]
Yes sir
