### ISSUE TITLE
Something to do in prison?

### ISSUE THREAD

**Issue by Tetronas** [ChainedDev/CityLife#32]
Currently, the only thing that we can do in prison is wait around and do nothing, or alt tab to play another game while we wait.

If you try to do something criminal related, this is easily asking us to wait 1 hour in real life, doing nothing. Because if we walk away or try to kill ourself or do anything to pass the time other than stand around alone... This is failRP.

Can we please implement some sort of activity or at least have access to the prison yard?

**Comment by ChainedDev** [comment]
Courtyard access seems reasonable

**Comment by ChainedDev** [comment]
Planned to add more to prison a little more :soontm: than soon so you won't afk to play afk simulator because your character is in trouble

**Comment by JJG1997** [comment]
What about community service for the minor sentences?

**Comment by ChainedDev** [comment]
Oh wow! You can make food!@!@! Make new issue with more ideas if you guys want!
