### ISSUE TITLE
Small change for the new inventory 

### ISSUE THREAD

**Issue by hippyyy** [ChainedDev/CityLife#320]
**Is your feature request related to a problem? Please describe.**
Yes it is indeed related to a problem, i see alot of people including my self having issues with pulling out weapons and all that stuff from the quick menu so i think that if we keep the inventory as it is right now seeing as it is indeed a good inventory but get rid of the quick menu and replace it for the scroolwheel like we use to have before we wouldnt have the problem of our guns not comming out and all that stuff

**Describe the feature you'd like**
Change the quick menu from the inventory back to the scroolwheel menu allowing us to pull our weapons out without issue 

**Describe alternatives you've considered**
Removing the quick menu or fixing it but i know for a fact that 90% of people would love to have the scrollwheel back including my self

**Comment by ArkRevert** [comment]
I believe the issue with that is you can't put the scroll wheel with the new inventory since they are 2 different inventories but I'm not 100% sure.

**Comment by ChainedDev** [comment]
Should be way smoother now
