### ISSUE TITLE
Clock In, Clock Out Logs for PD

### ISSUE THREAD

**Issue by Skader91** [ChainedDev/CityLife#324]
**Is your feature request related to a problem? Please describe.**
It's hard to base activity on anything other than mdt reports for police

**Describe the feature you'd like**
Other jobs have clock in clock out, We need the same for PD.

**Describe alternatives you've considered**
There are discord bot's that track when and for how long someone joins a channel, we can do that for Dispatch

**Comment by ChainedDev** [comment]
Mentioned in #221
