### ISSUE TITLE
Fish Market

### ISSUE THREAD

**Issue by EvaLaura69** [ChainedDev/CityLife#326]
**Is your feature request related to a problem? Please describe.**
Add another fishsale place on the other side of the map too, or move the current one in the middle

**Describe the feature you'd like**
I would like to either have one in the middle like Sandy or have one more to Paleto

**Describe alternatives you've considered**
No alternatives

**Additional context**
Bring some life to the other side of the map too

**Comment by Forkedup** [comment]
I like this idea, do you have any spot suggestions for sandy or Poleto bay?

**Comment by EvaLaura69** [comment]
Tomorrow I will look for places and contact you about it
