### ISSUE TITLE
Advanced Lockpicks

### ISSUE THREAD

**Issue by EvaLaura69** [ChainedDev/CityLife#328]
**Is your feature request related to a problem? Please describe.**
Make advanced lockpicks craftable. 

**Describe the feature you'd like**
It is not ok for everyone to depend on a group of people.

**Describe alternatives you've considered**
No alternatives

**Comment by JJG1997** [comment]
Either this or a hidden NPC that sells them!

**Comment by EvaLaura69** [comment]
I agree with this too

**Comment by Forkedup** [comment]
Advanced Lockpicks are now implemented in their own unique way.
