### ISSUE TITLE
PDM feature

### ISSUE THREAD

**Issue by EvaLaura69** [ChainedDev/CityLife#329]
**Is your feature request related to a problem? Please describe.**
Give the possibility of towing cars to the PDM employees. A lost of stolen cars are abandoned on the property all the times.

**Describe the feature you'd like**
Give the possibility at least to the As.Manager

**Describe alternatives you've considered**
Provide us lockpicks when clocking in

**Additional context**
No additional context

**Comment by ChainedDev** [comment]
Report it to the police or mechanics to create rp for everyone
