### ISSUE TITLE
Cops Balancing

### ISSUE THREAD

**Issue by CityLifeB0i** [ChainedDev/CityLife#33]
**Is your feature request related to a problem? Please describe.**
Yes

**Describe the feature you'd like**
+ Cops shouldn't be carrying military issue/heavy weapons around the city. When was the last time anyone has seen a real officer just casually carrying an assault rifle while on duty in the middle of the city? LSPD officers should be limited to 9MM Pistols while just on normal duty, SASP officers are supposedly more "rural" and as such can possibly carry a Heavy revolver/Pump shotgun while on duty. However in response to a major call, such as officer down or bank robbery in progress, officers can then respond with heavy weapons. 

+ Cop Cars need a major nerf, they are zero percent realistic right now. They have a insane amount of health, travel faster than a formula one race car and have acceleration faster than a rocket ship on take off and to top it off, drive through objects/other vehicles like tanks. There is literally nothing better than seeing a police truck being able to ram into a parked semi truck and push it aside like a paper bag and continue along like it's not even there. Police car speed and acceleration needs a major nerf, as well as a decent health nerf and respond much more realistically to crashing into things especially vehicles.

**Comment by gullidog** [comment]
So, if you read the project board you would have seen we already have plans to nerf cop cars in the upcoming updates in terms of speed and acceleration.

**Comment by ChainedDev** [comment]
Cops have become balanced, let us know if you feel anything else needs to be balanced
