### ISSUE TITLE
Hitman jobs/contracts

### ISSUE THREAD

**Issue by SiriusAkaBabaYaga** [ChainedDev/CityLife#334]
**Is your feature request related to a problem? Please describe.**
[No, this is not related to any existing issues.]

**Describe the feature you'd like**
[I think that there should be added a new job of contract killing for dirty cash. Basically you would have to go to a secret spot on the map, and get a list (like from mechanic) which would include a local with their photo, time when the hunt starts (lets say 20 min), and potential location area on the map. Once a person would have the contract, all people with it would start the hunt on the local, while the cops would get a report call for someone potentially being killed. The cops would get their notification 5 min before the hunt starts, and would start patrolling and protecting the designated area. The hunt will lust for 30 min, and the prize for cops and assassins should be the same, however for assassins in dirty and for cops in cash. When the hunt ends, the contract resets to a new one in 1.30 hours and goes off the same way, with a different price, target, and location.]

**Describe alternatives you've considered**
[Imagine if crime organisations would be able to put out contracts for other players, but for higher prices. And the contracts would be available only once per 24 hours, and would be collected in a different secret spot like a bar of some sort.]

**Additional context**
[There could be made some additions for balancing. It could be made available for everyone or only for people who get the hitman job, with a restriction for only those playing at least for 2 weeks. There could be added ranking, and more things, which you could buy on a black market, for example a sniper rifle with a suppressor...or just generally a suppressor xD. ]

**Comment by ChainedDev** [comment]
Criminals can already rp putting hits/contracts out, I don't think this would be beneficial and would just increase people getting killed/killing for no reason

**Comment by SiriusAkaBabaYaga** [comment]
but that is if you are talking about the player bounties, what about the main part with local contracts

**Comment by SiriusAkaBabaYaga** [comment]
cause its neautural, however based on who is faster
