### ISSUE TITLE
Items in inventory not exactly beeing there

### ISSUE THREAD

**Issue by hippyyy** [ChainedDev/CityLife#335]
**Describe the bug**
So ive notice when i got fishing i will go and buy some baits 50 to be exact and ill go fishing and often it will tell le you ran out of baits but then i would look in my inventory and there would be 30 baits left that i paid for but that i cannot use, same goes with the fish! I would have 20 trouts sell like 10 and then it will tell me you no longuer have any fish to sell when i have 10 left

**How to Reproduce the Behavior**
Go buy baits and go fishing, it very well might also work with other stuff but fishing is where im getting issues the most regarding this

**Expected Behaviour**
Well if you have 50 baits you should be able to use all 50 seeing as you paid for them, and if you have 20 trouts you should be able to sell all 20 seeing as you caught them

**Screenshots**
Cant get ss rn sorry
**Additional context**
Well try to fix it or something loosing money isnt always fun :/

**Comment by ChainedDev** [comment]
Still re-occuring? @hippyyy

**Comment by hippyyy** [comment]
@ChainedDev not as frequently but yes. Id put ex: my meth supply in my house and when i relog i would still have it on me but its not exactly there

**Comment by Forkedup** [comment]
Glad it's less frequent, have you tried using /ensureinv ?

**Comment by hippyyy** [comment]
@Forkedup thats the thing, something i would go fish, and when i go to sell my fish it would tell me you no longuer have any fish but id have like 10 fish left and when i do /ensureinv they disappear but like i caught those fish its kinda annoying

**Comment by Dollar82** [comment]
they reason they disappear after you /ensureinv is because you already used/sold the items...
