### ISSUE TITLE
Fix the Tesla

### ISSUE THREAD

**Issue by MaximusPrimeIV** [ChainedDev/CityLife#337]
**Describe the bug**
[A clear and concise description of what the bug is. We still have to pay for gas for the Tesla when it's an electric car.

**How to Reproduce the Behavior**
Steps to reproduce the behaviour: not sure.

**Expected Behaviour**
[What was expected to happen. Us not paying for gas on an electric car.

**Screenshots**
[If applicable, add screenshots to help explain your problem. **Remove this line!**]

**Additional context**
[Add any other context about the problem here. **Remove this line!**]

**Comment by Forkedup** [comment]
Hi,

I made some changes to the gas volume of the car, but I don't think it will make a difference.

Gas is all controlled by one script, and you can't really add one car to be blacklisted from gas, although I completely understand your frustration with this.
