### ISSUE TITLE
GTA Rockstar Editor

### ISSUE THREAD

**Issue by km4411933** [ChainedDev/CityLife#339]
**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the feature you'd like**
I think it would be great to have the ability to record special events that happen in the city. Car meets, parties, just overall promoting CityLife. I know there are probably people like myself who enjoy video editing and think this would be a good feature to have. 

**Describe alternatives you've considered**
None that I can think of. 

**Additional context**
Maybe it could be implemented as an app in our phones to toggle it on/off. I know the editing feature of Rockstar Editor can be an issue so maybe only allow us to use it to record footage and not edit in the city.

**Comment by Forkedup** [comment]
Interesting Idea, but there are many ways to record that won't add additional memory usage to the City.

I believe if anything, we could add a cinematic mode, to make it easier to record and take pictures.

Appreciate the suggestion, take care!
