### ISSUE TITLE
6STR Vapid Drift Ellie Car Request

### ISSUE THREAD

**Issue by km4411933** [ChainedDev/CityLife#340]
**Describe the feature you'd like**
Just another car request champ! It would be dope to have some more drift cars as well. 

https://www.gta5-mods.com/vehicles/6str-vapid-drift-ellie-custom-add-on-tuning

**Comment by Forkedup** [comment]
Thanks for the suggestion. I’ll take a look at this car and consider it for a future update. 

Take care
