### ISSUE TITLE
Achievements 

### ISSUE THREAD

**Issue by Tiquoti** [ChainedDev/CityLife#341]
**Is your feature request related to a problem? Please describe.**
Nope, except if you consider a lack of character progression or "goal" a problem.

**Describe the feature you'd like**
It would be nice to have an achievement system so that you can strive to achieve something in the game. I read from a previous answer on a suggestion that character progression was being thought of being put in the city, and achievements would be one that I assume wouldn't bee too hard, examples of such achievements could be walking/driving certain distances, finding secret spots, making x amount of money with specific jobs, etc. It would be even better if some of those achievements could unlock specific cosmetics like outfits or car decals. Obviously I have no idea if those are feasible but even just a basic way to track stats would be fun

**Describe alternatives you've considered**
Have pet snails

**Additional context**
I like character progression and goals that I can strive for, more than just trying to make the most money and then buying cars.

**Comment by Forkedup** [comment]
I feel this would ruin the immersion.

On a side note, something like a progression system for jobs would be something possible in the future. Such as higher paychecks, different job tiers and or job levels.
