### ISSUE TITLE
New PDM cars to be imported

### ISSUE THREAD

**Issue by EvaLaura69** [ChainedDev/CityLife#344]
**Is your feature request related to a problem? Please describe.**
We need more variety, since the last rotation in PDM was a while ago

**Describe the feature you'd like**
The list of the new requested vehicles would be:
Stirling gt Nero custom
T20
Grotti itali GTO
Weeny dynasty
Ubermacht Zion Classic
Vulcar nebula turbo
Truffade thrax
Brioso

The list of vehicles that should come back
Neon
Faction
Faction Custom

**Describe alternatives you've considered**
No alternatives

**Additional context**

If anyone would like to add more to this list, just give a reply to this new proposal

**Comment by Forkedup** [comment]
Thank you, I’ll get with you and Drosh and we can figure out a nice rotation. There’s a lot of newer GTA cars I can show you guys as well.
