### ISSUE TITLE
GARAGE GATES

### ISSUE THREAD

**Issue by Dollar82** [ChainedDev/CityLife#346]
**Describe the bug**
[A clear and concise description of what the bug is.
The gates do not open,& it damages cars, i like my car undamaged 

**How to Reproduce the Behavior**
Do whatever was done to fix gate entering mine,it works now

**Expected Behaviour**
[What was expected to happen. **Remove this line!**]

**Screenshots**
[If applicable, add screenshots to help explain your problem. **Remove this line!**]

**Additional context**
[Add any other context about the problem here. **Remove this line!**]

**Comment by ChainedDev** [comment]
Please fill out more forms + add more detail :)
