### ISSUE TITLE
Fix the brabus G wagon

### ISSUE THREAD

**Issue by hippyyy** [ChainedDev/CityLife#347]
**Is your feature request related to a problem? Please describe.**
It kinda is yes the brabus g wagon doesnt have any cosmetic upgrades what so ever only performance wise and when changing the color on it it changes the Mercedes logo as well

**Describe the feature you'd like**
Some cosmetic upgrades for it and a fix to the logo changing color

![image](https://user-images.githubusercontent.com/68348921/90569132-a9906780-e183-11ea-9649-089d58e94b72.jpg)
![image](https://user-images.githubusercontent.com/68348921/90569154-b2813900-e183-11ea-839b-4360e29e3b68.jpg)

**Comment by Forkedup** [comment]
Hi, this is how the car was made. There are no mods for this car, just the basic upgrades/tints/colors.

Sorry about this, thank you for the report.
