### ISSUE TITLE
Some features I think would be cool to add down the road

### ISSUE THREAD

**Issue by Skeeelord** [ChainedDev/CityLife#35]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, just a feature to add more RP.

**Describe the feature you'd like**
- Grandma's house; somewhere that you can drag a friends body to revive them for a price, maybe like $25k. 
- Furniture for houses; custom interior decorating for owned properties, adds the possibility for a white-list or non white-list job of interior designer where people will pay you to decorate their houses but everyone has access to decorate so you don't have to have someone else do it
- Storage units; buyable storage units like the crates in the shipyards or the storage units by Vanilla Unicorn, have them be cheaper than apartments
- Illegal shop; somewhere you can buy zip ties (allows you to soft cuff), illegal ammo, body armor of different tiers, drills and other illegal items, could be hidden on the map
- tackling; shift+E while running to tackle someone
-stamina rework; idk if its just for females or not but sprint runs out after like 2 seconds of running and takes more than a few minutes to refill
- stress mechanic; things like joints, cigarettes, and caffeinated beverages lower stress built up from being near gunshots and/or getting hurt 
- cuffing rework; white listed cuffs can hard cuff and soft cuff, zip ties soft cuff only but you can escort, zip ties can be broken slowly over time and/or cut by a knife
- fictional firing range so you can work on your aim without getting harassed by the cops

**Describe alternatives you've considered**
N/A

**Additional context**
I don't expect all of these features to be added, just some features I think would be nice to add more RP and further improve the quality of the server :)

**Comment by Skeeelord** [comment]
oof i said fictional but i meant functional

**Comment by gullidog** [comment]
Some really good suggestions! Although, storage units/warehouses are already a thing and so is tackling but it is only for police. Have a good day :)
