### ISSUE TITLE
Home garage option 

### ISSUE THREAD

**Issue by codingispower** [ChainedDev/CityLife#352]
**Is your feature request related to a problem? Please describe.**
[No]

**Describe the feature you'd like**
[I'd like the option to store and retrieve my car from my home, or bring more public garages to the vacant lots around the city.]

**Describe alternatives you've considered**
[Only viable alternative is to only buy homes near a garage although a lot of the nicest homes are far from most businesses.]

**Additional context**
[Apologies if this had been brought up and denied before, i wasn't here to witness so i figured i'd suggest it.]

**Comment by ChainedDev** [comment]
Duplicate of #325
