### ISSUE TITLE
Auction house

### ISSUE THREAD

**Issue by Tropical-Gummies** [ChainedDev/CityLife#356]
**Is your feature request related to a problem? Please describe.**No

**Describe the feature you'd like**
 I would like the server to add a auction house to we’re you can auction off cars by dealerships and players 
**Describe alternatives you've considered**

**Additional context**
The auction house should be once a week at a specific time so a gathering off people can show up and auction for cars and have good interactions

**Comment by Forkedup** [comment]
Wouldn't a good alternative be a used-car shop?

One offers more RP, while one offers a fairly easy way to display your used car

**Comment by Tropical-Gummies** [comment]
You could do a poll but both are good

**Comment by Forkedup** [comment]
Something similar will be added in the future. 

Suggestion appreciated
