### ISSUE TITLE
New Japanese vehicles

### ISSUE THREAD

**Issue by MrWweed** [ChainedDev/CityLife#357]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
1.I'm thinking that a 1991 Honda NSX with flip up headlights would fit the server nicely, since its one of the most iconic Japanese cars. 2.As I've noticed this city has some of the Nissan GTR models, but i personally believe it lacks the R32 and R33 variants since they are also very iconic Japanese drift/tune cars. 3.We already have the Toyota Supra Mk4 but i think a lot of people could appreciate the beauty of the Supra Mk3. 4.The 2008 Lexus IS-F and Lexus SC300 would have their place in any Japanese car lovers garage.5. Although there's quite the range for Nissan cars i would suggest adding the 350z and 370z models to that family.6.When people talk about Japanese cars Mitsubishi comes to some peoples minds so to let those people get what they are craving for there should be an addition of the Mitsubishi Lancer Evo 6 and the Mitsubishi Eclipse.   
  

**Describe alternatives you've considered**
1.Both the one with the flip up headlights and the one without look nice. 2.There are a few more GTR variants that are less iconic but charming in their own way like the R30 and R31 which would look nice riding the streets of Los Santos. 3. Although not loved by all Supra fans the Mk5 supra should have its entry on to the streets. 4. Some of the Lexus Suvs would look nice as well. 5.If going the more classical Japanese tuner way the 300z isn't too shabby either. 6.The Mitsubishi 3000 GT would also be a great addition.

**Additional context**
1. Honda NSX (flip up): https://www.gta5-mods.com/vehicles/honda-nsx-r-na1-1992
    Honda NSX (regular lights): https://www.gta5-mods.com/vehicles/honda-nsx

2.Nissan R32: https://www.gta5-mods.com/vehicles/nissan-r32
   Nissan R33: https://www.gta5-mods.com/vehicles/nissan-skyline-r33-gtr-hq-replace
   Nissan R31: https://www.gta5-mods.com/vehicles/1987-nissan-skyline-gts-r-r31-add-on-tuning
   Nissan R30: https://www.gta5-mods.com/vehicles/nissan-skyline-rs-x-r30

3.Supra Mk3: https://www.gta5-mods.com/vehicles/1992-toyota-supra-turbo-mk3
   Supra Mk5: https://www.gta5-mods.com/vehicles/2020-toyota-supra-gr-a90-add-on-replace-fivem

4.Lexus IS-F: https://www.gta5-mods.com/vehicles/2008-lexus-is-f-replace-add-on
   Lexus SC300: https://www.gta5-mods.com/vehicles/lexus-sc300-tuned
   Lexus SUV: https://www.gta5-mods.com/vehicles/lexus-lx570-wald-2018-replace-add-on-alexhit
   
5.Nissan 350z: https://www.gta5-mods.com/vehicles/dk-s-veilside-nissan-350z-add-on-replace
   Nissan 370z: https://www.gta5-mods.com/vehicles/2016-nissan-370z-nismo-z34

6.Mitsubishi Lancer Evo IV: https://www.gta5-mods.com/vehicles/mitsubishi-lancer-evolution-vi-tme-cp9a-gsr-evo5-varis
   Mitsubishi Eclipse: https://www.gta5-mods.com/vehicles/1995-mitsubishi-eclipse-gsx

As a member of this community i would love to see at least 1 of these cars added

**Comment by Forkedup** [comment]
Thank you for taking the time to make this organized list of car suggestions, I’ll try to get all of these added to my test server for testing tomorrow.

**Comment by Forkedup** [comment]
Well, I hate to be the breaker of bad news.

I added all of these cars to my server, the only one that wasn't a resource hog (for the car model itself) was the supra mk3, which happens to be a right hand drive meaning it needs it's own resource to work properly.

If you have more suggestions I'm always down to test cars.

**Comment by Droshky** [comment]
can we get supra mk3 tho
