### ISSUE TITLE
Launcher 

### ISSUE THREAD

**Issue by BlamedEmporer67** [ChainedDev/CityLife#358]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
I would like to see a launcher for the server much like no pixels because (even tho I don’t know much about coding)I think this would resolve some server lag and fiveM ban problems along with other fiveM problems

**Comment by ChainedDev** [comment]
Thanks for your concerns but this would be nothing other than a wow factor and would be little to no fix for the problems unfortunately
