### ISSUE TITLE
New vehicle(s)

### ISSUE THREAD

**Issue by LeoGorlami** [ChainedDev/CityLife#359]
**Is your feature request related to a problem? Please describe.**
no i just always wanted this truck in RP and their arent any trucks in Luxury 

**Describe the feature you'd like**
i was hoping to add the 2017 ford raptor or the newer one, their big fast, and beautiful

**Describe alternatives you've considered**
i was also thinking of the 2017 Audi a4 quattro, these cars are a sports luxury i have one irl and i like speed and to ride like im on a nimbus cloud interior is gorgeous

**Additional context**
https://www.gta5-mods.com/vehicles/2017-audi-a4-quattro-abt-replace-tuning#description_tab
https://www.gta5-mods.com/vehicles/2017-ford-raptor-hq-rigged-suspension-multi-dirt-animated-engine-tuning

**Comment by Forkedup** [comment]
Thanks for the vehicle suggestions, I’ll throw them on my server and check them out tomorrow.

**Comment by Forkedup** [comment]
Closing the suggestion, I'm going to be looking for a mid-class truck to add to Luxury Auto's. 

Appreciate the suggestion, sadly the ford raptor is a very large vehicle and not optimized. The Audi is a great possibility for the future.
