### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by LeoGorlami** [ChainedDev/CityLife#360]
**What is the reason for this balance request?**
the request is for ores and the new change to shark fin sells

**What solution would you like?**
i mean i just don't understand the reasoning to lower shark fins sales. so are we supposed to grind for 10 hours a day 7 days a week just to get the one car we want, or the property we want? i understand that people were getting to much money from it but change the shark hot spots then. listen, i know its RP but its still a game, i love the city its great met some dope ass people and i hope to meet more, but don't punish the people grinding to provide for their group or get that car and flex, while also trying to bring great RP to the city to the sole reason that people can't keep their mouths shit about money spots. I would also like to add that the new mining system is trash only smelting one ore at a time? oh yeah lets just have our trucks full of ore so that can run a higher risk of us losing a ton of money. well not really a ton because diamond and gold are worth fuck all. but spending alot of time and going to sell it and saying to yourself this is going to take a month of my time to get what i want so i can RP more is pretty ridiculous. i hope i am making a valid point here, and im not the only one who feels this way, selling meth doesn't give you jack shit, and neither does heroin, so if we are taking the risk of going to jail for doing something then why are we doing it? I will continue to play but i feel like this is getting more grindy and less fun with the recent change i get the grind but sometimes the grind is too steep ya feel me? i love ya whoever is reading this, love the server, love the city, love the people, but please fix this way of making money. the more risk should mean more money and lets face it money talks and walks in this city. 

**Additional context**
i would love to hear your feedback, and yes i know i could leave, but that shouldn't be a mentality. i'd rather stay and kick it for a while.

**Comment by Skader91** [comment]
These were never meant to be farmed or "grinded" in a manner than makes you go from zero to "everything" in a matter of hours.

We will always reward actual RP instead of the grindy jobs.

**Comment by LeoGorlami** [comment]
i've never gotten everything in a matter of hours while shark fishing, so that point seems invalid. i still have an evo and granger with no upgrades and still 200,000 dollars away from the car and place i want.

**Comment by Skader91** [comment]
What I am saying is, you don't deserve to get everything you want from 1 grindy source that you can AFK during.
We do not reward that type of play style and when we notice it get's out of hand we make sure it isn't as rewarding to promote actual RP instead of Post ops/Fishing or Mining.

Everyone that grinds always says the same thing that they don't RP now until they have stuff but it ain't always about the destination. It's about the journey.

This is just my 2 cents and I am not a developer. Just an Admin. I will see if anyone else has a different opinion.
