### ISSUE TITLE
maybe we could get new cars ? 

### ISSUE THREAD

**Issue by Shadi1998** [ChainedDev/CityLife#361]
**Is your feature request related to a problem? Please describe.**
i just have this idea of adding new cars to the city 

**Describe the feature you'd like**
maybe the new cars would be like golf gti, golf r, seat leon, seat leon fr, seat leon cobra, bmw e30 and some nice other cars and acutally i'd be the first one to buy of these cars if they are in the city cuz you will look so god damn good 

and one more thing if you could fix this bug cuz i lost all my stuff while they were inside of my trunk. 

and thank you 👍

**Comment by Forkedup** [comment]
Hey, appreciate the suggestions. 

If you wouldn’t mind finding and linking the vehicles from https://www.gta5-mods.com 
It’ll speed the process up and make everything easier.

Thank you.

**Comment by Shadi1998** [comment]
yup sure thing man here's some of the vehicles 
https://www.gta5-mods.com/vehicles/volkswagen-golf-7-5r-2018-add-on

https://www.gta5-mods.com/vehicles/volkswagen-golf-7-gti-fmf-projectteam

**Comment by Forkedup** [comment]
You'll be pleased with a future update.

Thanks for the suggestions, take care.
