### ISSUE TITLE
New Drift cars with Drift mechanics

### ISSUE THREAD

**Issue by hippyyy** [ChainedDev/CityLife#362]
**Is your feature request related to a problem? Please describe.**
not a problem but it think alot of us enjoys drifting cars so having actual drift cars with good drift mechanics to enjoy our self would be amazing

**Describe the feature you'd like**
new drift cars heres a list
nissan 240sx
https://www.gta5-mods.com/vehicles/nissan-240sx-bn-drift-handling
![image](https://user-images.githubusercontent.com/68348921/91779003-a907c000-ebca-11ea-8169-3feb4b4e16c1.png)

nissan 180sx
https://www.gta5-mods.com/vehicles/nissan-180sx-rocket-bunny
![image](https://user-images.githubusercontent.com/68348921/91779036-c472cb00-ebca-11ea-8208-6f51712a4283.png)

nissan silvia s14
https://www.gta5-mods.com/vehicles/nissan-silvia-s14-zenki-stance
![image](https://user-images.githubusercontent.com/68348921/91779076-d9e7f500-ebca-11ea-907c-0474b4882a37.png)

nissan silvia s15
https://www.gta5-mods.com/vehicles/nissan-silvia-s15-tunable
![image](https://user-images.githubusercontent.com/68348921/91779101-ec622e80-ebca-11ea-86e7-3caf87245f86.png)

ford escort mk2 hoonigan
https://www.gta5-mods.com/vehicles/1978-hoonigan-ford-escort-mk2-rs-add-on-hq-template
![image](https://user-images.githubusercontent.com/68348921/91779128-069c0c80-ebcb-11ea-88b3-2dd318d87b25.png)

nissan 370z
https://www.gta5-mods.com/vehicles/2016-nissan-370z-nismo-add-on-lods
![image](https://user-images.githubusercontent.com/68348921/91779175-26333500-ebcb-11ea-9d31-b73864f3ae82.png)

**Describe alternatives you've considered**
add in cars that can be tuned for tuner guys some nice japanese cars that actually drifts

**Comment by Forkedup** [comment]
I'm still on the hunt for more Japanese vehicles, unfortunately none of these will be added to the city as they're very un-optimized. This is something I cannot fix as the car creator made the model very bad FPS wise.

Please feel free to suggest more :) I will most certainly test them.
