### ISSUE TITLE
ids linger after dc

### ISSUE THREAD

**Issue by skiredd** [ChainedDev/CityLife#363]
**Is your feature request related to a problem? Please describe.**
yes people who break the rules/combat log dc mid scenario
**Describe the feature you'd like**
I dont even know if this is possible, but have the ID and steam name still be in the F9 menu for at least a minute after they dc

**Describe alternatives you've considered**
Have another way to check who logs in certain situations for the normal player

**Comment by Forkedup** [comment]
I understand the frustration of someone logging mid scene, and know how annoying it can be.

However staff can handle this issue, and I don't believe it would be a good idea to allow civilians to have access to these logs.

We are changing the F9 Menu a bit very soon, to help prevent meta-gaming.
