### ISSUE TITLE
Importing Harleys

### ISSUE THREAD

**Issue by Kman259** [ChainedDev/CityLife#364]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
It would be awesome if we got Harley Davidsons added to the server. 

**Additional context**
Harley Davidson XLCR    https://www.gta5-mods.com/vehicles/harley-davidson-xlcr-add-on
Harley Davidson FLHXS  https://www.gta5-mods.com/vehicles/harley-davidson-flhxs-street-glide-special-2018-addon-replace-fivem
Harley Davidson Road King  https://www.gta5-mods.com/vehicles/harley-davidson-road-king

**Comment by Forkedup** [comment]
Thanks for the suggestion, sorry about the late reply just letting you know that you are being heard. 

I'm 100% looking for more bikes to add. GTA V Bikes, and custom add-ons as well. 

Be on the look out!
