### ISSUE TITLE
Realistic Animation to remove/put masks/shirts ect

### ISSUE THREAD

**Issue by hippyyy** [ChainedDev/CityLife#365]
**Is your feature request related to a problem? Please describe.**
Not a problem but its unrealistic how shirt and mask just desapears with a command make it so you actually do an animation of taking the mask off or shirt 

**Describe the feature you'd like**
Just make it a movement where you rip the mask of off your face or you take the shirt off

**Comment by hippyyy** [comment]
Bump

**Comment by ChainedDev** [comment]
Sure!
