### ISSUE TITLE
DRIPPED clothing store

### ISSUE THREAD

**Issue by FLAFLACKO** [ChainedDev/CityLife#366]
**Is your feature request related to a problem? Please describe.**
[My request is not related to a problem]

**Describe the feature you'd like**
[ i was thinkin to transform a normal clothing store to something more advanced, put a logo, and all the new outfits to be there, im thinkin kinda the situation with pdm and luxury autos, the clothes to be more expensive than the normal ones, to hire people there especially females, cause a lotta guys workin at pdm luxury now there is taco guys
To be able to do discounts, gifts, all the sectors to be seperated like tshirt shirt pants shoes sneakers would be better like this for rp situation
Im afraid if im gonna try the existing clothing store its not gonna be interesting for people cause they would go to the closest one since there is no new drip and all that stuff
Again just an idea :)) but im kinda hyped]

**Describe alternatives you've considered**
[I would like someone else to come with the idea but different path with suits and serious clothes and different store so we can have choices 

**Additional context**

**Comment by Forkedup** [comment]
Certainly a possibility. 

I think it would be a more down the line thing, in another business focused update.

I do like the idea of clothing stores being owned, or a owned clothing store, that does sell specialty clothing
