### ISSUE TITLE
Dealerships and cars

### ISSUE THREAD

**Issue by Hypnos1** [ChainedDev/CityLife#367]
So I had this Idea that maybe they could reduce lag in the city by separating the car dealerships by where the cars come from (american, italian, japanese, etc.) And have them spread across the city in different areas so it's more realistic and maybe have some limited run cars so I can only get them for a limited time also maybe some trucks in the future would be cool.

**Comment by Forkedup** [comment]
I appreciate the idea in terms of creating a more realistic immersion, but it would most likely if anything, be car dealerships separated by brand.

Limited time cars or a rotation for Luxury Auto's is definitely possible and I can talk to current owners of the business about it and see how they feel.
