### ISSUE TITLE
Custom radio music

### ISSUE THREAD

**Issue by CosmoKz** [ChainedDev/CityLife#368]
This is not related to an Issue.
**Describe the feature you'd like**
It would be amazing if there was something like /music in the studio, but for cars. Like you could do /music or /radio in a car and put in a custom youtube URL to play music in the radio.

**Additional context**
Just seems like an amazing feature that everyone would love if it's possible to make.

**Comment by skiredd** [comment]
already a feature in the boombox but i guess having a custom radio item that does the same thing on the move could work too

an alternative is to add mp3 files to the self radio in gta 5 but with that only you can hear the songs
