### ISSUE TITLE
Custom Bicycles :)

### ISSUE THREAD

**Issue by Malibu69420** [ChainedDev/CityLife#37]
**Is your feature request related to a problem? Please describe.**
Not at all, just adds a bit more realism and a hobby for better rp

**Describe the feature you'd like**
I would like custom bikes added to the city, as there are a multitude of add on bikes.
**Describe alternatives you've considered**
Better bmx handling.

Here are a few ive found that are nice

https://www.gta5-mods.com/vehicles/bmx-street-with-pegs-addon-replace
https://www.gta5-mods.com/vehicles/bmx-poland-edtion-2-addon-replace

**Comment by ChainedDev** [comment]
There's already BMX bikes in the city
