### ISSUE TITLE
another of a long list of cars, but a tasteful one

### ISSUE THREAD

**Issue by LeoGorlami** [ChainedDev/CityLife#371]
**Is your feature request related to a problem? Please describe.**
just wanting to give more ideas or possibilities for the car heads 

**Describe the feature you'd like**
(all the links you need to check into if you have time will be linked below)
-Ferrari 458 italia
-kawasaki ninja
-67 impala (not sure if it's an add-on or not)
-BMW S1000 RR 2014
-porsche cayenne turbo
-1987 Buick GNX
-2015 Volvo S60 Polestar 
-2020 Infiniti Q60 Project Black

**Describe alternatives you've considered**
no alternatives, i know this is alot and you have probably already tried most of these, but thanks for the time anyways, hope to see them in the city.

**Additional context**
https://www.gta5-mods.com/vehicles/ferrari-458-italia-autovista-add-on-replace
https://www.gta5-mods.com/vehicles/ninja-h2r
https://www.gta5-mods.com/vehicles/chevrolet-impala-67
https://www.gta5-mods.com/vehicles/bmw-s1000-rr-2014
https://www.gta5-mods.com/vehicles/2016-porsche-cayenne-turbo-s-beta
https://www.gta5-mods.com/vehicles/1987-buick-gnx-yarm1995
https://www.gta5-mods.com/vehicles/2015-volvo-s60-polestar-replace-analog-digital-dials
https://www.gta5-mods.com/vehicles/2020-infiniti-q60-project-black-replace-addon-s-1-0

**Comment by Forkedup** [comment]
Hello, I appreciate the suggestion and am writing this to let you know that I have tested all of these vehicles.

The only compatible vehicles that are healthy for the server, and would be a good fit are the Ninja, BMWs1000, and the 1987 Buick.

This doesn't mean they're all going to be added, but I most certainly appreciate the suggestions!

Take care.
