### ISSUE TITLE
Make Gun Grips reusable or fix them

### ISSUE THREAD

**Issue by hippyyy** [ChainedDev/CityLife#372]
**Describe the bug**
When adding a grip/flashlight to a gun if you place that gun back in your pockets, when taking it out you wont have the grip/flashlight on it anymore and if you try to replace it. It will tell you that you used all your grips
**How to Reproduce the Behavior**
Put a grip on a gun, put the gun in your pocket, take it out and see for your self

**Expected Behaviour**
The grip should disappear from your pocketd and dtay on your gun or at the very least be reusable

**Comment by Forkedup** [comment]
This is our on to-do list.

Thank you for the report, take care.
