### ISSUE TITLE
Kuh and Enzo's Discount Store's New Shipment list

### ISSUE THREAD

**Issue by AndrianiP** [ChainedDev/CityLife#373]
**Is your feature request related to a problem? Please describe.**

Yes. This list was created by **Lorenzo Blanco**, one of the co-owners of _Kuh and Enzo's Discount Store_ located at 1072 near the _VU_, but **inspired by our customers**. Our customers have given us **complaints** and **recommendations** of things they would like to be shipped from the factory to our store. We took a look around the factories and saw some things they might like and found things they recommended. Among these these things were, **new shoes, some new female clothing options, and some jerseys** that were not just Bulls. We hope as the owners of a clothing store you guys would take our opinions a bit more serious and maybe try to ship these clothes to our store.

**Describe alternatives you've considered**
To work with our current clothes and tell our customers that sorry we cannot ship these to you. Please forgive us for not having control of the factories.

**EDIT: Removed Male non mp clothes and added mp male clothes. Also added mp shoes that i could find. Im not too sure how exactly shoes work with them being mp or not...**

**Additional context**

New Shoes (Bottom half is listed as MP i dont know exactly how this works whether they are exclusive or not to male or female)

https://www.gta5-mods.com/player/air-jordan-iv-for-franklin-add-on

https://www.gta5-mods.com/player/air-jordan-1-new-texture-1-0

https://www.gta5-mods.com/player/adidas-superstar-new-texture

https://www.gta5-mods.com/player/travis-scott-sneaker-pack

https://www.gta5-mods.com/player/nike-air-max-1-new-texture

https://www.gta5-mods.com/player/yeezy-boost-350-v2-textures

https://www.gta5-mods.com/player/shoes-air-max-template-fivem-ready-mp-male-femal-baskets-packs

https://www.gta5-mods.com/player/shoes-yeezy-gta5-fivem-ready-mp-male-femal-baskets-packs-timaxx

https://www.gta5-mods.com/player/shoes-air-jordan-template-fivem-ready-mp-male-femal-baskets-packs

MP Female Clothes

https://www.gta5-mods.com/player/cat-ears-for-mp-female

https://www.gta5-mods.com/player/sweater-pack-for-mp-female

https://www.gta5-mods.com/player/skirt-tights-and-socks-for-mp-female

https://www.gta5-mods.com/player/adidas-t-shirt-for-mp-female

https://www.gta5-mods.com/player/ripped-shirt-for-mp-female

https://www.gta5-mods.com/player/mai-cardigan-for-mp-female

https://www.gta5-mods.com/player/oversized-hoodie-jacket-for-mp-female

https://www.gta5-mods.com/player/bandana-pack-for-mp-female

https://www.gta5-mods.com/player/round-prescription-glasses-pack-for-mp-female

https://www.gta5-mods.com/player/bon-bon-choker-for-mp-female

https://www.gta5-mods.com/player/oversized-hoodie-for-mp-female

https://www.gta5-mods.com/player/winter-jacket-beanie-for-mp-female

https://www.gta5-mods.com/player/summer-dress-for-mp-female

https://www.gta5-mods.com/player/open-back-tank-top-for-mp-female

https://www.gta5-mods.com/player/mp-female-round-glasses

https://www.gta5-mods.com/player/mp-female-nuptse-jacket-vcnovell

https://www.gta5-mods.com/player/mp-female-tube-top

https://www.gta5-mods.com/player/mp-adidas-crop-top-pack\

https://www.gta5-mods.com/player/tracksuit-adidas-for-mp-female

https://www.gta5-mods.com/player/adidas-hoodie-mp-female-by-elofm

MP Male Clothes 

https://www.gta5-mods.com/player/t-shirt-survetement-psg-basket-mp-male

https://www.gta5-mods.com/player/mp-male-loose-joker-brand-pack

https://www.gta5-mods.com/player/mp-male-loose-shirt-pack

https://www.gta5-mods.com/player/mp-male-designer-shirt-kenzo-fivem-ready-qween

https://www.gta5-mods.com/player/t-shirt-chucky-male-mp

https://www.gta5-mods.com/player/t-shirt-levi-s-for-male-mp-fivem

https://www.gta5-mods.com/player/t-shirt-adidas-for-male-mp-fivem

https://www.gta5-mods.com/player/fivem-ready-male-tshirt

https://www.gta5-mods.com/player/teddy-fresh-hoodie-by-elofm-high-quality-fivem-ready

https://www.gta5-mods.com/player/mp-male-canadagoose-jacket

https://www.gta5-mods.com/player/new-york-ranger-hockey-jersey-for-mp-male

https://www.gta5-mods.com/player/mp-male-detroit-red-wings-jersey

https://www.gta5-mods.com/player/nike-adidas-sweatshirt-pack-for-mp

https://www.gta5-mods.com/player/mp-diamond-chain-pack-for-male-female

https://da.gta5-mods.com/player/black-nike-cap

**Comment by km4411933** [comment]
Adding to this. I'm more interested in the clothing packs/sagged jeans but I thought I'd throw in some one-off pieces as well.

Male Clothes:

https://www.gta5-mods.com/player/a-large-package-of-clothes-for-franklin

https://www.gta5-mods.com/player/pack-of-clothes-for-franklin-3

https://www.gta5-mods.com/player/pack-for-franklin

https://www.gta5-mods.com/player/a-large-package-of-clothes-for-franklin

https://www.gta5-mods.com/player/off-white-industrial-belt

https://www.gta5-mods.com/player/amiri-jeans-2-pack

https://www.gta5-mods.com/player/serenede-jeans-2-pack

https://www.gta5-mods.com/player/sagged-jean-balmain

https://www.gta5-mods.com/player/sagged-jean-amiri#

https://www.gta5-mods.com/player/sagged-khaki-pants

https://www.gta5-mods.com/player/skinny-jeans-fyzicz

https://www.gta5-mods.com/player/sagged-jean-balmain-orange-camo

https://www.gta5-mods.com/player/large-sagged-jean

https://www.gta5-mods.com/player/hoodies-collection

https://www.gta5-mods.com/player/fresh-adidas-outfit-for-franklin

https://www.gta5-mods.com/player/supreme-x-champion-hoodie

**Comment by thejorhanstahl** [comment]
A lot of the stuff is for Singleplayer characters and not MP Male/Female - Not usable.

**Comment by ShatteredArdilla** [comment]
> A lot of the stuff is for Singleplayer characters and not MP Male/Female - Not usable.

Ah okay i see what you mean. I was not too sure whenever i was making the list but im glad this got cleared up fast! I changed the list and removed the non mp clothing and added mp clothing.

**Comment by Forkedup** [comment]
Appreciate the suggestions for new clothing.

I will be looking for more as time goes, and will most certainly reference these links.

Thanks again!

**Comment by ChainedDev** [comment]
New outfits coming soon
