### ISSUE TITLE
Additional Space (via Bags)

### ISSUE THREAD

**Issue by OxFive** [ChainedDev/CityLife#374]
**Is your feature request related to a problem? Please describe.**
No, this would be primarily an additional feature for players to spend their money on and facilitate 

**Describe alternatives you've considered**
Im suggesting the addition of bags for additional player space. The fanny pack across the chest and gyms bags that are carried behind could have alternate skins and would allow for additional "pocket space" which would be reffered to as "bag space". Fanny packs could carry 100lbs and the gym bags 250lbs. The price for these features should be made expensive. 120k for the small bag and 250k for the large bag, so that not every new player is running around with extra bag space. Alternatively these bags could potentially be crafted from rare items found around LS (see below for details).

**Additional context**
- Bags could be purchasable from Tool shop. (As expensive as houses)

- Alternative to purchasable bags are craftable bags (items spread around each job)
_Example: **Not my exact idea, but similar** https://www.youtube.com/watch?v=SaCEh6xCzcM_
   _Fanny pack would require x1 of each item and x0 leather scraps, Duffle bag would require x2 of each item, and x0 cloth scraps_
   - Ripped bag (Garbage runs) 
   - Tangled Fishing Line (Fishing)
   - Cloth Scraps (Fishing) (for fanny pack)
   - Leather Scraps (Hunting) (for duffle bag)
   - Needle (Tool Shop)
   - Leather Strap (Hunting)

- New Grouppe6 Skins to seperate these bags from other models.

- Only 1 bag can be equipped at a time.

- Can use old trunk key bind of _Y + F2_. (Allows bag to be opened independantly of the pockets, with a "drop" menu on the right side)

- Cannot be dropped or unequipped, but can be hidden with /bag command (does not erase inventory) this means each player would need to buy their own bag/crafting materials & find the work bench

- Bag is emptied if player respawns themselves; same as pockets, but the bag would not be deleted on respawning.

_Functionality_
- Items from pockets would be dropped on the ground, take your hand out of your pockets, open your bag, pick items up from the ground and transfer them into your bag.  Items from your bag and pockets would need to be seen seperately to allow items to be dropped while the bag is equipped.
- When selling items (mined minerals for example), items would be sold from the bag as well, this way the bag can operate as secondary pockets.

**Comment by ChainedDev** [comment]
This would definitely be possible it's just a question of seeing if it would be abusable in any way

**Comment by skiredd** [comment]
this what beta testers r for o_o
