### ISSUE TITLE
Balancing for Pizza This

### ISSUE THREAD

**Issue by Baja-Blast** [ChainedDev/CityLife#375]
Is your feature request related to a problem? Please describe.
The Feature is not related to any particular problem.

Describe the feature you'd like
Pizza this is a great new addition to the city. When it was brought in to the server the prices were being worked on till it was at a reasonable pay point. Since the tweaks i believe the pay has gotten a little too nerfed and now makes the job near obsolete for the sheer amount of work you have to do. 

Describe alternatives you've considered
Any of the alternatives could work to balance the job.
1| Pay upon vehicle drop off can be increased
2| Down payment for the vehicle could be lowered
EX: $350 car deposit and on return $500 + deposit back
3| Less damage done to vehicle on drop off earns more money

Additional context
Pizza this is a fun job but in order to compete with other jobs around the city the pay must be comparable to other delivery type jobs in the city like post ops or go postal which give upwards of $150/Min.

**Comment by Forkedup** [comment]
It was brought into the city and paid $85 per delivery,

After a few hours it was buffed to $80-$120 per delivery, the deposit / bonus was never changed.

It yields around 7-8k an hour, but has a faster vehicle than Go-Postal.

My data could be wrong, but I'd appreciate it if you could post how much you currently are making working pizza and I'll double check people's logs.

**Comment by Baja-Blast** [comment]
No problem

After some testing
7-8k per hour is pretty close to what i have found
Tips can be as low as $68 up to $120

**Comment by Baja-Blast** [comment]
As low as 60*

**Comment by ChainedDev** [comment]
> No problem
> 
> After some testing
> 7-8k per hour is pretty close to what i have found
> Tips can be as low as $68 up to $120

Seems really good
