### ISSUE TITLE
Removing whitelist jobs from f9/Id list

### ISSUE THREAD

**Issue by Jbhhendrickx** [ChainedDev/CityLife#377]
**What is the reason for this balance request?**
The reason for me writing this balance request is for whitelist jobs to get removed from the f9 key. It has lately gotten out of control in the city and I'm getting really annoyed by it. For some examples let's say there are 0 mechs on duty and you a civ where busy doing pizza delivery and you where working towards that sweet new upgrade on your new ride there you are meta gameing spamming your f9 till a mech gets on duty you then see there is 1 mech on and u run over there as fast as possible and none is there what's the first thing even after that they do let's msg the mech on twitter because I know there is adlest 1 "on duty". Another example and one I hear the most of DRUG SALES no need for risk at all let me just flex that f9 oh no cops DRUG TIME!! Woooo ez profit one of the best if u have the gooood stuff also another couple scenes that would involve looking for cops is Oxy runs and the scrapyard let's just go around blasting every local we see why NOT there is no police I just checked my f9 key and I'm good to go! (I know even people who fly in just at a certain time for that reason). Let's now look at the lawyer side I have seen multiple times over and over people including officers not mentioning any names just flex f9 to see if a lawyer is in the city if not oh well let's not send a msg the there phone no need I pressed f9. Last one D8 agents once everyone is over there spamming that f9 key till they see one what's the first thing they do let's spam them on twitter or there msgs.

**What solution would you like?**
What I would like to see is whitelist jobs all of them being completely removed from the f9 key/I'd list this makes for bad role play and if removed could make alot more good roleplay. I know there is sections on the discord where you can reach out to a D8 agent or even a lawyer that's the way it should be or having to manually going to check your self in the city hence why it would make for better roleplay I know other states have it and it works makes people think more before committing something illegal.

**Comment by Forkedup** [comment]
Hi, we have been aware of this issue, and are planning a fix for the next update.

It will result in less meta-gaming, and hopefully better roleplay.

Thank you for the suggestion!
