### ISSUE TITLE
Downed Citizens as passengers

### ISSUE THREAD

**Issue by OxFive** [ChainedDev/CityLife#379]
**Is your feature request related to a problem? Please describe.**
Yes, being unable to load downed citizens into the passenger seat of vehicles puts more strain on pockets, EMS, and the entire city.

**Describe the feature you'd like**
I'm suggesting that a feature be added where a victim may be /carry 'd to a vehicle and then /load 'd into a passenger seat. I feel that this would prevent carry while driving, heavy workloads on EMS, more RPable situations and interaction between citizens.

**Describe alternatives you've considered**
Alternativly, perhaps victims may be loaded into the trunk somehow (as i have seen in other cities).

**Additional context**

**Comment by ChainedDev** [comment]
Yes would be way better and make the hassle of the horrible looking carrying all the time or having to revive people that should still be downed until transported, will look into making this possible in the near future
