### ISSUE TITLE
3D printers 

### ISSUE THREAD

**Issue by Ashytoon** [ChainedDev/CityLife#38]
**Is your feature request related to a problem? Please describe.**
No, just a cool feature.

**Describe the feature you'd like**
3D printer that can be used to create weapons. (Weapons would have a chance of failure, causing damage to you if they fail.) The printer would be stored in your home and would most likely be expensive. 

**Describe alternatives you've considered**
There could be a small amount of the printers in the city, like a black market item. The printer could be used for crafting other items.

**Additional context**

**Comment by ChainedDev** [comment]
Not sure how you'd be able to craft everything with a printer, there's going to be locations where you can craft certain things there though

**Comment by ChainedDev** [comment]
Not sure how you'd be able to craft everything with a printer, there's going to be other ways to do it though
