### ISSUE TITLE
Burner phones

### ISSUE THREAD

**Issue by Buskworth** [ChainedDev/CityLife#380]
**Is your feature request related to a problem? Please describe.**
It's impossible to have a secret identity or conduct business in private if you have the same phone number

**Describe the feature you'd like**
The ability to buy an extra phone with a different number or burner phones in order to have secret personas on the same character

**Describe alternatives you've considered**
Using notes to converse in private, but you have to be face to face.

**Additional context**
If you wanted to be a hitman for example, but you had a job that involves someone your character knows, then you can't use that number or your secret identity is revealed. Makes the RP difficult.

**Comment by ChainedDev** [comment]
Have you ever experimented with the dark web app on the phone?

**Comment by skiredd** [comment]
dark web 

and also u can anonymously call people with the phone but idk if that actually works or not

**Comment by Forkedup** [comment]
> dark web
> 
> and also u can anonymously call people with the phone but idk if that actually works or not

These are some great options that are already implemented, and for calling, maybe just give them a random radio channel.

Burner phones / plates / fake ID's definitely are a possibility in the future though, thanks for the suggestion.
