### ISSUE TITLE
Bugs and laggy gameplay in the sever, never does that in other severs.

### ISSUE THREAD

**Issue by HotboyAvante** [ChainedDev/CityLife#381]
**Describe the bug**
Everytime i fly in the city my character clothes and hair bugs out, My character hair will change colors to like pink, orange, yellow grey, and etc. Also my when I fly in it will be stuck saying cant be default danny so change clothes when my clothes are already changed , and Sometimes it bugs the clothes out the checker clothes. The biggest is I'm just buggy through out the city when walking and driving around it's so laggy and bugs out, it not smooth gameplay and it never does this other severs so I don't know why I just bug and lag so much in this sever.

**How to Reproduce the Behavior**
Steps to reproduce the behaviour:

**Expected Behaviour**
[What was expected to happen. **Remove this line!**]

**Screenshots**
[If applicable, add screenshots to help explain your problem. **Remove this line!**]

**Additional context**
[Add any other context about the problem here. **Remove this line!**]

**Comment by skiredd** [comment]
what is the slot size of the other servers ur on?

pretty sure 100 player slots brings a lot of issues

**Comment by HotboyAvante** [comment]
What are the other servers that have lower slot size for city life?

**Comment by skiredd** [comment]
citylife doesnt have other servers

im asking what the slot size on other servers you play are

**Comment by HotboyAvante** [comment]
100, 120, 90, 65, and 80

**Comment by skiredd** [comment]
100 slots brings major issues

idk how this server works specifically, but I have been in other servers that have entirely custom frameworks which support higher player numbers more

**Comment by HotboyAvante** [comment]
Ok so will that be ever fixed

**Comment by Forkedup** [comment]
Same issue opened again in issue #382
