### ISSUE TITLE
Can We get a second sever cause the main one cause to bug and lag through the city cause the player slot size and a lot going on in the city....

### ISSUE THREAD

**Issue by HotboyAvante** [ChainedDev/CityLife#382]
**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the current issue is. **Remove this line!**]

**Describe the feature you'd like**
[A clear and concise description of what you want to happen. Include any other documents that may reenforce your idea here. *Can we get a second sever cause the main sever slot size cause me to lag and bug through out the city I cant even have a smooth gameplay like other severs allow to do.
**Describe alternatives you've considered**
Can we get a second sever cause the main sever slot size cause me to lag and bug through out the city I cant even have a smooth gameplay like other severs allow to do.

**Additional context**
[Add any other context or screenshots about the feature request here. **Remove this line!**]

**Comment by Forkedup** [comment]
We are always striving to optimize our city to run as smoothly as possible, and we understand that not everyone has thousands of dollars to spend on high-end gaming software. 

For now, we will continue to stay at 100 slots, but will discuss the possibility of opening another server to reduce slots on both.

I'd recommend lowering your graphic settings, and making sure your hardware drivers are up to date.

**Comment by HotboyAvante** [comment]
It's not that some sever I can play on high and normal prefectly fine on other severs.

**Comment by Forkedup** [comment]
> It's not that some sever I can play on high and normal perfectly fine on other severs.

Comparing city's isn't really relevant unless they run the same framework/amount of slots, but I understand what you're saying

**Comment by HotboyAvante** [comment]
you do have a point I was just making a suggestion on a second sever that run better than the main one because less amount of people on the slot
