### ISSUE TITLE
Mechanic rework

### ISSUE THREAD

**Issue by codingispower** [ChainedDev/CityLife#383]
**What is the reason for this balance request?**
[Begging mechanics to show up at the shop is becoming a popular trend]

**What solution would you like?**
[Reintroduce the old way of us customizing our own cars like way back when I first came to the city without removing the mechanics role completely for those that actually wish to RP with those job positions. The mechanic that do fly in consistently are likely spread thin between roadside assistance and being at benny's putting more strain on the current system of things. ]

**Additional context**
[ The current system forces you to need a mechanic who likely is out doing their own thing with their friends, roadside mechanic things or are just not in the city all together. If I can buy a vehicle without a salesman let me customize it to my liking in the same token. The solution is not simply hiring more people how many dozens of mechanics don't wake up? Lastly,  I like the few mechanics I've spoken with a lot & this will in no way make me give them less RP if I can do things myself again.

**Comment by Forkedup** [comment]
If they're clocked on I don't see why they'd be with friends, unless at Benny's.

Reverting it to old ways decreases the RP, I believe that mechanics just need to actively recruit, and set strict rules of how they operate.

I do however understand that mechanics are not in the best state, and that is something we plan on changing soon.

Possibly adding more shops that are owned by different people, and operate at different locations is along the lines of what this change would entail.

**Comment by codingispower** [comment]
thanks for the response. I hope the changes work out for the better it sounds like it can be good for all.
