### ISSUE TITLE
Balancing Car Speed

### ISSUE THREAD

**Issue by km4411933** [ChainedDev/CityLife#384]
**What is the reason for this balance request?**
There are a bunch of dope cars in the city that lack speed. I have an idea that could be a solution for balancing the speed curve for this issue. 

**What solution would you like?**
The idea would involve paying a hefty price for speed upgrades after maxing out your car. An example of this would be for each 10mph increase, you pay 100k or a reasonable price. Of course, setting a max speed of 170/180mph and leaving the supercars that can go 200+ mph out of this upgrade. This allows people to buy cars they enjoy and have it keep up with cars in the same tier. 

**Additional context**
Another example; buying a Blista Kanjo for $12,000 with a max speed of about 120/130 after normal upgrades but being able to upgrade it further to hit 170mph and paying $400,000/$500,000 in order to accomplish this. Random idea but I thought I'd throw it out there.

**Comment by Forkedup** [comment]
I'm seeing more of this being a tuner chip type deal, which is possible.

Tuner chip cost is $100,000, increases max speed by 10.

Not a bad idea, possibly a max of 1-2 per vehicle.

**Comment by km4411933** [comment]
This would be perfect in my opinion. I do think cars already hitting 170+mph shouldn't qualify for a tuner chip though. It should only be for slower cars that just want to keep up.

**Comment by ChainedDev** [comment]
IF we were to add tuner chips it would be one time use, so you don't need one and good for life. But it brings into account the problem of "What if I want to test the tuner chip before actually installing it on a car"

**Comment by gamerdude23** [comment]
Perma chips could be cool though, but expensive at the same time. If you have a car you really like and want to bring out the max potential and are willing to drop a lot of money on it, it would help a lot of people

**Comment by ChainedDev** [comment]
👁️‍🗨️ 👁️
