### ISSUE TITLE
Whitelist all PDM and lux cars

### ISSUE THREAD

**Issue by WillGG12** [ChainedDev/CityLife#385]
**Is your feature request related to a problem? Please describe.**
Its a problem for salesmen as most of the time, people come in without speaking to a salesman. And the salesman makes no compensation

**Describe the feature you'd like**
Just like the supercar group in PDM, you need a salesman to put the discount on then the vehicle is available for purchase.

**Describe alternatives you've considered**
Or lock the doors to PDM and lux and allow people to ping a salesman to come to either dealership

**Additional context**
None

**Comment by Forkedup** [comment]
Thanks for the suggestion, I already thought it operated this way.

I talked to the owners of Luxury Auto's/PDM, changes will be live in Saturday's update.

Take care.
