### ISSUE TITLE
Trunk Space on Boats

### ISSUE THREAD

**Issue by sirstatetheobvo** [ChainedDev/CityLife#386]
**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the current issue is. **Remove this line!**]

**Describe the feature you'd like**
[id like a fishing boat with some more storage please due to being a fisher id like to be able to go out for three four days on a fishing trip without having to go back to sore as often me and my team mainly fish for our jobs and wanted to make it in to a commercial business as we see there is good money to be made in fishing and wed like to capitalise on this as much as possible if this could be added it would be great or even if you could add more storage to the boats already available in the server ]

**Describe alternatives you've considered**
[ more storage on the boats already in city life ]

**Additional context**
[Aa boat dealer would be handy too due to no one knowing the storage on the boats and I've asked everyone they are just saying it glove box and this just isn't enough space many thanks for your time ]

**Comment by ChainedDev** [comment]
Is there any specific kind of boats you think would be best?

**Comment by JooniJunebug** [comment]
I think the best way instead of adding trunks to boats, would be to extend the glove box storage and just make it a "storage" instead of the glovebox. (Also feel like this would be better for instead of finding the trunks and easier to code)
