### ISSUE TITLE
Lexus Rc 350 F sport

### ISSUE THREAD

**Issue by goldbee2g** [ChainedDev/CityLife#387]
**What is the reason for this balance request?**
Compared to the speed and handling of the other cars in its price range: Demon (high top end), and GTR (mid-high top end, good launch, good handling), the lexus falls behind in every way aside from the launch. for its price its top speed as a 2 door its top speed and handling are both lackluster. I love the look of the car and everything is perfect for me aside from the fact that it is slow for what it costs. Another major problem i have with it is that when reversing only the right backlight activates. Super annoying if u have OCD. 

**What solution would you like?**
Please give it minor handling buffs and at the very least noticeable top speed buffs. the current top speed is only like 146 in a straight line.

**Additional context**
I'm in class but i've sent u a pic of the stupid taillights.

**Comment by Forkedup** [comment]
> Please give it minor handling buffs and at the very least noticeable top speed buffs. the current top speed is only like 146 in a straight line.

This is a fairly unrealistic way of testing a vehicles speed, as you're honestly never driving down a pure-flat road. 

Anyways, I made some changes to the vehicle. The changes will be live on Saturday, 10/3

I attempted to fix the lighting issue.

Thanks for the report.
