### ISSUE TITLE
Fixing lag

### ISSUE THREAD

**Issue by goldbee2g** [ChainedDev/CityLife#388]
**What is the reason for this balance request?**
The trucking in the city makes for a lot of lag, there is 2 specific places where truckers dump their trucks and leave them there. one is in the checkpoint at paleto, and the other is at the actual trucking location where u take out trucks.

**What solution would you like?**
If its possible for you to have a certain area where entities would despawn every 10 minutes or so, i think it would remove a huge amount of the random unnecessary entities in the map.

**Comment by ChainedDev** [comment]
Trucks should automatically despawn when going too far away from them, or starting another route. Will look into making sure everything is working as intended
