### ISSUE TITLE
Lexus Rc350

### ISSUE THREAD

**Issue by goldbee2g** [ChainedDev/CityLife#389]
**What is the reason for this balance request?**
The lexus is still slow and poor performance for its price range. It's got M5 performance (***Handling, Speed, braking, acceleration***) without being a 4 door and 3 rows of trunk. Yesterday I got heavily dusted by an e36 and could barely beat a Camaro in a race. But I still appreciate you trying to fix the tail lights :pepeOK:

**What solution would you like?**
minor speed and handling buffs, maybe more torque etc.

**Comment by Forkedup** [comment]
Please read my reply on #387
