### ISSUE TITLE
Craftable/Growable drugs

### ISSUE THREAD

**Issue by JJG1997** [ChainedDev/CityLife#39]
**Is your feature request related to a problem? Please describe.**
Nope, just a feature I think would add more RP.

**Describe the feature you'd like**
So, maybe have a hidden NPC lets say who sells weed seeds. You can buy as many as you want off of them and can grow these in a warehouse (safe way) or in the open (not so safe) these would need to be watered, fertilized and cut down to gain buds. You'd then have to buy plastic bags (either form the hidden NPC or any shop. There would be crafting benches across the city where you can bag these buds and you either hoard them and keep them to sell in masses to other players to sell onto NPC's or you can sell to NPC's for yourself. This would be completely player ran in terms of the economics and how much they would sell the masses to other players for. 

I understand this is a lot of coding so can understand why this might not be added or even considered. This can also be used for cocaine, heroin and all the other drugs. Not sure the processes which is why I used weed as an example!

**Describe alternatives you've considered**

N/a

**Comment by JJG1997** [comment]
Might not be added*

**Comment by Resqect** [comment]
We are not No Pixel
