### ISSUE TITLE
TUNER'S FLATBED TOW TRUCK

### ISSUE THREAD

**Issue by Dollar82** [ChainedDev/CityLife#390]
**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the current issue is. **Remove this line!**]

**Describe the feature you'd like**
Strobe lights on the flatbed tow truck that mechanics spawn from turner, & possible changing it with one with a working bed like this one https://www.gta5-mods.com/vehicles/mtl-flatbed-tow-truck

**Describe alternatives you've considered**
[What alternatives solutions have you considered? **Remove this line!**]

**Additional context**
[Add any other context or screenshots about the feature request here. **Remove this line!**]

**Comment by Forkedup** [comment]
Added the flatbed.
