### ISSUE TITLE
Issue with combat pistols, and other weapons

### ISSUE THREAD

**Issue by hippyyy** [ChainedDev/CityLife#391]
**Is your feature request related to a problem? Please describe.**
Yea indeed, the combat pistol for a reason or an other isn’t able to have a flashlight added to it, not a major issue but as a cop i would like to see were im pointing my weapon at in the dark.

Adding to this, for whatever reason when placing a flashlight/grip onto a weapon it will proceed to take it off of your person and apply onto the weapon, but if you place said weapon back into your pockets you will lose the attachement on it, having you go and buy an other one, really frustrating and with the issue happening the flashlights and grips have no use and is never seen beeing used

**Describe the feature you'd like**
I would like that the combat pistol would be able to have a flashlight mounted onto it, and to possibly have any attachement stay onto a weapon ex: you use it onto your pistol, it will be removed from your pockets and applied and if desired too you can remove that flashlight and gain it back onto your pockets to either apply onto a weapon or to store for the time beeing. And potentially have silencers introduced im aware theres some in the city but they are extremely uncommon to come across, would be nice to have some sort of way to aquire said attachement 

**Additional context**
This is the second time im requesting this fix/suggestion and ive talked to alot of people around the city and i can say that they all had same opinions about attachements on weapons

**Comment by Forkedup** [comment]
Attachments are very buggy, I agree.
We do plan on fixing them in a future update.

**Comment by Chainedster** [comment]
Please open a new suggestion about attachments
