### ISSUE TITLE
Allow pressing for gang colors

### ISSUE THREAD

**Issue by Suedii** [ChainedDev/CityLife#392]
**What is the reason for this balance request?**
Gangs should be allowed to press other gangs if they try to claim their colors.

**What solution would you like?**
Remove the stoopid rules about not being allowed to press for colors/gangcolors.

**Additional context**
These new danny gangs tho...

**Comment by Forkedup** [comment]
To an extent, if they're mocking you, or trying to replace you, then it's fine.

If you represent say the color green, you cannot kill or flame someone over having a green car. Be reasonable.
