### ISSUE TITLE
Ford GT Buffs 

### ISSUE THREAD

**Issue by RodneyMOB** [ChainedDev/CityLife#393]
I currently Own a ford GT in the city and it is my prize possession, I do have a few issues with it that I would like to see fixed if you could. the first thing I would like is a buff on the car as I have mine maxed out and it only goes 175 on a flat, IRL that care goes 215 Flat out. and the second thing I would like on it is a engine cover that opens and closes, Right now I only have the doors that open and close nothing else. and finally if possible some sort of cosmetics that I could put on its not big but would be nice. I have pent 1/2 a mill on this car cant cant do anything to it 
Thanks

**Comment by Forkedup** [comment]
Fixed, let me know how it is next tsunami. (25 mins from now)

Thanks for the report!

**Comment by RodneyMOB** [comment]
thank you the car is much better now
