### ISSUE TITLE
Ghillie suits And atvs for hunting

### ISSUE THREAD

**Issue by goldbee2g** [ChainedDev/CityLife#394]
**Is your feature request related to a problem? Please describe.**
Limited off roading vehicles, and outfits for immersive hunting.

**Describe the feature you'd like**
Ghillie suits and proper ATV’s at the bike shop so that I can feel more like I’m an actual hunter rather than some guy wearing a camouflage Jacket and pants

**Additional context**
Hunting is already not very realistic and it could be just a little more immersive if ghillie suits were introduced.

**Comment by Forkedup** [comment]
ATV's soon, as for ghillies, I have the file's for it I just need to find them again.

Expect at least half soon, thanks for the suggestion!
