### ISSUE TITLE
Porsche Buff/fixes

### ISSUE THREAD

**Issue by LeoGorlami** [ChainedDev/CityLife#396]
hey guys, i bought my porsche like a month ago and i've noticed that it only goes 175 top speed stock porsche 911 is 190 when i have transmission turbo and engine it should got at the most 230, i mean i understand not having super fast speeds, and the neck break issue, but as of right now the pdm fake porsche aka the comet goes faster than the porsche, i also was wondering if i could get some customization options, really just the headlights and the front window tints. i just find it odd that a cheaper version of my car is slower and it doesn't hit the correct speeds, i appreciate your time and i hope we can get this resolved thank you. Leo 
p.s the windows also do not come down.

**Comment by Forkedup** [comment]
Made changes, should be good to go.

The car unfortunately did not come with any further customization than what it has.

Thanks for the report
