### ISSUE TITLE
MOSLEY USED AUTO SALES & REPAIR 

### ISSUE THREAD

**Issue by Dollar82** [ChainedDev/CityLife#397]
**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the current issue is. **Remove this line!**]

**Describe the feature you'd like**
[Good evening,M.O.B. needs this really bad,we have great rp at used carlot,we now also have 2 mechanics,if we could get this & a spot in the garage for mechs to work & clock in & out would be great...

https://www.gta5-mods.com/maps/mosley-s-auto-shop-interior-sp-fivem]

**Describe alternatives you've considered**
[What alternatives solutions have you considered? **Remove this line!**]

**Additional context**
[Add any other context or screenshots about the feature request here. **Remove this line!**]

**Comment by Forkedup** [comment]
I 100% respect what you guys are doing, and appreciate it.

After looking into these files, I just don't think it's reasonable. It would stream large file sizes smack dab in the middle of the city, causing people to have more performance issues, and more issues falling through the map.

While an alternative is certainly possibly, I'm hopeful we'll work something out.

**Comment by skiredd** [comment]
ive played in other cities with that mosley autos interior 

it absolutely fucking ruins fps

the center of the city already has major fps problems

one location i could suggest (if possible) is somewhere up the highway on the left side of the map, in like chumash or something

**Comment by Dollar82** [comment]
> ive played in other cities with that mosley autos interior
> 
> it absolutely fucking ruins fps
> 
> the center of the city already has major fps problems
> 
> one location i could suggest (if possible) is somewhere up the highway on the left side of the map, in like chumash or something

We would be definitely be interested in that

**Comment by RodneyMOB** [comment]
is there a possibility of us getting a custom building some ware out of the city

**Comment by RodneyMOB** [comment]
we have found this and seen it working in another city do you think we could use it at the used car lot ?
https://forum.cfx.re/t/release-esx-qalle-sellvehicles-sell-used-cars/196642

**Comment by ChainedDev** [comment]
Unsure on the map but will aim for having a working used car lot at some point in the near future
