### ISSUE TITLE
Oxy Reword

### ISSUE THREAD

**Issue by AfricanGod47** [ChainedDev/CityLife#399]
**Describe the bug**
Alright, so over the course of the last month I've done a lot of oxy runs. It seems to me that oxy is very inconsistent. I constantly will have the buyer try to run or try to fight me and after I kill them it'll say +2 oxy and then I look into my pockets and nothing is there. So once I started it noticing after having whole runs of it telling me I've gotten oxy and find out at the end that I didn't receive any of it I start to test several ways to see if it's a pockets problem or the script for oxy and after testing various ways to try to repeat it, not once did it seem to be the pockets it was just the script bugging out in some sort of way. Not only was I not receiving oxy there were even times I wouldn't receive money even. That's what makes me believe that it's the Oxy script messing up.

**How to Reproduce the Behavior**
Steps to reproduce the behaviour: Honestly, there is no way to consistently get it to not give you oxy it is completely random and it's doesn't matter if there are no people in the city or if there is a queue of 50+ it just happens at random. Also, it could just be one sale of your run or it could be all of them.

**Expected Behaviour**
The obvious is that you expect to receive the oxy that shows on your screen. As well with money. 

**Screenshots**
I will get some clips and post them in here after I get them.

**Additional context**

**Comment by Forkedup** [comment]
Thanks for the report, I'll start testing Oxy tomorrow.

It is most likely due to inventory changes.

**Comment by ChainedDev** [comment]
Will look into it, the base mechanic is you start with 10 oxy for your delivery and those count as destinations, sometimes when you get an "oxy" it really means getting an extra delivery, will look into rewording it in places it makes more sense and causes confusion

**Comment by liesog** [comment]
This same thing happens to me consistently when running oxy. When I get a +1 or +2 and check my inventory but its not there, it goes to "deep pockets" as some call them. I know this because twice I've either died or been arrested and it says "-25 oxy"
 in the bottom right that I know I didn't have before, along with many other items including fishing bait, meth, etc.

**Comment by Forkedup** [comment]
@liesog 
When it says +2 oxy and doesn't give you the oxy, it gives you +2 deliveries instead, as an example.
