### ISSUE TITLE
#rp-youtube or #videos

### ISSUE THREAD

**Issue by Jxcob** [ChainedDev/CityLife#40]
**Is your feature request related to a problem? Please describe.**
No, it's not a problem.

**Describe the feature you'd like**
#rp-youtube or #videos to place videos or even small yet entertaining clips created on the server.

**Describe alternatives you've considered**
I could just place it in #rp-instagram or #rp-twitter, but it doesn't seem right.

**Comment by ChainedDev** [comment]
Added in a #clips channel in General, all rp related clips can go into rp-twitter and rp-instagram like always :D
