### ISSUE TITLE
Mercedes AMG GT-R buff

### ISSUE THREAD

**Issue by RogWells** [ChainedDev/CityLife#401]
The Mercedes I think could use a slight buff. The stock top speed is around 170. Outside of the city, the top speed is around 198 mph. The main reason I believe it needs this buff is because of its $300k price point. I figured with is being more expensive than most cars in the dealership it would be a bit quicker than the others, but this isn't the case.

**Comment by Forkedup** [comment]
Made some changes to the AMG GTR, let me know how it feels.

Thanks
