### ISSUE TITLE
MECHANICS CLOCK IN LOCATION/TOW TRUCK SPAWN LOCATION

### ISSUE THREAD

**Issue by Dollar82** [ChainedDev/CityLife#402]
**Is your feature request related to a problem? Please describe.**
[Only 2 shops mechanics can clock in at,& only 1 shop spawns tow trucks]

**Describe the feature you'd like**
[For mechanics to be able to clock in & spawn tow trucks from all shops ]

**Describe alternatives you've considered**
[What alternatives solutions have you considered? **Remove this line!**]

**Additional context**
[Add any other context or screenshots about the feature request here. **Remove this line!**]

**Comment by Forkedup** [comment]
I believe this is certainly a feature we can implement, but only when said mechanic / group purchases said mechanic shop.
