### ISSUE TITLE
The cbr needs a buff bad 

### ISSUE THREAD

**Issue by sirstatetheobvo** [ChainedDev/CityLife#404]
**What is the reason for this balance request?**
[A cbr in real live would do 190 stock and full maxed 210+ (depending on the rider) easy and in game it does 145 i mean i can link videos from youtube if you like need it just annoys me when i would be doing every car other then most hyper cars easy and they wouldnt stand a chace to keep up ]

**What solution would you like?**
[its mph needs to be increased desperately other then that its great just the top end speed i feel the accleation is correct just needs top end speed  ]

**Additional context**
[Add any other context or screenshots about the balance request here. **Remove this line!**]

**Comment by Forkedup** [comment]
I plan on bringing in two more bikes, each a different tier, each faster and more expensive.

It'd be something like this, in terms of ranking.

#1 NEWBIKE
#2 NEWBIKE
#3 CBRR

So for now, the price and speed will remain the same.

**Comment by sirstatetheobvo** [comment]
Ok but the speed of the cbr rr isn’t realistic that’s why I needs buffed but unless your bringing in the h2 or the mv then not many bikes are faster then the cbr rr it’s a fuel injection with all the mod will smoke most think other then the two bikes I’ve mentioned above please make it realistic I’ve own this bike In real life and it’s disappointing when a shitty little Audi can out run me when it should be the other way around it’s just stupid there no way an Audi is quicker the power to weight ratio is so off please fix it

**Comment by sirstatetheobvo** [comment]
For example my cbr 125r did 83 with to people on this cbr rr (ment to be 1000cc) only does 101 with two people on it needs fixing
