### ISSUE TITLE
Item: Wheel 

### ISSUE THREAD

**Issue by goldbee2g** [ChainedDev/CityLife#405]
**Is your feature request related to a problem? Please describe.**
Repair kits fixing Popped tires is unrealistic

**Describe the feature you'd like**
Make repair kits res pawn the car with full hp, and then pop the tires that were already popped, so that the person has to use a spare wheel item they would keep in their trunk to repair their tires.

Just a cool feature I saw on some clips.

**Comment by Forkedup** [comment]
Repair kits: repair only engine damage
Advanced repair kits: repair full body and engine damage

**Comment by ChainedDev** [comment]
Merged into #416
