### ISSUE TITLE
Shooting in legs and feet

### ISSUE THREAD

**Issue by goldbee2g** [ChainedDev/CityLife#406]
**Is your feature request related to a problem? Please describe.**
Some rp Limitations without the ability to force someone on their knees through pain 

**Describe the feature you'd like**
Allow for thigh down shots to send someone to the floor (Ragdoll effect)
**Additional context**
Many cool rp scenarios I’ve seen in clips where people shoot out knees as a punishment or as a way to use non lethal means to force someone to submit. Also more realistic if you are in a chase getting hit multiple times in the legs at some point you are bound to fall over and collapse.

**Comment by ChainedDev** [comment]
Can you share these clips as I think it would just make whoever shoots first in a gun fight wins automatically
