### ISSUE TITLE
improved jewellery store

### ISSUE THREAD

**Issue by Lukey447** [ChainedDev/CityLife#407]
jewellery stores currently give around 8k for ALL the glass cabinets. compared to the 8 mill from the campaign this is a big downgrade.

At the moment the jewellery store is very shit. 8k is so little that it is not at all worth the risk considering the police response time is so quick due the the minimum police on the server to perform the robbery being so high (8). right now you can break the cabinets with any pistol. not only does this not make sense but the breaking animation doesn't work with the pistol as it is too small. my suggestion is to simply stop pistol smashing but higher the cut to around 2-4k per cabinet. losing shotguns is a higher risk so it pushes to a more creative and rp friendly way of robbing the store instead of a quick smash and grab with a grove street pistol found by a Danny.

**Comment by ChainedDev** [comment]
Our economy is not even remotely the same to campaign, also just like regular jewelry stores, majority of the value isn't found in the glass showrooms

**Comment by Lukey447** [comment]
in high end jewellery stores one ring alone can cost you average around 25k. but that's too much. 2k isn't. each cabinet should give you multiple rings and diamonds instead of just the one as it makes more sense. my suggestion gives a buff and a nerf also before anyone says it will be too OP.

**Comment by ChainedDev** [comment]
Even if that, if you're just smashing the glass cabinets you're not even robbing the full jewelry store

**Comment by Lukey447** [comment]
I don't get your point. if you want to add a way to rob a safe in the back room then do that but I'm talking ONLY about the cabinets. they at the moment give a humiliating lack of money which is why most the server doesn't even know it exists. a waste of a mod really. right now there is 0 reason to rob the store unless you want a quick 2k as a danny end of.

**Comment by ChainedDev** [comment]
> if you want to add a way to rob a safe in the back room then do that 

There already is, the reason you don't make 40k off the cabinets is so any danny doesnt just want in and do it like you're stating. Do the full store then see how much you make

**Comment by Lukey447** [comment]
shotguns cost 3k. Danny's don't want to risk that much so you'll get more experienced people robbing. also Danny's are way more likely to rob them now than in my suggestion but from the looks of it suggestions never get accepted anyway

**Comment by ChainedDev** [comment]
I can't even understand what you're trying to suggest

**Comment by Lukey447** [comment]
really? because you did last comment ago. don't try and undermine me by playing dumb bro I've stated 50 times what my suggestion is

**Comment by ChainedDev** [comment]
Haha you're right, makes sense and balances it, I read this wrong earlier this morning waking up

**Comment by ChainedDev** [comment]
Thank you, all finished and should be live soon
