### ISSUE TITLE
Sandking Trunk Space

### ISSUE THREAD

**Issue by REDDGLARE** [ChainedDev/CityLife#409]
**What is the reason for this balance request?**
The Sandking truck has a tiny amount of trunk space for its sheer size. Being one of the largest trucks we can own I believe it should have a large amount of trunk space. It currently has the same amount of trunk space as the Pinto which in turn makes it outmatched by nearly every other vehicle.

**What solution would you like?**
The trunk space should be at least 6 rows of space at minimum if not more. As well as possibly upping the weight it can hold to an appropriate amount. 

**Additional context**
It is slow, bulky, and big. It needs the added trunk space to make it even worth driving. You can add a bed cover over the bed of the truck making it seem even more realistic to have a large trunk.

**Comment by Forkedup** [comment]
Trunk spaces will be re-worked soon, thanks for pointing this out!

**Comment by REDDGLARE** [comment]
Thanks!
