### ISSUE TITLE
Cruise Control

### ISSUE THREAD

**Issue by kuf-x** [ChainedDev/CityLife#41]
Cruise Control doesnt appear to be working, but regardless..  ** [Suggestion] ** Capped Cruise Control. Press Y & have it set your speed max. So if i press Y at 35 mph, it makes 35 mph the max. So if i hold W, it wont go past 35 mph. Instead of pressing Y and it driving for you.

**Comment by ChainedDev** [comment]
Cruise control should be fixed after next restart, I do like the idea of it just taking over your max speed instead of auto piloting you :D
