### ISSUE TITLE
A Different Nissan GTR

### ISSUE THREAD

**Issue by Renatuh** [ChainedDev/CityLife#410]
**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the current issue is. **Remove this line!**]

**Describe the feature you'd like**
I Feel that this Nissan GT-R Liberty Walk is better than the one already in the city. [https://www.gta5-mods.com/vehicles/2019-nissan-gt-r-liberty-walk-lb-performance-the-second-generation](url)

)**Describe alternatives you've considered**
[What alternatives solutions have you considered? **Remove this line!**]

**Additional context**
[Add any other context or screenshots about the feature request here. **Remove this line!**]

**Comment by Forkedup** [comment]
Please kindly repost this in #411 using the new format

Thank you!
