### ISSUE TITLE
Grotti Itali GTO issue

### ISSUE THREAD

**Issue by km4411933** [ChainedDev/CityLife#412]
**What is the reason for this balance request?**
The new Grotti Itali GTO seems to bounce a lot, even with max armor to weigh it down. In other cities I've tried, it doesn't have this issue. I do have the suspension stock but that's because the car slows down when I add suspension which isn't what I want. 

**What solution would you like?**
I'm not exactly sure what would be a good solution. Anything that could keep it planted to the ground a bit more. Maybe improving the suspension so the car doesn't lose speed at the cost of handling? The car jumps when you go over any small bump in the road. Especially when you're in the city as well since the road isn't all even. 

**Additional context**
Just improving this issue could be a great buff for the cars handling.

**Comment by Forkedup** [comment]
Hey, just to clarify - car weight only affects what happens when you hit other vehicles / most collisions. Suspension is the issue here. I'll attempt some fixes, keep me posted on the results.

Thanks for the report!
