### ISSUE TITLE
BMW S1000XR 2019  AT sanders Motorcycle

### ISSUE THREAD

**Issue by BearExcelz-Angel** [ChainedDev/CityLife#413]
**Is your feature request related to a problem? Please describe.**
[A clear and concise description of what the current issue is. **Remove this line!**]

**Describe the feature you'd like**
i would really like to see the BMW 51000XR 2019 at sanders motorcycle shop. as i been rping there as a Owner/salesman

**Describe alternatives you've considered**
[What alternatives solutions have you considered? **Remove this line!**]

**Additional context**
https://www.gta5-mods.com/vehicles/s1000xr-2019-add-on

**Comment by Forkedup** [comment]
Hello! Please repost in #411
