### ISSUE TITLE
Washing Buff

### ISSUE THREAD

**Issue by AfricanGod47** [ChainedDev/CityLife#415]
**Is your feature request related to a problem? Please describe.**
It's sort of in issue but the money wash limiting you to only wash a certain amount without a way to put your dirty anywhere seems a bit overkill. 

**Describe the feature you'd like**
I would like to see there either be a way to put your dirty money somewhere safe (Which I know it probably a lot of work.) or until such system is available to clean as much as you want or be able to have more than it can wash.

**Describe alternatives you've considered**
Already listed them above, Maybe if it's even a 50k limit I feel that would be a better change till we get a better alternative. 

**Additional context**
With how a secret location works it only seems reasonable to have there be an actual benefit to knowing where such things are but at the moment it seems that there really isn't one.

**Comment by Forkedup** [comment]
Hi, this issue has just recently been brought to my attention, and we 100% plan on making changes to it!

Thank you for the heads up.

**Comment by AfricanGod47** [comment]
Thanks for the quick repsone

**Comment by ChainedDev** [comment]
Thank you, all finished and should be live soon
