### ISSUE TITLE
More space in the server

### ISSUE THREAD

**Issue by ItsCoffee** [ChainedDev/CityLife#418]
The reason for this, is because many people, like me have to wait in really long queues.

Making more space in the server, maybe up to 200-300 people would reduce the amount of long queues us players would have to go through.

**Comment by Forkedup** [comment]
Hi, we will extend slots as we see fit.

We could certainly allow more, but it only degrades performance, and quality of life. I hope you understand. 
We occasionally will bring up our second city when the queue is very large, so keep an eye out for that!
