### ISSUE TITLE
A Interactive Menu

### ISSUE THREAD

**Issue by BlamedEmporer678** [ChainedDev/CityLife#419]
**Is your feature request related to a problem? Please describe.**
I think there should be more interactive options

**Describe the feature you'd like**
I would like to see a menu in the game to escort and put in cars so you dont have to have 2 people to save a friend or put a robber in the trunk 
**Describe alternatives you've considered**
no alternatives, but i think a new phone would be great

**Additional context**

**Comment by ChainedDev** [comment]
Interesting would make more things possible and smoother to do will look into doing something like this

**Comment by ChainedDev** [comment]
Feel free to open more suggestions with features we can add to it, possibilities are endless!
