### ISSUE TITLE
Some more things for the ladies!

### ISSUE THREAD

**Issue by NovaStar671** [ChainedDev/CityLife#423]
https://www.gta5-mods.com/player/retex-new-mp-female-head-texture-0-8-beta
https://www.gta5-mods.com/player/new-clothes-stuff-mp-female
https://www.gta5-mods.com/player/bikini-pack-for-mpfemale
https://www.gta5-mods.com/player/momiji-tops-for-mpfemale
https://www.gta5-mods.com/player/momiji-thongs-for-mpfemale
https://www.gta5-mods.com/player/high-heels-pack-for-mpfemale-part-1
https://www.gta5-mods.com/player/long-wavy-hairstyle-for-mp-female

These are clothes hair and retextures. I noticed that there is some nice clothes for girls but not really for strippers. I have talked to a few girls and I feel like this will improve the game for us.

**Comment by chromewick** [comment]
yah id like to see some more I guess you can say girly clothes in the city. pretty dresses and all that. maybe some hairs as well that can be long and you can still wear a hoodie.
