### ISSUE TITLE
More Crim Activities!

### ISSUE THREAD

**Issue by HeliosEMV** [ChainedDev/CityLife#424]
**Is your feature request related to a problem? Please describe.**
**The problem is that there is a lack of criminal activities.**

**Describe the feature you'd like**
**In my opinion there needs to be more ways criminals can make money other than selling drugs all day. We need high risk high reward activities such as heists, drug runs, missions, etc that are actually exciting to do so we don’t have to sit there and flex E all day to make money. I know I’m not the only one in this boat as it’s talked about almost every day IC and OOC, please consider putting some time and effort into implementing things like this to keep the city fresh and fun for the sake of content. I would really appreciate a response other than create your own Criminal RP because at this point it’s ridiculous to hear that after months of no new Crim Activities.**]

**Describe alternatives you've considered**
**I’ve considered creating unique Crim RP but it get’s old trying to come up with new things to do and making no money at the same time.**

**Additional context**
**I believe in you guys please consider this, make a poll or ask the community in some way and I can 110% assure you others will agree that we need things like this.**

**Comment by ChainedDev** [comment]
Lack of info, moving to #429
