### ISSUE TITLE
New Wheels

### ISSUE THREAD

**Issue by Metrillex** [ChainedDev/CityLife#425]
**Is your feature request related to a problem? Please describe.**
No i would not consider this request to be related to an issue or problem.

**Describe the feature you'd like**
I would love to see the Benny's Bespoke Wheels and the Street Wheels that are available in the base game multiplayer to be added to the city.
**Describe alternatives you've considered**
If they only work with their respective vehicles that would be understandable.

**Additional context**
I think having the plethora of new wheels in the city would be a great thing for the multitude of car enthusiasts that reside in the city. Plus with them being a base game wheel I'm hoping its not a feature that's too hard to implement.

**Comment by ChainedDev** [comment]
Wheels work differently then everything and add a bunch of lag, not what we're looking for currently. Thanks for your suggestion though
