### ISSUE TITLE
Whitelist gang application has been down for weeks

### ISSUE THREAD

**Issue by OttoLFritz** [ChainedDev/CityLife#426]
**Describe the bug**
The link found in #annoucments channel of discordia that directs you to the application to whitelist a gang has been down for some time

Steps to reproduce the behaviour:
Fix the link

**Expected Behaviour**
Please fix the link son gangs can actually apply for this feature

**Comment by ChainedDev** [comment]
http://rplife.city/apply/WhitelistedGang
