### ISSUE TITLE
Adding Trunks to Boats

### ISSUE THREAD

**Issue by JooniJunebug** [ChainedDev/CityLife#428]
**Is your feature request related to a problem? Please describe.**
Not exactly, you guys said recently you were reworking trunks didn't know if this was apart of the plan.
**Describe the feature you'd like**
Trunks Added to Boats
**Describe alternatives you've considered**
Making the Glovebox's bigger and renamed to *Trunks*

**Additional context**
I think adding Trunks to boats would change up the way fishing works and encourage people to buy boats.

**Comment by ChainedDev** [comment]
Duplicate of #386
