### ISSUE TITLE
Car Trailers

### ISSUE THREAD

**Issue by anhp2006** [ChainedDev/CityLife#43]
**[Suggestion by xXPinkishRatXx]** I think car trailers can make RP a bit more fun. If I were to use a car trailer in an RP situation, i'd use then to haul my "project car". And I think they should be priced at around 10k

**Comment by ChainedDev** [comment]
Do you mean like the mechanic flat beds?

**Comment by anhp2006** [comment]
No like separate car trailers for pickup trucks or vehicles with tow hooks
