### ISSUE TITLE
Offroad vehicle for EMS

### ISSUE THREAD

**Issue by REDDGLARE** [ChainedDev/CityLife#430]
**Is your feature request related to a problem? Please describe.**
So this issue is two fold. First and foremost we currently do not have a great off-road vehicle available to EMS. The explorer is decent but the low ground clearance hinders it. It can be a struggle to climb mountains and dirt paths in a large ambulance that is suited for highways and city streets. This can even be risky as it is fairly easy to flip the ambulances while climbing. The second part is there is currently no vehicle upgrade for reaching EMS 3. EMS 1,2,4, and command get new vehicles but not EMS 3.

**Describe the feature you'd like**
I would like to see a truck added to the EMS vehicle line up, available at EMS 3. This would give a EMS 3 a new vehicle and allow us to efficiently reach off-road calls. 

**Describe alternatives you've considered**
The only alternative I see is continuing with what we have now and just dealing with what we have. 

**Additional context**
https://www.lcpdfr.com/downloads/gta5mods/vehiclemodels/29207-non-els-2017-ford-f150-fire-utility-fivem-ready/

Just an example as to what I am suggesting.

**Comment by ChainedDev** [comment]
Have you tried a helicopter?

**Comment by Baja-Blast** [comment]
Yes the invisible trees and walls make it an unreliable option.

**Comment by Wally-W** [comment]
Also helicopters are only available to EMT IV and above, it can take a few months for people to reach that rank.

**Comment by Baja-Blast** [comment]
Bumping this suggestion! Ems is still in desperate need of an off road vehicle. Pick up truck, ATV or something of the sort.
