### ISSUE TITLE
Extend the 10-50/10-52 alert icon time for EMS — or allow another Call for Help after it expires

### ISSUE THREAD

**Issue by Wally-W** [ChainedDev/CityLife#431]
**Is your feature request related to a problem? Please describe.**
EMS will miss someone's Call for Help if the alert icon on the map expires before they can respond to it. 

It can take a couple minutes to treat just one person, after adding the time it took to reach their location. If it's a scene with multiple victims, that time can increase a lot — situations involving Police can easily take 10-15 minutes.  So you can imagine if we're getting multiple calls in a short amount of time, we can't save everyone before one or more of those alert icons disappear from the map. 

At that point, EMS no longer knows where that downed person is or that they still need help — and people just stay downed for 20+ minutes expecting EMS to come save them, without knowing their Call for Help has disappeared.

**Describe the feature you'd like**
Ideally, allow for another Call for Help alert to be sent after the first one expires and disappears from the map, so that EMS knows someone still requires assistance.

Another nice addition would be a clear notification to the downed person that their alert was successfully sent, as there are places on the map where people can't actually call for help, since there are no npc's around to trigger it.

I believe these changes would be good for everyone in the city, and greatly reduce people's frustration with waiting for EMS.

**Describe alternatives you've considered**
Extending the alert icon's timer would be an alternative, but I'm not sure if every Dispatch alert is tied to the same timer, so that may not be feasible without causing extreme clutter.

People can also currently re-log and it will send out a fresh alert when they come back in the server, but not many people know this, and no one knows when their Call for Help actually disappears from our map.

**Comment by ChainedDev** [comment]
Alert time has been hotfixed, Unsure about calling a second time if others would like to cast their input feel free!
