### ISSUE TITLE
More EU staff

### ISSUE THREAD

**Issue by TheLitteralIcemanStraightOuttaFinlandia** [ChainedDev/CityLife#432]
**Is your feature request related to a problem? Please describe.**
Getting rdmed, vdmed or experiencing issues in the city are very hard to resolve due to the lack of EU staff, as of writing this there is no staff avalible at all. and i just got RDMed with evidence. This has happened to many other EU friends aswell and if this city should be a 24/7 city where the community is active all day and night. It cant work like this in the current state where me for example cant get assistance half of the time.

**Describe the feature you'd like**
Recruit more staff members in the EU timezone.

**Describe alternatives you've considered**
Force staff to be awake all night.

**Comment by ChainedDev** [comment]
EU Players apply for staff! https://rplife.city/apply/Staff
