### ISSUE TITLE
Radio

### ISSUE THREAD

**Issue by Ashytoon** [ChainedDev/CityLife#435]
**Is your feature request related to a problem? Please describe.**
Radio channel is constantly visible.

**Describe the feature you'd like**
When sending clip/streaming, the radio frequency is on screen, and anyone can see it and join the radio. Obviously this is meta, but it would be nice to maybe be able to take it off the screen? Maybe it could show up when you press F9, so you can check what channel you’re on..?

**Describe alternatives you've considered**
Not sure what other options there are

**Additional context**

**Comment by ChainedDev** [comment]
Some streamers put a overlay box over where the radio would be so it's not visible to the stream :)
