### ISSUE TITLE
Adding More Biker Clothing

### ISSUE THREAD

**Issue by JooniJunebug** [ChainedDev/CityLife#436]
**Is your feature request related to a problem? Please describe.**
No, but I know many people would enjoy to see this clothing and it would add something unique.

**Describe the feature you'd like**
More Lost MC and other biker clothing so maybe another group could come into the fold.
**Describe alternatives you've considered**
Deal with what we have.
**Additional context**
https://www.gta5-mods.com/player/lost-mc-and-angels-of-death-biker-vests

**Comment by xxArmyGuy727xx** [comment]
I just wanna bump this really quick since it's been buried. Definitely needed
