### ISSUE TITLE
Weekly or Monthly gang power rankings

### ISSUE THREAD

**Issue by xCarterx** [ChainedDev/CityLife#437]
**Is your feature request related to a problem? Please describe.**
[No there is no specific problems, just maybe giving gangs something to strive for to be a top the power rankings .]

**Describe the feature you'd like**
 I was thinking monthly power ranking how ever staff would like, basically gangs would be ranked on the things they did that  month, example say TMN wins a War or Pastas buy a new business , also considering ally’s, numbers, assets, etc.  all of this would be taken into account and shift the power rankings , maybe the top 3 gangs each ranking get something ? A shipment of some sort? Just an idea .]

**Describe alternatives you've considered**
Not sure what any alternative methods could be, I feel power rankings is pretty unique . ]

**Additional context**
I think it would be very cool, and add another element to gangs, giving them something to strive for, or giving Gangs bragging rights if they had a great month, also gives the community some kinda insight on the gangs and things that us gangs do if they aren’t really in that kinda life a way for them to keep track. Gives us gangs something to compete for make us actually wanna do things in the city, and it also would gives gangs recognition for being in the city accomplishing stuff]

**Comment by Aspratic** [comment]
I like the idea. I can definitely put some power rankings out for the gangs. Not sure if we were to reward them what they would get, but going to talk to some people and get this out. Think its a good concept. If you have any ideas for some type of rewards list em here. -Colby
