### ISSUE TITLE
More Hospitals

### ISSUE THREAD

**Issue by Baja-Blast** [ChainedDev/CityLife#439]
**Is your feature request related to a problem? Please describe.**
Currently there is only one hospital to use but there are five different medical centers around the map.

**Describe the feature you'd like**
I would suggest something similarly set up to the police departments in Sandy/Paleto where EMS can pull out/put away their vehicles and Re up on their medical supplies. Additionally if patients could be checked in at these alternative hospital locations.

**Describe alternatives you've considered**
As of now some EMS roleplay checking people into other medical facilities like sandy shores medical center. It does the job but with no tools there and no beds to check into the time there is limited.

**Additional context**
EMS RULES!

**Comment by ChainedDev** [comment]
Sandy's looking cool
