### ISSUE TITLE
More Tactical Clothing

### ISSUE THREAD

**Issue by Cudii** [ChainedDev/CityLife#440]
**Is your feature request related to a problem? Please describe.**
I tend to notice that there isn’t a lot of tactical gear in the clothing stores. 

**Describe the feature you'd like**
Add more tactical gear into the clothing stores as I do know that many people like to have tactical outfits for certain events that happen in the city. I’ve seen leg holsters, nicer vest, helmets, etc, before and that would be amazing to add into the city. I personally enjoy wearing tactical and so do certain groups in the city. 

**Describe alternatives you've considered**
Let people be able to change more of the police vest to a pure black vest as some of the vest are nice and go with certain outfits. 

**Additional context**
These outfits would go nice with military events :)

**Comment by Forkedup** [comment]
Hi, I am always open to add more clothing.

Please feel free to link me suggestions from gta5-mods.com
