### ISSUE TITLE
Trucking job gets scuffed if multiple people start it too fast

### ISSUE THREAD

**Issue by youngsinatra99** [ChainedDev/CityLife#441]
**Describe the bug**
If two or more players start the trucking job without the last person hooking up their trailer they will all spawn in the same spot and blow up or flip over, resulting in both players having to drive far away from the trucking job and come back to restart and have it reset.

**How to Reproduce the Behavior**
Steps to reproduce the behaviour: Have two people start the trucking job without one of them waiting for the other to drive away with their trailer.

**Expected Behaviour**
Simply detect if there is already a trailer within the spawn radius and not allow the other player to start the job. **AND/OR**
Add multiple spawn points for the trucks and trailers.

**Screenshots**
N/A self explanatory & most likely you already know what I'm describing

**Additional context**
This comes down to lazy coding by whoever wrote the trucking job. No offence is meant by this, I'm a programmer myself and I'm simply stating what I'm seeing.

**Comment by ChickenDipper1** [comment]
This can get annoying, I usually line all the left over trucks up to make it actually look like a truckers yard :P
