### ISSUE TITLE
New Whitelisted City

### ISSUE THREAD

**Issue by Synical1** [ChainedDev/CityLife#443]
**Is your feature request related to a problem? Please describe.**
yes, way too much fail rp and little kids that don't know how to rp, and so many people going OOC

**Describe the feature you'd like**
I would like a new city/server that is whitelisted and people have to apply for via rp website or google forms and in the whitelist make them define fail rp, fear life rule, RDM, VDM, Powergaming, and Metagaming. this way the people that properly know how to rp can enjoy their time

**Describe alternatives you've considered**
really push rules that people have to follow.

**Additional context**
N/A

**Comment by ChainedDev** [comment]
Make sure to get clips and make proper reports, we'll be on the lookup and will always be looking to get people who don't belong in the community out
