### ISSUE TITLE
Money Wash Bug

### ISSUE THREAD

**Issue by Gunnar15** [ChainedDev/CityLife#444]
**Describe the bug**
When you wash your money in the money wash you can only do the process once and then the machine bugs out and doesn't allow you to wash again unless you leave and rejoin the server. 

**Expected Behaviour**
You can wash your dirty money multiple times without having to rejoin the server.

**Comment by ChainedDev** [comment]
Thanks for letting us know, I fixed it and will be all ready on next update!
