### ISSUE TITLE
Paragon R Buff

### ISSUE THREAD

**Issue by JayRusso1** [ChainedDev/CityLife#445]
**What is the reason for this balance request?**
I feel like the Paragon R is just a little bit too slow for the price/upgrades.
**What solution would you like?**
Preferably a tiny buff, nothing too extreme.

**Additional context**
The Paragon R with engine and turbo cruises on a flat at around 145-150, reckon it's a tiny bit slow for a car that has a V-12 in it, love the car just hoping for a slight buff :)

**Comment by Forkedup** [comment]
Paragon R has been buffed.
