### ISSUE TITLE
NPC Requesting Taxi Service

### ISSUE THREAD

**Issue by EDGIES** [ChainedDev/CityLife#447]
**Is your feature request related to a problem? Please describe.**
I tend to see not too many people using the taxi service and it puts a disadvantage for someone that would like to be a taxi driver to make income.

**Describe the feature you'd like**
The feature I would like to introduce would be an optional job for a taxi driver to have a request from a NPC. For an example player would press "E" and a GPS coordinates would take the taxi driver to pick up an NPC. Then another GPS coordinates will be sent for the destination. This would fill the time for players waiting for other players to request a taxi service.

**Describe alternatives you've considered**
Another alternative would be to add version of uber/ lyft  for player to player service and have taxi for player to NPC service.

**Comment by Forkedup** [comment]
Hi, thank you very much for the suggestion

Fortunately for you, this is coming in our newest update.

We look forward to you using it, and giving us feedback on how it feels overall.
