### ISSUE TITLE
Collectables

### ISSUE THREAD

**Issue by thebestgloyounger** [ChainedDev/CityLife#449]
**Is your feature request related to a problem? Please describe.**
Negative

**Describe the feature you'd like**
Collectable items. Maybe add things such as katanas and stuff that would just be a collectable for people. Make some rare like 1/1 collectables and some more common. I feel like it might open new roleplay scenarios such as a character dedicated to own every collectable buying them from people forcing them etc. Maybe some paintings or something like that would need to be obtained through illegal events. I feel like it would be a good but not necessary feature.

**Describe alternatives you've considered**
Add collectable items that cannot be used or anything just an item in your inventory

**Additional context**
I believe I've said everything up there.

**Comment by Forkedup** [comment]
Hmm, 

How would you suggest this system gets implemented? 

For example, adding a rare chance to receive X item from say the garbage job / scanning?

I guess In other words, would just implementing unique and rare items in almost all things, as a way to add a sort of RNG/RP element to possibly get more people into doing said activities for new reasons?

I like this idea, but I'd also like some more examples of how you think this system would or could work.

**Comment by thebestgloyounger** [comment]
Yeah possibly have more common collectables obtained through scanning and garbage job.

Maybe for the RP sake create scenarios to obtain certain collectables like 1/1 collectables. Example mission I don't know go to this and this location silently takes out guards or something so it creates more roleplay as well. Maybe have the people that do the sneaky stuff right now give out those missions.

Like from scanning maybe get things such as a meteorite on the certain spot (possibly more scanning spots). Maybe even rare ores in the mines like ruby or something. 

I'm personally a collector myself and I would really enjoy something like that implemented into the city.

**Comment by ChainedDev** [comment]
Got a nice load of Collectables to introduce :D
