### ISSUE TITLE
Personal Vehicles Despawn

### ISSUE THREAD

**Issue by kuf-x** [ChainedDev/CityLife#45]
**Describe the bug**
Personal Vehicles Despawn and get Auto impounded

**How to Reproduce the Behavior**
park, lock, and then get out of sight from it for about 5 minutes. I would park at garbage depot, do a run.. come back and its gone every time. (not stolen)

**Expected Behaviour**
vehicle despawns and goes to impound

**Additional context**
not sure if its a distance, or time thing.. or a combination of both? before you could leave your vehicle somewhere forever until it was either stolen or server restart

**Comment by ChainedDev** [comment]
We were messing with some OneSync variables and certain benefits like: No Ghost Vehicles and non-despawning vehicles(we think), although it seems nice, it also brought local cars to becoming absolutely rampant and extremely crazy, we're unsure on which is the better trade-off as of now
