### ISSUE TITLE
Fashion Overhaul 

### ISSUE THREAD

**Issue by kiidtre** [ChainedDev/CityLife#450]
**Is your feature request related to a problem? Please describe.**
I tend to notice that there is a huge opportunity of having more "hypebeast"/"streetwear" fashion in the city. 

**Describe the feature you'd like**
I was thinking more shoes such as Jordans 1s, 3s, 4s, 5s, 7s, 10s, 11s, 12s, 14s(which i can link if needed). Maybe even some Yeezy Boost 700s or the 300s (multiple style that I can link as well). Have a refresh to the Nikes by adding "SB Dunks" and more "Air Force 1s" Also I was thinking that more brands of clothes should be introduced to the city such as V Lone, Anti Social Social Club, Stussy, Palace, Kith, The Hundreds, 10 Deep, Billionaire Boys Club, and Bape. More styles of pants should be available like skinny jeans and more cargo pants. (which can all be linked)

**Describe alternatives you've considered**
With these different styles of shoes and clothes, it would give payers a more distinct look. Kinda just put more clothing combos together and have some very drippy fits.

**Additional context**
These outfits would be nice to have for in city parties or gatherings :)

**Comment by Forkedup** [comment]
I do have some new clothing ready for next update, but I'd be more than glad to see some suggestions from gta5-mods.com!

**Comment by kiidtre** [comment]
Yeezy Shoes
https://www.gta5-mods.com/player/adidas-yeezy-boost-700-addon-replace
https://www.gta5-mods.com/player/yeezy-350-boost-turtle-dove-white
https://www.gta5-mods.com/player/adidas-yeezy-boost-700-mauve
https://www.gta5-mods.com/player/yeezy-350-boost-v2-red-2-black-red
https://www.gta5-mods.com/player/triple-white-yeezy-350-boost-v2-texture-by-mattly
https://www.gta5-mods.com/player/mastermind-japan-yeezy
https://www.gta5-mods.com/player/yeezy-350-v2-beluga-1-0-colorway-texture

Jordans
https://www.gta5-mods.com/player/travis-scott-x-nike-air-jordan-6
https://www.gta5-mods.com/player/air-jordan-1-new-texture-1-0
https://www.gta5-mods.com/player/nike-air-jordan-1-retro-high-og-nrg
https://www.gta5-mods.com/player/nike-air-jordan-1-retro-high-bloodlines
https://www.gta5-mods.com/player/4k-air-jordan-3
https://www.gta5-mods.com/player/air-jordan-v-for-franklin-add-on
https://www.gta5-mods.com/player/deep-royal-blue-jordan-12-s
https://www.gta5-mods.com/player/air-jordan-4-kaws
https://www.gta5-mods.com/player/royal-blue-jordan-12s

Nike
https://www.gta5-mods.com/player/2021-nike-air-force-1-low-x-off-white-university-gold
https://www.gta5-mods.com/player/nike-af1-off-white-university-blue
https://www.gta5-mods.com/player/nike-sb-dunk-low-grateful-dead-bears-pack
https://www.gta5-mods.com/player/nike-sb-dunk-low-travis-scott
https://www.gta5-mods.com/player/nike-sb-dunk-lobster-5-pack
https://www.gta5-mods.com/player/nike-sb-ben-jerry-s-chunky-dunky

Clothes
https://www.gta5-mods.com/player/nike-swoosh-poly-knit-pants-tobi7
https://www.gta5-mods.com/player/pack-nike-academy-jogger-pants
https://www.gta5-mods.com/player/mini-hypebeast-tee-pack
https://www.gta5-mods.com/player/skinny-ripped-denim-jeans
https://www.gta5-mods.com/player/skinny-jeans-fyzicz
https://www.gta5-mods.com/player/serenede-jeans-2-pack
https://www.gta5-mods.com/player/supreme-x-thenorthface-x-gore-tex-pants-pack

**Comment by kiidtre** [comment]
Here is some more ideas I have came across recently as well. Hope to see these in the city !

**More Clothes**
https://www.gta5-mods.com/player/camo-sagged-jeans
https://www.gta5-mods.com/player/supreme-cross-box-logo-hoodie
https://www.gta5-mods.com/player/anti-social-social-club-tee-for-mp-male
https://www.gta5-mods.com/player/ralph-lauren-polo-chicago-bear-hoodie
https://www.gta5-mods.com/player/misfits-skull-tee
https://www.gta5-mods.com/player/bape-vlone-hoodie-for-mp
https://www.gta5-mods.com/player/shirt-pack-for-sp-fivem-male-jeremydaking
https://www.gta5-mods.com/player/palace-collection
https://www.gta5-mods.com/player/stussy-collection
https://www.gta5-mods.com/player/givenchy-collection
https://www.gta5-mods.com/player/pullover-hoodies-textures
https://www.gta5-mods.com/player/ftp-hoodie-for-mp-male-and-female
https://www.gta5-mods.com/player/pack-nike-academy-jogger-pants
https://www.gta5-mods.com/player/mp-hoodie-pack-off-white-supreme-nasa-sp-fivem
https://www.gta5-mods.com/player/billionaire-boys-club-hoodie-pack
https://www.gta5-mods.com/player/off-white-exclusive-t-shirt
https://www.gta5-mods.com/player/slightly-oversized-hoodie-pack-for-mp-2ac43b3d-ec3f-48ff-af49-281e473ae25c
https://www.gta5-mods.com/player/serenede-jeans-2-pack
https://www.gta5-mods.com/player/kappa-multi-color-banda-hoodie-pack

**Hairstyles**
https://www.gta5-mods.com/player/mp-male-short-locs
https://www.gta5-mods.com/player/kato-s-dreads-style-for-mp-male-sp-fivem
gta5-mods.com/player/wave-check-for-mp-male
