### ISSUE TITLE
Camaro Top Speed Fix

### ISSUE THREAD

**Issue by AnineAhmetovic** [ChainedDev/CityLife#451]
**What is the reason for this balance request?**
[Because i paid allot of money for the camaro and its not fast at all people in stock phantos that cost 4.5k are almost faster than me]

**What solution would you like?**
[Pumping up the max speed on the camaro to like 160 170 or something]

**Additional context**
[I have no additional context]

**Comment by Forkedup** [comment]
Hi, 

@AnineAhmetovic What is the current cruising speed of the vehicle?

Also, is it upgraded?

**Comment by AnineAhmetovic** [comment]
The current cruising spreed is around 100 and its fully upgraded exept
