### ISSUE TITLE
EMS Incentives 

### ISSUE THREAD

**Issue by OttoFritz0** [ChainedDev/CityLife#452]
**Is your feature request related to a problem? Please describe.**
The problem in this case would be the high turnover rate in EMS, if people who join and are active for a week, then disappear and never to be heard of again.

**Describe the feature you'd like**
I sincerely believe the main cause of this issue is the repetition and low pay of the job (granted any decent EMT isn’t in this for the money) But I believe that a little incentive would greatly help increase the activity and amount of EMS within the city; my suggestion is to add some sort of bonus system wherein EMTS receive a bonus for every (let’s say 5 revives) they get a bonus of $50, it’s not a lot more but it’s something that allows EMTs to make a little bit more money as illegal means are completely off the table for EMS. This I believe would greatly increase the overall activity and mood of EMS because it allows a bit more financial stability. 

**Describe alternatives you've considered**
-Alternatively I suppose the wages could be increased in general but that would mean also increasing other whitelist pay rates to balance it out. 
-Or perhaps there’s some way you could increase wages based on how many EMS are on duty, day for example when I am often the only one clocked in for hours and I’m dealing with a constant excess of twenty-some calls it could be like overtime or holiday pay (times and a half, not sure if that’s only a Canadian thing so forgive me if that sounds strange).

**Additional context**
Don’t get me wrong, EMS is starting to thrive really well again, and our Command staff is doing an amazing job, I just genuinely think that this incentive would help to increase our activity tenfold.

**Comment by ChainedDev** [comment]
I know the EMS Bank Account doesn't really get added into such as the Police Department, we can make some sources of income slowly add to the EMS Fund such as:

- Players Checking in to the hospital
- Players getting Hospitalized
