### ISSUE TITLE
Nissan GTR Top Speed Increase

### ISSUE THREAD

**Issue by TeddyR1** [ChainedDev/CityLife#453]
I recently acquired the Nissan GTR and was slightly underwhelmed when I upgraded it and it gets to about 170-180 and holds. I think it should be higher because realistically it goes about 205. Idk when other cars that cost less can hold up I just think it could use a little buff in speed to even it out.

**Comment by Forkedup** [comment]
I adjusted the car accordingly, please give me feedback upon testing it next tsunami

Thanks for the heads up

**Comment by TeddyR1** [comment]
Okay i just did two runs on the highway and tested it driving in from the
highway twice and it feels even slower. Before tsunami i was able to cruise
between 170-180 and now i am going 160ish and cant get it passed 200 even
driving into the city passed pillbox. but it def feels slower than it was
before

**Comment by Forkedup** [comment]
@TeddyR1 

How is it now?
