### ISSUE TITLE
Allow use of own truck cabs for trucking job

### ISSUE THREAD

**Issue by ChickenDipper1** [ChainedDev/CityLife#454]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the feature you'd like**
Please allow us to buy our own trucks to use with the trucking job, maybe add a small bonus for using your own vehicle to cover fuel.
It would also be good if once you take the trucking job you keep the truck you start with and only new trailers are spawned.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ChainedDev** [comment]
I don't think this would work out
