### ISSUE TITLE
Toggle vehicle lights also toggles voice range

### ISSUE THREAD

**Issue by ChickenDipper1** [ChainedDev/CityLife#455]
**Describe the bug**
Toggle vehicle lights also toggles voice range (normal, shout, whisper)

**How to Reproduce the Behavior**
Steps to reproduce the behaviour: Press H on k/b to toggle vehicle lights, voice range also changes.
Have tried rebinding lights to another key, but these moves the problem to the new key.

**Expected Behaviour**
Lights and voice range should have independent keys.

**Screenshots**
N/A
**Additional context**
N/A

**Comment by ChainedDev** [comment]
I get how this can be annoying, for some reason we forgot to change the voice mode key back to SHIFT + H and we can make it so headlights are only H will work on getting this changed shortly

**Comment by ChainedDev** [comment]
Oops, H is the default keybind for GTA's headlights, would require us to change H to another key

**Comment by Dollar82** [comment]
👁👁
