### ISSUE TITLE
Increase Times for Murder Charges

### ISSUE THREAD

**Issue by loc562** [ChainedDev/CityLife#456]
**What is the reason for this balance request?**
Murder charge as of 05122020 is 25 months in jail. That shit is ridiculous as murder means a CK. To those who don't already know, a CK occurs when a player decided to permanently kill off their character and it's storyline. Other charges such as prostitution is 10 months and is nowhere near as bad as murder but is still 1/3 of its time. A lot of people in this city dont really value other peoples lives and I think its sorta retarded how people are totin ar15s and are ready to kill anybody without a care in the world because the value and importance of life in this city is so low that nobody CKs and nobody has yet faced the consequence of going to jail for a CK.

**What solution would you like?**
Raise time served on all the charges that involve murder and especially murder because 25 months aint shit and with it being only 25 months it means literally nothing to CK and adds onto the problem of life meaning absolutely nothing. Raise time served for murder back up to 200 

**Additional context**
None

**Comment by willllhodgson** [comment]
200 for murder I think 80

**Comment by loc562** [comment]
80 soft make it 200

**Comment by Chainedster** [comment]
Old suggestion, there has been a rework since
