### ISSUE TITLE
Player run radio station

### ISSUE THREAD

**Issue by LuuckPesoPeso** [ChainedDev/CityLife#458]
**Is your feature request related to a problem? Please describe.**
This feature is not related to a problem it would just make the city feel more connected and authentic in a way.

**Describe the feature you'd like**
A player-run radio station would be a fun feature to add to the city. I know it is possible because I have seen it in other cities before. I would gladly sit down to create a new hour or so long mix of music, player created ads for their businesses, and other features every month to be played in peoples' cars.

**Additional context**
I would go through each month and create a new mix of popular music at the time to make sure that the station still feels authentic.
If any higher-ups are interested please message me on discord Luuck#9013

**Comment by Chainedster** [comment]
Any players interested please make a new suggestion
