### ISSUE TITLE
Scuba Diving Job + Scanner Revival

### ISSUE THREAD

**Issue by arrowo1** [ChainedDev/CityLife#460]
**Describe the feature you'd like**
1st Job:  Scuba diving and finding treasures and/or sunken items such as phones and jewelry and sell them at the pawn shop.

2nd Job: Metal detecting - Since gun parts are useless to most players, the scanner could be renamed to "Metal Detector" and new loot such as jewelry, phones, gold/iron/silver can be obtained along with the gun parts and sold to the Pawn shop or Sellables.

**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by Forkedup** [comment]
I'm not entirely sure how gun parts are useless to most players, as you can give / sell them to gangs for weapons / $.

You can also probably fairly easily get hired by said gangs to scan.

Also, there will be a new passive job in our newest update, but I certainly like the idea of a Scuba diving job. 

Check out #teasers on our discord!

**Comment by ChainedDev** [comment]
Yes will be nice to get rid of the Scanner being dead content by utilizing it more at the beach!

**Comment by Chainedster** [comment]
Added a while ago
