### ISSUE TITLE
PostOp/GoPostal variation to job

### ISSUE THREAD

**Issue by ChickenDipper1** [ChainedDev/CityLife#462]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the feature you'd like**
I just thought it may be good to make one of either PostOp or Gopostal require you to get out of the van, go to the back of the van and grab a package out, then drop off the package at the delivery spot.
Maybe then make the job pay slightly more than the other, as now you need to do a little more work.
It would make these jobs a bit different, as currently they are almost identical apart from drop of locations.

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by ChainedDev** [comment]
Yeah, would be nice to make them both function like Pizza Delivery does, can look into it!

**Comment by ChickenDipper1** [comment]
Might be good to just change one of the jobs to function like Pizza Delivery, so for example change PostOp to be similar to Pizza Delivery and leave GoPostal as it is.
That way people could choose one or the other based on if they want to earn a little more because they need to do a little extra work or not.

Your server, your choice :)
