### ISSUE TITLE
RR Wraith Hood Ornament

### ISSUE THREAD

**Issue by JayRusso1** [ChainedDev/CityLife#466]
**Describe the bug**
Sometimes the Wraith comes out of Lux without a hood ornament.

**How to Reproduce the Behavior**
Steps to reproduce the behaviour: Just buy a few Wraiths and you can see that some will come without the hood ornament.

**Expected Behaviour**
The car comes out with all of it's pieces on it.

**Additional context**
I feel like a good fix to this is changing it so the hood ornament is in the 'Vehicle Extras' menu.

**Comment by Forkedup** [comment]
It appears to be listed in the "extras" menu, but upon checking the vehicle in the city, the extra's menu does not appear.

I guess for the people that purchase it and don't get the ornament, I can refund it for them until they do.

**Comment by JayRusso1** [comment]
I have a ticket about my car, been there for 2 days,  Server Bugs Ticket-2260.
