### ISSUE TITLE
Comet Retro Custom Speed Fix

### ISSUE THREAD

**Issue by Metrillex** [ChainedDev/CityLife#468]
What is the reason for this balance request?
I recently got my hands on a comet retro custom and was a little sad to see the the fastest i could get the car to cruising on the highway was 125 mph and only 150mph max coming into the city with the car maxed.

What solution would you like?
I would love to see the speed increased a little bit. Nothing crazy maybe something like 150-160 cruising on the highway.

Additional context
I know they are classified as super cars but the Sultan RS and Banshee Custom both go 160+ cruising on the highway.

**Comment by Metrillex** [comment]
Also forgot to add but the car has no trunk as well.

**Comment by Forkedup** [comment]
Gave it handling for next tsunami, let me know how it feels!

**Comment by Metrillex** [comment]
Thank you so much!!! It feels awesome now its gonna be my daily driver 👍
