### ISSUE TITLE
Carry option

### ISSUE THREAD

**Issue by lilxsuicide** [ChainedDev/CityLife#47]
**Is your feature request related to a problem? No

**Describe the feature you'd like. A carry a downed person option that way they can be taken to the hospital when theres no ems 

**Describe alternatives you've considered**
You could just give us the escort option that ems already have 
**Additional context**
It sucks dying when there’s no ems on at 3 am and losing all your cash, phone, food, and everything else, this feature would be a great improvement

**Comment by eye-ship-mice-elf** [comment]
Have a /carry or somet when next to someone downed or not so you can also use it in kidnapping scenarios

**Comment by ChainedDev** [comment]
> Have a /carry or somet when next to someone downed or not so you can also use it in kidnapping scenarios

This is coming soon

**Comment by gavisuprstar** [comment]
Can you also add a point in this where the carried person can be put into the cars trunk by pressing E near the trunk

**Comment by Skader91** [comment]
Going to be a pain in the ass for Emergency Services if someone does a distress signal then their buddy carries them away.

**Comment by ChainedDev** [comment]
Carry Feature
We have released this feature early so please don't abuse it. This will be considered a test run, if abused it will be removed.

[+] If you are down and call medical attention, do not have anyone carry you then drive you to a hospital. Either call for EMS or get carried away, don't make EMS jobs harder. If you do this you will be banned.
[+] If you are driving a car, you cannot carry someone. Have a passenger carry them.
[+] Do not carry people for no reason. This isn't a playground. Use it when you have to in serious situations. 

You can /carry if near someone and if you're being carried do /carry to stop it
