### ISSUE TITLE
Keybind for shuffle seat

### ISSUE THREAD

**Issue by ChickenDipper1** [ChainedDev/CityLife#470]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the feature you'd like**
A keybind to shuffle vehicle seats would be nice.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ChainedDev** [comment]
You can do /seat [0-3] in a car to switch seats already, we can probably add it to the vehicle menu in the future
