### ISSUE TITLE
Flexing R to call EMS - Does not work when using a xbox controller

### ISSUE THREAD

**Issue by ChickenDipper1** [ChainedDev/CityLife#472]
**Describe the bug**
Press R on the keyboard or any button on the controller doesn't do anything if you have a xbox controller in use or plugged in.

**How to Reproduce the Behavior**
Steps to reproduce the behaviour: Use xbox controller to play, get downed and cannot call EMS.

**Expected Behaviour**
R on keyboard should work when using a controller.

**Screenshots**

**Additional context**

**Comment by Dollar82** [comment]
Mines work fine & i use a controller 24/7 make sure your big picture is on in steam

**Comment by ChainedDev** [comment]
Is this still an issue or just a keybinding issue? I don't have a Xbox Controller linked to test it really

**Comment by Dollar82** [comment]
Never was a issue

**Comment by ChickenDipper1** [comment]
@ChainedDev Yep still a weird issue
@Dollar82 Maybe not for you...
