### ISSUE TITLE
Shooting from vehicles

### ISSUE THREAD

**Issue by Ashytoon** [ChainedDev/CityLife#474]
**What is the reason for this balance request?**
Almost every gunfight involves someone shooting from a vehicle, which means you can barely hit them.

**What solution would you like?**
Disable shooting from vehicles.

**Additional context**

**Comment by MatthewHall-Basic** [comment]
Agreed

**Comment by Dollar82** [comment]
Hell nah,how realistic would that be🤣

**Comment by thebestgloyounger** [comment]
you mad cus you wouldn't be able to shoot out of vehicles 24/7?

**Comment by Dollar82** [comment]
Not at all,i can't shoot anyway 🤷🏾‍♂️😅

**Comment by Forkedup** [comment]
Fixed
