### ISSUE TITLE
Supra Balance

### ISSUE THREAD

**Issue by Tulips9999** [ChainedDev/CityLife#475]
**What is the reason for this balance request?**
[A concise description that describes the balance request in-depth. **Remove this line!**]

**What solution would you like?**
[A concise description that describes what you would like to happen. **Remove this line!**]

**Additional context**
[Add any other context or screenshots about the balance request here. **Remove this line!**]

**Comment by Tulips9999** [comment]
So I work on cars in real life, and when you get a supra tuned, it gets rid of the electronic limiter, letting the top speed of the car which was previously limited to 165 get up to speeds of 210

**Comment by Forkedup** [comment]
What's the current cruising speed while upgraded? I believe it's only a 100,000 car, so it won't be going 210MPH

**Comment by Tulips9999** [comment]
before this I had an bmw e36 with only turbo and it was going 190at max and it cost 75k while the supra is 120k andgoing 165 at max

**Comment by Forkedup** [comment]
190 Cruising? Going downhill legion does not count as that is 1% of your driving time.

I'll slightly buff the supra, and nerf the e36 if that's the case

**Comment by Tulips9999** [comment]
The e36 was at like 185 cruising

**Comment by loc562** [comment]
cap

**Comment by Forkedup** [comment]
> cap

Please reply with something constructive rather than that. If you have the vehicle with upgrades, how do you feel about it?
