### ISSUE TITLE
Re-launch Weazel News

### ISSUE THREAD

**Issue by OttoLFritz** [ChainedDev/CityLife#479]
**Is your feature request related to a problem? Please describe.**
The problem is Weazel news is either gone or just so dead no one even remembers them.

**Describe the feature you'd like**
I would like to offer any help I can in revamping Weazel news and creating another fun whitelisted job for the community to apply for and do.
**Describe alternatives you've considered**
Somehow getting the current Weazel News team active again.

**Additional context**
I have a pretty solid plan built up so far so if you want to talk about it more with me my discord is Ramielvoodoo#1744

**Comment by Forkedup** [comment]
Closing as this was done!
