### ISSUE TITLE
Doctors

### ISSUE THREAD

**Issue by JJG1997** [ChainedDev/CityLife#48]
**Is your feature request related to a problem? Please describe.**

No just another RP interaction.

**Describe the feature you'd like**

Add in doctors and when someone has serious injuries (burns, GSWs, died from explosion) they have to be taken to a doctor for the RP to be healed instead of being healed in the middle of a random place

**Describe alternatives you've considered**

None!

**Additional context**

This would add to realism!

**Comment by ChainedDev** [comment]
With lack of EMS this isn't really possible, if anyone is seeing this and actually is serious about rping this position feel free to apply. Players could just lay down on the bed while EMS heal then with their menu options as of now, although could be better implemented in future
