### ISSUE TITLE
New Suzuki GSX-R Buff

### ISSUE THREAD

**Issue by thebestgloyounger** [ChainedDev/CityLife#481]
**What is the reason for this balance request?**
The new Suzuki GSX-R which costs $55,000 same amount as the CBR need a little buff. The motorcycle is decent fast, but it's slower than the CBR which is the same price + the texture is like paper

**What solution would you like?**
Buff the motorcycle to go a little faster or make it a little cheaper + if there's a fix to the paper texture.

**Additional context**
No additional context

**Comment by Forkedup** [comment]
Will look into this, thank you :)

**Comment by Forkedup** [comment]
Buffed it a bit, also fixed the textures.
