### ISSUE TITLE
Elegy Retro

### ISSUE THREAD

**Issue by gamerdude23** [ChainedDev/CityLife#482]
**What is the reason for this balance request?**
The Elegy retro, being sold for around 60k, is really slow for the price. It's a sports car but it can be beat by cheaper cars. After being maxed besides armor and suspension, it reached around 150 going into the city. It cruises at a good 120-130, but some other cheaper/tuner cars can cruise higher for cheaper. 
When tested for drive train, it is rwd, but in vanilla, it should be 4wd.
**What solution would you like?**
Increase the top speed.
Change to 4wd
**Additional context**
None

**Comment by Forkedup** [comment]
Buffed for next tsunami, don't expect anything crazy.

Thanks for the suggestion!
