### ISSUE TITLE
Opening pockets while downed

### ISSUE THREAD

**Issue by FalseH28** [ChainedDev/CityLife#484]
**Describe the bug**
Anyone is able to open their pockets while down and take out their phone to message or tweet for help.

**How to Reproduce the Behavior**
Steps to reproduce the behaviour: Flexing F2 muscle while downed and dragging the phone onto use.

**Expected Behaviour**
Not being able to open pockets or being able to open pockets to see what you have but all items being locked into place so that nothing can be moved.

**Screenshots**
[If applicable, add screenshots to help explain your problem. **Remove this line!**]

**Additional context**
[Add any other context about the problem here. **Remove this line!**]

**Comment by ChainedDev** [comment]
Fixed next update, thanks!
