### ISSUE TITLE
Camaro speed balance

### ISSUE THREAD

**Issue by AnineAhmetovic** [ChainedDev/CityLife#487]
**What is the reason for this balance request?**
[the reason for this request is because for an example the viseris is 72k it goes 200 stock the camaro is 70 max upgraded and goes 130 and every camaro owner has complained about it]

**What solution would you like?**
[just please buff the camaro and give it a good top speed so it is fast like the viseris atleast 210 max upgraded]

**Additional context**
[the cruising speed is around 110 mine is max upgraded without armor and goes 140 on the highway max]

**Comment by gamerdude23** [comment]
may as well boost a lot of cars though ngl. kinda ridiculous that a heavy police crown vic can go faster than a sports car.

**Comment by JayRusso1** [comment]
the viseris maxed cruises at 170 wdym 200 lmaooo

**Comment by Forkedup** [comment]
Let me know how it is after 6AM EST today. Thanks!

**Comment by AnineAhmetovic** [comment]
> the viseris maxed cruises at 170 wdym 200 lmaooo

That means the pdm salesman gave me the wrong information
