### ISSUE TITLE
Dodge Viper is unrealistic

### ISSUE THREAD

**Issue by Richcarlos** [ChainedDev/CityLife#489]
What is the reason for this balance request?
[The Dodge viper costs too little.]

What solution would you like?
In real life the dodge viper is a expensive ass vehicle and it is the second fastest vehicle that dodge offers next to the demon. You guys should have made the car cost at least 120k.

Additional context
[Thanks for your time 👍 it currently costs only 75k]

**Comment by Forkedup** [comment]
Tweaked the price a bit.
