### ISSUE TITLE
Cyclone at PDM feels too slow

### ISSUE THREAD

**Issue by WillGG12** [ChainedDev/CityLife#490]
**What is the reason for this balance request?**
I feel that the Cyclone available at PDM should be a bit quicker. It feels slow for what kind of car that it is. On the wiki, it is recognised as a Electric HYPERCAR. Hypercars are normally fast cars.
**What solution would you like?**
To balance out the speed so it feels like a hypercar

**Comment by ChainedDev** [comment]
Hypercars are normally fast cars.

Not Electric cars

**Comment by thebestgloyounger** [comment]
Electric cars aren't slower than pantos tho

**Comment by Forkedup** [comment]
> Electric cars aren't slower than pantos tho

After some testing, it is certainly faster than the panto, but I will make some tweaks as I agree it could be a bit better
