### ISSUE TITLE
Notifications for dark chat

### ISSUE THREAD

**Issue by Cudii** [ChainedDev/CityLife#492]
**Is your feature request related to a problem? Please describe.**
Many people in the city use dark chat as their source of contact and they may have a lot of different dark chats. It can be hard to tell which dark chat is the recent one because all you get is a notification sound.  

**Describe the feature you'd like**
Make dark chats be easier to see which channel has a recent message. for example, if you get a dark message, it can highlight a certain channel to tell you which one has a recent message.  

**Describe alternatives you've considered**
Put recent dark chat channels at the top just like how irl phones would put recent messages at the top. 

**Additional context**

**Comment by ChainedDev** [comment]
This is possible however would have to look into the possibilities if we can even edit our phone enough because it would require us to add a "Notifications on/off" setting due to streamers or other people not wanting the channels they're in to accidently get shown

**Comment by ChainedDev** [comment]
Not possible as of now, hopefully the sound should suffice for now
