### ISSUE TITLE
Flares

### ISSUE THREAD

**Issue by thebestgloyounger** [ChainedDev/CityLife#493]
**Describe the bug**
Not sure if it's a bug, but when you have flares you're unable to use them or got anything to do with them

**How to Reproduce the Behavior**
Maybe try looking into it adding them back or something?

**Expected Behaviour**
Supposed to pull a flare out or something

**Screenshots**
Unable to post a screenshot

**Additional context**
No additional context

**Comment by ChainedDev** [comment]
Fixed next update!
