### ISSUE TITLE
Maze Bank 

### ISSUE THREAD

**Issue by OttoFritz0** [ChainedDev/CityLife#495]
**Is your feature request related to a problem? Please describe.**
Not really, it would just be a really cool idea to think about implementing into the City.

**Describe the feature you'd like**
Open up Maze Bank and allow certain banking features to be available (loans, mortgages, etc), and perhaps even a savings account where you earn 1% interest after however long. Basically this would help add a more sense of realism to the City, and the option to take out a mortgage omg side the new rambling of Dynasty 8 will create a lot of opportunities for the City. If someone failed to make their payments etc then they could risk having their vehicles or homes repo’d if they were set up as collateral, you could also have Maze Bank issue warrants via the SASP if people attempted to cheat the bank or whatnot.

**Describe alternatives you've considered**
[What alternatives solutions have you considered?
No other alternatives, just a idea I’d like to see implemented, I have a lot more going on inside my head as to how it would work etc, so feel free to DM me on discord or reply to this thread if you have any questions! Ramielvoodoo#1744

**Comment by REDDGLARE** [comment]
I think these are great ideas but I disagree with it being a City implemented thing. These are great business for people to create.

**Comment by OttoFritz0** [comment]
I agree, I was thinking it could be both, ran by citizens (I mean if def be down if it was green lit) but with the areas like mortgages etc where it’s a lot of money being granted to a citizen, if we were completely backed by the city people would be less likely to attempt to scam us out of hundreds of thousands of dollars. Like I said I have a lot of thoughts and ideas running through my head regarding this so I’m open to whatever the government thinks, I’d definitely be down to acquire a business license and attempt to launch it myself. I just figured since paycheques and PayPal’s come through MAZE it’d make sense to have it mostly government controlled (similar to how EMS and PD are run with government funds backing them) is what I was possibly thinking
