### ISSUE TITLE
City too quiet

### ISSUE THREAD

**Issue by gamerdude23** [ChainedDev/CityLife#497]
**Is your feature request related to a problem? Please describe.**
Isn't much of a problem.

**Describe the feature you'd like**
The city needs more sound. It can't just be car crashes and police sirens. Make car exhausts sound nicer and louder. Add some city ambience and some more people walking the streets in the middle of the city near legion. City feels a little dead sometimes with no life. 

**Describe alternatives you've considered**
Nothing much

**Additional context**
Would make racing a bit more cooler, hearing engines rip and echo from a few blocks away.

**Comment by Forkedup** [comment]
Our extra sounds script that enhances certain sounds around the city has been disabled for a while as we optimize it for our OneSync Infinity.
