### ISSUE TITLE
Whitelist Weazel News

### ISSUE THREAD

**Issue by OttoFritz0** [ChainedDev/CityLife#499]
**Is your feature request related to a problem? Please describe.**
Weazel isn’t a whitelisted job

**Describe the feature you'd like**
I’d like to petition for Weazel News to be added as a whitelist job in city. I am currently the only reporter in the City, and well I’m paid really well by Drosh, and I don’t care about the 20 minute paycheque, but whitelisting can benefit Weazel News in various ways, you could add a Reporter only garage in the Weazel news parking lot, you could make use of the Weazel News phone app in some better way if it’s whitelisted, maybe set it up as a variation to twitter for reporters to make little announcements in city? You could also add various interaction points inside the Weazek News building, as of right now it’s one giant, beautifully interior building that serves no real purpose.

**Describe alternatives you've considered**
None

**Additional Context** 
This could also encourage more people to apply as a Reporter, although we’re getting by with just me it would be nice to have a change in articles as everyone’s writing style is different and a nice break, I’m willing to train and mentor future Reporters.

**Comment by OttoFritz0** [comment]
Side note: whitelisting would also give us the opportunity to hire other fields, cameraman, sports/weather/etc reporter, editor, all of that could be possible. At the moment I’m just contracting a camera man and giving him a sizeable cut out of my own salary

**Comment by justsomeideas** [comment]
Lmaoooo how y’all have a separate RP channel in the discord but ain’t whitelisted 🤨
