### ISSUE TITLE
Car Finance & Repo Job

### ISSUE THREAD

**Issue by JJG1997** [ChainedDev/CityLife#50]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
Adding in car finance so you can finance cars and pay over time (only the time you are in the city counts towards paying it.) There could also be Repo Job's for Police, Mechanics or another job entirely (whitelisted or not idk) who would have access to a database of cars with outstanding payments on, if they are not paid off within a certain amount of days, the car would be repossessed and taken from the person who took finance out on it.

**Describe alternatives you've considered**
None

**Comment by ChainedDev** [comment]
Down the road, not now
