### ISSUE TITLE
Taxi Job Balance

### ISSUE THREAD

**Issue by km4411933** [ChainedDev/CityLife#500]
**What is the reason for this balance request?**
The taxi job has been fun but it needs some balancing. What you get paid doesn't match up with the distance you drive similar to trucking or PostOps/Gopostal. Currently, I can do a 6 mile trip and only get paid $200ish and do a 3 mile trip and be paid $450.

**What solution would you like?**
My solution would be to just balance the amount of money you get based on the distance of the ride. An alternate/addition solution can also be to increase the rate at which we get passengers. 

**Additional context**
Just a small change that I think could improve the taxi job.

**Comment by ChainedDev** [comment]
The main goal of it is to interact and give rides to other civilians and earn more money that way, the ai deliveries is meant to be in offtime and not the main source of income. Will look into a slight buff though
