### ISSUE TITLE
Race harness

### ISSUE THREAD

**Issue by km4411933** [ChainedDev/CityLife#501]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the feature you'd like**
It would be great to add race harnesses to the city. Having it a car upgrade would be dope imo. Driving better isn't always a solution for car deaths because there are times when random cars pop out of nowhere and there's nothing you can do to avoid them. Having a race harness installed into your car can fix this issue. It can be an upgrade that cost a couple of thousand to have installed. 

**Describe alternatives you've considered**
[What alternatives solutions have you considered? **Remove this line!**]

**Additional context**
I randomly died from a ghost car the came out of nowhere and needed to request this feature. It would also be great for when there are races around the city.

**Comment by gamerdude23** [comment]
a seatbelt works
