### ISSUE TITLE
Defibrillator / reviving device 

### ISSUE THREAD

**Issue by MrD2K** [ChainedDev/CityLife#502]
Looking to open discussions on a device that can be crafted or sold for high price by ems or drug stores. Make a defibrillator so people can revive each other. Obviously you want to make it a rare item so make it really expensive or require it to be crafted. Make it like a advance repair kit and make it so after 2-3 uses it will disappear from your pockets. 

This isn’t a device to undermine the job of EMS but to help with wars between gangs or those late night when no ems are in the city.  Because in IRL sometimes people can save other people’s lives. 

To add to the RP aspect maybe make the device only heal the downed person half way because obviously in ooc you wouldn’t be in 100% condition after being treated by anyone for any type of injury or accident.

**Comment by OttoFritz0** [comment]
I like the idea, though the man issue with this is a Defibrillator would only work in very few RP situations when their hearts stop pumping blood. Use a defib on someone who was just lit up by a M4 in a gang war wouldn’t do anything. Maybe a advanced Medkit or something would work better, but I agree with only bringing back half your health.

**Comment by MrD2K** [comment]
Yeah I see what you mean. I was just trying to think of a name of some kinda medical device that’s used to save lives.  Defibrillator came to mind but yes basically like a advance med kit.

Yeah bring the said person back to life with only 25-50 percent health.

**Comment by ChainedDev** [comment]
There's other means than having a item you can do it anywhere
