### ISSUE TITLE
Relaunch BSCO

### ISSUE THREAD

**Issue by OttoFritz0** [ChainedDev/CityLife#504]
**Is your feature request related to a problem? Please describe.**
I would like to see The Blaine County Sheriffs Office re opened because SASP doesn’t seem to be able to handle the amount of calls they get and BSCO would take a lot of workload off by dealing with county calls

**Describe the feature you'd like**
Simply re launch BSCO and start recruiting, this would take a lot of strain off SASP and offer another route of law enforcement to apply for, I get SASP are State Police and I’m not saying limit them to the city but if you had BSCO operating they could respond to county calls much quicker or even deal with the lesser calls that always get ignored by SASP due to not wanting to drive 9 miles for a drug sale.

**Describe alternatives you've considered**
[What alternatives solutions have you considered? Recruit a whole lot more SASP and designate a few each shift to be in the County, maybe give them the option to spawn in at the old BSCO detachment 

**Additional context**
Everyone wants BSCO back

**Comment by OttoFritz0** [comment]
Adding on to it so it doesn’t get ignored: 

Why do we need BCSO?

Blaine County is a geologically diverse county, featuring a large desert region, dense forest and several mountains. Blaine County is the single largest rural area in the State. Blaine County contains the towns of Grapeseed, Sandy Shores and Paleto Bay, as well as several other smaller settlements. This is a vast area that is relatively left untouched by SASP and is essentially a free-for-all for any and all crime. Although SASP is relatively active and does their job well, it is difficult for them to focus on both City and rural crime as they simply don’t have the man power to handle both simultaneously. Re-launching BCSO would help take a great deal of stress off the shoulders of SASP and allow them to focus more on City crime, as they are state troopers they would still have full jurisdiction in the county but would have the added support and backup of the Sheriffs. However, if done correctly SASP would only need to be in the County for raids and other high risk operations as secondary for the Sheriffs. Relaunching BCSO would also greatly increase interest within the city as it would present a more unique and diverse law enforcement position for newcomers to the City to apply for. With the ever increasing numbers of new citizens to the City the strain on SASP is becoming evident as many citizens have decided to openly spit in the face of the city by openly walking around the city with class 2’s out, with SASP being able to focus more on solely the City this would allow them to start cracking down on these individuals and helping deter crime further. 

Below is the general structure of hierarchy that would be presented with the re-launch of BCSO:
Senior Management
* Sheriff
* Undersheriff
* Assistant Sheriff
* Division Chief
Ranks
* Captain
* Lieutenant
* Sergeant
* Deputy Sheriff (II) (Master Field Training Officer)
* Deputy Sheriff  (I) (Field Training Officer / Detective / Custody Senior Deputy)
* Deputy Sheriff

Give us more opportunity for a new, refreshing whitelist law enforcement job. I would personally love to apply for and do BCSO as I much prefer being in the County then in city.

**Comment by Sturdyinnit** [comment]
This is hella needed.
There's too much crime going on in the main city, anything outside of it is swarming with robberies and shootings.
Constantly being in BC gives off completely different vibes too, I can imagine some people would way prefer that over the urban policing.

**Comment by OttoFritz0** [comment]
> This is hella needed.
> There's too much crime going on in the main city, anything outside of it is swarming with robberies and shootings.
> Constantly being in BC gives off completely different vibes too, I can imagine some people would way prefer that over the urban policing.

I 100% agree, it would vastly improve the RP of the server as it wouldn’t be solely one small state police department dealing with the numerous whitelisted gangs and Danny’s, I’d even go as far to argue that it’s almost low-effort RP to just have a small state police department solely responsible for such a vast amount of area.
