### ISSUE TITLE
Speed on Lamborghini Gallardo S

### ISSUE THREAD

**Issue by JimSteel1** [ChainedDev/CityLife#507]
**What is the reason for this balance request?*
I think that the Lamborghini Gallardo S should be faster because it is a 750k car that cruises at 175mph to 180mph. 
The top speed on the Lamborghini Gallardo S is only 211mph. I should have a better top speed and a better acceleration.

**What solution would you like?**
I would like if the Lamborghini Gallardo S would cruise at 180mph to 190mph and the top speed will be like 220-225. 

**Additional context**
I feel like it's a Lamborghini so it should have the speed right now it is a little faster than the nessan GTR

**Comment by JayRusso1** [comment]
Top speed IRL is like 199, the car isn't for speed it's for luxury.

**Comment by OttoFritz0** [comment]
Nah bruh 211 is too fast for this car it deserves to be nerfed if anything giving all the idiots who seek to try to hit 210 going through legion square 🤦🏻‍♂️

**Comment by Forkedup** [comment]
Just tested this vehicle, I believe it's perfect where it's at.
