### ISSUE TITLE
EMS Stretchers

### ISSUE THREAD

**Issue by HIPPIEMAN420** [ChainedDev/CityLife#511]
**Is your feature request related to a problem? Please describe.**
Not a problem but a suggestion, I have seen in other cities that EMS can have working stretchers. It would increase the RP and would make it a lot more realistic when transporting people to Pillbox.

**Describe the feature you'd like**
Add the stretchers, allows ems to transport patients properly

**Describe alternatives you've considered**
none

**Additional context**
[Add any other context or screenshots about the feature request here. **Remove this line!**]

**Comment by ChainedDev** [comment]
Duplicate of #135
