### ISSUE TITLE
Mazda MX5 suspension scuff

### ISSUE THREAD

**Issue by CreepyEK** [ChainedDev/CityLife#512]
**What is the reason for this balance request?**
Mazda MX5 suspension scuff

**What solution would you like?**
Play around with the suspension somehow, it makes the car go way faster than it perhaps should, and it'd be nice if it were a little more playful as it was advertised as a "drift king".

**Additional context**
It is most noticable on the highway, you can hear the suspension scuffing constantly and the car seems to go faster because of it.

**Comment by Forkedup** [comment]
suspension doesn't effect speed, the sound is annoying though I agree.

do you have your suspension fully down?

**Comment by CreepyEK** [comment]
Yeah I do have my suspension all the way down, would you recommend I revert it to stock suspension?
