### ISSUE TITLE
C63 mercedes new year handling

### ISSUE THREAD

**Issue by tyson1096** [ChainedDev/CityLife#513]
**What is the reason for this balance request?**
The handing of the vehicle feels like your driving a tank it doesn't turn well at all.

**What solution would you like?**
Able to turn even at higher speeds like a normal vehicle if possible.

**Comment by Cele121** [comment]
I completely agree with this. The C63's handling is pretty bad

**Comment by Forkedup** [comment]
Updated the handling for next tsunami! Should be a bit tighter while also drifty :)

Let me know your feedback on this! Thanks for the suggestion!

**Comment by tyson1096** [comment]
Thank you hopping on to see how it feels

**Comment by tyson1096** [comment]
handing still feels slightly off it is a bit better but compared to other vehicles its still scary to drive when trying to take a sharp turn you slow down and then turn but with the Mercedes still feels back heavy as if doesnt stick to ground when trying to turn. there are alot of other vehicles thaty can turn at higher speeds but for the Mercedes u have to slow way down or u lose control turning. like on the highway alot of the car u can turn left and right in going back and forth but Mercedes is a bit rough to do and alot of times end up spinning out. It does feel better then before but feel it could be better still.

**Comment by ChainedDev** [comment]
Drives amazing
