### ISSUE TITLE
Weazel Features

### ISSUE THREAD

**Issue by OttoFritz0** [ChainedDev/CityLife#515]
**Is your feature request related to a problem? Please describe.**
Not a problem just some cool ideas I wanted to put out there 

**Describe the feature you'd like**
Adding these mod packs for Weazel News, the new van would be nice as it would stop us from being mistaken for locals, but same with the clothing pack, I think the Press/Media vests would be nice to have for ride alongs Weazel takes with SASP and EMS. 

https://www.gta5-mods.com/player/media-eup-pack-livepd-press-stringer

https://www.gta5-mods.com/paintjobs/mercedes-sprinter-weazel-news

**Describe alternatives you've considered**
[What alternatives solutions have you considered? None really, just an idea I think would be cool and help Weazel News become more recognizable in city as I’m often mistaken for some random RPinf Weazel rather then an Official reporter .

**Comment by OttoFritz0** [comment]
(If the vest skins were to be added in we could actually set up a Live PD/Live Rescue video special with SASP and EMS ❤️)

**Comment by Sturdyinnit** [comment]
Seems only fitting!

**Comment by Chainedster** [comment]
Needs paychecks
