### ISSUE TITLE
Lack of mechanics

### ISSUE THREAD

**Issue by AnineAhmetovic** [ChainedDev/CityLife#516]
**What is the reason for this balance request?**
[my request is to make mechanics have more active, because bow everytime i play people just keep asking any mechs? And people have to wait so long until a mech finaly comes online so you can tune your car]

**What solution would you like?**
[Maby pay them more? or have like mechanic of the week were the mechanic that clocked in the most get extra cash]

**Comment by Sturdyinnit** [comment]
There are a lot of people waiting to hear from their mechanic application. I don't feel like the pay should specifically be increased as mechanics tend to earn most of their wage from tips anyways. I'd like to at least hear why the process takes so long.

**Comment by JayRusso1** [comment]
We just reviewed 50+ mechanic applications today, hopefully the department will be more active soon!
