### ISSUE TITLE
new and special more realistic gun sounds.

### ISSUE THREAD

**Issue by fatman3313** [ChainedDev/CityLife#518]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the feature you'd like**
ive been watching alot of videos from different rp servers and one feature that caught my eye and lets say ear.. is how the guns in these servers sound. the vintage , sns and combat pistol have that unique sound that gives you the rush and feeling that you are actually the one whos pulling the trigger and firing. i would love to see these special sounds to the guns added in to citylife as they will greatly enhance everyone's roleplay experience. ( watch the video i linked to hear the guns for yourself.) 

https://www.youtube.com/watch?v=K_qqBUG2C_I&ab_channel=YBNPLUG

**Comment by fatman3313** [comment]
here's another video showing more of the sounds: https://www.youtube.com/watch?v=wU3I1LqJk_0&ab_channel=YBNPLUG

**Comment by Dollar82** [comment]
CLRP gun sound mod is disabled at moment,but we have one

**Comment by fatman3313** [comment]
Is there an eta on when it’s gonna be enabled again ?

**Comment by ChainedDev** [comment]
> CLRP gun sound mod is disabled at moment,but we have one

What are you talking about?

**Comment by Yamipandah** [comment]
Those sounds are part if the visual mod they have installed themselves that’s something you could totally do right now

> **Is your feature request related to a problem? Please describe.**
> No.
> 
> **Describe the feature you'd like**
> ive been watching alot of videos from different rp servers and one feature that caught my eye and lets say ear.. is how the guns in these servers sound. the vintage , sns and combat pistol have that unique sound that gives you the rush and feeling that you are actually the one whos pulling the trigger and firing. i would love to see these special sounds to the guns added in to citylife as they will greatly enhance everyone's roleplay experience. ( watch the video i linked to hear the guns for yourself.)
> 
> https://www.youtube.com/watch?v=K_qqBUG2C_I&ab_channel=YBNPLUG

**Comment by fatman3313** [comment]
thanks alot , will do. stay safe !.

**Comment by ChainedDev** [comment]
If we figure out how to stream it server side it will be a possibility, this will be on the backburner for now
