### ISSUE TITLE
Change Emergency Dispatch Messges

### ISSUE THREAD

**Issue by TimmyTwoStep** [ChainedDev/CityLife#519]
**Is your feature request related to a problem? Please describe.**
Sorta yeah, when you have a bunch of things happened at once, the entire left side of the screen gets swallowed by dispatch messages 

**Describe the feature you'd like**
After the update that added the Z menu and all the status effects like, Smells like Weed, Red eyes, gunshot residue, and all the others that are in there, I think it'd just be so much cleaner if emergency messages for EMS/PD popped up in the text box with the rest of everything.

**Describe alternatives you've considered**
I haven't thought of any

**Additional context**
N/A

**Comment by Chainedster** [comment]
Wouldn't your chat get swallowed with dispatch messages and make it look even more messy?

**Comment by TimmyTwoStep** [comment]
I wrote this before /311 and /911, and I haven't been in the city for awhile so I'm not sure how it would turn out now
