### ISSUE TITLE
Traffic Lights

### ISSUE THREAD

**Issue by Skader91** [ChainedDev/CityLife#52]
**Is your feature request related to a problem? Please describe.**
Currently it is a law to stop and wait for the entire traffic light

**Describe the feature you'd like**
I think it would cut down on a lot of unnecessary "meh" RP if SASP and Civilians both treat a red light like a stop sign

**Comment by ChainedDev** [comment]
But the PD gets more funds giving an extra ticket if someone runs a red light 💸
