### ISSUE TITLE
fisherman 

### ISSUE THREAD

**Issue by mark156235** [ChainedDev/CityLife#523]
ok so am from Scotland and we having fishing boats that go out to sea and catch fish they make a lot off money for doing this i was wondering if its possible to make this a white list job in the city you have to be on a fishing boat and take it out to sea like one off the gta tug boats and maybe take it to a point on the map out at sea for fishing ground and you can make a good income from fishing but you have to fill out a good application to get job you could have like deck crew mate and skipper 3 different roles on the boat and depending what role you have you can make more money skipper the most then mate and last deck crew and you have to take the boat out to sea to get to fishing ground and kind of set up a work boat type thing to the city if you could get back to me as what your thinking

**Comment by MrD2K** [comment]
That would be good rp. You could hire a ship captain and a first mate. Fish for certain types of sea life  like tuna , crab, bonitos, grouper.

**Comment by mark156235** [comment]
I know I'd love it to be a thing

**Comment by mark156235** [comment]
A add on u can make a fish and chip shop for the fish off the fishing boats

**Comment by ChainedDev** [comment]
Fishing could use a rework
