### ISSUE TITLE
Furia car

### ISSUE THREAD

**Issue by wordaroundtown** [ChainedDev/CityLife#524]
**What is the reason for this balance request?**

**What solution would you like?**
[A concise description that describes what you would like to happen. **Remove this line!**] I just feel like the furia supercar speed should be bumped up a little its a $415k car and it goes about 190 mph, theres $150k-175k cars that go 180-185 mph i just feel it should be bumped up a little faster for being a supercar and being how expensive it is, thank you. 

**Additional context**

**Comment by Forkedup** [comment]
Balanced.
