### ISSUE TITLE
Transfer houses

### ISSUE THREAD

**Issue by wordaroundtown** [ChainedDev/CityLife#525]
**Is your feature request related to a problem? Please describe.**
I feel like its just a pain for everybody including dynasty 8 when they have to go out there way just to transfer a house to someone else for someone.

**Describe the feature you'd like**
Just a simple option in the Z interaction menu where you can sell your house to someone else without having to have dynasty 8 there or in the city.

**Describe alternatives you've considered**
I know it makes dynasty 8 a little money from doing it but i feel like it will be better for everybody if you have someone trying to buy your house if u could just go up to the house with them and put the price you want for the house on the door and they just flex E and pay it then the house transfers to them and the money goes to your bank.

**Additional context**
[Add any other context or screenshots about the feature request here. **Remove this line!**]

**Comment by TimmyTwoStep** [comment]
Remove all reason to have a D8 and forget rp

**Comment by wordaroundtown** [comment]
> Remove all reason to have a D8 and forget rp
How? there still gonna be needed to sell houses to people you can just transfer your own to someone else
