### ISSUE TITLE
When respawning we don’t lose our items.

### ISSUE THREAD

**Issue by fatman3313** [ChainedDev/CityLife#526]
**What is the reason for this balance request?**
This is the BIGGEST fiveM role play server and we as players MUST value our lives but when dying and just waiting for the timer to end then clicking r to respawn and spawning with most of our items on us kills the whole “valuing live “ vibe ... what’s the point of keeping all my stuff after I respawn... and this eliminates the need of ems for some players ( they can just respawn and not lose anything ) which again a real bummer and I think that making it that we lose everything we have on us when we respawn instead of getting revived by ems a must to greatly enhance the overall rp experience.
**What solution would you like?**
Making it that we lose every item on us if we choose to respawn and not getting helped by ems or by a player carrying us to the hospital to be checked.
**Additional context**
I’ve been in a lot of situations where it ended up in a gun fight and after the outcome of me loosing I’m like ( oh well I don’t lose my items at least and feel empty inside as I don’t get that rush feeling of realizing that I lost everything that I had on me ) or after winning a gun fight I’m always like ( I wish that the people I killed lost their items so they learn that resorting / escalating the situation to a gun fight is the last thing we want as we really value our lives and we should think everything through ). So again ... making it that we lose everything if we chose to respawn is a must.

**Comment by AnineAhmetovic** [comment]
keeping your shit is to op and is not realistic, in stead of that maby if you stuff would drop and you have like 2 minutes to get there and pick your stuff back up

**Comment by ChainedDev** [comment]
People being able to keep their stuff after dying would just encourage not fearing for your life

**Comment by fatman3313** [comment]
Exactly and that’s why I HIGHLY suggest making it so we lose our items when we die so the the rp highly enhances and we value what we’ve got.

**Comment by ChainedDev** [comment]
Ah gotcha, I thought you were originally saying that people should keep everything but I agree it should be doing so but is bugged, will look more into fixing it so it works as proper

**Comment by fatman3313** [comment]
Awesome! Looking forward to see this bug fixed , keep up the good work and stay safe ! @ChainedDev .
