### ISSUE TITLE
Save Vehicle Damage in Garages

### ISSUE THREAD

**Issue by AnineAhmetovic** [ChainedDev/CityLife#527]
**Is your feature request related to a problem? Please describe.**
[this may sound stupid asf but i think that if you make it that if you put your car in the garage it doesnt get repaired and refueled  that the city would be more alive, because the only thing you see al day is people in legion just puting cars in the garage and taking em out again, plus i never see people at repair shops or gas station. it would make the city so much more alive]

**Describe the feature you'd like**
[make the garage not repairing and refueling your car]

**Comment by Dollar82** [comment]
i second this!
