### ISSUE TITLE
ADD A CHURCH INTERIOR

### ISSUE THREAD

**Issue by xGRIMEYx** [ChainedDev/CityLife#529]
**Is your feature request related to a problem? Please describe.**
[This is not related to a problem.]

**Describe the feature you'd like**
[A viewer on my stream suggested that him and his group were looking for a city that had a church with an interior. This would be an amazing additional to the life of the city as it opens up characters and story lines for the community. It would be a great place to organize in the event of a wedding or funeral for characters within the city. A religious group can run the church, have Sunday Service for the community and Bible Studies.]

**Describe alternatives you've considered**
[There are no alternatives. Plan A is the only plan. We don't do Plan B.]

**Additional context**
[https://www.gta5-mods.com/maps/gta-iv-suffolk-church-sp-fivem]

**Comment by REDDGLARE** [comment]
Pretty good idea actually. I like this!

**Comment by Yamipandah** [comment]
We have had a church interior before, this would have to be something that is rped out for a while before getting added in just because I’m sure the city doesn’t need any unused assets.

**Comment by skiredd** [comment]
rip father ezekiel 💯
