### ISSUE TITLE
New Job Ideas

### ISSUE THREAD

**Issue by yggun** [ChainedDev/CityLife#53]
**Is your feature request related to a problem? Please describe.**
I believe that there aren't enough jobs for the average civilian to do. Currently, garbage and mining are really the only two non-whitelisted jobs that give you items to use/sell. I think spreading the loot table out from garbage and possibly mining in order to give more options for civilians would be a good idea. 

**Describe the feature you'd like**
Implementing a locksmithing job. When you are hired as a locksmith, you get routes to drive to similar to garbage, but you have to get out of your vehicle, walk to a door and go into a lockpick minigame. If you fail, RNG if you get to try again or move on to the next house and you miss out on a paying customer and potential loot such as; scrap, iron, drill bits etc. 

Implement an IT job. When hired as an IT worker, you get routes like mentioned above. You have to complete a timed minigame. if you complete it, you get paid and possibly loot like wires for laptops. If you fail you have to go to the next spot. 

Maybe even implementing some sort of small chance RNG loot table for fishing. 

**Additional context**
I think spreading the loot tables out and creating more jobs will make for more people to stay in the city longer. Making the jobs still grindy but also rewarding at the same time with the possibility of getting random items. This also has the potential to add more RP scenarios. New players do legal jobs, get the items but don't know what to do with them so they sell them to the organizations/gangs or even just more experienced players for cash. It's a win-win. Keeps the civs happy, helps criminals, and creates a more diverse economy.

**Comment by ChainedDev** [comment]
I do like the idea of legal jobs but higher priorities as of now
