### ISSUE TITLE
Black bandana for back pocket 

### ISSUE THREAD

**Issue by fiXXer1** [ChainedDev/CityLife#531]
**Is your feature request related to a problem? Please describe.**
Not really a problem just a suggestion. 

**Describe the feature you'd like**

Is there any way you can put black bandanna flags back into the wardrobe for back pockets? They took away all the black and now there is only grey and other bright colors. I like the realistic look of having a "flag" or color that some families can have in back pocket.. I know its not used for gang/family color use but most family's use it and the black was something we usually rep. It just adds a more realistic feel to the RP. Also im not sure if it is just a bug that happened as of why its not in clothing shirt2 list now. thanks

**Describe alternatives you've considered**
Not sure. Just figured there is grey, red, green, tan but yet no black anymore so figured that would be something to ask for. 

**Additional context**
Thanks

**Comment by Forkedup** [comment]
Hello,

The second variant of the Bandana is black.

black
https://imgur.com/a/jPqInRk

grey
https://imgur.com/a/PpcY1o9
