### ISSUE TITLE
Job at Burger Shot!

### ISSUE THREAD

**Issue by petterngn** [ChainedDev/CityLife#533]
**Is your feature request related to a problem? Please describe.**
Not really, more of a feature. 

**Describe the feature you'd like**
A job at Burger Shot would be amazing and here's why. Food deliveries and most other legal jobs have little to none interactions. It is also really good for newcomers because this job does not require traveling or a car. A worker can simply come in, begin their work, and start making food/drink in the back. You should also make it so that food at Burger Shot is much better than a convenience store (more filling, cheaper, etc) so people would want to come in here and order food, which creates more RP. Workers can get paid by the hours so even if no one comes, they can still earn some money (unless they're idle of course). If a person starts a job but quits or runs away before like 10 mins, they can be penalized. And in my experience with other cities, burger shot has always been everyone's favorite because it's where they all can come to get food, chill out, and get to meet new people, not doing illegal activities all the time. 

**Describe alternatives you've considered**
No alternatives. 

**Additional context**
Burget Shot was my first job and I still love it today. It might sound boring to some people, but Burget Shot has always lead me to some super fun, if not best, RP due to the many interactions. CityLife is still the best city out there, but it could be much better with this addition :)

**Comment by JayRusso1** [comment]
Burger Shot is actually owned and you're more than welcome to apply :) https://forms.gle/tsjc8kLW3tLGd1Sp8

**Comment by petterngn** [comment]
> Burger Shot is actually owned and you're more than welcome to apply :) https://forms.gle/tsjc8kLW3tLGd1Sp8

Yes, but I'm saying that it should be open to the public, like you can simply come in and press E to start working. Right now, Burger Shot is pretty dead because the application is a bit tedious for such a simple job, and since no one really apply and willing to work 24/7, you rarely see any workers, which makes no one want to come to Burger Shot. So please consider making this job public and the food at Burger Shot worthwhile because I can almost guarantee that there will be a lot more fun legal rp for everyone :d
