### ISSUE TITLE
Vehicle Customization Options

### ISSUE THREAD

**Issue by KirbyDD** [ChainedDev/CityLife#538]
**Is your feature request related to a problem? Please describe.**
Not a technical problem but an RP problem.

**Describe the feature you'd like**
Similar to how you can check in at a hospital instead of EMS reviving you when there is no EMS around, there should be some system to work on my car when there are no mechanics around. Server two never has mechanics online, so you have to go to server one. When you go to server one, even if there are mechanics clocked in, plenty of times they do not have their shop open, are just privately working on their friends cars, or doing roadside assistance(which I have personally never seen). 

**Describe alternatives you've considered**
- Give mechanics a commission per vehicle worked on to incentivize mechanics to have shops open
- You could let citizens change cosmetics of their vehicle and not performance items when no mechanics are in the city.
- You could incorporate a leveling system where starting out maybe all you can do is change tires or rims and build up to being a mechanic that can do what current mechanics can.
 - You could hire more mechanics. I personally have applied as well as other people I know but never heard back.

**Additional context**
I as well as some others I have seen feel like unless we become friends with the mechs we don't have any option to do anything with our cars but drive them.

**Comment by JimSteel1** [comment]
Then mech would never be needed and be pushed out from there job I do understand your point and it's not a bad one but it would not work in the city.
