### ISSUE TITLE
Ass pulling needs to go !

### ISSUE THREAD

**Issue by fatman3313** [ChainedDev/CityLife#541]
**What is the reason for this balance request?**
[A concise description that describes the balance request in-depth. Role playing on citylife has been THE best experience of ever had on my whole 800 hours on rp servers. I’ve been whitelisted on a couple of big cities and let me be fully honest city life comes down as the top 3 for sure ! But one thing that is HUGLY impacting the city in a negative way is “ ass pulling “, which is let’s say we’re in a situation that led to the use of firearms and a guy pulls a shotgun or an m4 or an smg out of his ass ( not quite literally but just like in GTA online ). I am highly suggesting that some rules and changes are put in place to diminish this “ ass pulling “ phenomenal from the city and to greatly affect the rp experience in a good way.

**What solution would you like?**
[A concise description that describes what you would like to happen. For example , most of the time I carry a pistol on me just in case a hostile situation escalates really quickly and I make sure to wear the gun strap carrying thingie on me and make sure that it’s visible so other players “ notice” that I am carrying a firearm, however whenever I’m carrying a big gun like a shotgun or an assault rifle or an smg I ALWAYS and I mean ALWAYS wear a bag on me ( to make sure that people around me know that I might have a deadly firearm in this back duffel bag that might be used). And I ALWAYS before I pull it out make sure to use and type me “ /me puts duffle bag on the floor and unracks an m4 / shotgun / mini smg “ or whatever gun that requires to be held in a different way to be able to carry it with me. And also use the “ /e pick up” emote to show that I’m putting the bag on the floor and that I’m taking the big gun out.

**Additional context**
[Add any other context or screenshots about the balance request here. Citylife is the biggest rp server with arguably the best community out there . Why not keep doing what we do best and shine through other communities and show how great rp truly is, by implementing / enforcing the right rules and implementing the correct penalties to discourage players from always escalating most situations into a bloody gun fight. Again this is A role playing community , we’re not a deathmatch community where if a guy insults me I pull an aK out of my ass and Starr shooting , lets implement a “ force “ where when you are carrying a big firearm you must use bags and use the correct /me’s and if not you guys will take the correct form of action. I would looove for this to happen as it adds a little more realism to our experiences in beautiful citiglife !.

**Comment by leuit** [comment]
To add to this, you could only holster/equip via your vehicle trunk if you don't have a bag.
