### ISSUE TITLE
Radio animation 

### ISSUE THREAD

**Issue by wordaroundtown** [ChainedDev/CityLife#549]
**Is your feature request related to a problem? Please describe.**
The problem with radios now is now say your robbing someone at the casino, they could be holding down the caps lock muscle and be like oh why are you robbing me at this casino and there whole gang would know where hes getting robbed at but you have no idea hes talking on the radio because theres no animation of him talking into it.

**Describe the feature you'd like**
Just a little animation that shows people talking into there radio so everyone knows when someone is talking to there radio or not.

**Describe alternatives you've considered**
[What alternatives solutions have you considered? **Remove this line!**]

**Additional context**
[Add any other context or screenshots about the feature request here. **Remove this line!**]

**Comment by ChainedDev** [comment]
#553
