### ISSUE TITLE
Food and water

### ISSUE THREAD

**Issue by littlewilms** [ChainedDev/CityLife#55]
Constantly buying 15 bottles of water and burgers to refill my thirst and hunger
Make it so burgers and water replenish your thirst and hunger more instead of eating 6 burgers and 6 bottles of water every half hour

**Comment by ChainedDev** [comment]
Yeah, I don't think people can eat 10 burgers at a time just to not be starving IRL, can def look into redoing food % variations shortly but housing is main priority

**Comment by ChainedDev** [comment]
OMG why do I have to eat 10 burgers to be full????????

**Comment by NinjaTinaH** [comment]
Are you guys eating them too fast? takes 3-4 burgers for me... Gotta wait for the animation to step before you eat another or it doesn't count.

**Comment by littlewilms** [comment]
I figured that out but still 3-4 burgers is a bit much  and hunger goes down quickly

**Comment by ChainedDev** [comment]
Will be looking into re-adjusting values very shortly

**Comment by ChainedDev** [comment]
Made some adjustments to the values of various food/drinks
