### ISSUE TITLE
Gangs

### ISSUE THREAD

**Issue by CREASE-C13** [ChainedDev/CityLife#550]
the wipe was good for everyone it stopped people just coming in and fucking everything up and it's rare to get an ar or any auto which is good I recently joined a gang and every gang is entitled to craft a genre of an illegal item which is good but it's a bit unfair because if a gang war broke out we wouldn't be able to get are hands-on equipment and they would be able to I understand you guys don't want guns to get out of hand like last time but you could set up what the minimum sale of a gun would be to someone or just we can only sell within our gang or to other gangs but I just wanted to clear this out because I think all gangs that are whitelisted should be able to manufacture what all the other gangs can or it just makes the gangs that can make the better stuff becomes more superior which is unfair.

**Comment by TimmyTwoStep** [comment]
Have you heard of gang rp?

**Comment by APOLLO81-C** [comment]
In the Gang Roleplay, players will join together to develop gangs and criminal organizations to compete for turf. ... The objective is to eradicate enemy gangs by killing the enemy leader off and taking over their turf. The winner will be established once all leaders are killed. lol if only 2 gangs in the city have autos hows that supposed to work who are the other gangs going to get their guns off when people are at war
