### ISSUE TITLE
2018 Bentley Continental SS

### ISSUE THREAD

**Issue by MikeGemini09** [ChainedDev/CityLife#552]
**What is the reason for this balance request?**
I just bought this car from Lux. I'm not complaining about buying it and wanting a refund but I do believe the car should be a lot faster. Stock top speed is about 140 mph. Realistically this car is a 6.0 V12 and has 700 Hp. This car should be close to 200 mph top speed it is also $360k with gold citizenship in game so it should be at least close to speed of the cars in that price range.

**What solution would you like?**
Raise the stock max speed closer to 200 mph

**Additional context**
Acceleration isn't too bad for this car but could be a little higher but that isn't a huge issue

**Comment by APOLLO81-C** [comment]
that's what I said it's still way to slow even when upgraded
