### ISSUE TITLE
Radio Animations & Radio Filter

### ISSUE THREAD

**Issue by NetworkParadoxx** [ChainedDev/CityLife#553]
**Is your feature request related to a problem? Please describe.**
Radio Animations will make it so it's known when someone is using their radio realistically, rather than hotmicing unrealistically to call their friends. Radio Filter is just aesthetic.

**Describe the feature you'd like**
When someone uses a radio, it will play the /e radio animation for the duration the keybind is held down. While talking on the radio, it should also have a filter when others speak to provide a more immersive experience.

**Describe alternatives you've considered**
N/A, mostly QOL update.

**Additional context**
Animation used:
![image](https://user-images.githubusercontent.com/63690514/105618036-1ce07a00-5db1-11eb-9961-9bcd22379512.png)

**Comment by Sturdyinnit** [comment]
The animation used to be a thing but for some reason it doesn't work anymore. It's confusing when you're in a group of people and some are using radio without the animation. Should be added back.
As for the audio filter I'm split. It would add notable immersion which is sick, but some people just have horrible mics and a filter will even lower their audio output quality. A slight distortion however wouldn't hurt.
