### ISSUE TITLE
Eclipse Towers

### ISSUE THREAD

**Issue by TimmyTwoStep** [ChainedDev/CityLife#554]
**Is your feature request related to a problem? Please describe.**
No it is not.

**Describe the feature you'd like**

https://www.gta5-mods.com/maps/mlo-rooftop-eclipse-tower

I would like to see this mod used on the server, it could fit in quite well if you ask me. It would be nice to have this open to the public or another alternative is allowing only Diamond supporters, I'm not a D8 or anything, but I'm almost positive no one owns a property Eclipse Towers besides a small handfull, so this seems like a more reasonable choice, a sort of high life to the package.

**Describe alternatives you've considered**
Allow anyone to purchase a property at Eclipse, granting them access to the roof outside of Diamond.

**Additional context**
N/A

**Comment by Cudii** [comment]
As a diamond supporter, a FREE room would be absolutely dope along with this rooftop access. I could only imagine :(

**Comment by APOLLO81-C** [comment]
I agree with Cudii because it was part of the diamond supporter package so if you were to add for everyone to buy the eclipse towers it would be less worth it to get the diamond
