### ISSUE TITLE
Enus Windsor Livery

### ISSUE THREAD

**Issue by Sturdyinnit** [ChainedDev/CityLife#555]
**Describe the bug**
I recently got my hands on a Windsor. After taking it to a mechanic I was surprised to hear that the livery cannot be changed. It is expected to have 9 livery options including a blank canvas, yet we're stuck with the most ugly and obnoxious one, ruining the luxury look of the vehicle.
Is this intended or is this a bug?

**Screenshots**
Screenshot 1: Currently the only livery available (cannot be removed either)
Screenshot 2: The liveries implemented in the base game (Grand Theft Auto Online)

Thank you very much for having a look

![windsor](https://user-images.githubusercontent.com/75695867/105851986-1e45b880-5fe4-11eb-8ab3-56cf80e108ef.jpg)
![liverieswindsor](https://user-images.githubusercontent.com/75695867/105851997-230a6c80-5fe4-11eb-9bf0-6e99f4e012ea.png)

**Comment by JayRusso1** [comment]
Mech here, livery changes based on performance for this vehicle :)
