### ISSUE TITLE
Property entry bug/glitch

### ISSUE THREAD

**Issue by Sturdyinnit** [ChainedDev/CityLife#556]
**Describe the bug**
No names of who you're letting into your house, being able to teleport people.

**How to Reproduce the Behavior**
1. Knock on a door
2. Have the owner accept your entry whenever
3. You're teleported inside no matter how long ago you knocked or where you are, your request does not vanish after being accepted

**Expected Behaviour**
The request should vanish after a certain amount of time.
Name, ID or Steam name should let you distinguish requests.

**Screenshots**
Will send when in city if needed.

**Additional context**
Nil

**Comment by TimmyTwoStep** [comment]
I've had this happen before when i knocked on someone's property as they left and my request stayed, hours later they snter the property and say my request and accepted me in then I got teleported out of my car across the map

**Comment by Dollar82** [comment]
Yes,& if someone leaves before owner,it dosen't kick everyone & owner has to take flight cause their stuck in space,makes it hard to have a house party

**Comment by Sturdyinnit** [comment]
Seems to work now.
Still cannot distinguish who you're letting in but at least the requests dissapear after being accepted. Thank you!
