### ISSUE TITLE
Changing scoreboard

### ISSUE THREAD

**Issue by gavisuprstar** [ChainedDev/CityLife#56]
1) replace steam name with steam 2 id. 
2) adding a colour preference in the scoreboard for admins and above(as shown in attachment)
3) change the design of the scoreboard something like the pic in the attachment.
4) adding recent disconnections in the the scoreboard so people can see who disconnected recently with reason of disconnection.(as shown in another attachment) (may help in combat logging).

![Screen Shot 2020-01-27 at 3 30 27 AM](https://user-images.githubusercontent.com/56530553/73142516-9c137300-40b5-11ea-8c69-6411f2495c28.png)

![Screen Shot 2020-01-27 at 3 35 28 AM](https://user-images.githubusercontent.com/56530553/73142551-1e039c00-40b6-11ea-8708-aec8783c69d3.png)

**Comment by clrpindmanager** [comment]
Much Needed

**Comment by clrpindmanager** [comment]
Also When someone is doing fail rp , a person can submit report through our forums wherein he will be in need of STEAM2ID or Hex ID instead of Steam Name (actually steam name can be changed). with valid Video Proof

**Comment by gavisuprstar** [comment]
https://forum.cfx.re/t/modern-scoreboard-cd-scoreboard-esx-and-warmenu-based/958745

@ChainedDev @gullidog  this may help you guys regarding this, you may need to alter some parts but yea, basic principle of this script is same... i hope you guys will give it a look.

**Comment by gullidog** [comment]
We already have a scoreboard like this?

**Comment by strangeclrpindia** [comment]
This scoreboard is something professional and it provides you steam Id instead of Steam Name. Because anyone can change their Steam name but Steam ID remains the same of any account. so for Staff purpose it would be good
