### ISSUE TITLE
Shotguns on Motorcycles

### ISSUE THREAD

**Issue by MikeGemini09** [ChainedDev/CityLife#560]
**What is the reason for this balance request?**
Realistically if you are riding a motorcycle and try to shoot a shotgun, you will fall off the motorcycle. The other issue with motorcycle and guns is that you can't see when someone has a gun out or not. These are 2 issues that are being taken advantage of and needs to be fixed

**What solution would you like?**
Not able to shoot shotguns off a motorcycle. And show that you are hold a gun if on a motorcycle

**Comment by AnineAhmetovic** [comment]
nah if you do that everyone is gonna sit on a bike and rob you or kill you, and the gangmembers wil be even bigger d*ckheads

**Comment by MikeGemini09** [comment]
@AnineAhmetovic they could already rob and kill you on a bike because they can hold pistols, smgs and shotguns on a bike. You just wont be able to see it until they point it. I'm suggesting to take the shotguns away because this is suppose to be a realistic server and shooting a shotgun off a bike is not realistic at all.

**Comment by HyperSoldier** [comment]
@AnineAhmetovic What are you even saying?  This is to remove shotgun use from motorcycles, not allow it.

Not being able to visually see if someone has a gun ready to shoot provides a huge advantage to people on motorcycles.
