### ISSUE TITLE
Selling to locals

### ISSUE THREAD

**Issue by milanclrp** [ChainedDev/CityLife#562]
**Describe the bug**
[So we all know about the new selling rule, how you have to be very close to the local so you can complete the drug deal. In my case they start running away, I'm also catching up by running right beside the local, but it says "too far away from buyer". ]

**How to Reproduce the Behavior**
Steps to reproduce the behaviour: By freezing the locals when you proceed to sell them something. 

**Expected Behaviour**
[I should be able to sell to the lcoal without it running away which ruins the deal, i cant really sell to the local if they are running away (btw they start running for no reason). ]

**Screenshots**
[dont really have, but it's been happening to everyone]

**Additional context**
[nope]

**Comment by Skader91** [comment]
Locals don't run away from you if you aren't aggressive while approaching them, if you can please prove me wrong by posting uploaded video evidence and we will look into it.
