### ISSUE TITLE
Dark Chat

### ISSUE THREAD

**Issue by CREASE-C13** [ChainedDev/CityLife#564]
Please add dark chat back to the phones

**Comment by TimmyTwoStep** [comment]
I would like to see sim cards more then darkchat

**Comment by MiGrane4Mayor** [comment]
How would sim cards work?

**Comment by TimmyTwoStep** [comment]
Basically SIM card work as they normally would, you could swap them in and out between each other for business if you know what I'm saying.

**Comment by breakdownhxc** [comment]
just bumping to get more info on the progress of this.
