### ISSUE TITLE
Scanning

### ISSUE THREAD

**Issue by CREASE-C13** [ChainedDev/CityLife#568]
when scanning you seem to find nothing when you dig which doesn't make sense because a scanner picks up metal so when you dig you should be bound to find something

**Comment by TimmyTwoStep** [comment]
I agree with you giving you something everytime, because it really doesn't make sense that it would pick something up, but when you dig for it you find nothing. Best way I look at it is I just imagine if I dig a spot and find nothing, its probably just some waste of sheet metal or whatever.

**Comment by CREASE-C13** [comment]
yeah i think you should at least get like an old can or something in that range
