### ISSUE TITLE
DOJ (Department of Justice)

### ISSUE THREAD

**Issue by clrpindmanager** [ChainedDev/CityLife#57]
There should be a Fines/Charges and Jail Time Menu in game developed for cops. So wherein Cops can see their Fine and Jail Time as per the crime committed. You can see examples in the attachments. It will lead to a smooth and realistic Roleplay wherein CLRP can get boosted. Indian Server need it much possibly.
This is also called as DOJ, make some feature that by a keybind or command we can open it

![Screenshot (1090)](https://user-images.githubusercontent.com/60332040/73145344-1dc5c980-40d3-11ea-87e6-cc8358113882.png)
![Screenshot (1089)](https://user-images.githubusercontent.com/60332040/73145345-1dc5c980-40d3-11ea-9dec-ff3a3d13210b.png)
![Screenshot (1088)](https://user-images.githubusercontent.com/60332040/73145346-1dc5c980-40d3-11ea-99f5-05fc535628dc.png)

**Comment by gavisuprstar** [comment]
This will be so handy for sasp
