### ISSUE TITLE
the double barrel/motorcycle

### ISSUE THREAD

**Issue by xEloez1** [ChainedDev/CityLife#571]
the double barrel/motorcycle meta is wayyy to op 

**What solution would you like?**
[remove shooting shotguns pistols from cars and motorcycles!**]

**Additional context**
[my capture recorded the second monitor. ****]

**Comment by josefsufaj** [comment]
from cars? tf r u smoking

**Comment by JimSteel1** [comment]
I fully agree with you on taking the shooting on a bike away, as of right now everyone is on a bike with shotguns. I think that it is fine to shoot in a car. Especially in a car because you have to look in first person, bikes you don’t. I say keep car shooting take the bike shooting out.
