### ISSUE TITLE
Banks,Bank trucks,Stores

### ISSUE THREAD

**Issue by CREASE-C13** [ChainedDev/CityLife#573]
if I got to be honest when acquiring things for the bank which I'm not going to say but when you pull off a bank truck or even a bank the payout is way too little I hit a bank truck and got away with it and only got 8000 dirty and some other things which were good but the payout should definitely be much more especially for banks even stores you get 1 to 4k dirty for cracking a safe it should be at least 10k dirty.

**Comment by Chainedster** [comment]
Can you please explain this more thoroughly so I can understand exactly what you're wanting to be buffed

**Comment by CREASE-C13** [comment]
The amount you get from bank trucks banks and stores etc
