### ISSUE TITLE
Weed rework

### ISSUE THREAD

**Issue by pap340** [ChainedDev/CityLife#574]
**Is your feature request related to a problem? Please describe.**
No problem with weed.

**Describe the feature you'd like**
To add different strains. And i see soon we can plant on our own. But do not allow people to plant in their home.

**Describe alternatives you've considered**
Maybe make the regular weed spot low grade weed and add another spot of picking that gives you random chance for different strains. Or add a weed shop that sells seeds for different strains. Maybe even make these unmarked locations.

**Additional context**
Its just to make the weed more popular because other drugs are being used way more.

**Comment by CREASE-C13** [comment]
maybe not strains so much but the low-grade medium grade and high-grade weed and obviously high-grade makes more money medium is average and low grade is a low amount of money and maybe if you would really like different strains then smoke on the water should sell them
