### ISSUE TITLE
Contender performance issues 

### ISSUE THREAD

**Issue by Avotic** [ChainedDev/CityLife#577]
**What is the reason for this balance request?**

The Vapid Contender is modeled after a toyota tundra devrolo diablo edition, the toyota tundra boasts a 350 hp V8 with a top speed of 110.  With the custom devrolo diablo body kit and engine upgrades this brings the truck to about 530hp going 0-60 in about 6 seconds.  The acceleration for the truck is on point, but the top speed is very lack luster for a smaller truck boasting over 500 hp and I'd really like to see a bump up to about 135-140.  It's a high powered custom edition off road vehicle and I'd really like it to reflect that.  Thanks.
**What solution would you like?**
I'd really like to see this truck running true to its likeness.

**Additional context**
N/a

**Comment by Forkedup** [comment]
Adjusted the handling
