### ISSUE TITLE
Office space 

### ISSUE THREAD

**Issue by Wassupmarcus** [ChainedDev/CityLife#578]
**Is your feature request related to a problem? Please describe.**
My current issue is the fact I paid like 125k for an Office that has very little storage I feel as if it should have more due to the cost of it.

**Describe the feature you'd like**
All I would like is like  3-5 more rows of storage would seem fair, where I could have more storage to store my belongings without getting them stolen.

**Describe alternatives you've considered**
I've considered buying cars but I've already bought the office so it would just be like I'm wasting my money after I had already bought a 125 thousand dollar office. 
**Additional context**
I'm not asking for much and to be completely honest I don't think many other people have an office that's why I believe it should be more so more people will purchase one.
Thank you, Marcus Fields

**Comment by MiGrane4Mayor** [comment]
Although i might understand where your coming from, i disagree.125k for a store is actually very very cheap. Commercial property retails for a lot more than that after the Jan 15 update of storage which leads me to believe you purchased this A LONG LONG LONG time ago. The starting price is over 200k now, And holds 25 for the most expensive one (Storage became a commodity). Storage is Only part of the appraisal as well. Location, sq footage of building, amenities, all get taken into consideration.
