### ISSUE TITLE
/admin command needs Upgrade

### ISSUE THREAD

**Issue by clrpindmanager** [ChainedDev/CityLife#58]
There should be a special command for /admin wherein admins can spectate people and inspect them for any fail rps. Also teleport player, slap player must come in the same /admin command as shown in the attachment
![Screenshot (1094)](https://user-images.githubusercontent.com/60332040/73145556-38e50900-40d4-11ea-929d-de75bd3a860b.png)
![Screenshot (1093)](https://user-images.githubusercontent.com/60332040/73145557-38e50900-40d4-11ea-8dfc-0bf39dd9e645.png)
![Screenshot (1092)](https://user-images.githubusercontent.com/60332040/73145558-38e50900-40d4-11ea-9bcf-a24181a70d7f.png)
![Screenshot (1091)](https://user-images.githubusercontent.com/60332040/73145559-38e50900-40d4-11ea-83bc-7d4ec39719dc.png)

**Comment by yggun** [comment]
lmao

**Comment by gavisuprstar** [comment]
The name of this script is Easyadmin and canbe easily findout on fivem forum... below is the link of this script
 https://forum.cfx.re/t/release-easyadmin-its-as-easy-as-it-gets/42245

**Comment by gullidog** [comment]
Hi, thank you for the suggestion. However, we already have this menu implemented in game for staff.
