### ISSUE TITLE
Mechanic/Tow & Taxi App on Phone

### ISSUE THREAD

**Issue by Polaris1777** [ChainedDev/CityLife#582]
**Is your feature request related to a problem? Please describe.**
The problem is that people have no way to contact roadside mechanics or towing services, nor to contact a taxi or anything without using twitter or something. This leads to more broken cars on the road and more theft of local vehicles.

**Describe the feature you'd like**
Add an app on your phone to contact Mechanics and Taxi where they can message you back.

**Describe alternatives you've considered**
/mechanic and /taxi command perhaps

**Additional context**
N/A

**Comment by Chainedster** [comment]
👍
