### ISSUE TITLE
Double Barrel Shotgun Damage

### ISSUE THREAD

**Issue by milanclrp** [ChainedDev/CityLife#583]
**What is the reason for this balance request?**
[You guys nerfed the double barrel shotgun damage to the point where it makes no sense]
**What solution would you like?**
[Make it a resonable 2 shots to the head, not 6]

**Additional context**
[ I shot him close up 6 times and he managed to run away, which makes no sense ]

**Comment by CREASE-C13** [comment]
I don't care who is downvoting this a shotgun up close does not take 6 shots to the head to kill someone IRL so why should it in city life I think the double barrel on a bike yes that's op as fuck but ground to the ground that's what it should be
