### ISSUE TITLE
Enhance Doctor Roleplay

### ISSUE THREAD

**Issue by strangeclrpindia** [ChainedDev/CityLife#59]
To enhance EMS Roleplay and Especially Doctor, we need treating injuries animation of the patient on the bed. A place wherein Doctor can sign in specially for surgery and can treat patients until he is sign off from surgery duty. 

Must watch the attachment: https://youtu.be/FWwOR_ItYD8

**Comment by gullidog** [comment]
This is something you can roleplay yourselves as EMS.
