### ISSUE TITLE
Too many cars, cant race

### ISSUE THREAD

**Issue by gamerdude23** [ChainedDev/CityLife#591]
**Is your feature request related to a problem? Please describe.**
It is some what of a problem, there are way too local cars and makes it too hard to race here. If this spot had less local cars driving, it could be a popular racing spot and give the city a larger racing scene. 

**Describe the feature you'd like**
Have less or no cars there, would make racing there competitive and fun.

![](https://i.gyazo.com/23304412a00edce516370b49ff871932.png)

**Describe alternatives you've considered**
Not a lot of good racing spots with a lot of turns in the city. 

**Additional context**

![image](https://user-images.githubusercontent.com/75970972/109080069-c8346580-76b4-11eb-9641-681abc7415fe.png)

**Comment by Chainedster** [comment]
drive safer
