### ISSUE TITLE
Gang areas

### ISSUE THREAD

**Issue by AnineAhmetovic** [ChainedDev/CityLife#599]
**Is your feature request related to a problem? Please describe.**
[It would be cool if you entered a zone that is owneed by a gang that it would pop up on yout screen]

**Describe the feature you'd like**
[for example when you drive into a area it pops up and says ''you entered the sick car gang zone'']

**Describe alternatives you've considered**
[and gangs could take over the locations and maby buy houses there for cheaper or they get more money when selling weed in that area]

**Additional context**
[Add any other context or screenshots about the feature request here. **Remove this line!**]

**Comment by JimSteel1** [comment]
Then it takes away the RP of finding were what gang claims. In real life there’s no notification on your phone that pops up saying your in TC zone or GSM zone.

**Comment by AnineAhmetovic** [comment]
then they could make it that you discover it or have to name it when you find out, so when you start the areas are just blank

**Comment by MiGrane4Mayor** [comment]
This is a great idea! For gtav online
