### ISSUE TITLE
Need record of Duty Hours for to see Activeness of SASP and EMS

### ISSUE THREAD

**Issue by clrpindmanager** [ChainedDev/CityLife#60]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
Whenever EMS and SASP went ON-DUTY or OFF-DUTY, there must be a record of the timestamp log on Discord Server wherein it will clearly mentioned that the person went on-duty at what time and went off-duty at what time ! It would be quite interesting and this timestamp should be only be visible for FTOs, High Command and Admins, because it can help them for Promoting the active ones and Demoting the Inactive ones. Please consider this idea because it can get boosted the CityLife Roleplay Servers and especially India.

**Describe alternatives you've considered**
IDK

**Additional context**
I am sending an attachment wherein you can see how timestamp works!!!
![Screenshot (1086)](https://user-images.githubusercontent.com/60332040/73219451-288b6780-4182-11ea-85f1-8e80346dd5e7.png)

**Comment by gavisuprstar** [comment]
@ChainedDev @gullidog for this, the following link of the script may help you, this script also has the tracker system it it, so you guys need to see if it can help....

**Comment by Droshky** [comment]
bump, should be very simple to do. I would enjoy having this as well.

**Comment by gavisuprstar** [comment]
@ChainedDev @gullidog for this, the following link of the script may help you, this script also has the tracker system it it, so you guys need to see if it can help....

https://forum.cfx.re/t/release-policeemsactivity-emergency-blips-script/935188

**Comment by ChainedDev** [comment]
<https://chained.pw/imgs/idrde.png> -- Already Exists
