### ISSUE TITLE
Buff the elegy 

### ISSUE THREAD

**Issue by gamerdude23** [ChainedDev/CityLife#600]
**What is the reason for this balance request?**
An upgraded elegy retro can be beat by a stock e36

**What solution would you like?**
Increase top speed of the elegy,. 

**Additional context**
Elegy is sold for a lil over 80k, and mine is upgraded, the e36 stock is 75k. maybe nerf the e36 top speed?

**Comment by Forkedup** [comment]
Thank you for the suggestion, after reviewing I made some tweaks to both the Elegy and Elegy Retro

**Comment by AnineAhmetovic** [comment]
what did u change if i may ask

**Comment by Forkedup** [comment]
Slight changes to the top speeds of both
