### ISSUE TITLE
auto engine 

### ISSUE THREAD

**Issue by AnineAhmetovic** [ChainedDev/CityLife#606]
**Is your feature request related to a problem? Please describe.**
[make it when you leave your car that it doesnt just automaticly turn off]

**Describe the feature you'd like**
[so that you have to manualy turn off your car, because soemtime i just want to chill and have the car radio on while im outside of it, or when ur in a car meet you want the underglow on.]

**Describe alternatives you've considered**
[What alternatives solutions have you considered? **Remove this line!**]

**Additional context**
[Add any other context or screenshots about the feature request here. **Remove this line!**]

**Comment by Chainedster** [comment]
Hold F kek
