### ISSUE TITLE
Car Robbing Must be Fix, it takes hour to rob a car

### ISSUE THREAD

**Issue by strangeclrpindia** [ChainedDev/CityLife#61]
Please make some changes in robbing a car. Its very difficult to rob a car when you are new to the city or playing as new character.
Do make change like the below attachment and video link I shared wherein the person gun-points towards the car , civilian gets out of the vehicle and drop the keys to the person and leave.

Its much needed especially one of the favourite of Indian Subcontinent , because they'll get bore to s

https://drive.google.com/open?id=1KjRS-aNu6darINc5GuAZk_YylfQhrE0W

![Screenshot (1133)](https://user-images.githubusercontent.com/60332040/73302000-e6bdf800-4239-11ea-85c2-3b4c773d34fc.png)
earch a vehicle properly

**Comment by gullidog** [comment]
I see what you mean sort of, the only problem with this idea is new players won't have a gun?
