### ISSUE TITLE
Casino!!!!

### ISSUE THREAD

**Issue by Cucumba18** [ChainedDev/CityLife#612]
**Describe the feature you'd like**
A casino either run by trusted and OG players or run by staff to make it fair and not corrupt. Roulette table, blackjack, a bar and a reward wheel! You could do certain events and different rewards if you spend so much $$ within the casino. Another idea is that you could wash money within the casino too. Instead of the jobs where you have to go see a guy or go into the washing place, you could put dirty money down on a table and come out with clean money. 

**Describe alternatives you've considered**
Back of the shop or secret gambling rooms that you need connections to know about, police could raid if they know the location and times but someone would have to snitch to have that info.

**Comment by Chainedster** [comment]
Finally we have it!
