### ISSUE TITLE
Update the confirmation code more frequently

### ISSUE THREAD

**Issue by YoungArtorious** [ChainedDev/CityLife#613]
I believe that the CL confirmation code should be updated on a more frequent basis. I think updating the CC more often will benefit CL as a whole because it will force people to read the rules more often and it can help improve RP as a whole. The only drawback I see from doing this would be an increase in people asking other players for the CC when it does get changed. Doing this would be a huge change for the city, and I imagine the logistical side of things for this would be a lot to handle. But I think this change would improve the overall RP of the city.

**Comment by Chainedster** [comment]
One's coming real real soon 😉 

Gonna go ahead and close this for now
