### ISSUE TITLE
Supporter Car Showcase Bug ! Need to be FIXED ASAP Please !

### ISSUE THREAD

**Issue by clrpindmanager** [ChainedDev/CityLife#62]
**Describe the bug**
Near the Support Vehicle Purchase Shop, there's a bug that after sometime Car-View turns into a bug wherein We cannot see car properly, so this might take a negative effect on the Supporters Perks. 

**Expected Behaviour**
Actually there should not be such glitch shown in the attachments. Cars should be seen properly, please remove the bug

![vlcsnap-2020-02-01-21h13m25s720](https://user-images.githubusercontent.com/60332040/73594852-318c8800-4538-11ea-8713-01e6f5c9fdb6.png)
![vlcsnap-2020-02-01-21h13m42s422](https://user-images.githubusercontent.com/60332040/73594853-32251e80-4538-11ea-852c-8d2f8ef71a0f.png)
![vlcsnap-2020-02-01-21h13m48s004](https://user-images.githubusercontent.com/60332040/73594854-32251e80-4538-11ea-8cd8-09ff19f4d97b.png)

**Comment by gullidog** [comment]
Hi! Thank you for the report. However, I was not able to re-create this bug? It might be due to poor ping or connection. Would love some additional information so I can look further into this!

**Comment by clrpindmanager** [comment]
gullidog please watch this : https://youtu.be/pMUcdbVcBp4

**Comment by clrpindmanager** [comment]
Every Time I re-connect the city, I would get the same output
bug

**Comment by gullidog** [comment]
This seems to be an issue on your end, try lowering you graphic settings or upgrade your PC specs. Have a good day!

**Comment by clrpindmanager** [comment]
Ok thanks, will try in lower graphics
