### ISSUE TITLE
make actions change keybinds

### ISSUE THREAD

**Issue by lemonjezus** [ChainedDev/CityLife#620]
**Is your feature request related to a problem? Please describe.**
some commands like the radio talking one is just at the wrong place

**Describe the feature you'd like**
being able to change some actions you do to other keybinds

**Describe alternatives you've considered**
none

**Additional context**
if you're used to a certain city and ud like to have the same keybinds just being able to change them would be nice

**Comment by Chainedster** [comment]
Settings -> Keybinds -> FiveM -> Yeet
