### ISSUE TITLE
Buff Sultan RS Super Top speed

### ISSUE THREAD

**Issue by kimoo77** [ChainedDev/CityLife#622]
**What is the reason for this balance request?**
The Sultan needs a Buff to its top speed 150 to 160 aint it.

**What solution would you like?**
I would like the Sultan to get a higher Top speed Maybe 180 to 190 or 170 to 180 that would be very much appreciated and would make me use this car more and more.

**Additional context**
None

**Comment by Forkedup** [comment]
Slightly modified the Sultan RS's top speed
