### ISSUE TITLE
investment bank account

### ISSUE THREAD

**Issue by lemonjezus** [ChainedDev/CityLife#624]
**Is your feature request related to a problem? Please describe.**
no

**Describe the feature you'd like**
a seperate account in your bank you could add an amount that would get investment overtime. like a "savings account"

**Describe alternatives you've considered**
none

**Additional context**
with that account ud put a certain amount and youd be locked out of your money for maybe depending on the percentage of interest you gain you gotta keep it in for 1-7 days and the money would stay locked in there untill its over and then the money would get automatically transferred into your basic "checking account"

**Comment by Forkedup** [comment]
This is a fairly common requested feature, and to me it's just asking for free money. I do understand that the money would be locked, but to me it feels too easy.

#BITCOIN

**Comment by lemonjezus** [comment]
> This is a fairly common requested feature, and to me it's just asking for free money. I do understand that the money would be locked, but to me it feels too easy.
> 
> #BITCOIN

to me its just another game feature that could be fun playing with because most of what i see is drugs and legal jobs but what about cyber stuff ynow or like a casino too
