### ISSUE TITLE
Courthouse

### ISSUE THREAD

**Issue by gavisuprstar** [ChainedDev/CityLife#63]
**Describe the bug**
[A clear and concise description of what the bug is. **Remove this line!**]
There is no way out from the courthouse. Once people goes in the courthouse, they stuck

**How to Reproduce the Behavior**
Steps to reproduce the behaviour:

**Screenshots**
[If applicable, add screenshots to help explain your problem. **Remove this line!**]

**Additional context**
[Add any other context about the problem here. **Remove this line!**]
You can make way out or dimply dont make way in

**Comment by ChainedDev** [comment]
In progress of fixing courthouse, sorry for it imprisoning whoever goes in, please be cautious and don't enter until fixed

**Comment by ChainedDev** [comment]
Added in latest updates
