### ISSUE TITLE
Bike NERFS

### ISSUE THREAD

**Issue by ghost** [ChainedDev/CityLife#631]
**What is the reason for this balance request?**
Bikes are too strong. Period, any sort of chase ends with the bike being able to be gone in a matter of seconds with extreme speeds with very easy turning. The BMW is hands down the most commonly used bike for crimes and makes it near impossible to chase said bike in any sort of police chase or even gangs...

**What solution would you like?**
To have all the bikes handling reduced.. OR (AT LEAST THE BMW BIKE) If there is already handling on these bikes it needs to be even more nerfed as its ridiculous to even deal with anymore.

**Additional context**
Bikes too op.. need nerfs.. all you see in city rn is bikes bikes bikes with nothing but gun fire surrounding them. It's boring to deal with and nothing can really be done to deal with it either, ramming them isnt even allowed, so in order to catch them they literally have to crash which is very unlikely with the current state of them.

**Comment by MatthewHall-Basic** [comment]
I contradict that, and think there should be bike police. the bike speeds and handling are for the most part pretty legit. plenty of crimes are committed all over using bikes for the exact reason of mobility and speed.
