### ISSUE TITLE
BMW M5 Buff?

### ISSUE THREAD

**Issue by AwknEU** [ChainedDev/CityLife#633]
What is the reason for this balance request?
I believe that the M5 should be buffed a little as when it is maxed it goes 150-155, before i test drove the car... as it was 200k i thought it might have been a bit faster, especially just cruising however was fairly disappointed when the car was slower than a maxed elegy retro (which is 80k stock).

**What solution would you like?**
A buff to the BMW M5, i believe the handling on the car is good however a few tweaks to top speed in my opinion should be changed.

**Comment by Forkedup** [comment]
I re-balanced the car after noticing an issue, please let me know how it performs post buff.

**Comment by AwknEU** [comment]
Still cruising around 135, ifeels slightly better however still believe the 80k Elegy Retro is faster ;/

**Comment by Forkedup** [comment]
135?

**Comment by AwknEU** [comment]
yessir.
