### ISSUE TITLE
Gun Shot Residue 

### ISSUE THREAD

**Issue by JimSteel1** [ChainedDev/CityLife#634]
**Is your feature request related to a problem? Please describe.**
I would like there to be a way to wash Gun Shot Residue off yourself

**Describe the feature you'd like**
I would like a way to go into an open body of water and or a house with a bathroom and be able to wash the Gun Shot Residue off your skin.

**Additional context**
This would make better RP for people to have to run and hide to wash it off the Gun Shot Residue.

**Comment by CreepyEK** [comment]
It's not as easy as that to "wash" GSR, it'll be all over you, on your clothes and everything, not just your hands. Water is not good enough to get rid of GSR.
