### ISSUE TITLE
EMS/Police should get priority

### ISSUE THREAD

**Issue by MottyOG** [ChainedDev/CityLife#636]
**Is your feature request related to a problem? Please describe.**
 Yes, the lack of EMS and Police that are on the server really makes the playing experience sometimes a pain.

**Describe the feature you'd like**
EMS and Police are whitelisted jobs, you have to be around for awhile before you can even get onto either force, they should receive priority into the server.

**Describe alternatives you've considered**
An alternative would be to making them something like gold priority, however, I believe they need it in some way shape or form.

**Additional context**
By giving priority to EMS and Police the playing experience on the server would improve greatly.

**Comment by Dollar82** [comment]
Can't,they usually have multiple characters,so if they have priority they could select another character besides ems/pd

**Comment by MottyOG** [comment]
> Can't,they usually have multiple characters,so if they have priority they could select another character besides ems/pd

Quite frankly, it shouldn't matter in my opinion...if you are accepted into a whitelisted job, you should have priority to get into the city.

**Comment by Dollar82** [comment]
It should matter,if you're ems with priobut never go on your eme,get it now?

**Comment by MottyOG** [comment]
> It should matter,if you're ems with priobut never go on your eme,get it now?

that can be tracked and handled if abused...
