### ISSUE TITLE
Add An Item To Change Clothes With

### ISSUE THREAD

**Issue by BenjamillionBillion** [ChainedDev/CityLife#637]
So currently the only way to change your clothes would be at a house, which makes sense. So if people are “homeless” you can add an item that’s acquired by “doing laundry” or from searching trash or something. or even just buying the item from a clothing store. But when this “Clothing” item is used, it brings up the outfit menu.

**Comment by Chainedster** [comment]
Maybe when you take your mask of it'll give you a item to use to put it back on
