### ISSUE TITLE
Buff Jugular Top Speed & Trunk

### ISSUE THREAD

**Issue by Doxified** [ChainedDev/CityLife#638]
**What is the reason for this balance request?**
The Jugular needs a buff to its top speed as it's **150 - 160** **maxed out**. The car also deserves more storage, the BMW 5 has two rows of trunk space at the same price of $200k.

**What solution would you like?**
I would like to see the Jugular get a top speed buff to at least 180 or higher, and at least to be considered with 2 rows of trunk space versus the 1 it currently has, upgrading the car to max it out does completely nothing other than to hit 160 slightly quicker which is depressing considering the price tag and performance to such. 

**Additional context**
The car stock is the same as if it was completely maxed out.

**Comment by Forkedup** [comment]
Adjusting top speed/acceleration.

Keeping trunk space the same.
