### ISSUE TITLE
Character Switching

### ISSUE THREAD

**Issue by clrpindmanager** [ChainedDev/CityLife#64]
Actually we should have a location wherein we can Switch Characters and don't need to Re-connect the server. Like most of the servers have a location called as Train Station wherein people can Switch their Characters, so if this implemented, will be a great thing.

**Comment by gavisuprstar** [comment]
Yeah at train station infront of job selector, it will be better to add where pressing E will load back to the character selector page, that will be handy

**Comment by ChainedDev** [comment]
Will be a thing when we redo our character system, down the road feature not anytime soon
