### ISSUE TITLE
/boss and more for business owners

### ISSUE THREAD

**Issue by ThomasBonelli** [ChainedDev/CityLife#640]
In this server there is very little player interaction at stores and business.

Make it to where all player owned businesses have a /boss menu and some way to make passive income. I think this would help with the current problem in this server where you are almost forced to be a criminal because the lack of worth doing legal jobs.  

If this is not possible because this would have to be coded, I think all business should at least have a /boss menu so that they can hire people and have a way to separate there business funds from personal funds.

**Comment by ThomasBonelli** [comment]
The income does not also have to be passive. For example, having operable cash registers for 24/7's and restaurants. Passive income would be easiest to set up for all types of businesses though.

**Comment by Chainedster** [comment]
This would mostly be for whitelisted jobs that have an interior/actual business with them
