### ISSUE TITLE
Lawyer question channel

### ISSUE THREAD

**Issue by PraeJaeger** [ChainedDev/CityLife#643]
**Is your feature request related to a problem? Please describe.**
Too many people are talking in the looking for lawyer channel in the discord, this isn't normally and issue but it muddles down the response time to people who are simply looking for a lawyer. 

**Describe the feature you'd like**
I would like to see a separate channel in the discord for people to talk about the DOJ or ask simple questions to the DOJ members. 

**Describe alternatives you've considered**
Creating a google survey for people to send in requesting a lawyer, this would also help the DOJ members decide which cases they would like to take on and give them more background on cases they are about to take on. 

**Additional context**
N/A

**Comment by MiGrane4Mayor** [comment]
If I'm understanding correctly, and to be clear I'm not even doj, but that sounds like ic issues which you could/ have to handle IN character IN the city. No need for people to talk ABOUT the DOJ. When they can just talk TO DOJ. Lawyers always have to have the right of privacy when it comes to their cases, this is counter productive to that standard. For example, would you want troopers, and even the District attorney seeing everything your admitting to on a public IC server? How would they ever be able to represent you, when publicly in character you just admitted to the crime they charged you for.
