### ISSUE TITLE
GoodFellas M4

### ISSUE THREAD

**Issue by suffer1000** [ChainedDev/CityLife#645]
This bmw sounds like a mustang. Everyone who has one and I would like for it to go back to the original sound. which sounded like a urus.

**Comment by Forkedup** [comment]
The original sound was deleted.

Is there any other sounds that you can think of that you guys enjoy? Let me know and I can swap it out for you.

**Comment by suffer1000** [comment]
One that sounds like a bmw. If it is possible you put the sound on demons car which imo sounds the closest, if not the urus sound. either of those 3 is good

**Comment by suffer1000** [comment]
his lykan*

**Comment by suffer1000** [comment]
are any of these possible? if not, sounding like the m5 would be nice too.

**Comment by Forkedup** [comment]
Will change it to that, effective next restart.
