### ISSUE TITLE
Lamborghini LP700

### ISSUE THREAD

**Issue by suffer1000** [ChainedDev/CityLife#646]
The LP700 should be faster, it is very slow for the car it is. it should be the speed of the gallardo if anything. But it is slower, more expensive and realistically should be quite faster than it is

**Comment by Forkedup** [comment]
Can I have some information on top speed cruising, etc?

Thank you

**Comment by suffer1000** [comment]
LP700 cruises at like anywhere between 175-185, and like 210 into the city, and the gallardo goes like 245 into the city and way better acceleration.

**Comment by Forkedup** [comment]
Okay, into the city is irrelevant as you reach that speed for 10 seconds.

Cruising speed / acceleration is what I'm interested in. Thank you for the feedback

**Comment by suffer1000** [comment]
perfect. what i meant by into the city is like that’s the highest speed it could reach, and that’s going into the city so driving normally isn’t possible to reach it

**Comment by Shadi1998** [comment]
the lambo still the same speed

**Comment by Forkedup** [comment]
> the lambo still the same speed

Will be updated in around 6 hours
