### ISSUE TITLE
Selling

### ISSUE THREAD

**Issue by Doxified** [ChainedDev/CityLife#650]
**What is the reason for this balance request?**
It makes no sense for selling smelted items from ore to be instant, and for others such as packaged pigs, caught fish, and how other things aren't instant money into your pockets.

**What solution would you like?**
Balance/change how fish, smelted ore, and pigs, and other items and jobs are sold and how the money is to come into your pocket. For example, selling packaged pig takes forever, and I mean forever, selling smelted mined items is instant and just makes no sense that everything else isn't like that.

**Additional context**
It would be amazing to see this come out or even looked at or given some sort of attention for this to happen before the big update comes out as it's game-breaking and very frustrating.

**Comment by Chainedster** [comment]
Wow, you read my mind on this one. I've been working on a standalone system that can be used for everything described above across all jobs which will make everything more uniform and balanced time wise. Gonna close this as I've already been working on it and haven't even seen this suggestion
