### ISSUE TITLE
PD Shotgun 

### ISSUE THREAD

**Issue by Dollar82** [ChainedDev/CityLife#651]
**What is the reason for this balance request?**
[PD shotgun is not strong enough, guess it got buffed with the double barrel]

**What solution would you like?**
[A soulution would be bring in a different shotgun for PD]

**Additional context**
[Everyone knows the shotgun not good anymore so they just run up on you with a melee,PD need somethingto knock'em back a little]

**Comment by ghost** [comment]
PD needs more attention throughout everything. 

All these NON cop cars keep getting speed BUFFS and they overlook PD cars too. PD cars cannot even keep up with half the vehicles in the city. 

Guns are an issue as well. Glock is a pea compared to Class 2 weapons. AP pistol literally 2 hits you full body armour. 

Cops should be able to shoot from a moving vehicle or something to counter this a little more no matter the driving speed. 

There's just a bunch of shit the PD is currently lacking on that keeps getting piled on top off.

**Comment by ghost** [comment]
Also in regards to vehicles this is literally the same with our Speeder unit. Our Speeder unit is literally a potato unit that tops at 160-170 and slides all over the place, again compared to most CIV cars and high end cars that people seem to do crime in, the speeder unit can't even keep up lmao.
