### ISSUE TITLE
200 SLOTS

### ISSUE THREAD

**Issue by scott9-9-9** [ChainedDev/CityLife#653]
push the server too 200 slots as there is a 50+ queue every night

**Comment by Forkedup** [comment]
Increasing the capacity of the server by any amount has drawbacks.

We of course have plans for expansion, but it has to be done in increments to assure solid performance and correct optimization as it grows.

**Comment by vaillant0** [comment]
I think this is a great idea. but I think it will open the doors to more rule breakers. I think if it’s to the point of like 100 person que maybe increase to like 175.

**Comment by AnineAhmetovic** [comment]
im gonna make it simple, more slots=more lag
