### ISSUE TITLE
You can have more than 2 jobs

### ISSUE THREAD

**Issue by vaillant0** [ChainedDev/CityLife#656]
**Is your feature request related to a problem? Please describe.**
So I recently got a job mechanic and had an opportunity open at PDM as well. sadly I'm gonna have to reject the job. I know you could be a mech and be a ems or cop. 

**Describe the feature you'd like**
That people can at least have more than one job, instead of being a mech and a cop, make it where people can be a mech and D8 or D8 and PDM. 

**Describe alternatives you've considered**
alternatives is that people have to wait a week or two weeks to apply at another job.  or open it up where you can get two jobs. 

**Additional context**
 if accepted, I think it should come in play after the update

**Comment by xrowdydawy** [comment]
You can have multiple jobs at once just on different character. I am pretty sure that people who are mechanics and cops have two separate characters.
