### ISSUE TITLE
BMW M5 Speed Buff

### ISSUE THREAD

**Issue by Doxified** [ChainedDev/CityLife#659]
**What is the reason for this balance request?**
The car is 200k, and cruises at 135, it used to cruise at, at least 150 which is a huge downgrade.

**What solution would you like?**
At least buff it or fix it so it's not so slow. This car has a lot of potentials but isn't as enjoyable as it could be. I feel like a BMW should at least live up to it's name or at least be somewhat decent and not pure shit.

**Additional context**
The car looks amazing and drives as such as well, just doesn't feel luxurious if it's a slow piece of garbage.

**Comment by Forkedup** [comment]
How does it feel after recent changes?

**Comment by Doxified** [comment]
> How does it feel after recent changes?

Although the buff was an improvement, the car still isn't worth it when compared to a Jugular. The Jugular hits nearly 180-200 on the highway with 2 people inside of the car. I feel there should be some sort of standard for the cars that cost and are actually worth 200k. I feel like there should be a standard for speed when the car costs around 200k if not more. I understand the cars aren't all about speeds and mainly for looks, but a name-brand BMW car should be quicker than an off-brand or at least as quick.

The BMW M5 speed of 150 is kinda sad, let alone someone who looks to purchase a nice car to get let done that it is slow as shit. You can figure out some sort of balance for the car, and or a buff to the acceleration or a top speed buff.

**Comment by TrooperJoe** [comment]
Jugular needs a nerf. Was chasing it the other day and it was hitting 190.

**Comment by Doxified** [comment]
> Jugular needs a nerf. Was chasing it the other day and it was hitting 190.

It doesn't need much of a nerf, the car breaks down fairly easy so it kinda makes up for it but, I feel it should be nerfed slightly, but nothing big.

**Comment by TrooperJoe** [comment]
The fastest police car goes just over 190. A 4 door car that cost 200k should not go that fast IMO

**Comment by Doxified** [comment]
> The fastest police car goes just over 190. A 4 door car that cost 200k should not go that fast IMO

If you feel the police cars should go quicker then make the proper suggestion about it, every single update/change is usually in more favor of the police than the criminals in most situations if not all.

**Comment by TrooperJoe** [comment]
I’m fine with the speeds of police cars. That is why I suggested a nerf on the jugular. There aren’t any other cars in that price range that hit those speeds.

**Comment by Doxified** [comment]
> I’m fine with the speeds of police cars. That is why I suggested a nerf on the jugular. There aren’t any other cars in that price range that hit those speeds.

The dodge demon is 175k, and with a 2 door, it hits 180 stock, and 210 maxed out.
