### ISSUE TITLE
Sultan RS Acceleration, Top speed and Handling 

### ISSUE THREAD

**Issue by kimoo77** [ChainedDev/CityLife#660]
**What is the reason for this balance request?**
The Acceleration on the Sultan is not that good, Would like to have a way more faster acceleration on the car and maybe a little buff on its speed also the Handling is a little stiff so would like it to be a little more easier to turn.

**What solution would you like?**
Making the Acceleration faster than what it is and buff the top speed a little more and make the handling easier than what it is.

**Additional context**
Nope.

**Comment by AnineAhmetovic** [comment]
its a sultan rs, not a lambo?
