### ISSUE TITLE
City Life RP

### ISSUE THREAD

**Issue by CREASE-C13** [ChainedDev/CityLife#662]
this server has been great for a lot of people but all the OGS are leaving I mean you can leave your server off people coming and going but you may know that a lot of people just leave after 4 months because they realize whats wrong obviously you can delete this but this is just the truth

1. Stop letting people pay for their shit just ruining it for other people like if you have to pay for your weapons, yeah you might be earning money but think if people like me are sick of it there going to cancel their queue priority and you are going to lose more money
2. Whitelist I understand that this has been spoken about a lot and just gets thrown out the window again because of money like there's so many ways to earn more money and have better RP pay for whitelist apps or fucking just make a whitelist server and keep the main cities up for new people 
3. upgrades the actual server physically is outdated and makes peoples game lag like fuck you could actually invest in a server to make it better like you cant add a casino because it's so outdated and I don't know post on fiver or something to get your own scripts or find a professional that's what no pixel did and look at them its just the simple fact that if stuff doesn't change in the future this server will die and most people will leave

**Comment by uwuowox** [comment]
While I agree 100% with this post; there are a few things that need highlighting.

1. "Paying for shit" - This shouldn't be happening in the server AT ALL as this conflicts directly with FiveM TOS and as such will have the server closed down. Anything offering "monetary services" for in-game benefits are strictly prohibited.
2. Whitelisting is a great idea however it splits up the community and I've seen other servers try it out but it just flops. I agree though I just do not see it happening. _mans making too much $_
3. I do not know about server upgrades but if this is true then yes fucking please, if you're going to have over 400+ supporters you better fucking bet your ass your servers are grade A. _mind the language._ So I really hope that the servers are truly the best they can have. As I said though I'm not aware about server stuff so it may already be that is it "the best" _lol prolly not tho_ 
4. Don't compare this server to No-Pixel, that's just stupid. That's the only thing I do not agree with you on this post + the whole leaving thing that's also stupid, you think anyone cares? _not trying to be mean here I'm just letting you know that they literally do not care if you and a few friends leave._

Much love.

**Comment by lol7lol** [comment]
youre a fed
