### ISSUE TITLE
2021 Ford Bronco

### ISSUE THREAD

**Issue by dadasmProjects** [ChainedDev/CityLife#663]
**Is your feature request related to a problem? Please describe.**
Nope!

**Describe the feature you'd like**
I think that adding a 2021 Ford Bronco would be excellent!

**Describe alternatives you've considered**
Not sure! I think that adding some more import cars would be great!

**Additional context**
Here is the mod for it :D 
https://www.gta5-mods.com/vehicles/2021-ford-bronco-wildtrak-add-on-fivem

**Comment by Forkedup** [comment]
Hi, this car is unfortunately too unoptimized for a populated city.

High Poly/vert count.

I appreciate the suggestion!
