### ISSUE TITLE
M8 Handling

### ISSUE THREAD

**Issue by AwknEU** [ChainedDev/CityLife#664]
I recently became a diamond tax payer and bought the BMW M8, and found the handling to be awful... im not too sure if its just me but the car loves to loop out. Maxed brakes arent as effective as they should be either imo... compared to the M5 this thing is a nightmare to drive. Not to mention a little bit of damage and the car turns into a tin can... im sure this is just the Car Mods fault tho.

**What solution would you like?**
An overall balance of the m8, i feel the speed is good enough, acceleration is good enough however the issues i have listed above could definetly be improved. These issues really became clear when i maxed the engine and brakes and put turbo on.

**Comment by Forkedup** [comment]
It is meant to be more of a drifty car.

The deformation, and brakes have been slightly tweaked. Thank you.

**Comment by AwknEU** [comment]
Yeah i understand that but even trying to drift it just loops out, hopefully these tweaks makes it easier to drive because atm its painful to take corners
