### ISSUE TITLE
Female Character Bugs

### ISSUE THREAD

**Issue by honeybones** [ChainedDev/CityLife#666]
**Describe the bug**
1. Females can only obtain 100% health by paying to check into pillbox, medkits don't heal us as much as they heal the male characters, I shouldn't have to explain further why that is frustrating. 
2. 50% of the time since recent updates when I load into the city I'm loading into life invader. Even if I had to relog because I had a glitch, and only disconnect for 2 minutes, I'll spawn in across the map. And half of the time I take damage, lose my armour or just straight up load in dead for no reason. As far as I can tell this is happening more with female characters?

**Comment by CREASE-C13** [comment]
i thought this was funny in a way at first when i heard about females health being down i think the main reason is because the GTA girl character has a smaller hit box
