### ISSUE TITLE
Nightblade performance not upgrading. 

### ISSUE THREAD

**Issue by e4ethan** [ChainedDev/CityLife#667]
**What is the reason for this balance request?**
[Ive spent $30000 on maxing out the performance on the Nightblade Motorbike for it to not go any quicker! I've asked 4 mechanics to look at it an they've said it must be the bike and to contact the government.**]

**What solution would you like?**
[The performance upgrades to work. Acceleration, top speed etc.  **]

**Additional context**
[Stock Top Speed was 125mph from what i could get to and Maxed out Mods,Engine,Turbo its still 125mph**]

**Comment by Forkedup** [comment]
I made some tweaks with the nightblade, unsure why it doesn't change after being upgraded.

The top speed might not change, but gear shifting & acceleration surely should when purchasing all of that.
