### ISSUE TITLE
Police balance 

### ISSUE THREAD

**Issue by Marshall676** [ChainedDev/CityLife#669]
**What is the reason for this balance request?**

from personal experience in the city cops are too powerful i understand that these "buffs" for cops are caused by the low police count at some hours but recently i have been playing while 5-9 cops are on and considering rule (6.1) if even 3 or 4 cops pull up they are automatically at an advantage to a group of 5. the fact that cops have AR's and can stack multiple heavy armours in their inventory is unfair cops will always win the fight unless the group uses hard to get weapons i should not have to shoot one cop 10x+ in the head in order to kill them with a pistol.

**What solution would you like?**
limiting the use of heavy armour and AR's to certain scenes and the amount of armour a cop can take from the PD. example i think the use of such powerful gear should be reserved to scenes such as bank robberies and situations that would require SWAT irl. at a minimum police should not be allowed to take more than one heavy armour from pd or place a spare in their trunk  

**Additional context**
balance cops or buff pistols i should not be able to shoot a police officer multiple times in the head but be able to hit him with a bat once and do 50% damage

**Comment by MiGrane4Mayor** [comment]
Dear Marshl676, you have absolutely no idea what you are talking about.
1)You dont just get an m4 when you become a cop it takes MONTHSSSS
2)a vest is not powerful, its standard gear.
3)when we pop a vest it literally stops everything we do for around 7 seconds (we cant even walk)
4)i personally only carry 2 to 3 (not abnormal)
4)oxys are more powerful then our vests
5)how old are you that you dont understand this and instead had to come make a suggestion about it?
please close this shit out dont even respond to it i beg you this is one of the worst suggestions ive seen in a very very long time

**Comment by Marshall676** [comment]
> Dear Marshl676, you have absolutely no idea what you are talking about.
> 1)You dont just get an m4 when you become a cop it takes MONTHSSSS
> 2)a vest is not powerful, its standard gear.
> 3)when we pop a vest it literally stops everything we do for around 7 seconds (we cant even walk)
> 4)i personally only carry 2 to 3 (not abnormal)
> 4)oxys are more powerful then our vests
> 5)how old are you that you dont understand this and instead had to come make a suggestion about it?
> please close this shit out dont even respond to it i beg you this is one of the worst suggestions ive seen in a very very long time



1. it does not matter how hard the M4 is to get as an officer. unless you join a gang or rob a cop you will never have enough fire power to take on a police officer with a AR. oh yeah and cant cops just like go back to the pd and pull another M4 out their ass?

2. i guess the bodyvest isn't powerful but i mean still seems to protect against getting mag dumped by a pistol

3. not abormal? i'd love to know what police officer in real life carries "2-3" heavy armoured vests on them at all times

4. "oxys are more powerful then our vests" what exactly is your point we have to go out and grind to get oxy while police just goto the pd and get heavy vests...????.

5. didnt expect any less from a cop lmao tell me with a straight face cops are balanced when i can shoot you with 2 pistol mags in the head and you still breathing

**Comment by Marshall676** [comment]
i guess the bodyvest isn't powerful but i mean still seems to protect against getting mag dumped by a pistol... in the head*

**Comment by Marshall676** [comment]
also next time you try to mount a defence try not skipping over entire points piggy

**Comment by InsaneInThyBrain** [comment]
Never have you ever shot a cop with 2 mags ever lol cops are actually at a disadvantage in 90% of the shit they deal with everyday im a crim and ive only had an m4 pulled on me one time and it was because i was conspiring with others to break a homie out from a scene just aim better next time lol

**Comment by MiGrane4Mayor** [comment]
> also next time you try to mount a defence try not skipping over entire points piggy

I literally hit every every single point you made. You just sound salty. The owners should just close this ticket out because ive seen some dumb shit before but you top the list atm. Congrats 👏 rat 🐀

**Comment by YourCuteLol** [comment]
imagine saying cops too powerful and its not realistic... what poverty country you livin in homie? cops have huge budgets kiss my ass

**Comment by Marshall676** [comment]
> imagine saying cops too powerful and its not realistic... what poverty country you livin in homie? cops have huge budgets kiss my ass

sorry my country has not researched the type of technology that allows an officer to carry multiple heavy bodyarmours on their person. but i guess thats realistic right?

**Comment by Marshall676** [comment]
> Never have you ever shot a cop with 2 mags ever lol cops are actually at a disadvantage in 90% of the shit they deal with everyday im a crim and ive only had an m4 pulled on me one time and it was because i was conspiring with others to break a homie out from a scene just aim better next time lol

id be more than happy to test this out

**Comment by MiGrane4Mayor** [comment]
> > imagine saying cops too powerful and its not realistic... what poverty country you livin in homie? cops have huge budgets kiss my ass
> 
> sorry my country has not researched the type of technology that allows an officer to carry multiple heavy bodyarmours on their person. but i guess thats realistic right?

I'm sure popping 15 oxys is super realistic though, or how about shooting a gun while using a med kit, and smoking a joint in the middle of a gun fight. On god 😆 🤣 😂 im done. Close this ticket 🎫 out chained please! I'll leave you with this one piece of advice. We all have the same 250 lbs of inventory weight. What you choose to do with yours is up to you. Good luck on them streets 🙏 💯 💪

**Comment by Marshall676** [comment]
> > > imagine saying cops too powerful and its not realistic... what poverty country you livin in homie? cops have huge budgets kiss my ass
> > 
> > 
> > sorry my country has not researched the type of technology that allows an officer to carry multiple heavy bodyarmours on their person. but i guess thats realistic right?
> 
> I'm sure popping 15 oxys is super realistic though, or how about shooting a gun while using a med kit, and smoking a joint in the middle of a gun fight. On god 😆 🤣 😂 im done. Close this ticket 🎫 out chained please! I'll leave you with this one piece of advice. We all have the same 250 lbs of inventory weight. What you choose to do with yours is up to you. Good luck on them streets 🙏 💯 💪



Joy emote ahah!... great suggestion maybe make a ticket about a feature for drug OD's but not sure when they added the ability to shoot while using a medkit...? i love how its a cop arguing that the police aren't over powered and it was only the police who responded with "no" emotes on the suggestion the fact is carrying multiple HEAVY FUCKING ARMOURS in your ass is alot less realistic than carrying from what i would assume 15 pills of oxy would fit into one little bottle   🤣 🤣 🤣 🤣 🤣. im done too with this ticket police are broken and overpowered in and out of the city my friends have been charged with bullshit crimes i have been rdm'd by police simping for a girl the goes on this server is a shithole maybe next month i wont have to wait over a week for two managers to look at my ticket for priority while they play WoW and gta
