### ISSUE TITLE
Adding a Wheel Width command

### ISSUE THREAD

**Issue by yggun** [ChainedDev/CityLife#67]
**Is your feature request related to a problem? Please describe.**
For some cars with custom body kits, such as the Nissan GTR with the Liberty Walk body kit. The wheels dont match the kit. They stay stock length. 

**Describe the feature you'd like**
A command such as /tirewidth where you could say do /tirewidth 2 and it would make the tires widen a bit to match the kit that you have on your car.

![20200210102247_1](https://user-images.githubusercontent.com/59383830/74166449-9446e900-4bf4-11ea-8043-1e918ea86b2a.jpg)
![20200210102249_1](https://user-images.githubusercontent.com/59383830/74166450-94df7f80-4bf4-11ea-9052-f4fd0f9fbb20.jpg)
![20200210102253_1](https://user-images.githubusercontent.com/59383830/74166453-94df7f80-4bf4-11ea-80ca-38144f298958.jpg)

**Comment by gullidog** [comment]
This is something I have been looking into recently, to release with the new Mechanic Buff/better upgrade system. The only problem is that I am not sure if it will appear for everyone and only display client-side. I will know more tonight after further testing and will make a decision based on it. Thanks for the suggestion!

**Comment by gullidog** [comment]
After further testing, I have come to the conclusion that at the moment this isn't going to happen. Although, this may be a possibility in the future. Thanks!

**Gullidog**
