### ISSUE TITLE
Fix ATM outside FBC

### ISSUE THREAD

**Issue by Sheeshhhh** [ChainedDev/CityLife#672]
**Is your feature request related to a problem? Please describe.**
People need to go a long way to the city to get cash for tips.

**Describe the feature you'd like**
There is an ATM outside Florida Boy Customs that could not be used. Getting it fixed would save time for us and customers

**Describe alternatives you've considered**
No idea

**Additional context**
None

**Comment by Dollar82** [comment]
This has already been addressed, & will be fix,thanks for the recommendation tho

**Comment by Sheeshhhh** [comment]
My Bad
