### ISSUE TITLE
Luxury Autos Cars

### ISSUE THREAD

**Issue by Doxified** [ChainedDev/CityLife#679]
**Is your feature request related to a problem? Please describe.**
It's not really a problem, but it definitely makes the city boring over time. I know a lot of people would agree with me here as well.

**Describe the feature you'd like**
I currently feel like the luxury autos cars are getting pretty bland and boring. I understand there's PDM cars that get rotated, but I've not seen any new cars added to lux recently at all, and as a diamond tax payer, you had a limited option of cars to choose from.

**Describe alternatives you've considered**
I've tried to enjoy the cars in the city for the most part, but I don't really feel like we should have to pay massive amounts of money for a decent luxury car to be imported into the city. I understand the point of the process and the idea, but it just sucks knowing you have a small selection to pick from, and you're often forced to buy something that everyone else already has. 

**Additional context**
Add more luxury cars to Lux, and of ones that aren't imports, meaning don't add cars that were imported already.

**Comment by InsaneInThyBrain** [comment]
I agree it gets old looking at the same 80 cars everyone owns and drives around
