### ISSUE TITLE
People should not be manufacturing drugs on the first day

### ISSUE THREAD

**Issue by Kman259** [ChainedDev/CityLife#680]
**What is the reason for this balance request?**
Currently in the server, you are able to grow weed and cook meth on the first day. (yes meth is hidden but the location is freely handed out unfortunately) I think it is kind of unrealistic for people to be manufacturing drugs on their first day in the city. They should have to work their way up to that point. 

**What solution would you like?**
Make it more difficult to make drugs (and have the prices adjusted to reflect the higher difficulty). I think the meth ingredients should be found from doing jobs such as garbage. The weed farm and rolling should also 100% not be on the map. 

**Additional context**
This change would bring so much more interaction/rp and make the drug scene feel more realistic because people won't be fucking heisenberg on their first day in the city. Lower-tier/newer criminals would now have to RP with the higher-tier/more experienced criminals to get a hold of the drugs. And the higher tiered criminals would have to interact with garbage men and other civilians to get the needed ingredients.

**Comment by vaillant0** [comment]
I agree to the part of making harder to find or give it out, but I don't think making the grind harder (time wise) then what it is.  I disagree with taking off the picking  place, but I agree with taking off rolling. and how would new comers get money they have to start somewhere?

**Comment by Kman259** [comment]
They pay would increase to match the increased effort required so it wouldnt really be more of a grind per say. It doesn't make sense for an illiegal weed farm to be on google maps. New people can make money from civilian jobs. They can then actually roleplay and make connections to learn where the weed spots are lol.
