### ISSUE TITLE
Fix Custom Tires in Shops

### ISSUE THREAD

**Issue by PurpleRei** [ChainedDev/CityLife#681]
**Describe the bug**
Custom tires dont stick on cars after you put them in garage

**How to Reproduce the Behavior**
Apply customs tires at a shop, put car in garage, take car out of garage upgrade gone

**Expected Behaviour**
Custom tires supposed to stay on after garage 

**Screenshots**
N/a

**Additional context**
N/a

**Comment by Chainedster** [comment]
Okay! Done!
