### ISSUE TITLE
Oxy too op

### ISSUE THREAD

**Issue by Billy-Grey** [ChainedDev/CityLife#684]
**What is the reason for this balance request?**
Oxy is way too op. I think it should have some sort of change

**What solution would you like?**
I think a good idea to fix the oxy spamming would be to make it so oxy heals you but takes like 30-40 seconds to fill you to full health. Having it insta heal you is weird and shootouts become oxy battles whoever runs out of oxy first loses or whoever fucks up on oxying up

**Additional context**
No additional context

**Comment by Forkedup** [comment]
Hi, I appreciate the suggestion

In our newest update, changes have been made to Oxy to reduce it's effectiveness.
