### ISSUE TITLE
Job Levels

### ISSUE THREAD

**Issue by Brownie2424** [ChainedDev/CityLife#687]
**Describe the feature you'd like**
Add a level system within jobs such as Garbage, Fishing, Taxi, and other jobs that are non-whitelist. Being a higher level could include higher pay, a higher chance of getting items such as better fish or items from garbage.

**Comment by Stumbino1** [comment]
Would love to talk to the devs about creating a tow truck job where someone can impound vehicles around the city, and also stop by and give them repairs for a fee. I think it would allow for cool interactions between civilians and the tow truck driver. It would help keep the streets clear from players vehicles that stay there when their game crashes or when they break down. The model of the tow truck is already in the game so as far as coding goes that would be a load off of yalls backs to.

**Comment by Dollar82** [comment]
Become a mechanic, everything you mentioned is already working in the city

**Comment by Stumbino1** [comment]
> Become a mechanic, everything you mentioned is already working in the city

But mechanics primarily work on cars at Mech shops, I've been in the city for almost two months and have never seen a mechanic impound a vehicle. I would like the tow truck job to primarily focus on impounding vehicles that are littered across the city. It would also help with people having their head pop and vehicle out in the middle of nowhere, and then they get their entire inventory stolen. This would allow mechanics to focus on upgrading cars etc. and open up another legal job opportunity for civilians not wanting to do crime.
