### ISSUE TITLE
Clothing Suggestions

### ISSUE THREAD

**Issue by VloneSama** [ChainedDev/CityLife#69]
**Is your feature request related to a problem? Please describe.**
I feel like the clothing in this server can be better, the base game clothing in my opinion looks goofy and sometimes doesn't fit the character, for instance, some of the pants are super tight, and there are torsos that are huge, and can make the character look really funny looking. I also think that new clothing would make the server more appealing to play.

**Describe the feature you'd like**
I think that a good feature to add is a clothing suggestion channel, where players/users can suggest different type of clothing, they have to send a link and a preview of the specified clothing, and the players can vote if they would like to see it in the city. 

**Describe alternatives you've considered**
Maybe instead of player voting, maybe it can just be approved by a mod/admin to be put in the city.

**Comment by ChainedDev** [comment]
We've tried making out clothing selection better but didn't get time to getting through all of it, I will leave this open as a spot for people to post suggestions of outfit

**Comment by VloneSama** [comment]
is there a way that the community can vote for the different clothing, so that the popular clothing are prioritised?

**Comment by VloneSama** [comment]
and just a question, is it hard to implement clothing? and would you be eager to have like a small team to help implement the clothing, so that it wouldn't have to be approved by higher ups?

**Comment by ChainedDev** [comment]
> and just a question, is it hard to implement clothing? and would you be eager to have like a small team to help implement the clothing, so that it wouldn't have to be approved by higher ups?

Not really an expert on it but if you have any experience working with clothes packs and want to help out send me a message on discord 😃

**Comment by gullidog** [comment]
New cosmetics are in the work, check #teasers in discord to see progress! If people would like to comment any clothing suggestions here feel free! 

_**gullidog**_
