### ISSUE TITLE
Driving rules for better RP experience

### ISSUE THREAD

**Issue by 1of1Kemani** [ChainedDev/CityLife#694]
**Is your feature request related to a problem? Please describe.**
Yes and no - CLRP advocates a server of high quality RP which is not the first-hand impression you receive when you first hop on the server. You see people going 140 mph through the city and every intersection, currently resulting in many accidental VDM cases, bikers being hit by cars and killed, crashes, etc. You're meant to value your character's life, therefore you shouldn't be speeding to the limit for no reason. Not only would this benefit the RP quality, but also put a little less work to do for the EMS at Pillbox giving them time to reach out where needed when EMS assistance is required.

**Describe the feature you'd like**
Implement rules for more realistic driving - there are many ways to do this. Driving at a high speed is in general not the issue, but when everyone starts to cut through traffic and intersections excessively especially in high population areas is when the issue becomes clear. You can either be super strict which I don't think is appealing to the majority of players, or add some guidelines with reasonable possible punishment if broken. These could sound something along:

1. Not driving like a human not caring about your character's life.
2. Driving fast and turning corners going 50 mph+
3. Drifting/cutting/driving into the wrong lanes. (THIS HAPPENS HUNDREDS OF TIMES DAILY!!!)

Consequences: Depending on the severity, anything from a verbal warning to ban.

**Describe alternatives you've considered**
At this point I can't think of anything else that would help this issue.

**Additional context**
None atm.

**Comment by Avotic** [comment]
Apply for SASP and do traffic patrols.  🤷‍♂️
