### ISSUE TITLE
Balance / Fix to trucking

### ISSUE THREAD

**Issue by CooMonster** [ChainedDev/CityLife#70]
**What is the reason for this balance request?**
Trucking on the server does not make a lot of money and you go form the same place to place/ only one stop and then your done.

**What solution would you like?**
Adding multiply locations on 1 job and more trucks, higher pay.

**Additional context**
If you get out of the truck on a job you can not get back in it and you lose the job.

**Comment by ChainedDev** [comment]
Will be checking it out to make sure the job is actually worth it

**Comment by ChainedDev** [comment]
Reworked a while ago never updated issue
