### ISSUE TITLE
Cadillac Escalade & GMC Yukon Handling Changes 

### ISSUE THREAD

**Issue by Doxified** [ChainedDev/CityLife#701]
**What is the reason for this balance request?**

The Cadillac Escalade and the GMC Yukon are pretty nice cheaper SUVs available in the city but they handle like an eighteen wheeler in terms of performance, upgrading both vehicles doesn't solve or make much of a difference to them.

**What solution would you like?**

GMC Yukon - Slight handling changes

Cadillac Escalade - Big handling changes 

**Additional context**

I appreciate everyone's feedback on the cars listed above, and I feel like they need this badly.

**Comment by Chainedster** [comment]
They handle amazingly!
