### ISSUE TITLE
Toyota Gt86 Bug

### ISSUE THREAD

**Issue by Ceezy420** [ChainedDev/CityLife#71]
**Describe the bug**
(Car seems unfinished)
Toyota gt86 Trunk is empty , see right through to the ground + rear wheels, As well as the lisence plate floats when you open trunk 

The Engine looks like a pixelated photo and does not render a Realistic 3d Engine, which doesnt make the RP very much fun , when GTA cars' engines look much better. 

**How to Reproduce the Behavior**
Please work on issues above, or remove the model replace it with a better worked on mod, 

**Expected Behaviour**
As described above

**Screenshots**
Rp2findout?  . Screen shots Never work for me in game

**Additional context**
If  has to be removed from game , will we be reimbursed or will the car be traded out for the fixed version ? .

**Comment by gullidog** [comment]
Thanks for letting us know, will investigate this. And we personally do not make car models so yeah...
