### ISSUE TITLE
Visible body weight to characters  

### ISSUE THREAD

**Issue by vaillant0** [ChainedDev/CityLife#712]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
For me everybody in the city be built the same visually. If you guys can maybe add where you can become fat, skinny, bodybuilder. Like make it where you can change your body weight. I think this will add some humor in the city.

**Comment by Dollar82** [comment]
Right, be like ol fat ass boy😂😂 i like it tho💪🏾
