### ISSUE TITLE
Losing pistol license for non-violent crime.

### ISSUE THREAD

**Issue by Ophiez** [ChainedDev/CityLife#714]
**What is the reason for this balance request?**
I think losing your firearm license for a crime that didn't include violence or use of a firearm deters people from doing petty crime and/or drug sales. Paying 5k every time you get arrested regardless of if you used a weapon or not is pretty unbalanced because all crimes already have a monetary consequence. 

**What solution would you like?**
Stop taking weapons licenses away for crimes where no weapon was used.

**Additional context**
I get that cops are used to being shot at but not everyone uses violence as a solution and I think rewarding crims actually RPing with cops instead of just turning everything into a gun fight will benefit the server.  Thanks.

**Comment by TrooperJoe** [comment]
This is dumb. Felons can’t have firearms. Be happy you can buy it back at all.

**Comment by Ophiez** [comment]
> This is dumb. Felons can’t have firearms. Be happy you can buy it back at all.

Not all crimes that get your license taken are felonies. Not every criminal is a felon.

**Comment by TrooperJoe** [comment]
What did you do to get it taken? Police have to follow what is written for them by the DoJ.

**Comment by Ophiez** [comment]
I've had it taken from me for having a little bit of weed w/o selling it, just simple possession and for selling small amounts of weed (less than 20 joints). I've had my license taken from me when I wasn't even carrying a weapon, what reason in RP would a cop have to even check for licensing if I don't even have one? I just think it's dumb that people who choose not to shoot cops who are trying to catch them and actually let them RP out their jobs by being non-violent should have this treatment. "Felons" shouldn't have a lot of things within RP but it would just be nice for people who only use weapons for self-defense or maybe not at all.

**Comment by REDDGLARE** [comment]
Then use the court system! If you believe it was wrongfully take contact a lawyer. If you think the law needs to be changed, again contact a lawyer. Get a case started. Use your problem to create some RP.
