### ISSUE TITLE
Actual Car Garage for Properties that has upgradable garages + New cars.

### ISSUE THREAD

**Issue by justanotherdan** [ChainedDev/CityLife#715]
**Describe the feature you'd like**
Would like to see that the purchasable properties like houses and mansion has actual car garage where you can store atleast 1 car instead of the garage been just a storage. Also would really like to see the Sultan Classic and Comet/Comet SR in the city next.

**Comment by REDDGLARE** [comment]
I imagine having personal garages would cause some very serious performance issues for the server. As for the cars, go down to one of the dealerships and let them know!
