### ISSUE TITLE
Removal of Radio’s from Criminals.

### ISSUE THREAD

**Issue by JordanAdams12** [ChainedDev/CityLife#717]
**What is the reason for this balance request?**
[A concise description that describes the balance request in-depth. This has been on my mind for a while, regarding the radios, in my opinion it makes no sense for a group of criminals/gang members to all have radios on them and be using them with combat comms like this is call of duty. Criminals are not police, there is no need for radios. In my opinion it’s a very abused feature and has a win mentality embedded within it, if you get pulled up on in real life you’re not going to turn on your walkie talkie and radio in to other gang members? You’re going to use your phone and try to escape. I understand because the phones are now touch screen it’s a lot harder to do, but the whole radio thing is FailRP for gangs.

**What solution would you like?**
[A concise description that describes what you would like to happen. Radio’s to be removed from everyone’s inventory and stores besides police. If possible making phones useable while moving again like they used to be, to make it easier to communicate while possibly evading someone (optional).

**Additional context**
[Add any other context or screenshots about the balance request here.

**Comment by darku1337** [comment]
Not that I'm in a criminal organization in real life or anything but I'd imagine that the criminal groups that have the money to buy a set of radios and work on the street a lot would definitely do so and do so today
