### ISSUE TITLE
Expungement of records

### ISSUE THREAD

**Issue by henrioad** [ChainedDev/CityLife#719]
**Is your feature request related to a problem? Please describe.**
Right now it's too hard to expunge your record, having to wait 2 months without committing a felony is ridiculous. 2 months is a very long time. So if you're a criminal and have been caught only once or twice and you want to turn your life around, like making a business or something else, you have to wait 2 months before you can even do anything you want to do.

**Describe the feature you'd like**
The judges should start expunging records after 20-30 days of no felonies committed.

P.S If you think this suggestion is bad, please let me know why because i don't see any downsides to this.

**Comment by MiGrane4Mayor** [comment]
Its 2 months for a felony
Its only 1 for a misdemeanor .
Don't do the crime if you can't do the time!
