### ISSUE TITLE
More cars (Here's a start)

### ISSUE THREAD

**Issue by DeluxeGekkon** [ChainedDev/CityLife#72]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, but importing more cars will be more immersive, and therefore being better with RP.  

**Describe the feature you'd like**
Plain and simple - more cars.  here is a small list of cars I would LOVE to see in the city:
1. https://www.gta5-mods.com/vehicles/honda-civic-type-r-ek9-add-on-oiv
2. https://www.gta5-mods.com/vehicles/honda-civic-ej2-coupe
3. https://www.gta5-mods.com/vehicles/180sx-type-x-tunable
4. https://www.gta5-mods.com/vehicles/bmw-m5-f90-add-on-deniska111
5.https://www.gta5-mods.com/vehicles/demonhawk-add-on-only

It doesn't have to be the ones listed, these are just examples I've seen from other cities.

**Describe alternatives you've considered**
The obvious alternatives are the PDM cars etc, but as I said earlier, it's more immersive for me, and I feel it allows for more potential in RP (Ex, FnF car shows, specific market car meets (JDM, German, American Muscle, etc.)).

**Additional context**
This whole website is a potential additional context/content! https://www.gta5-mods.com/vehicles

**Comment by ChainedDev** [comment]
Possibly planning a JDM update soon

**Comment by ChainedDev** [comment]
#94
