### ISSUE TITLE
dpScenes addition

### ISSUE THREAD

**Issue by MaskedVortex** [ChainedDev/CityLife#723]
**Is your feature request related to a problem? Please describe.**
There is currently no evidence feature for Law Enforcement (that I know of), and no other feature that compliments the things that this script can do.

**Describe the feature you'd like**
dpScenes is a script that allows players to create customizable textboxs that will disappear over time. These can be customized in so many different ways, and can be used and configured for anything. Signs, evidence, Graffiti, and more. It's completely free and from a trusted source. https://esx-scripts.com/dpscenes-1-0-world-scenes-notes-standalone-releases/

**Describe alternatives you've considered**
N/A

**Additional context**
Link: https://esx-scripts.com/dpscenes-1-0-world-scenes-notes-standalone-releases/

**Comment by 1of1Kemani** [comment]
![billede_2021-05-24_151443](https://user-images.githubusercontent.com/82116552/119353109-c58ce080-bca2-11eb-84a4-f5abe5510082.png)

Example here as well - a picture I took just a minute ago.
