### ISSUE TITLE
Car delivery 

### ISSUE THREAD

**Issue by Brownie2424** [ChainedDev/CityLife#732]
**Describe the feature you'd like**
I was thinking that a car delivery from one garage to another would be a great idea something like you pay $500 for your car to be moved garages and would take from 10-15 minutes from when you requested it. 

**Additional context**
Also, have an optional fee for repairing and refilling the car when putting it in the garage.

**Comment by lyon5189** [comment]
Not a bad Idea. I like the idea of it taking awhile. I think 10-20 minutes might make it so people don't just abuse it. Also $500-$2000 would make it expensive enough for people to not abuse it.
