### ISSUE TITLE
Small business income 

### ISSUE THREAD

**Issue by Baja-Blast** [ChainedDev/CityLife#733]
**Describe the feature you'd like**
I would like for small businesses like gas stations, tool shops, bars like yellow jack, and Smoke on the water to have system that would have the owners make income off of products sold at their location. It would provide a lot more incentive to own a business with a sort of passive income. 

**Additional context**
EX: A Player buys a stack of sandwiches from Grove St gas station the owner would receive a portion of the profits.

**Comment by lyon5189** [comment]
I agree this would be great!

**Comment by Chainedster** [comment]
Yellow jack and Smoke on the water could qualify, but the others not going to happen :/
