### ISSUE TITLE
city car garages

### ISSUE THREAD

**Issue by deadlydr3am** [ChainedDev/CityLife#735]
**Is your feature request related to a problem? Please describe.**
this feature was in the city before the recent update
**Describe the feature you'd like**
if you could add back the feature with the garage where you can pay to get it fix.

**Describe alternatives you've considered**
keeping an advance repair kit and other such things on your person

**Additional context**
this would allow the people in the city to save money

**Comment by CreepyEK** [comment]
It was easily abused, people would put their car away in the middle of a fight and pull it right back out, fixing their tyres ect, instntly. Repairing shouldn't be an instant process.
