### ISSUE TITLE
Inventory for low resolution

### ISSUE THREAD

**Issue by LightningJake** [ChainedDev/CityLife#74]
**What is the reason for this balance request?**
My resolution is 1366x768. The inventory is cropped for me and I cannot see the Full inventory because of it, the first column is half visible to me. It's probably because the inventory is optimised for 1920x1080p.

**What solution would you like?**
Can we do something so as to fix the inventory in lower resolution screens? Like rescale the inventory or something?

**Additional context**
No additional content.

-citylife rp india

**Comment by gullidog** [comment]
Is this something you definitely cannot change?

**Comment by LightningJake** [comment]
Nope, because my monitor's native resolution is 1366x768 therefore the maximum resolution I can play on is 1366x768p.

**Comment by gavisuprstar** [comment]
Yup, it happens with me too, goes of from screen..... cant we replace the inventory sith the inventory something like nopixel? I mean it is shorter in size and loogs good too.

**Comment by ChainedDev** [comment]
I think someone manager to get it to work with the lowest resolution possible and it worked fine, just had to scroll.

**Comment by gullidog** [comment]
Is this issue solved? @LightningJake
