### ISSUE TITLE
Car breaking when spawned in from garage or impound lot 

### ISSUE THREAD

**Issue by Jimlayhe** [ChainedDev/CityLife#743]
**Describe the bug**
when I Spawn in my car from garage the windows break and the engine is breaks I have to repair every time costing me lots of money sometimes i would exit then car after i repair it go back in it and it would be damaged again. fyi this happens to both of my cars BMW E36 and GMC YUKON 

**How to Reproduce the Behavior**
Steps to reproduce the behaviour: Spawn in a car do nothing lol its breaks its self

**Expected Behaviour**
car doesn't break

**Screenshots**

**Additional context**

**Comment by Chainedster** [comment]
It's because it pulls it out how it was stored in the garage last, so when you fix it you need to store it in the garage and it won't happen agian. 

If you want this mechanic changed please make a new suggetion
