### ISSUE TITLE
The system is corrupt.

### ISSUE THREAD

**Issue by Ritzy853** [ChainedDev/CityLife#746]
**Is your feature request related to a problem? 
    The legal system is corrupt, people who do illegal activities and are penalized have to face huge fines and restriction issues through out their stay. These fines are tremendous and once paid off they are left with nothing. They are then forced to continue to do illegal activities which can get them in deeper debt if failed, or monotonous legal freelance work that have minimum amount of role-play and gets in to more of a grind aspect of the game. Which I'm sure the goal of city-life is not to grind money.

**Describe the feature you'd like**

Offer more roleplay activities that people can earn money which are leagal, like burger shot, lux, pdm, bean machine.

**Describe alternatives you've considered**

Lower the cost of court expungements or allow all legal court fees to negate bank account.

**Comment by TimmyTwoStep** [comment]
Don't get caught and have to pay fines 🤷‍♂️
