### ISSUE TITLE
/shield command to enhance Police Roleplay

### ISSUE THREAD

**Issue by strangeclrpindia** [ChainedDev/CityLife#75]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
We can add /shield command for the SASP all roles, so that while having gun-fight they can at least block bullets or enhance the roleplay and show some quality. No server has this script, but if it gets implemented here, It would be a great impression

**EXAMPLE GIF**
https://gyazo.com/42ac702003faa94297dae076265f10ac
https://gyazo.com/6a82e5aaf1844c3039d717c5528cf57d

**Comment by ChainedDev** [comment]
That just looks broken
