### ISSUE TITLE
Game messages to player covered by HUD

### ISSUE THREAD

**Issue by lyon5189** [ChainedDev/CityLife#756]
**Describe the bug**
Often a player will recieve message from the game such as "there are stingrays in the water" or the hunter telling you to drop stuff off at the hunting lodge or the time left at the hospital or prison. These messages are covered by the HUD. "/togstatus" does remove the HUD to view these messages but I feel that the messages should not overlap with the HUD at all.

**How to Reproduce the Behavior**
Steps to reproduce the behaviour: Harvest an animal with a knife after shooting it and you will see a message to return the fur to the hunting lodge to get paid. You will notice that this message will be covered by the player's HUD.

**Expected Behaviour**
The messages should be moved up above the player's HUD so they do not overlap. When a player gets into a vehicle their map appears as well so the messages should also be moved higher on the player's screen while a player is in a vehicle.

**Comment by Chainedster** [comment]
Will be working on these, if you can send me a complete list it will be easier in getting them all done at once

**Comment by Resqect** [comment]
Bedding notification moved from above map - to top right
Jail Timer repositioned from bottom right - to above mini map  
Hospital timer repositioned from bottom right - to above mini map
change hud from square - to circle
Give ID notification repositioned from bottom right - to above mini map
