### ISSUE TITLE
The vintage pistol

### ISSUE THREAD

**Issue by izward** [ChainedDev/CityLife#763]
Please re skin the video vintage pistol to a 1911 everyone would agree with this one bro they got to that vintage looks so bad

**Comment by TimmyTwoStep** [comment]
Heavy Pistol is a 1911 with a red dot.

**Comment by Suedii** [comment]
As Timmy said, the Heavy Pistol is a 1911.
If anything the vintage pistol should be re skinned to a proper FN 1922. No need to take a gun that is supposed to look like a 1922 and re skin it to a M1911 that’s is already replicated by the Heavy Pistol.

But if you really don’t like the looks of the vintage at least suggest something like a classic Luger which is logical :)
