### ISSUE TITLE
A Clarification Within The Castle Rule

### ISSUE THREAD

**Issue by 6nomed** [ChainedDev/CityLife#769]
**Is your feature request related to a problem? Please describe.**
Having been punished for a misunderstanding over the abuse of the castle rule, yes. 

**Describe the feature you'd like**
I believe there should be a clarification within the castle rule that describes how an interaction between a gang pulling up to another gang's territory should be handled in reference to numbers. Specifically, something that defines and clarifies specifically how a group considered in any way unfriendly or with previous or current negative intentions cannot arrive with more than 5 members to either intimidate the "home" gang or suppress their ability to roleplay through restricting a conflict.

**Describe alternatives you've considered**
This is merely a simple clarification to the rule and the most efficient way to deter other individuals from doing the sort of thing I did.

**Additional context**
Through my conversation with several staff members I was encouraged to create this suggestion and therefore have support in this clarification.

**Comment by Chainedster** [comment]
Read rules
