### ISSUE TITLE
Use of Phone

### ISSUE THREAD

**Issue by Vollanplays** [ChainedDev/CityLife#771]
**Is your feature request related to a problem? Please describe.**

I feel like its kind of akward that you cant move when on the Phone, like you can move IRL if you have your phone out

**Describe the feature you'd like**
Better so you can move and walk around and drive and make it a ticket if you get caught whit your phone out while driving

**Describe alternatives you've considered**
Just make so if someone drives or sum whit phone up they get a ticket
IRL if you have a phone you dont stop and and still all the time when you use it, same whit driving, soo many people use their phone while driving.

**Additional context**
<3

**Comment by TimmyTwoStep** [comment]
It used to be an option on phones to use arrow keys or cursor control, cursor control stopped you from moving around. I would like to see it an option again to use arrows, then again it really isn't the worse thing, I'm fine with either or. As far as driving with a phone out as a ticket, if we wanted to we could call is carless driving if we really wanted to charge them.
