### ISSUE TITLE
Ingame Applications

### ISSUE THREAD

**Issue by clarencecode1** [ChainedDev/CityLife#772]
**Is your feature request related to a problem? Please describe.**
Yes, many applications are submitted but there are many trolls. I believe the google forum style is good at filtering the trolls but there's also an issue with it. It doesn't fully show the character of the person being interviewed.

**Describe the feature you'd like**
I think that there should be in-person interviews "ingame" that would help the applicant be more understood as a character. This will also help prevent people blatantly just googling things and would make it more RP-based applications.

**Describe alternatives you've considered**
I also think that the forum is good but I think it could be better. This would help with that because the officers would be able to understand the applicants easier.

**Comment by itsBllue** [comment]
This is already a thing, the interview stage is part 2 of your application, just as any other job. Gotta pass the first stage to get to the next one guy
