### ISSUE TITLE
Wtf is happening with the city. 

### ISSUE THREAD

**Issue by Tick123** [ChainedDev/CityLife#773]
**What is the reason for this balance request?**
It is not balance request. Wtf is going on with the city. I think the city needs to have a community meeting about what is happening . weed is still not working, the constant hackers in the city - you can not even host an event now because a hacker will show up and blow it up. Paleto bay is broken. the headaches/lag is happening every night tbh I think because of the player count. Some sort of lack of admins. The amount of new players that dont know the rules, I currently have 5 tickets for different situations. I mean the list could go on. I know many people that have been in the city for quite awhile are feeling the same.

**What solution would you like?**
[A concise description that describes what you would like to happen. **Remove this line!**]
I think the city should go back into two servers with a 150 player count. I think this would balance out everything I stated above, and would mainly help with people that come on to the server just to shitlord. Another possible way the server can fix shitlording is whitelisting, it should be players with 500 hrs plus get auto excepted, and below that should have to put in an application. 

**Additional context**
I know this city is really supported, and makes thousand's a month, but tbh I feel like the money that people donate is not going back into the city how it should be. Hire a developer that can fix the fucking city.

**Comment by loc562** [comment]
welcome to citylife rp where there will never be a time where the server runs without some sort of problem and being whitelisted
