### ISSUE TITLE
Thrax is slow compared to similar priced cars

### ISSUE THREAD

**Issue by developincognito** [ChainedDev/CityLife#777]
**What is the reason for this balance request?**
I believe the Thrax should have a higher top speed. Currently a maxed out one hits around 200 but cars like the Buggati hit 280. Granted they are slightly different price ranges. I've seen the Thrax valued around $1.6m while the Bugatti is $2.3m.

**What solution would you like?**
An increase to have the Thrax top speed hit around 220-260

**Comment by gamerdude23** [comment]
a price gap of 700,000 is slight? i dont know man, a panto is like 5k, and a ford gt is like 400k, even with smaller price gap they tend to outperform each other a lot. if you want to go 280, then just buy the buggati.

**Comment by developincognito** [comment]
Yeah I know what you mean. Some cheap cars go really fast like the panto or fort gt. Hell, I own a 100k muscle car that tops out at 190 but the Thrax is $1,500,000 more and it only goes 20 mph faster?

Maybe I'm wrong in believing that price would have a mild correlation to top speed. I understand that there are a ton of factors other than top speed to account for.

All that said, you're right in that I should just buy the Buggati and I plan to. However, I still stand by my desire for the Thrax to go faster.

**Comment by themorganheffer** [comment]
I completely agree the thrax needs a slight buff it is way to slow for how much it costs

**Comment by Jadderson** [comment]
Price doesnt really mean anything when buying a car, shit my 3.3 million dollar Ferrari got gapped by a 100k muscle car.

**Comment by gamerdude23** [comment]
i understand what you mean by price = speed, but you cant really go any faster realistically. i guess youre paying for luxury, my 250k shitbox was gapped by 100k muscle car too.
