### ISSUE TITLE
simple QoL for inventory

### ISSUE THREAD

**Issue by desirex11** [ChainedDev/CityLife#778]
Currently it is very clunky to use the inventory for purchasing a bulk of items. this is mainly due to limitations with the amount of items that are purchasable in a single transaction. I am not sure if it is due to limitations in the script or if its for some other unknown reason.

The best and most straight-forward fix would be to raise the limit of certain items to buy more than 1 at a time.

If it is impossible to raise the number of items per transaction on things such as fish bait, water, fertilizer etc, then a nice work around would be to add a "pack" of said items that you can use in your inventory to give a larger quanity. For example instead of buying a water bottle 1 by 1, a "pack of water bottles" could be for example open and give you 12 bottles. this could be translated to almost any item that requires bulk purchase. it could also lead to the implementation of a "bulk" grocery store.

**Comment by Chainedster** [comment]
I set the limits on each on purpose, do you guys rock with the limits ⁉️
