### ISSUE TITLE
SASP garage

### ISSUE THREAD

**Issue by gavisuprstar** [ChainedDev/CityLife#78]
**Is your feature request related to a problem? 
Noo

**Describe the feature you'd like**

We already have the vehicle authorised to every rank. But a rank cant even take out vehicle of the lower ranks. For example a chief cant take out any bike, how about changing the system to take out vehicles of lower rank too.

**Describe alternatives you've considered**
Or we can simply add a menu for the garage where there are all the vehicles available so that theres no inbuilt authorised system. After that we can manually took decisions and make the vehicles authorised according to rank.

**Comment by Droshky** [comment]
wym?

**Comment by gavisuprstar** [comment]
I wanna say like a chief can only use 5 vehicles and not any bike, so it will be good to add more or simply put every vehicle without any authority so any sasp can take out any vehicle.

**Comment by ChainedDev** [comment]
Chief could just not use bike
