### ISSUE TITLE
Add an option to delete messages on the phone app.

### ISSUE THREAD

**Issue by nomenow** [ChainedDev/CityLife#791]
**What is the reason for this balance request?**
I feel like my phone might be lagging because of it and its just not clean there should be an option like that :D

**What solution would you like?**
[A concise description that describes what you would like to happen. **Remove this line!**]

**Additional context**
[Add any other context or screenshots about the balance request here. **Remove this line!**]

**Comment by Chainedster** [comment]
Sure!
