### ISSUE TITLE
Lower Prison fines and times 

### ISSUE THREAD

**Issue by skinnylispboi** [ChainedDev/CityLife#795]
**What is the reason for this balance request?**
This is a Game not real life, I get that your trying to be semi realistic with the time and money, but not everybody wants to wait in an hour in a video game just to play again, also the fines are way to expensive if u don't have a lot of money, the highest fine should be 5k - 8k minimum. 

**What solution would you like?**
Makes fines and Prison time lower 
**Additional context**
I'm sure a lot of people agree with me on this one

**Comment by Dollar82** [comment]
Can't do the TIME,don't do the CRIME!
                                                    
                                                  -Florida
