### ISSUE TITLE
One More Judge

### ISSUE THREAD

**Issue by cookyomamma** [ChainedDev/CityLife#796]
**What is the reason for this balance request?**
The reason for this suggestion is due to me being on during the time the judges are supposed to be on for a few days to never see them once.

**What solution would you like?**
I think one more judge or even two more would lighten the workload for the other judges.

**Additional context**
I understand that people have a life outside of roleplay, and that's why more judges are necessary.

**Comment by Chainedster** [comment]
Not a development feature
