### ISSUE TITLE
/carry

### ISSUE THREAD

**Issue by BRYSONROBBEDYOU** [ChainedDev/CityLife#80]
**Is your feature request related to a problem? Please describe.**
/carry/carry/carry/carry/carry/carry/carry/carry/carry/carry/carry/carry

**Describe the feature you'd like**
/carry/carry/carry/carry/carry/carry/carry/carry/carry/carry/carry/carry/carry/carry

**Describe alternatives you've considered**
/carry/carry/carry/carry/carry/carry/carry/carry/carry/carry

**Additional context**
/carry/carry/carry/carry/carry/carry/carry/carry

**Comment by ChainedDev** [comment]
This is why we do not like you

**Comment by ChainedDev** [comment]
This is why we do not like you
