### ISSUE TITLE
BMW S1000r speed change

### ISSUE THREAD

**Issue by ExsX** [ChainedDev/CityLife#800]
The Suzuki GSX-R at the price of $55k has a top speed at about 170 mph going on the highway hitting tiny bumps, however, the $140k BMW S1000r tops out at about 150 mph at the same circumstances.

(Note that my example is that both are maxed, maxed engine, turbo, suspension, all that jazz, but neither have armor)

I feel its a little odd especially since the GSX-R is 1/3 of the price but faster in every way.

**Comment by killxxr** [comment]
its used and abused by the community during heavy gang beef since it has fast acceleration and the grip on corners is insane so you can take corners going 120+ and not have anything happen to you since you cant fall off of due to the gta physics unless you hit something.
