### ISSUE TITLE
Drop player limit and bring more locals in

### ISSUE THREAD

**Issue by BenjiStoneHenji** [ChainedDev/CityLife#809]
**What is the reason for this balance request?**
it so boring driving around the city and seeing no locals anywhere. makes it look like a post apocalyptic wasteland. also makes it really annoying trying to sell drugs without every gang or family pressing you every 2 seconds just for trying to sell a few joints. shouldnt have to hang around garages just to see a couple locals if youre lucky since thats where every gang thinks they need to linger around now.

**What solution would you like?**
Drop player limit and bring more locals in

**Additional context**
seems like these gangs and families have absolutely nothing better to do than linger around garages since thats the only chance you really get to see locals. ive also noticed these groups having way more members chasing people down than they should based on the amount allowed in interactions. (example - just recently was witness to a person by themselves being chased by 8 members of a family with 4-5 vehicles)

**Comment by TheMilkyWaine** [comment]
Weird, i made a suggestion about bringing more locals and local drivers back about 2 weeks ago looks like it was deleted....
