### ISSUE TITLE
Fines

### ISSUE THREAD

**Issue by Skader91** [ChainedDev/CityLife#81]
**Describe the bug**
Fines issued to civilians disappear, no society fund nor personal

**How to Reproduce the Behavior**
Fine a offender

**Expected Behaviour**
$$$ in the bank

**Screenshots**
Not applicable

**Additional context**
Would prefer it all go toward society fund to do community events.

**Comment by ChainedDev** [comment]
It doesn't increase the /society ?

**Comment by Skader91** [comment]
It does not.

**Comment by Skader91** [comment]
![image](https://user-images.githubusercontent.com/59831450/75086709-7b8fda80-54f4-11ea-8426-1491d99a3c06.png)

**Comment by Skader91** [comment]
What's odd is I have put money into the society fund and it will not increase either.

**Comment by ChainedDev** [comment]
Fixed now, should be running fine
