### ISSUE TITLE
Feature Request: Holding F to Respawn.

### ISSUE THREAD

**Issue by CustomChance** [ChainedDev/CityLife#811]
**Is your feature request related to a problem? Please describe.**
Yes, The problem is that people accidentally press f while dead and lose all of their items.

**Describe the feature you'd like**
Instead of just tapping F after waiting 300 seconds you should make it so you have to hold down F for 5 seconds to respawn this is to prevent people from accidentally pressing f and losing there items ( Happened to me before)

**Describe alternatives you've considered**
When pressing F make it show a prompt to Continue and respawn or to stop the respawning.

**Additional context**
(Blank)

**Comment by Chainedster** [comment]
👀

**Comment by Chainedster** [comment]
Duplicate of #231
