### ISSUE TITLE
House Robbing

### ISSUE THREAD

**Issue by R4v3N55** [ChainedDev/CityLife#815]
**Is your feature request related to a problem? Please describe.**
No it is not related to a problem at all its just something i feel is missing.

**Describe the feature you'd like**
So the feature i and many more that i know of would want added is for you to be able to rob houses, maybe with a lockpick/advanced lockpick or a crowbar maybe, this is just a feature i feel is missing almost everywhere and i feel like it would bring a whole new level to robbing in general.

**Describe alternatives you've considered**
So what if i feel like becoming a house robber in the city, i cant do that atm only way to rob is robbing a store, bank or player but thats not what i and many more want we want to rob houses with maybe a crowbar or a lockpick/advanced lockpick, when robbing a house some people may have alarms that you have to "hack" or something like that and if not you just waltz in and steal thier tv or maybe thier microwave and then store it in the trunk of your vehicle (if you have enough space or weight in it) and then taking it tro maybe the pawn shop or some type of blackmarket for stolen goods maybe.

**Additional context**
I just feel like this has been missing on way to many servers i tried out, i know NoPixel has it and thats where i saw it first, but yeah i want this to be a thing in our city aswell. 

Thanks for reading.

**Comment by Dollar82** [comment]
This already a feature sir,has been forever.

**Comment by R4v3N55** [comment]
> This already a feature sir,has been forever.

never seen or heard about it in the city so i just didnt think it was
