### ISSUE TITLE
Fueling boats

### ISSUE THREAD

**Issue by coevan** [ChainedDev/CityLife#82]
**Is your feature request related to a problem? Please describe.**
There is currently no way to fuel boats

**Describe the feature you'd like**
Either Jerry cans could be able to fuel boats or some kind of boat fueling station

**Describe alternatives you've considered**
the only current way to refuel is getting a new boat in the impound for 550$

**Additional context**

**Comment by gavisuprstar** [comment]
I can suggest you for a new fueling system which includes jerry cans too...  

https://github.com/InZidiuZ/LegacyFuel

**Comment by gullidog** [comment]
We Legit use this system already, so please stop linking random scripts.

**Comment by ChainedDev** [comment]
hey, I can't fuel a boat

**Comment by ChainedDev** [comment]
sixty nine
