### ISSUE TITLE
Dodge Demon

### ISSUE THREAD

**Issue by Cudii** [ChainedDev/CityLife#821]
**What is the reason for this balance request?**
The current sound of the Dodge Demon doesn’t sound good.

**What solution would you like?**
Change the sound of the Demon to actually sound like a Demon. Very loud instead of sounding like it’s stuttering.

**Additional context**
Make car sound good.

**Comment by Forkedup** [comment]
The sound was changed based on a previous suggestion. MAKE YO MIND UP FOLKS.

**Comment by PurpleRei** [comment]
> The sound was changed based on a previous suggestion. MAKE YO MIND UP FOLKS.

I think most of the really high end muscle cars, mustang, camaro 2015 (sounds good), 69 charger, 2015 charger, track hawk and the other newer and classic muscle cars should have the camed choppy exhaust sound or a least a combo, kina how you did on the 2015 cámaro that thing sounds dope
