### ISSUE TITLE
ADD NEW FEATURE FOR SASP

### ISSUE THREAD

**Issue by PhoEniXCLRP** [ChainedDev/CityLife#83]
Add a /fine [ID] [Amount] for SASP and remove that in game fineZ & jail  system and also add a /jail [id] [time]
its very useful system. kindly add it ASAP.

**Comment by ChainedDev** [comment]
/jail [id] [time] already exists, have thought about reworking the fine system before not sure how we're gonna fully do it yet

**Comment by gavisuprstar** [comment]
How about making all the F6 menu in command system, like /drag for escort, /hc for handcuff and /impound for impounding a vehicle

**Comment by ChainedDev** [comment]
> How about making all the F6 menu in command system, like /drag for escort, /hc for handcuff and /impound for impounding a vehicle

Literally no point in doing that

**Comment by Droshky** [comment]
> How about making all the F6 menu in command system, like /drag for escort, /hc for handcuff and /impound for impounding a vehicle

bro what, hell noo.

**Comment by Skader91** [comment]
Chief votes no

**Comment by ChainedDev** [comment]
Duplicat of #81
