### ISSUE TITLE
McLaren Senna top speed buff

### ISSUE THREAD

**Issue by lxwiis** [ChainedDev/CityLife#833]
**Is your feature request related to a problem? Please describe.**
Not so much an issue but the McLaren Senna is to slow for the price of the car

**Describe the feature you'd like**
The acceleration of the car is great just for top speed to be in creased by 15-25 mph more and 300k cars from PDM are faster

**Describe alternatives you've considered**
N/A

**Additional context**
Just like I said a lot of the cheaper sport car options such as Comet S2 etc are faster than the 1.3mil supercar

**Comment by Forkedup** [comment]
Balanced
