### ISSUE TITLE
Wood cutting

### ISSUE THREAD

**Issue by RETS-D** [ChainedDev/CityLife#835]
**What is the reason for this balance request?**
Well when you chop tree’s down & get the wood you can carry 50 total but when you sand the wood the max stack is 10.

**What solution would you like?**
Either increase the size of the stack or increase the pay for sanded wood as it’s sooo far away from what you can make from other jobs.

**Additional context**
Just seems this could do with a quick update so there are other routes of RP/ money making.

**Comment by Forkedup** [comment]
Doubled the stack size of sanded wood
