### ISSUE TITLE
New Digs Who Dis

### ISSUE THREAD

**Issue by Skader91** [ChainedDev/CityLife#84]
**Is your feature request related to a problem? Please describe.**
Yeah, SASP outfits suck.

**Describe the feature you'd like**
https://www.lcpdfr.com/downloads/gta5mods/character/19993-san-andreas-state-police-ped-pack/

**Comment by ChainedDev** [comment]
Need the MP Ped clothing outfits not ped skins since we only support the multiplayer character currently

**Comment by Skader91** [comment]
Having a harder time trying to find MP Ped clothing, Something like this perhaps?

https://www.lcpdfr.com/downloads/gta5mods/character/23642-lore-friendly-black-san-andreas-state-police-eup-uniforms-idaho-based/

**Comment by ChainedDev** [comment]
> Having a harder time trying to find MP Ped clothing, Something like this perhaps?
> 
> https://www.lcpdfr.com/downloads/gta5mods/character/23642-lore-friendly-black-san-andreas-state-police-eup-uniforms-idaho-based/

yeah

**Comment by Skader91** [comment]
Bump
