### ISSUE TITLE
when i place a weed pot and water/feed it to fast my game bugs and i cant do anything after.

### ISSUE THREAD

**Issue by jackplayzyt** [ChainedDev/CityLife#842]
**Describe the bug**
[A clear and concise description of what the bug is. **Remove this line!**]

**How to Reproduce the Behavior**
Steps to reproduce the behaviour:

**Expected Behaviour**
[What was expected to happen. **Remove this line!**]

**Screenshots**
[If applicable, add screenshots to help explain your problem. **Remove this line!**]

**Additional context**
[Add any other context about the problem here. **Remove this line!**]

**Comment by Chainedster** [comment]
Please add context and details to this please
