### ISSUE TITLE
Autarch Speed

### ISSUE THREAD

**Issue by joshvo2001** [ChainedDev/CityLife#843]
**What is the reason for this balance request?**
[The car stock price is 415k and it's out of the rotation at PDM so its OOR car, but the only thing that I feel not satisficed about this car is the acceleration and the speed is kind of ass, it's go for like 160 maxed and 180 down the hill. **]

**What solution would you like?**
[I hope that admin and staff team can work and consider about this because this car is like a supercar and the speed should be faster than it *]

**Additional context**
[Add any other context or screenshots about the balance request here. **Remove this line!**]

**Comment by Forkedup** [comment]
All cars are being re-worked and classed
