### ISSUE TITLE
Good Cars for the POLICE

### ISSUE THREAD

**Issue by strangeclrpindia** [ChainedDev/CityLife#85]
As Police have less number of cars and their Speed is too less. Its not a competition with the criminals but Police High Command should have a good fast car which competes with criminal's vehicles.

Also Must Introduce Police Prison Bus (for taking specific criminals to prison and jailing them there, sounds good RP) , Police Transporter (Bullet Proof), Police Stockade for SWAT.
If Police Department have cars like Sedan, Mustang GT, Tahoe, Silverado, etc it would look professionalism. Its just a suggestion to add New Vehicles for PD, it would help the department a lot.
![image](https://user-images.githubusercontent.com/60332040/75120312-b8083580-56b0-11ea-9a2d-0831cabaa985.png)
![image](https://user-images.githubusercontent.com/60332040/75120314-bb9bbc80-56b0-11ea-8e93-6fa0c9c103a1.png)
![image](https://user-images.githubusercontent.com/60332040/75120316-be96ad00-56b0-11ea-9b42-898246bfb026.png)
![image](https://user-images.githubusercontent.com/60332040/75120321-e4bc4d00-56b0-11ea-818b-e16b61307985.png)

**Comment by ChainedDev** [comment]
We need actual things to do inside prison before the rp of transporting needs to be a thing

**Comment by gullidog** [comment]
Plus that mustang is a big no no :)
