### ISSUE TITLE
PD Mustang Sound Reduction

### ISSUE THREAD

**Issue by ItsWookiee** [ChainedDev/CityLife#851]
**What is the reason for this balance request?**
The PD Mustang is just so visceral in an audible sense, it's incredibly loud and obnoxious. It's very hard to hear others in the car, or even those on the radio/shots being fired (even with a louder gun/siren pack)

**What solution would you like?**
To please reduce the sound of the car, it's hard to hear much of anything besides the car and some of the sirens. The general sound is nice, but the volume is just too much. Thank you.

**Comment by Forkedup** [comment]
Will apply it in a few server restarts. 
Please let me know if the change amply satisfies your ears.

**Comment by ItsWookiee** [comment]
It's much better, thank you!
