### ISSUE TITLE
BF400 Handling

### ISSUE THREAD

**Issue by SamiKekkonen** [ChainedDev/CityLife#852]
**What is the reason for this balance request?**
When driving the BF400 at low speed it's almos impossible to turn the bike propperly. The wheel will turn but it's like the engine is going to die when you are standing still. At low speed the wheel will again turn but the bike is barely turning. At high speed it turns like it did before the update.

**What solution would you like?**
I feel like the handling was good befor the update and I wish it would go back to that. The speed decrease seems fair to me so the only thing I wish for is the handling at low speed to be improved.

**Comment by Forkedup** [comment]
Will be good after tsunami, thanks for the bug report
