### ISSUE TITLE
Emperor Vectre buff

### ISSUE THREAD

**Issue by CreepyEK** [ChainedDev/CityLife#853]
**What is the reason for this balance request?**
The Emperor Vectre for the 145k pricetag is extremely slow barely pushing 120-130mph. Most cars that are way cheaper easily out-perform it.

**What solution would you like?**
I would like to see this car perform at mid/high A class due to its sporty appearance and pricetag.

**Additional context**
No additional context.

**Comment by Chainedster** [comment]
Price doesn't equal speed anywhere
