### ISSUE TITLE
Zorrusso rebalance

### ISSUE THREAD

**Issue by alystial** [ChainedDev/CityLife#854]
**What is the reason for this balance request?**
This is an imported super car that barely goes 120 and doesn't perform as it should. The handling feels great but the speed is underperforming for such a car. I believe there are only 2 in city as well so it was likely looked over due to this.

**What solution would you like?**
A slight increase in speed to perform as an imported super car should. I've included a screenshot of the car information. 

![Screenshot 2022-08-26 181101](https://user-images.githubusercontent.com/112213103/186997183-4c6404e4-aa28-44e3-8a2f-41f86231d267.jpg)

**Comment by Forkedup** [comment]
Thank you, unfortunately I didn't create a handling file for this car, it will be fixed within a few days.
