### ISSUE TITLE
Phone photo bug

### ISSUE THREAD

**Issue by M3thican** [ChainedDev/CityLife#856]
**Describe the bug**
The phone script currently has a bug where you cannot take a photo with the phone. The discord png link its supposed to self paste is no longer pasting upon taking of the picture. It is broken for everyone I have asked.

**How to Reproduce the Behavior**
Try to take a photo with the phone.

**Expected Behaviour**
Photo supposed to be taken upon "take photo"?

**Comment by Chainedster** [comment]
Fixed
