### ISSUE TITLE
Adder buff

### ISSUE THREAD

**Issue by CreepyEK** [ChainedDev/CityLife#859]
**What is the reason for this balance request?**
The Adder, being a $1,150,000 car from PDM is simply way too slow and the handling isn't great, a lot of cars far cheaper within the 165-200k+ range beat it very easily. It goes about 145mph on a flat and feels very weird through cornering.

**What solution would you like?**
The solution I would like to see is up the speed a decent bit and slightly tweak the handling, maybe seeing it go up to like 170 on a flat or something around there.

**Additional context**
No additional context.

**Comment by Forkedup** [comment]
Thanks for the report, it should be better balanced now. Was an oversight!
