### ISSUE TITLE
Stock Market (Companies)

### ISSUE THREAD

**Issue by strangeclrpindia** [ChainedDev/CityLife#86]
Can Introduce Stock Markets wherein People can invest some amount of money to government and Start their Own Business Company with name, description, employees, of their choice. Every Company will have separate choice of opening shares and people can invest in any company so that There would be profit/loss system. Government has option of Accepting Companies and It would help the Real Estate Agency Dynasty 8

**Comment by ChainedDev** [comment]
Didn't follow format
