### ISSUE TITLE
PD Vehicles Speed Testing (WITH DATA) (CAUGHT IN HD) (POGCHAMP) 

### ISSUE THREAD

**Issue by yzwookie** [ChainedDev/CityLife#861]
To my dearest Bundabillion, 

All vehicles have been tested with the following upgrades; Engine, Turbo, Brakes, Armour, Transmission. Everything but the Explorer has suspension. The point of this isn't to make PD OP, but to make us balanced and the playing field fair for us to combat crims. These complaints and comments are coming from our best drivers and their feedback, this isn't a matter of driver skill or error. Testing has been done midday on the 19th of September. Videos are included for your viewing pleasure, ah yes, pleasure. 

Here's the facts tested at the airport:

**PD Challenger on flat:** ~145mph
Bumps: ~160mph
0-60: 4s
0-100: 8s
https://youtu.be/0z1-RXkzxig

**PD Corvette on flat:** ~140mph
Bumps: ~165mph
0-60: 3.5s
0-100: 8s 
https://youtu.be/X9EDknprlQw

**PD Mustang on flat:** ~140mph
Bumps: ~170mph
0-60: 3s
0-100: 7s 
https://youtu.be/L2QL1sz45b8

**PD Explorer on flat:** ~135mph
Bumps: ~160mph
0-60: 5s
0-100: 14s
https://youtu.be/HWjayahLwK8

**PD Charger on flat:** ~150mph
Bumps: ~190mph
0-60: 2.5s
0-100: 5s
https://youtu.be/LNPTJTgENRc

After viewing the data, the Charger is our fastest vehicle in the fleet. This shouldn't be the case, nor should it be going that fast. The hierarchy for speed units should go as follows from "worst" to "best"; Mustang, Challenger, Corvette. When crims look behind them and see a speed unit, they should be thinking "oh fiddlesticks, it's a fast car", not "LOL ur slow pal ttyl bozo L nerd". Yes, on the daily we get gapped by so many vehicles on the road. 

Our best vehicle in the fleet should be the Corvette, that is how the speed division is structured and setup with Tony's input. Not saying it should have the highest top speed, the Challenger should, but as an overall speed unit it should be the best. Quite frankly, the speed units should be apart of the best vehicles in the entire server. They aren't widespread every trooper has one, their intention is to be kept away for the best of the best drivers we have. In the videos, you can see how they all suffer from understeer, that is fine for the Challenger, and the Mustang we can work around it, but the Corvette being AWD it becomes a problem, if that could be looked into that'd be fantastic. The Charger is somehow on rails and is our unofficial speed unit. 

As for the explorer, the top speed isn't an issue at all actually, it's the acceleration, it behaves as if it has 2ftlbs of torque. It has the HP clearly by the numbers but it takes forever to get there. Please if this could be looked into, thank you. 

The most ideal situation is the speed units perform like the Charger, as there's less than a handful of cars that beat the Charger. What should the charger be lessened to? Unsure, maybe 15mph slower from overall top speed. An honourable mention to the Schafter is being made, if it can go just 15mph faster it'd be perfect, if not that's fine. As for the other PD vehicles, only the BMW1200RT can see a slight increase (just slight) and bikes should be fine, other than that, they're great. 

Thank you for your time Mr Bundabillion.

With swag regards,
vv

**Comment by yzwookie** [comment]
We've done our testing with the pushed update, the three speed cars are better, just not quite where they need to be. 15-20mph more in speeds would finalize them I believe to truly compete against S+ cars. The challenger is the most iffy because it weighs the most. The charger is still really fast and goes the speeds where we need the speed vehicles to go. Speed goes about 15-20mph slower than charger still. The other cars are fine, thank you.

**Comment by yzwookie** [comment]
Happy belated mister,

So touching back in after testing over a longer period of time,

The charger needs to see a speed reduction of about 20mph, it should only go like 160-165. It's still our fastest vehicle when it shouldn't be, right now capable of hitting about 180-190. Those should be the speed car speeds, not a normal police car. 

The corvette has serious understeer (doesn't want to turn in, lack of grip in the front), and lacks a bit of torque and top end still. Only hits about 170, should be hitting 180 comfortably, but handles great.

The challenger is still slow, needs like another 100ftlb of torque (it's really slow off the line), and the mustang is alright, but it needs a bit of hp and torque to be competitive. Both should be hitting 180. 

All in all this should be the final update for the speed cars. 

Kind of a side thing, the taurus and explorer have been reported to be very loud, if those could be reduced slightly that'd be great, and the crown vic has no engine sound at all. After that we should be good, thank you!

**Comment by Forkedup** [comment]
Changes were made, please let me know if there are any other issues

@yzwookie
