### ISSUE TITLE
Ford GT, Carbon fiber trim looks green in sunlight

### ISSUE THREAD

**Issue by Enzhymez** [ChainedDev/CityLife#867]
Whenever it's daytime, the side skirts and the trim in the front turn a shade of green instead of black. This happens on all carbon fiber parts and can't be fixed in the mechanic

This bug is visible at all points whenever in natural lighting 

Possibly fix the discoloration of carbon fiber parts

![Desktop Screenshot 2022 10 15 - 16 14 01 77 (2)](https://user-images.githubusercontent.com/777791/196006076-0a6e5a4e-8e2b-4630-95af-f5615558cd85.png)
![Desktop Screenshot 2022 10 15 - 16 11 41 30 (3)](https://user-images.githubusercontent.com/777791/196006083-4e29c2cd-9c06-4497-b42e-897aed8f8fa0.png)

![Desktop Screenshot 2022 10 15 - 18 00 35 23 (2)](https://user-images.githubusercontent.com/777791/196009235-ec04c3ec-633a-4e80-8ccf-379999c1db8e.png)

**Comment by Forkedup** [comment]
Sadly this happens when re-sizing textures.

Some textures have to be re-sized in order for the car to be optimized.

Cars have to be optimized for the city to work smoother for everyone. Unfortunately re-sizing things likes to mess with color shades.
