### ISSUE TITLE
Incomplete Pillbox - Getting Dead

### ISSUE THREAD

**Issue by strangeclrpindia** [ChainedDev/CityLife#87]
Pillbox of CityLife Roleplay India is Incomplete, When People checks in, they get fall down in the tunnel and died. This glitch/bug is extremely important to get fixed ASAP
![image](https://user-images.githubusercontent.com/60332040/75120416-ce62c100-56b1-11ea-92ce-20f302aa02ea.png)

https://cdn.discordapp.com/attachments/663496353095090187/681160702861246510/unknown.png

**Comment by strangeclrpindia** [comment]
https://cdn.discordapp.com/attachments/663496353095090187/680411794203869191/20200221191835_1.jpg

**Comment by ChainedDev** [comment]
Lower graphics settings, haven't been able to replicate

**Comment by strangeclrpindia** [comment]
Tried Still Not working , and most of the people dying

**Comment by ChainedDev** [comment]
> Tried Still Not working , and most of the people dying

proabably because livestrem

**Comment by gullidog** [comment]
That is the reason ^^

**Comment by strangeclrpindia** [comment]
People without livestream facing the same issue, And he was just showing the glitch on Livestream to others

**Comment by strangeclrpindia** [comment]
https://cdn.discordapp.com/attachments/663496353095090187/680411794203869191/20200221191835_1.jpg

**Comment by gullidog** [comment]
This is a screenshot? Does not help but if Textures aren't loading in it is a client side issue with your PC.
