### ISSUE TITLE
S class car balance

### ISSUE THREAD

**Issue by CreepyEK** [ChainedDev/CityLife#875]
**What is the reason for this balance request?**
Some S class vehicles are significantly underpowered vs other S class cars, most predominantly the R35 GTR, McLaren 675LT, and some others, also the T20 is significantly overpowered comparative to other vehicles, even faster than some X class cars.

**What solution would you like?**
Re-evaluate some of the S class vehicles & the T20 to tighten the balance between each

**Additional context**
No additional context.

**Comment by Chainedster** [comment]
Are these test done on regular fully upgraded vehicles, or tuner chipped vehicles?

**Comment by CreepyEK** [comment]
Fully upgraded without chips

**Comment by Forkedup** [comment]
Thank you, will balance accordingly
