### ISSUE TITLE
Los Santos Custom glitch [CLRP INDIA]

### ISSUE THREAD

**Issue by strangeclrpindia** [ChainedDev/CityLife#88]
When tried upgrading engine, this is the error everyone getting in CityLife Roleplay India. Need to get Fixed ASA
![Screenshot (1273)](https://user-images.githubusercontent.com/60332040/75120552-98720c80-56b2-11ea-96d7-fd5da880dccb.png)
P.

**Comment by ChainedDev** [comment]
That's not a bug, that's not a engine upgrade, that is armour for a vehicle

**Comment by strangeclrpindia** [comment]
Yeah I mean oops, Armour Upgrade . But how's the pricing 
Only Level 3 has some different price

**Comment by ChainedDev** [comment]
> Yeah I mean oops, Armour Upgrade . But how's the pricing
> Only Level 3 has some different price

That's how it's supposed to be
