### ISSUE TITLE
Spawn point

### ISSUE THREAD

**Issue by DopeDynamic** [ChainedDev/CityLife#90]
**Is your feature request related to a problem? Please describe.**
[Spawn point in the city is very poor we spawn where we left the city this is not good]

**Describe the feature you'd like**
[The spawn point in the city will be train station because anyone want to come in the city he or she will come either by train or bus so there be spawn point of bus station or train station for all playera]

**Describe alternatives you've considered**
[Spawning anywhere create problems for new player and this is not according to rp because if anyone want to come in the city he cannot come directly he will come by the train or bus ]

**Additional context**
[Add any other context or screenshots about the feature request here. **Remove this line!**]

**Comment by gullidog** [comment]
Sorry, what do you mean. New players spawn at the LifeInvader Building?

**Comment by NinjaTinaH** [comment]
I think he means that we automatically get ported to the nearest train or bus but... the keyword we currently use is "take a flight in/out" which means airport.

Don't quite like this idea due to how far garages are (and the ability to rob people loading in whom may have just d/c-ed)

**Comment by JJG1997** [comment]
Leave near a garage after parking your car...?

**Comment by NinjaTinaH** [comment]
> Leave near a garage after parking your car...?

Tell me that if you've d/c while doing an activity and had to run across the city just to get money then to impound.

**Comment by JJG1997** [comment]
Same issue if you dc and then you fly in at a train station?

**Comment by NinjaTinaH** [comment]
> You would get the same issue you you dc if you were teleported to a train station

Only thing is, if people are nearby, you dont have to do the running.

**Comment by mrchoudharyy** [comment]
hey chained i am experiencing a bit issue while entering in the indian server after the loading screen it directly shows a black screen i waited for more than a half an hour one day but it didn't went forward i tried deleting cache also but that idea also didnt worked in others players screen they see me as invisible but in my screen it black so if possible can you help in this situation.

**Comment by ChainedDev** [comment]
we spawn where we left the city this is not good. No that is the point of it

i am experiencing a issue while entering in the indian Server relog
