### ISSUE TITLE
GoPostal but its helicopters

### ISSUE THREAD

**Issue by Decirus** [ChainedDev/CityLife#91]
**Is your feature request related to a problem? Please describe.**
No, it'd just be cool to have this.

**Describe the feature you'd like**
Obviously having everyone do this would be chaotic so maybe have it so you have to do a license for this and it costs something like 20k, and makes you 5k a run. You'd start at LOS Airport and have to fly all the way across the map to Paleto, "dropping" off a package.

**Describe alternatives you've considered**
Maybe do airplanes instead? then you have to extend it by landing plane, going to the back of it and unloading the package then maybe hop in another vehicle and transport it

**Comment by ChainedDev** [comment]
This is probably one of the dumbest jobs ever
