### ISSUE TITLE
Prison time

### ISSUE THREAD

**Issue by gavisuprstar** [ChainedDev/CityLife#93]
**Is your feature request related to a problem? 
Yes 
[A clear and concise description of what the current issue is. 

When a person goes to jail,  his only time counts when he is in the city with same character which canbe difficult specially for streamers to be in jail for long time.

**Describe the feature you'd like**
It will be great if you make a system that the jail time counts even after he disconnected or chang the character.

**Comment by gullidog** [comment]
This is the whole point of jail? We don't give streamers special treatment. This suggestion doesnt make sense.
