### ISSUE TITLE
More Car Imports

### ISSUE THREAD

**Issue by ChainedDev** [ChainedDev/CityLife#94]
What kind of Imports do you guys want to see? Post here

**Comment by DeluxeGekkon** [comment]
we need civics (coups, type rs, sedans), nsx, skylines, 180sx, rx7 FD or FC, 350/370Z, Maybe even the Mitsubishi evolutions, BMWs (z4, m series, 300 series), Supercars, (Lambo, Ferrari), hell even some trucks

**Comment by klucx** [comment]
A regular GTR R32 would be amazing. No widebody, no fancy mods, just a stock R32 with maybe optional body modificaitons

**Comment by rcj0003** [comment]
The Skyline GT-R (R34) and the Lancer Evo X for sure.

**Comment by JJG1997** [comment]
https://www.gta5-mods.com/vehicles/volkswagen-golf-7-5r-2018-add-on

**Comment by JJG1997** [comment]
https://www.gta5-mods.com/vehicles/nissan-skyline-gt-r-bnr34-yca-y97y

**Comment by JJG1997** [comment]
Not a car but additional customisation 

https://www.gta5-mods.com/vehicles/jdm-rims-pack

**Comment by JJG1997** [comment]
https://www.gta5-mods.com/vehicles/bmw-m5-f90-2018-add-on

**Comment by kreg423** [comment]
https://www.gta5-mods.com/vehicles/4-wheel-mobility-scooter

**Comment by klucx** [comment]
- R32
- R33
- S15
- '97 / '85 BMW M3
- 1997 MX-5 Miata and 2019 MX-5 Miata
- Fiat Spider (Modern)
- Ford Raptor
- Tesla Model 3 / S for all people, and nerf the model X, make it a little cheaper and make it available to everyone
- M5
- M2
- Lotus Elise
- Older Lancer Evo X
- Golf R

**Comment by klucx** [comment]
Also an Audi S5 Quattro

**Comment by kreg423** [comment]
https://www.gta5-mods.com/player/fivem-new-red-admin-blue-staff-ped-v1-0
this would be good so i can give people tickets while still in character

**Comment by DeluxeGekkon** [comment]
https://www.gta5-mods.com/vehicles/honda-civic-type-r-ek9

**Comment by Malibu-Discord-Helper** [comment]
https://www.gta5-mods.com/vehicles/2012-infiniti-ipl-g-coupe-add-on NOW

**Comment by ChainedDev** [comment]
Hey, spam this with cars please

**Comment by JJG1997** [comment]
https://www.gta5-mods.com/vehicles/mercedes-amg-gt63-s-coupe

**Comment by JJG1997** [comment]
https://www.gta5-mods.com/vehicles/volkswagen-golf-r-realistic-handling

**Comment by Billy-Grey** [comment]
https://sl.gta5-mods.com/vehicles/subaru-impreza-wrx-sti-2004-add-on-tuning

**Comment by Billy-Grey** [comment]
https://sl.gta5-mods.com/vehicles/jeep-srt-8-2015-add-on-replace

**Comment by Billy-Grey** [comment]
https://sl.gta5-mods.com/vehicles/mercedes-benz-s600-w140

**Comment by Billy-Grey** [comment]
https://www.gta5-mods.com/vehicles/wheels-custom-pack-ganjahouse - Nobel

**Comment by ChainedDev** [comment]
No wheel packs please :D - Server Performance

**Comment by Billy-Grey** [comment]
;-;

**Comment by Billy-Grey** [comment]
https://sl.gta5-mods.com/vehicles/1966-ford-mustang-fastback-2-2-template-owners_manual

**Comment by Billy-Grey** [comment]
https://sl.gta5-mods.com/vehicles/2008-chevrolet-tahoe-unmarked-slicktop
https://sl.gta5-mods.com/vehicles/2015-police-mustang-gt-addon
I assume this counts Tony?

**Comment by TheLitteralIcemanStraightOuttaFinlandia** [comment]
https://sv.gta5-mods.com/vehicles/bmw-m3-e36-streetcustom-add-on-tuning
Giving up my Life Insurance for supporter if this gets in

**Comment by TheLitteralIcemanStraightOuttaFinlandia** [comment]
https://www.gta5-mods.com/vehicles/2020-chevy-silverado-3500-stock-fivem-ready-replace-sniperops1
https://www.gta5-mods.com/vehicles/1978-ford-f150-xlt-add-on

**Comment by TheLitteralIcemanStraightOuttaFinlandia** [comment]
https://www.gta5-mods.com/vehicles/1983-volvo-242-turbo-template-included
https://www.gta5-mods.com/vehicles/hummer-h1
https://www.gta5-mods.com/vehicles/jeep-cherokee-xj-1996-add-on-replace-extras-dirt
https://www.gta5-mods.com/vehicles/bmw-e30-318i-cabriolet-phase-1

**Comment by klucx** [comment]
677035

**Comment by klucx** [comment]
https://www.gta5-mods.com/vehicles/mercedes-benz-brabus-850

**Comment by ChainedDev** [comment]
Old Thread, many cars already added and more from this planned to be over the future
