### ISSUE TITLE
Whitelist Jobs

### ISSUE THREAD

**Issue by RichyRich007** [ChainedDev/CityLife#95]
PDM job -----Car Dealership!------
add a Whitelist job where you assign someone as "car-dealer" their role is to help sale cars. and let people test drive cars.
ALSO -----Custom Stores?------ 
let people open and finance their own store for whatever they want to sale in it for a weekly / biweekly rent / mortgage

**Comment by gullidog** [comment]
Ideas and reworks for whitelisted jobs are in the works! Thanks for the suggestion, I will also leave this open for others to comment any other suggestions they have for whitelisted jobs!

_**gullidog**_

**Comment by ChainedDev** [comment]
Own a Store? 👀

**Comment by ChainedDev** [comment]
PDM Job 👍 @droshky

Not sure what you meant by stores as in like a open market where you put in items and a price for them?
