### ISSUE TITLE
Hide blip

### ISSUE THREAD

**Issue by PhoEniXCLRP** [ChainedDev/CityLife#96]
Hide the blip of illegal places from the map. Of Indian server and change that map to this https://www.dropbox.com/sh/11caj3ke55iztww/AACdheoGfaqRjxgPGxOQgsfTa?dl=0 map this best map it has all tha names if street highways etc.

**Comment by gullidog** [comment]
First of all, illegal places do not have any blips? Second of all, linking a dropbox link is not helpful. It doesn't show us what it looks like or anything.

**Comment by yggun** [comment]
You can download a custom map for FiveM yourself.

**Comment by ChainedDev** [comment]
Our map is dope that's why we used it not changing it
