### ISSUE TITLE
"Press H if EMS can't see you"

### ISSUE THREAD

**Issue by yggun** [ChainedDev/CityLife#97]
**Is your feature request related to a problem? Please describe.
As EMS, more than half the calls I respond to I cannot see the person/they arent actually where they are in my eyes. It makes the RP a bit more wonky when I'm giving /me prompts 5 yards away from where the body is in my eyes for other people nearby or for the victim. Or having people fly in and out because I can't see them.

**Describe the feature you'd like**
A key for people to press when EMS/Police cant see them for whatever reason.

**Additional context**
I know previously we had a button we could press if EMS couldnt see people.

**Comment by ChainedDev** [comment]
Will be looking into making it automatically fix while dead instead of having a button to do it

**Comment by yggun** [comment]
10-4.

**Comment by ChainedDev** [comment]
WTF??? You guys still haven't added this yet? LOSERS

**Comment by ChainedDev** [comment]
HURRY TF UP

**Comment by jackofalloffs** [comment]
its ok ems is used to being forgotten about /s
