### ISSUE TITLE
Can't Connect To Server !!!!!

### ISSUE THREAD

**Issue by abhi9avs** [ChainedDev/CityLife#98]
**Describe the bug**
[A clear and concise description of what the bug is. **Remove this line!**]

**How to Reproduce the Behavior**
Steps to reproduce the behaviour:

**Expected Behaviour**
[What was expected to happen. **Remove this line!**]

**Screenshots**
[If applicable, add screenshots to help explain your problem. **Remove this line!**]

**Additional context**
[Add any other context about the problem here. **Remove this line!**]

**Comment by abhi9avs** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/61831222/75979496-a1f74200-5f06-11ea-938a-9190fea8eddc.png)  
cant connect to server ,, stuck at loading screen , not showing any manual at first

**Comment by gullidog** [comment]
This should have been submitted in support in discord, but press F8 and type guide
