### ISSUE TITLE
House Pin Codes

### ISSUE THREAD

**Issue by JJG1997** [ChainedDev/CityLife#99]
**Describe the bug**
If one of your friends enter your apartment using a pin code, when they come out they're unable to lock it so it just remains unlocks unless you're there.

**Expected Behaviour**
Door should lock behind them when they leave your apartment. This allows people to share a house

**Comment by RichyRich007** [comment]
i had this problem too. it says i code 4-8 digits. but when i had a 4-6 number code it didnt work. they couldnt relock the door. it had to be 8 digit for it to work

**Comment by JJG1997** [comment]
I've had it as 8 digits but it doesn't lock after they leave unless the person that owns it locks it

**Comment by gullidog** [comment]
This is currently being looked into and worked on! However, I will still leave this open for others to comment on similar issues they have had.

_**gullidog**_

**Comment by JJG1997** [comment]
I was told after I put this in that you just have to re-enter the pin to lock the house!

**Comment by ChainedDev** [comment]
BRO! MAKE IT SO CODES ARE INVIS!!!!!!!!!!!!!! REEEEEEEEEEEEE
